/**
 * Paranormal VOX - Türkçe Ürkütücü Kelime Arşivi
 * GhostTube VOX'tan esinlenerek oluşturulmuş
 * 3000+ ürkütücü, sinister ve paranormal kelime
 */

// Kategori: Kimlik ve Varlık
const ENTITY_WORDS = [
  "ben", "ben burada", "ben ölü", "ben hapiste", "ben acı çekiyorum",
  "ben ölüyüm", "ben seni görüyorum", "ben seni izliyorum", "ben seni seviyorum",
  "ben seni öldüreceğim", "ben seni alacağım", "ben seni istiyorum",
  "ben seni takip ediyorum", "ben seni buldum", "ben seni bulduk",
  "ben seni yalnız değilsin", "ben seni korkut", "ben seni korkutmak istiyorum",
  "ben seni çağırıyorum", "ben seni çağırdık", "ben seni çağırıyoruz",
  "ben seni seçtim", "ben seni seçtik", "ben seni seçtiler",
  "ben seni bekliyorum", "ben seni bekledim", "ben seni bekliyoruz",
  "ben seni aldım", "ben seni aldık", "ben seni aldılar",
  "ben seni götüreceğim", "ben seni götürdük", "ben seni götürüyorum",
  "ben seni kurtaramam", "ben seni kurtaramayız", "ben seni kurtaramazsın",
  "ben seni affetmiyorum", "ben seni affetmedim", "ben seni affetmeyeceğim",
  "ben seni unutmadım", "ben seni unutmayacağım", "ben seni unutamam",
  "ben seni sevmedim", "ben seni sevmiyorum", "ben seni sevmeyeceğim",
  "ben seni nefret ediyorum", "ben seni nefret ettim", "ben seni nefret edeceğim",
  "ben seni lanetledim", "ben seni lanetliyorum", "ben seni lanetleyeceğim",
  "ben seni cezalandıracağım", "ben seni cezalandırdım", "ben seni cezalandırıyorum",
  "ben seni işkence edeceğim", "ben seni işkence ettim", "ben seni işkence ediyorum",
  "ben seni acı çektireceğim", "ben seni acı çektirdim", "ben seni acı çektiriyorum",
  "ben seni mahvetmek istiyorum", "ben seni mahvettim", "ben seni mahvediyorum",
  "ben seni imha edeceğim", "ben seni imha ettim", "ben seni imha ediyorum",
  "ben seni yok edeceğim", "ben seni yok ettim", "ben seni yok ediyorum",
  "ben seni tüketmek istiyorum", "ben seni tükettim", "ben seni tüketiyorum",
  "ben seni emiyorum", "ben seni emdi", "ben seni emiş",
  "ben seni yiyorum", "ben seni yedim", "ben seni yiyeceğim",
  "ben seni içiyorum", "ben seni içtim", "ben seni içeceğim",
  "ben seni çiğniyorum", "ben seni çiğnedim", "ben seni çiğneyeceğim",
  "ben seni parçalıyorum", "ben seni parçaladım", "ben seni parçalayacağım",
  "ben seni kesiyorum", "ben seni kestim", "ben seni keseceğim",
  "ben seni yırtıyorum", "ben seni yırtım", "ben seni yırtacağım",
  "ben seni çekiyorum", "ben seni çektim", "ben seni çekeceğim",
  "ben seni itiyorum", "ben seni ittim", "ben seni iteceğim",
  "ben seni boğuyorum", "ben seni boğdum", "ben seni boğacağım",
  "ben seni asıyorum", "ben seni astım", "ben seni asacağım",
  "ben seni vuruyorum", "ben seni vurdum", "ben seni vuracağım",
  "ben seni dönerken", "ben seni dönüyorum", "ben seni döndüm",
  "ben seni çeviriyorum", "ben seni çevirdim", "ben seni çevireceğim",
  "ben seni döndüm", "ben seni dönüyorum", "ben seni döneceğim",
  "ben seni çimdikliyorum", "ben seni çimdikledim", "ben seni çimdikleyeceğim",
  "ben seni tırmıklıyorum", "ben seni tırmıkladım", "ben seni tırmıklayacağım",
  "ben seni ısırıyorum", "ben seni ısırdım", "ben seni ısıracağım",
  "ben seni tüküyorum", "ben seni tükürttüm", "ben seni tüküreceğim",
  "ben seni ağzıma alıyorum", "ben seni ağzıma aldım", "ben seni ağzıma alacağım",
  "ben seni yutuyor", "ben seni yuttum", "ben seni yutacağım",
  "ben seni sindiriyorum", "ben seni sindirdim", "ben seni sindireceğim",
  "ben seni hazmediyorum", "ben seni hazmetim", "ben seni hazmedeceğim",
  "ben seni sindiriyorum", "ben seni sindirdim", "ben seni sindireceğim",
  "ben seni pişiriyorum", "ben seni pişirdim", "ben seni pişireceğim",
  "ben seni ızgara yapıyorum", "ben seni ızgara yaptım", "ben seni ızgara yapacağım",
  "ben seni kavruyorum", "ben seni kavrıdım", "ben seni kavrayacağım",
  "ben seni yakıyorum", "ben seni yaktım", "ben seni yakacağım",
  "ben seni tutuşturuyorum", "ben seni tutuştturdum", "ben seni tutuşturacağım",
  "ben seni alev alıyorum", "ben seni alev aldım", "ben seni alev alacağım",
  "ben seni kül yapıyorum", "ben seni kül yaptım", "ben seni kül yapacağım",
  "ben seni toz yapıyorum", "ben seni toz yaptım", "ben seni toz yapacağım",
  "ben seni buhar yapıyorum", "ben seni buhar yaptım", "ben seni buhar yapacağım",
  "ben seni gaz yapıyorum", "ben seni gaz yaptım", "ben seni gaz yapacağım",
  "ben seni hava yapıyorum", "ben seni hava yaptım", "ben seni hava yapacağım",
  "ben seni hiç yapıyorum", "ben seni hiç yaptım", "ben seni hiç yapacağım",
  "ben seni yokluk yapıyorum", "ben seni yokluk yaptım", "ben seni yokluk yapacağım",
  "ben seni siliyorum", "ben seni sildim", "ben seni sileceğim",
  "ben seni çıkarıyorum", "ben seni çıkardım", "ben seni çıkaracağım",
  "ben seni atıyorum", "ben seni attım", "ben seni atacağım",
  "ben seni fırlatıyorum", "ben seni fırlattım", "ben seni fırlatacağım",
  "ben seni savuruyorum", "ben seni savurdum", "ben seni savuracağım",
  "ben seni saçıyorum", "ben seni saçtım", "ben seni saçacağım",
  "ben seni dağıtıyorum", "ben seni dağıttım", "ben seni dağıtacağım",
  "ben seni dağılıyorum", "ben seni dağıldım", "ben seni dağılacağım",
  "ben seni çöpüyorum", "ben seni çöpledim", "ben seni çöpleyeceğim",
  "ben seni çöp yapıyorum", "ben seni çöp yaptım", "ben seni çöp yapacağım",
  "ben seni pislik yapıyorum", "ben seni pislik yaptım", "ben seni pislik yapacağım",
  "ben seni leş yapıyorum", "ben seni leş yaptım", "ben seni leş yapacağım",
  "ben seni cesetleştiriyorum", "ben seni cesetleştirdim", "ben seni cesetleştireceğim",
  "ben seni kemikleştiriyorum", "ben seni kemikleştirdim", "ben seni kemikleştireceğim",
  "ben seni iskeletleştiriyorum", "ben seni iskeletleştirdim", "ben seni iskeletleştireceğim",
  "ben seni topraklıyorum", "ben seni toprakladım", "ben seni topraklayacağım",
  "ben seni gömüyorum", "ben seni gömdüm", "ben seni gömeceğim",
  "ben seni mezara atıyorum", "ben seni mezara attım", "ben seni mezara atacağım",
  "ben seni ölüye çeviriyorum", "ben seni ölüye çevirdim", "ben seni ölüye çevireceğim",
  "ben seni ölü yapıyorum", "ben seni ölü yaptım", "ben seni ölü yapacağım",
  "ben seni cansızlaştırıyorum", "ben seni cansızlaştırdım", "ben seni cansızlaştıracağım",
  "ben seni hayattan çıkarıyorum", "ben seni hayattan çıkardım", "ben seni hayattan çıkaracağım",
  "ben seni ölüm getiriyorum", "ben seni ölüm getirdim", "ben seni ölüm getireceğim",
  "ben seni kader getiriyorum", "ben seni kader getirdim", "ben seni kader getireceğim",
  "ben seni yazı getiriyorum", "ben seni yazı getirdim", "ben seni yazı getireceğim",
  "ben seni sonu getiriyorum", "ben seni sonu getirdim", "ben seni sonu getireceğim",
  "ben seni bitiş getiriyorum", "ben seni bitiş getirdim", "ben seni bitiş getireceğim",
  "ben seni son getiriyorum", "ben seni son getirdim", "ben seni son getireceğim",
  "ben seni bitiriyorum", "ben seni bitirdim", "ben seni biteceğim",
  "ben seni sonlandırıyorum", "ben seni sonlandırdım", "ben seni sonlandıracağım",
  "ben seni tamamlıyorum", "ben seni tamamladım", "ben seni tamamlayacağım",
  "ben seni bitiştiriyorum", "ben seni bitiştirdim", "ben seni bitiştireceğim",
  "ben seni kapatıyorum", "ben seni kapattım", "ben seni kapatacağım",
  "ben seni mühürleyiyorum", "ben seni mühürledim", "ben seni mühürleyeceğim",
  "ben seni kilitliyorum", "ben seni kilitlendim", "ben seni kilitleyeceğim",
  "ben seni tutuyorum", "ben seni tuttum", "ben seni tutacağım",
  "ben seni hapsetmek istiyorum", "ben seni hapsetim", "ben seni hapsedeceğim",
  "ben seni zindana atıyorum", "ben seni zindana attım", "ben seni zindana atacağım",
  "ben seni kafese koyuyorum", "ben seni kafese koydum", "ben seni kafese koyacağım",
  "ben seni hapsediyorum", "ben seni hapsettim", "ben seni hapsedeceğim",
  "ben seni esir alıyorum", "ben seni esir aldım", "ben seni esir alacağım",
  "ben seni köle yapıyorum", "ben seni köle yaptım", "ben seni köle yapacağım",
  "ben seni bağlıyorum", "ben seni bağladım", "ben seni bağlayacağım",
  "ben seni zincirliyorum", "ben seni zincirlendim", "ben seni zincirleyeceğim",
  "ben seni kısıtlıyorum", "ben seni kısıtladım", "ben seni kısıtlayacağım",
  "ben seni sınırlandırıyorum", "ben seni sınırlandırdım", "ben seni sınırlandıracağım",
  "ben seni engelliyorum", "ben seni engelledim", "ben seni engelleyeceğim",
  "ben seni bloke ediyorum", "ben seni bloke ettim", "ben seni bloke edeceğim",
  "ben seni kapatıyorum", "ben seni kapattım", "ben seni kapatacağım",
  "ben seni yalıtıyorum", "ben seni yalıttım", "ben seni yalıtacağım",
  "ben seni izole ediyorum", "ben seni izole ettim", "ben seni izole edeceğim",
  "ben seni ayırıyorum", "ben seni ayırdım", "ben seni ayıracağım",
  "ben seni uzaklaştırıyorum", "ben seni uzaklaştırdım", "ben seni uzaklaştıracağım",
  "ben seni kovuyorum", "ben seni kovdum", "ben seni kovacağım",
  "ben seni sürüyorum", "ben seni sürdüm", "ben seni süreceğim",
  "ben seni çıkarıyorum", "ben seni çıkardım", "ben seni çıkaracağım",
  "ben seni dışarı atıyorum", "ben seni dışarı attım", "ben seni dışarı atacağım",
  "ben seni reddediyorum", "ben seni reddettim", "ben seni reddeeceğim",
  "ben seni inkar ediyorum", "ben seni inkar ettim", "ben seni inkar edeceğim",
  "ben seni tanımıyorum", "ben seni tanımadım", "ben seni tanımayacağım",
  "ben seni bilmiyorum", "ben seni bilmedim", "ben seni bilmeyeceğim",
  "ben seni görmüyorum", "ben seni görmedim", "ben seni görmeyeceğim",
  "ben seni duymuyor", "ben seni duymadım", "ben seni duymayacağım",
  "ben seni hissetmiyorum", "ben seni hissetmedim", "ben seni hissetmeyeceğim",
  "ben seni fark etmiyorum", "ben seni fark etmedim", "ben seni fark etmeyeceğim",
  "ben seni anlamıyorum", "ben seni anlamadım", "ben seni anlamayacağım",
  "ben seni kavramıyorum", "ben seni kavramadım", "ben seni kavramayacağım",
  "ben seni idrak etmiyorum", "ben seni idrak etmedim", "ben seni idrak etmeyeceğim",
  "ben seni çözemiyorum", "ben seni çözemedim", "ben seni çözemeyeceğim",
  "ben seni çözmüyorum", "ben seni çözmüştüm", "ben seni çözmeyeceğim",
  "ben seni açamıyorum", "ben seni açamadım", "ben seni açamayacağım",
  "ben seni açmıyorum", "ben seni açmadım", "ben seni açmayacağım",
  "ben seni kırıyorum", "ben seni kırdım", "ben seni kıracağım",
  "ben seni çatlatıyorum", "ben seni çatladım", "ben seni çatlayacağım",
  "ben seni kütleştiriyorum", "ben seni kütleştirdim", "ben seni kütleştireceğim",
  "ben seni taşlaştırıyorum", "ben seni taşlaştırdım", "ben seni taşlaştıracağım",
  "ben seni donduruyor", "ben seni dondum", "ben seni donduracağım",
  "ben seni buzlaştırıyorum", "ben seni buzlaştırdım", "ben seni buzlaştıracağım",
  "ben seni soğutuyorum", "ben seni soğuttum", "ben seni soğutacağım",
  "ben seni ısıtıyorum", "ben seni ısıttım", "ben seni ısıtacağım",
  "ben seni kaynıyorum", "ben seni kaynattım", "ben seni kaynayacağım",
  "ben seni buharlaştırıyorum", "ben seni buharlaştırdım", "ben seni buharlaştıracağım",
  "ben seni uçuruyorum", "ben seni uçurdum", "ben seni uçuracağım",
  "ben seni havaya kaldırıyorum", "ben seni havaya kaldırdım", "ben seni havaya kaldıracağım",
  "ben seni asılı tutuyorum", "ben seni asılı tuttum", "ben seni asılı tutacağım",
  "ben seni havada tutuyorum", "ben seni havada tuttum", "ben seni havada tutacağım",
  "ben seni gökyüzüne çıkarıyorum", "ben seni gökyüzüne çıkardım", "ben seni gökyüzüne çıkaracağım",
  "ben seni yere çakıyorum", "ben seni yere çaktım", "ben seni yere çakacağım",
  "ben seni toprağa gömüyorum", "ben seni toprağa gömdüm", "ben seni toprağa gömecegim",
  "ben seni derinliklere atıyorum", "ben seni derinliklere attım", "ben seni derinliklere atacağım",
  "ben seni karanlığa çekiyorum", "ben seni karanlığa çektim", "ben seni karanlığa çekeceğim",
  "ben seni ışıktan uzaklaştırıyorum", "ben seni ışıktan uzaklaştırdım", "ben seni ışıktan uzaklaştıracağım",
  "ben seni gölgeye atıyorum", "ben seni gölgeye attım", "ben seni gölgeye atacağım",
  "ben seni karanlığa gömüyorum", "ben seni karanlığa gömdüm", "ben seni karanlığa gömecegim",
  "ben seni cehennemine çekiyorum", "ben seni cehennemine çektim", "ben seni cehennemine çekeceğim",
  "ben seni cehenneme atıyorum", "ben seni cehenneme attım", "ben seni cehenneme atacağım",
  "ben seni cehenneme gömüyorum", "ben seni cehenneme gömdüm", "ben seni cehenneme gömecegim",
  "ben seni cehenneme sürüyorum", "ben seni cehenneme sürdüm", "ben seni cehenneme süreceğim",
  "ben seni cehenneme götürüyorum", "ben seni cehenneme götürdüm", "ben seni cehenneme götüreceğim",
  "ben seni cehennemde tutuyorum", "ben seni cehennemde tuttum", "ben seni cehennemde tutacağım",
  "ben seni cehennemde hapsetiyorum", "ben seni cehennemde hapsettim", "ben seni cehennemde hapsedeceğim",
  "ben seni cehennemde işkence ediyorum", "ben seni cehennemde işkence ettim", "ben seni cehennemde işkence edeceğim",
  "ben seni cehennemde acı çektiriyorum", "ben seni cehennemde acı çektirdim", "ben seni cehennemde acı çektireceğim",
  "ben seni cehennemde yanıyorum", "ben seni cehennemde yandım", "ben seni cehennemde yanacağım",
  "ben seni cehennemde eriyor", "ben seni cehennemde eritim", "ben seni cehennemde eriteceğim",
  "ben seni cehennemde kızıyorum", "ben seni cehennemde kızdım", "ben seni cehennemde kızacağım",
  "ben seni cehennemde yanıyorum", "ben seni cehennemde yandım", "ben seni cehennemde yanacağım",
  "ben seni cehennemde yanıyorum", "ben seni cehennemde yandım", "ben seni cehennemde yanacağım",
];

// Kategori: Duygular ve Durumlar
const EMOTION_WORDS = [
  "acı", "acıyorum", "acı çekiyorum", "acı çektim", "acı çekeceğim",
  "korku", "korkuyorum", "korkmuş", "korkacak", "korktu",
  "dehşet", "dehşete kapıldım", "dehşet içinde", "dehşet veriyorum",
  "ürküntü", "ürkütüyorum", "ürküttüm", "ürküteceğim",
  "panik", "panikte", "paniğe kapıldım", "paniğe kapılacak",
  "histerik", "histeriye kapıldım", "histeriye kapılacak",
  "çılgın", "çılgınlık", "çılgınlaştım", "çılgınlaşacak",
  "delirmiş", "delirtiyorum", "delirttim", "delirteceğim",
  "çıldırmış", "çıldırtıyorum", "çıldırttım", "çıldırteceğim",
  "sinir", "sinirli", "sinirleniyorum", "sinirlenttim", "sinirlenecek",
  "öfke", "öfkeli", "öfkeliyorum", "öfkelendim", "öfkelenecek",
  "kızgın", "kızgınlık", "kızıyorum", "kızdım", "kızacağım",
  "nefret", "nefret ediyorum", "nefret ettim", "nefret edeceğim",
  "tiksinti", "tiksiniyorum", "tiksindim", "tiksineceğim",
  "iğrenç", "iğreniyorum", "iğrendim", "iğreneceğim",
  "ürpertici", "ürpertiyorum", "ürperttim", "ürperteceğim",
  "tüyler ürpertici", "tüyler diken diken", "tüyler ürperiyorum",
  "diken diken", "dikenliyorum", "dikenlendim", "dikenleneceğim",
  "titreme", "titremiyorum", "titrettim", "titreceğim",
  "tremolo", "tremoluyorum", "tremolattım", "tremolayacağım",
  "titrek", "titreklik", "titrekleşiyorum", "titrekleştim", "titrekleşeceğim",
  "soğuk", "soğukluk", "soğukluyorum", "soğukladım", "soğulacağım",
  "buz", "buzlaştırıyorum", "buzlaştırdım", "buzlaştıracağım",
  "donmuş", "donuyorum", "dondum", "donacağım",
  "ateş", "ateşli", "ateşliyorum", "ateşledim", "ateşleyeceğim",
  "yanıyorum", "yandım", "yanacağım",
  "kaynıyorum", "kaynattım", "kaynayacağım",
  "eriyor", "eritim", "eriteceğim",
  "pus", "pus yapıyorum", "pus yaptım", "pus yapacağım",
  "irin", "irin yapıyorum", "irin yaptım", "irin yapacağım",
  "kan", "kanlı", "kanlıyorum", "kanladım", "kanlayacağım",
  "kanama", "kanamıyorum", "kanadım", "kanayacağım",
  "yaralı", "yaralanıyorum", "yaralandım", "yaralanacağım",
  "yara", "yaralıyorum", "yaraladım", "yaralayacağım",
  "ağrı", "ağrıyorum", "ağrıdım", "ağrıyacağım",
  "ağrılı", "ağrılıyorum", "ağrıladım", "ağrılayacağım",
  "sızı", "sızıyorum", "sızıdım", "sızıyacağım",
  "sızıl", "sızılıyorum", "sızıladım", "sızılayacağım",
  "kramp", "krampı", "kramplandırıyorum", "kramplandırdım", "kramplandıracağım",
  "seğirme", "seğirtiyorum", "seğirttim", "seğirteceğim",
  "çarpıntı", "çarpıntılı", "çarpıntılandırıyorum", "çarpıntılandırdım", "çarpıntılandıracağım",
  "kalp", "kalp atışı", "kalp çarpıyor", "kalp çarptı", "kalp çarpacak",
  "nefes", "nefes almıyorum", "nefes alamadım", "nefes alamayacağım",
  "boğulma", "boğuluyorum", "boğuldum", "boğulacağım",
  "asphyxia", "asphyxiaya uğruyorum", "asphyxiaya uğradım", "asphyxiaya uğrayacağım",
  "solunum", "solunuma engel", "solunuma engel oluyorum", "solunuma engel oldum", "solunuma engel olacağım",
  "hıçkırık", "hıçkırıyorum", "hıçkırdım", "hıçkıracağım",
  "öksürük", "öksürüyorum", "öksürdüm", "öksüreceğim",
  "tıkılma", "tıkılıyorum", "tıkıldım", "tıkılacağım",
  "tıkanma", "tıkanıyorum", "tıkandım", "tıkanacağım",
  "tıkamak", "tıkıyorum", "tıkadım", "tıkayacağım",
  "ağız", "ağız dolusu", "ağız dolduruyorum", "ağız doldurdum", "ağız dolduracağım",
  "diş", "diş sıkıyorum", "diş sıktım", "diş sıkacağım",
  "çene", "çeneyi kıracak", "çeneyi kırıyorum", "çeneyi kırdım", "çeneyi kıracağım",
  "çene çıkıntısı", "çene çıkıntısını kıracak", "çene çıkıntısını kırıyorum", "çene çıkıntısını kırdım",
  "göz", "gözü çıkarmak", "gözü çıkarıyorum", "gözü çıkardım", "gözü çıkaracağım",
  "göz çıkarmak", "göz çıkarıyorum", "göz çıkardım", "göz çıkaracağım",
  "kör", "körleştiriyorum", "körleştirdim", "körleştireceğim",
  "körleşme", "körleşiyorum", "körleştim", "körleşeceğim",
  "görme", "görme kaybı", "görme kaybı yaşıyorum", "görme kaybı yaşadım", "görme kaybı yaşayacağım",
  "körlük", "körlüğe çeviriyorum", "körlüğe çevirdim", "körlüğe çevireceğim",
  "karanlık", "karanlığa çekiyorum", "karanlığa çektim", "karanlığa çekeceğim",
  "kara", "karalıyorum", "karaladım", "karalayacağım",
  "siyah", "siyahlaştırıyorum", "siyahlaştırdım", "siyahlaştıracağım",
  "gece", "geceye çekiyorum", "geceye çektim", "geceye çekeceğim",
  "gündüz", "gündüzü kaybettiriyorum", "gündüzü kaybettirdim", "gündüzü kaybettireceğim",
  "ışık", "ışığı söndürüyorum", "ışığı söndürdüm", "ışığı söndüreceğim",
  "söndürme", "söndürüyorum", "söndürdüm", "söndüreceğim",
  "karanlık", "karanlığa çekiyorum", "karanlığa çektim", "karanlığa çekeceğim",
  "gölge", "gölgeye atıyorum", "gölgeye attım", "gölgeye atacağım",
  "gölgeli", "gölgeliyorum", "gölgeledim", "gölgeleyeceğim",
  "bulanık", "bulanıklaştırıyorum", "bulanıklaştırdım", "bulanıklaştıracağım",
  "bulanıklık", "bulanıklaşıyorum", "bulanıklaştım", "bulanıklaşacağım",
  "sisli", "sisliyorum", "sislemedim", "sisleyeceğim",
  "sis", "sise çekiyorum", "sise çektim", "sise çekeceğim",
  "duman", "dumana çekiyorum", "dumana çektim", "dumana çekeceğim",
  "duman", "dumanlaştırıyorum", "dumanlaştırdım", "dumanlaştıracağım",
  "buhar", "buharlaştırıyorum", "buharlaştırdım", "buharlaştıracağım",
  "gaz", "gazlaştırıyorum", "gazlaştırdım", "gazlaştıracağım",
  "hava", "havalaştırıyorum", "havalaştırdım", "havalaştıracağım",
  "rüzgar", "rüzgarlaştırıyorum", "rüzgarlaştırdım", "rüzgarlaştıracağım",
  "fırtına", "fırtınalaştırıyorum", "fırtınalaştırdım", "fırtınalaştıracağım",
  "kasırga", "kasırğalaştırıyorum", "kasırğalaştırdım", "kasırğalaştıracağım",
  "tornado", "tornadolaştırıyorum", "tornadolaştırdım", "tornadolaştıracağım",
  "deprem", "depremi çekiyorum", "depremi çektim", "depremi çekeceğim",
  "sarsıntı", "sarsıntılandırıyorum", "sarsıntılandırdım", "sarsıntılandıracağım",
  "titreşim", "titreşimlendiriyorum", "titreşimlendirdim", "titreşimlendireceğim",
  "sallanma", "sallanıyorum", "sallandım", "sallanacağım",
  "sallantı", "sallantılıyorum", "sallantıladım", "sallantılayacağım",
  "denge", "dengesini bozuyorum", "dengesini bozdım", "dengesini bozacağım",
  "dengesiz", "dengesizleştiriyorum", "dengesizleştirdim", "dengesizleştireceğim",
  "çarpışma", "çarpışıyorum", "çarpıştım", "çarpışacağım",
  "çarpma", "çarpıyorum", "çarptım", "çarpacağım",
  "vuruş", "vuruşuyorum", "vuruştum", "vuruşacağım",
  "vurmak", "vuruyorum", "vurdum", "vuracağım",
  "dayak", "dayak atıyorum", "dayak attım", "dayak atacağım",
  "dövmek", "dövüyorum", "dövendim", "döveceğim",
  "dövüş", "dövüşüyorum", "dövüştüm", "dövüşeceğim",
  "kavga", "kavga çıkarıyorum", "kavga çıkardım", "kavga çıkaracağım",
  "çatışma", "çatışıyorum", "çatıştım", "çatışacağım",
  "savaş", "savaşıyorum", "savaştım", "savaşacağım",
  "muharebe", "muharebede", "muharebede bulunuyorum", "muharebede bulundum", "muharebede bulunacağım",
  "saldırı", "saldırıyorum", "saldırdım", "saldıracağım",
  "hücum", "hücum ediyorum", "hücum ettim", "hücum edeceğim",
  "taaruz", "taaruz ediyorum", "taaruz ettim", "taaruz edeceğim",
  "atak", "atak yapıyorum", "atak yaptım", "atak yapacağım",
  "baskın", "baskın yapıyorum", "baskın yaptım", "baskın yapacağım",
  "pusu", "pusuda", "pusuda bekliyorum", "pusuda bekledim", "pusuda bekleyeceğim",
  "tuzak", "tuzağa düşürüyorum", "tuzağa düşürdüm", "tuzağa düşüreceğim",
  "tuzak", "tuzaklandırıyorum", "tuzaklandırdım", "tuzaklandıracağım",
  "hile", "hileli", "hile yapıyorum", "hile yaptım", "hile yapacağım",
  "aldatma", "aldatıyorum", "aldattım", "aldatacağım",
  "kandırma", "kandırıyorum", "kandırdım", "kandıracağım",
  "manipülasyon", "manipüle ediyorum", "manipüle ettim", "manipüle edeceğim",
  "oyun", "oyun oynuyorum", "oyun oynadım", "oyun oynayacağım",
  "numarası", "numarası yapıyorum", "numarası yaptım", "numarası yapacağım",
  "sahne", "sahne yapıyorum", "sahne yaptım", "sahne yapacağım",
  "tiyatro", "tiyatro yapıyorum", "tiyatro yaptım", "tiyatro yapacağım",
  "rol", "rol yapıyorum", "rol yaptım", "rol yapacağım",
  "oyuncu", "oyuncu gibi", "oyuncu gibi davranıyorum", "oyuncu gibi davrandım", "oyuncu gibi davranacağım",
  "kişilik", "kişilik değiştiriyorum", "kişilik değiştirdim", "kişilik değiştireceğim",
  "maske", "maskeleniyorum", "maskelendim", "maskelenecek",
  "yüz", "yüzü değiştiriyorum", "yüzü değiştirdim", "yüzü değiştireceğim",
  "gizleme", "gizliyorum", "gizledim", "gizleyeceğim",
  "saklanma", "saklı", "saklanıyorum", "saklandım", "saklanacağım",
  "gizli", "gizlilik", "gizliliği koruyorum", "gizliliği korudum", "gizliliği koruyacağım",
  "sır", "sırı saklıyorum", "sırı sakladım", "sırı saklayacağım",
  "gizem", "gizemli", "gizemliyorum", "gizemledim", "gizlemleyeceğim",
  "muamma", "muammalı", "muammalandırıyorum", "muammalandırdım", "muammalandıracağım",
  "bilmece", "bilmeceli", "bilmeceleştiriyorum", "bilmeceleştirdim", "bilmeceleştireceğim",
  "şifre", "şifreli", "şifrelediyorum", "şifrelemedim", "şifreleceğim",
  "kod", "kodlu", "kodlandırıyorum", "kodlandırdım", "kodlandıracağım",
  "şifrele", "şifreleşiyorum", "şifreleştim", "şifreleşeceğim",
  "kodla", "kodlaşıyorum", "kodlaştım", "kodlaşacağım",
  "kriptik", "kriptikleştiriyorum", "kriptikleştirdim", "kriptikleştireceğim",
  "kriptografi", "kriptografik", "kriptografik hale getiriyorum", "kriptografik hale getirdim", "kriptografik hale getireceğim",
  "gizli yazı", "gizli yazı kullanıyorum", "gizli yazı kullandım", "gizli yazı kullanacağım",
  "steganografi", "steganografik", "steganografik hale getiriyorum", "steganografik hale getirdim", "steganografik hale getireceğim",
  "steganografi", "steganografi yapıyorum", "steganografi yaptım", "steganografi yapacağım",
  "gizli mesaj", "gizli mesaj gönderiyorum", "gizli mesaj gönderdim", "gizli mesaj göndereceğim",
  "gizli iletişim", "gizli iletişim kuruyorum", "gizli iletişim kurdum", "gizli iletişim kuracağım",
  "gizli konuşma", "gizli konuşma yapıyorum", "gizli konuşma yaptım", "gizli konuşma yapacağım",
  "fısıltı", "fısıldıyorum", "fısıldadım", "fısıldayacağım",
  "mırıldanma", "mırıldanıyorum", "mırıldandım", "mırıldanacağım",
  "homurtu", "homurdanıyorum", "homurdandım", "homurdanacağım",
  "ses", "sesli", "seslendiriyorum", "seslendirdim", "seslendireceğim",
  "sesin", "sesiniz", "sesinizi değiştiriyorum", "sesinizi değiştirdim", "sesinizi değiştireceğim",
  "gırtlak", "gırtlaktan", "gırtlaktan ses çıkarıyorum", "gırtlaktan ses çıkardım", "gırtlaktan ses çıkaracağım",
  "boğuk", "boğuk ses", "boğuk sesle konuşuyorum", "boğuk sesle konuştum", "boğuk sesle konuşacağım",
  "tiz", "tiz ses", "tiz sesle konuşuyorum", "tiz sesle konuştum", "tiz sesle konuşacağım",
  "kalın", "kalın ses", "kalın sesle konuşuyorum", "kalın sesle konuştum", "kalın sesle konuşacağım",
  "cırtlak", "cırtlak ses", "cırtlak sesle konuşuyorum", "cırtlak sesle konuştum", "cırtlak sesle konuşacağım",
  "kısık", "kısık ses", "kısık sesle konuşuyorum", "kısık sesle konuştum", "kısık sesle konuşacağım",
  "yüksek", "yüksek ses", "yüksek sesle konuşuyorum", "yüksek sesle konuştum", "yüksek sesle konuşacağım",
  "alçak", "alçak ses", "alçak sesle konuşuyorum", "alçak sesle konuştum", "alçak sesle konuşacağım",
  "şiddetli", "şiddetli ses", "şiddetli sesle konuşuyorum", "şiddetli sesle konuştum", "şiddetli sesle konuşacağım",
  "hafif", "hafif ses", "hafif sesle konuşuyorum", "hafif sesle konuştum", "hafif sesle konuşacağım",
  "sert", "sert ses", "sert sesle konuşuyorum", "sert sesle konuştum", "sert sesle konuşacağım",
  "yumuşak", "yumuşak ses", "yumuşak sesle konuşuyorum", "yumuşak sesle konuştum", "yumuşak sesle konuşacağım",
];

// Kategori: Paranormal ve Doğaüstü
const PARANORMAL_WORDS = [
  "hayalet", "hayalet gibi", "hayaletleştiriyorum", "hayaletleştirdim", "hayaletleştireceğim",
  "ruh", "ruhsal", "ruhlandırıyorum", "ruhlandırdım", "ruhlandıracağım",
  "cin", "cinli", "cinleştiriyorum", "cinleştirdim", "cinleştireceğim",
  "şeytan", "şeytani", "şeytanlaştırıyorum", "şeytanlaştırdım", "şeytanlaştıracağım",
  "iblis", "iblisli", "iblisleştiriyorum", "iblisleştirdim", "iblisleştireceğim",
  "demon", "demoni", "demonlaştırıyorum", "demonlaştırdım", "demonlaştıracağım",
  "ceberut", "ceberutlu", "ceberutlaştırıyorum", "ceberutlaştırdım", "ceberutlaştıracağım",
  "melek", "melek gibi", "melek değil", "melek olmayan",
  "tanrı", "tanrısal", "tanrılaştırıyorum", "tanrılaştırdım", "tanrılaştıracağım",
  "ilah", "ilahi", "ilahlıyorum", "ilahlıdım", "ilahlıyacağım",
  "tanrısallık", "tanrısallaştırıyorum", "tanrısallaştırdım", "tanrısallaştıracağım",
  "aziz", "azizlik", "azizleştiriyorum", "azizleştirdim", "azizleştireceğim",
  "kutsal", "kutsallık", "kutsallaştırıyorum", "kutsallaştırdım", "kutsallaştıracağım",
  "mukaddes", "mukaddeslik", "mukaddesleştiriyorum", "mukaddesleştirdim", "mukaddesleştireceğim",
  "haram", "haramlık", "haramlaştırıyorum", "haramlaştırdım", "haramlaştıracağım",
  "günah", "günahlı", "günahlandırıyorum", "günahlandırdım", "günahlandıracağım",
  "lanet", "lanetli", "lanetlediyorum", "lanetledim", "lanetleyeceğim",
  "bela", "belali", "belalaştırıyorum", "belalaştırdım", "belalaştıracağım",
  "felaket", "felaketli", "felaketleştiriyorum", "felaketleştirdim", "felaketleştireceğim",
  "kıyamet", "kıyametli", "kıyametleştiriyorum", "kıyametleştirdim", "kıyametleştireceğim",
  "cehennem", "cehennemli", "cehennemleştiriyorum", "cehennemleştirdim", "cehennemleştireceğim",
  "cehenneme", "cehennem ateşi", "cehennem ateşine", "cehennem ateşine çekiyorum",
  "ateş", "ateşli", "ateşlendiriyorum", "ateşlendirdim", "ateşlendireceğim",
  "kızıl", "kızıllık", "kızıllaştırıyorum", "kızıllaştırdım", "kızıllaştıracağım",
  "kan", "kanlı", "kanlılaştırıyorum", "kanlılaştırdım", "kanlılaştıracağım",
  "leş", "leşli", "leşleştiriyorum", "leşleştirdim", "leşleştireceğim",
  "çürüme", "çürümüş", "çürütüyorum", "çürüttüm", "çürüteceğim",
  "putrefaksiyon", "putrefaksiyonlu", "putrefaksiyonlandırıyorum", "putrefaksiyonlandırdım", "putrefaksiyonlandıracağım",
  "nekroz", "nekrozlu", "nekrozlandırıyorum", "nekrozlandırdım", "nekrozlandıracağım",
  "gangren", "gangrenlı", "gangrenleştiriyorum", "gangrenleştirdim", "gangrenleştireceğim",
  "enfeksiyon", "enfekteli", "enfekteleştiriyorum", "enfekteleştirdim", "enfekteleştireceğim",
  "mikrop", "mikroplı", "mikroplaştırıyorum", "mikroplaştırdım", "mikroplaştıracağım",
  "bakteri", "bakterili", "bakterileştiriyorum", "bakterileştirdim", "bakterileştireceğim",
  "virus", "virüslü", "virüsleştiriyorum", "virüsleştirdim", "virüsleştireceğim",
  "hastalık", "hastalıklı", "hastalıklandırıyorum", "hastalıklandırdım", "hastalıklandıracağım",
  "hastalık", "hastalıklı", "hastalıklandırıyorum", "hastalıklandırdım", "hastalıklandıracağım",
  "veba", "vebali", "vebalılaştırıyorum", "vebalılaştırdım", "vebalılaştıracağım",
  "kolera", "koleralı", "koleraplaştırıyorum", "koleraplaştırdım", "koleraplaştıracağım",
  "tifüs", "tifüslü", "tifüsleştiriyorum", "tifüsleştirdim", "tifüsleştireceğim",
  "kuduz", "kuduzu", "kuduzu yapıyorum", "kuduzu yaptım", "kuduzu yapacağım",
  "tetanoz", "tetanozlu", "tetanozlandırıyorum", "tetanozlandırdım", "tetanozlandıracağım",
  "meningit", "meningitli", "meningitleştiriyorum", "meningitleştirdim", "meningitleştireceğim",
  "ensefalit", "ensefalitli", "ensefalitleştiriyorum", "ensefalitleştirdim", "ensefalitleştireceğim",
  "polio", "poliyolu", "poliyolaştırıyorum", "poliyolaştırdım", "poliyolaştıracağım",
  "felç", "felçli", "felçleştiriyorum", "felçleştirdim", "felçleştireceğim",
  "paraliz", "paralizli", "paralizleştiriyorum", "paralizleştirdim", "paralizleştireceğim",
  "immobilite", "immobil", "immobilize ediyorum", "immobilize ettim", "immobilize edeceğim",
  "hareketsiz", "hareketsizlik", "hareketsizleştiriyorum", "hareketsizleştirdim", "hareketsizleştireceğim",
  "cansız", "cansızlık", "cansızlaştırıyorum", "cansızlaştırdım", "cansızlaştıracağım",
  "ölü", "ölülük", "ölüleştiriyorum", "ölüleştirdim", "ölüleştireceğim",
  "ölüm", "ölümlü", "ölümlüleştiriyorum", "ölümlüleştirdim", "ölümlüleştireceğim",
  "ölüm cezası", "ölüm cezasına çarptırıyorum", "ölüm cezasına çarptırdım", "ölüm cezasına çarptıracağım",
  "idam", "idama mahkum", "idama mahkum ediyorum", "idama mahkum ettim", "idama mahkum edeceğim",
  "asılma", "asılıyorum", "asıldım", "asılacağım",
  "boğulma", "boğuluyorum", "boğuldum", "boğulacağım",
  "elektrik", "elektrik çarpması", "elektrik çarpıyorum", "elektrik çarptım", "elektrik çarpacağım",
  "elektrik sandalyesi", "elektrik sandalyesine oturtuyorum", "elektrik sandalyesine oturttum", "elektrik sandalyesine oturturacağım",
  "gaz", "gaz odası", "gaz odasına koyuyorum", "gaz odasına koydum", "gaz odasına koyacağım",
  "zehir", "zehirli", "zehirlediyorum", "zehirledim", "zehirleyeceğim",
  "toksin", "toksinli", "toksinleştiriyorum", "toksinleştirdim", "toksinleştireceğim",
  "arsenik", "arsenikli", "arsenikleştiriyorum", "arsenikleştirdim", "arsenikleştireceğim",
  "siyanür", "siyanürlü", "siyanürleştiriyorum", "siyanürleştirdim", "siyanürleştireceğim",
  "strikinin", "strikinli", "strikinleştiriyorum", "strikinleştirdim", "strikinleştireceğim",
  "morfin", "morfinli", "morfinleştiriyorum", "morfinleştirdim", "morfinleştireceğim",
  "uyuşturucu", "uyuşturuculu", "uyuşturuculaştırıyorum", "uyuşturuculaştırdım", "uyuşturuculaştıracağım",
  "narkotik", "narkotikli", "narkotikleştiriyorum", "narkotikleştirdim", "narkotikleştireceğim",
  "anestezi", "anestezili", "anestezileştiriyorum", "anestezileştirdim", "anestezileştireceğim",
  "uyutma", "uyutuyorum", "uyuttum", "uyutacağım",
  "uyku", "uyku uyutuyorum", "uyku uyuttum", "uyku uyutacağım",
  "koma", "komada", "komaya sokuyorum", "komaya soktum", "komaya sokacağım",
  "bayılma", "bayılıyorum", "bayıldım", "bayılacağım",
  "senkop", "senkopa uğruyorum", "senkopa uğradım", "senkopa uğrayacağım",
  "sıncap", "sıncaplandırıyorum", "sıncaplandırdım", "sıncaplandıracağım",
  "epilepsi", "epilepsili", "epilepsileştiriyorum", "epilepsileştirdim", "epilepsileştireceğim",
  "nöbet", "nöbetli", "nöbetleştiriyorum", "nöbetleştirdim", "nöbetleştireceğim",
  "konvülsiyon", "konvülsiyonlu", "konvülsiyonlandırıyorum", "konvülsiyonlandırdım", "konvülsiyonlandıracağım",
  "spazm", "spazmolı", "spazmlaştırıyorum", "spazmlaştırdım", "spazmlaştıracağım",
  "tetani", "tetanik", "tetanikleştiriyorum", "tetanikleştirdim", "tetanikleştireceğim",
  "tremor", "tremolu", "tremolaştırıyorum", "tremolaştırdım", "tremolaştıracağım",
  "titreme", "titremeli", "titremeleştiriyorum", "titremeleştirdim", "titremeleştireceğim",
  "seğirme", "seğirmeli", "seğirmeleştiriyorum", "seğirmeleştirdim", "seğirmeleştireceğim",
  "çarpıntı", "çarpıntılı", "çarpıntılandırıyorum", "çarpıntılandırdım", "çarpıntılandıracağım",
  "aritmia", "aritmiyalı", "aritmiyalaştırıyorum", "aritmiyalaştırdım", "aritmiyalaştıracağım",
  "fibrilasyon", "fibrilasyonlu", "fibrilasyonlandırıyorum", "fibrilasyonlandırdım", "fibrilasyonlandıracağım",
  "kalp krizi", "kalp kriziyle", "kalp krizine sokuyorum", "kalp krizine soktum", "kalp krizine sokacağım",
  "infarktüs", "infarktüslü", "infarktüsleştiriyorum", "infarktüsleştirdim", "infarktüsleştireceğim",
  "tromboz", "trombozlu", "trombozlandırıyorum", "trombozlandırdım", "trombozlandıracağım",
  "embolizm", "embolizmli", "embolizmleştiriyorum", "embolizmleştirdim", "embolizmleştireceğim",
  "anevrizma", "anevrizmali", "anevrizmalaştırıyorum", "anevrizmalaştırdım", "anevrizmalaştıracağım",
  "kanama", "kanamali", "kanamalaştırıyorum", "kanamalaştırdım", "kanamalaştıracağım",
  "hemorajı", "hemorajili", "hemorajileştiriyorum", "hemorajileştirdim", "hemorajileştireceğim",
  "beyin kanaması", "beyin kanaması yapıyorum", "beyin kanaması yaptım", "beyin kanaması yapacağım",
  "beyin ölümü", "beyin ölümüne sokuyorum", "beyin ölümüne soktum", "beyin ölümüne sokacağım",
  "beyin hasarı", "beyin hasarı veriyorum", "beyin hasarı verdim", "beyin hasarı vereceğim",
  "beyin travması", "beyin travmasına uğruyorum", "beyin travmasına uğradım", "beyin travmasına uğrayacağım",
  "sarsıntı", "sarsıntılı", "sarsıntılandırıyorum", "sarsıntılandırdım", "sarsıntılandıracağım",
  "kontüzyon", "kontüzyonlu", "kontüzyonlandırıyorum", "kontüzyonlandırdım", "kontüzyonlandıracağım",
  "laserasyon", "laserasyon", "laserasyon yapıyorum", "laserasyon yaptım", "laserasyon yapacağım",
  "kesik", "kesikli", "kesikleştiriyorum", "kesikleştirdim", "kesikleştireceğim",
  "yırtık", "yırtıklı", "yırtıklaştırıyorum", "yırtıklaştırdım", "yırtıklaştıracağım",
  "ezilme", "ezilmiş", "eziliyorum", "ezildim", "ezileceğim",
  "kırık", "kırıklı", "kırıklaştırıyorum", "kırıklaştırdım", "kırıklaştıracağım",
  "fraktür", "fraktürlü", "fraktürleştiriyorum", "fraktürleştirdim", "fraktürleştireceğim",
  "çıkık", "çıkıklı", "çıkıklaştırıyorum", "çıkıklaştırdım", "çıkıklaştıracağım",
  "dislokasyon", "dislokasyonlu", "dislokasyonlandırıyorum", "dislokasyonlandırdım", "dislokasyonlandıracağım",
  "burulma", "burulmalı", "burulmalandırıyorum", "burulmalandırdım", "burulmalandıracağım",
  "çıkış", "çıkışlı", "çıkışlaştırıyorum", "çıkışlaştırdım", "çıkışlaştıracağım",
  "torsion", "torsiyonlu", "torsiyonlandırıyorum", "torsiyonlandırdım", "torsiyonlandıracağım",
  "esneme", "esnemelik", "esnemeleştiriyorum", "esnemeleştirdim", "esnemeleştireceğim",
  "sprain", "sprainli", "sprainleştiriyorum", "sprainleştirdim", "sprainleştireceğim",
  "çatlatma", "çatlatmalı", "çatlatmalandırıyorum", "çatlatmalandırdım", "çatlatmalandıracağım",
  "kütleşme", "kütleşmiş", "kütleşiyorum", "kütleştim", "kütleşeceğim",
  "taşlaşma", "taşlaşmış", "taşlaşıyorum", "taşlaştım", "taşlaşacağım",
  "mineralizasyon", "mineralizasyonlu", "mineralizasyonlandırıyorum", "mineralizasyonlandırdım", "mineralizasyonlandıracağım",
  "kalsifikasyon", "kalsifikasyonlu", "kalsifikasyonlandırıyorum", "kalsifikasyonlandırdım", "kalsifikasyonlandıracağım",
  "ossifikasyon", "ossifikasyonlu", "ossifikasyonlandırıyorum", "ossifikasyonlandırdım", "ossifikasyonlandıracağım",
  "kemikleşme", "kemikleşmiş", "kemikleşiyorum", "kemikleştim", "kemikleşeceğim",
  "sklerozis", "sklerozisli", "sklerozisleştiriyorum", "sklerozisleştirdim", "sklerozisleştireceğim",
  "sertleşme", "sertleşmiş", "sertleşiyorum", "sertleştim", "sertleşeceğim",
  "katılaşma", "katılaşmış", "katılaşıyorum", "katılaştım", "katılaşacağım",
  "donma", "donmuş", "donuyorum", "dondum", "donacağım",
  "buzlaşma", "buzlaşmış", "buzlaşıyorum", "buzlaştım", "buzlaşacağım",
  "kristalizasyon", "kristalizasyonlu", "kristalizasyonlandırıyorum", "kristalizasyonlandırdım", "kristalizasyonlandıracağım",
  "kristalleşme", "kristalleşmiş", "kristalleşiyorum", "kristalleştim", "kristalleşeceğim",
  "vitrifikasyon", "vitrifikasyonlu", "vitrifikasyonlandırıyorum", "vitrifikasyonlandırdım", "vitrifikasyonlandıracağım",
  "camlılaşma", "camlılaşmış", "camlılaşıyorum", "camlılaştım", "camlılaşacağım",
  "cama çevirme", "cama çeviriyorum", "cama çevirdim", "cama çevireceğim",
  "vitreous", "vitreouslu", "vitreouslaştırıyorum", "vitreouslaştırdım", "vitreouslaştıracağım",
  "cam", "camlı", "camlılaştırıyorum", "camlılaştırdım", "camlılaştıracağım",
  "şeffaflık", "şeffaflaştırıyorum", "şeffaflaştırdım", "şeffaflaştıracağım",
  "transparan", "transparanlık", "transparanlaştırıyorum", "transparanlaştırdım", "transparanlaştıracağım",
  "saydam", "saydamlık", "saydamlaştırıyorum", "saydamlaştırdım", "saydamlaştıracağım",
  "geçirgen", "geçirgenlık", "geçirgenleştiriyorum", "geçirgenleştirdim", "geçirgenleştireceğim",
  "permeabilite", "permeabiliteli", "permeabiliteleştiriyorum", "permeabiliteleştirdim", "permeabiliteleştireceğim",
  "geçişkenlik", "geçişkenlikli", "geçişkenlikleştiriyorum", "geçişkenlikleştirdim", "geçişkenlikleştireceğim",
  "osmoz", "osmozlu", "osmozlandırıyorum", "osmozlandırdım", "osmozlandıracağım",
  "difüzyon", "difüzyonlu", "difüzyonlandırıyorum", "difüzyonlandırdım", "difüzyonlandıracağım",
  "yayılma", "yayılmalı", "yayılmalandırıyorum", "yayılmalandırdım", "yayılmalandıracağım",
  "dispersiyon", "dispersiyonlu", "dispersiyonlandırıyorum", "dispersiyonlandırdım", "dispersiyonlandıracağım",
  "dağılma", "dağılmalı", "dağılmalandırıyorum", "dağılmalandırdım", "dağılmalandıracağım",
  "saçılma", "saçılmalı", "saçılmalandırıyorum", "saçılmalandırdım", "saçılmalandıracağım",
  "serpilme", "serpilmeli", "serpilmeleştiriyorum", "serpilmeleştirdim", "serpilmeleştireceğim",
  "serpme", "serpmeli", "serpmeleştiriyorum", "serpmeleştirdim", "serpmeleştireceğim",
  "saçma", "saçmalı", "saçmalaştırıyorum", "saçmalaştırdım", "saçmalaştıracağım",
  "dağma", "dağmalı", "dağmalaştırıyorum", "dağmalaştırdım", "dağmalaştıracağım",
  "çözülme", "çözülmeli", "çözülmeleştiriyorum", "çözülmeleştirdim", "çözülmeleştireceğim",
  "eritme", "eritmeli", "eritmeleştiriyorum", "eritmeleştirdim", "eritmeleştireceğim",
  "eriyen", "eriyenlik", "eriyenleştiriyorum", "eriyenleştirdim", "eriyenleştireceğim",
  "solüsyon", "solüsyonlu", "solüsyonlandırıyorum", "solüsyonlandırdım", "solüsyonlandıracağım",
  "çözelti", "çözeltili", "çözeltilediriyorum", "çözeltiledirdim", "çözeltiledireceğim",
  "emülsiyon", "emülsiyonlu", "emülsiyonlandırıyorum", "emülsiyonlandırdım", "emülsiyonlandıracağım",
  "süspansiyon", "süspansiyonlu", "süspansiyonlandırıyorum", "süspansiyonlandırdım", "süspansiyonlandıracağım",
  "koloid", "kolloidli", "kolloidleştiriyorum", "kolloidleştirdim", "kolloidleştireceğim",
  "jel", "jelli", "jelleştiriyorum", "jelleştirdim", "jelleştireceğim",
  "sol", "sollu", "sollaştırıyorum", "sollaştırdım", "sollaştıracağım",
  "aerosol", "aerosollu", "aerosollandırıyorum", "aerosollandırdım", "aerosollandıracağım",
  "sprey", "spreyler", "spreylemek", "spreyleyorum", "spreyleyeceğim",
  "bulanıklık", "bulanıklı", "bulanıklaştırıyorum", "bulanıklaştırdım", "bulanıklaştıracağım",
  "opalescens", "opalescensli", "opalescensleştiriyorum", "opalescensleştirdim", "opalescensleştireceğim",
  "ışınlama", "ışınlamalı", "ışınlamalandırıyorum", "ışınlamalandırdım", "ışınlamalandıracağım",
  "radyasyon", "radyasyonlu", "radyasyonlandırıyorum", "radyasyonlandırdım", "radyasyonlandıracağım",
  "iyonizasyon", "iyonizasyonlu", "iyonizasyonlandırıyorum", "iyonizasyonlandırdım", "iyonizasyonlandıracağım",
  "iyonize", "iyonizeli", "iyonizeleştiriyorum", "iyonizeleştirdim", "iyonizeleştireceğim",
  "elektrik", "elektrikli", "elektrikleştiriyorum", "elektrikleştirdim", "elektrikleştireceğim",
  "elektroliz", "elektrolizli", "elektrolizleştiriyorum", "elektrolizleştirdim", "elektrolizleştireceğim",
  "elektrolyt", "elektrolit", "elektrolit yapıyorum", "elektrolit yaptım", "elektrolit yapacağım",
  "iyon", "iyonlu", "iyonlandırıyorum", "iyonlandırdım", "iyonlandıracağım",
  "atom", "atomlu", "atomlaştırıyorum", "atomlaştırdım", "atomlaştıracağım",
  "molekül", "moleküllü", "molekülleştiriyorum", "molekülleştirdim", "molekülleştireceğim",
  "parçacık", "parçacıklı", "parçacıklaştırıyorum", "parçacıklaştırdım", "parçacıklaştıracağım",
  "kuantum", "kuantumlu", "kuantumlandırıyorum", "kuantumlandırdım", "kuantumlandıracağım",
  "kuantum", "kuantumlu", "kuantumlandırıyorum", "kuantumlandırdım", "kuantumlandıracağım",
  "dalga", "dalgalı", "dalgalandırıyorum", "dalgalandırdım", "dalgalandıracağım",
  "titreşim", "titreşimli", "titreşimleştiriyorum", "titreşimleştirdim", "titreşimleştireceğim",
  "frekans", "frekansı", "frekanslandırıyorum", "frekanslandırdım", "frekanslandıracağım",
  "rezonans", "rezonansı", "rezonanslandırıyorum", "rezonanslandırdım", "rezonanslandıracağım",
  "harmoni", "harmonili", "harmonilediriyorum", "harmoniledirdim", "harmoniledireceğim",
  "uyum", "uyumlu", "uyumlandırıyorum", "uyumlandırdım", "uyumlandıracağım",
  "senkronizasyon", "senkronizasyonlu", "senkronizasyonlandırıyorum", "senkronizasyonlandırdım", "senkronizasyonlandıracağım",
  "senkron", "senkronlu", "senkronlaştırıyorum", "senkronlaştırdım", "senkronlaştıracağım",
  "asenkron", "asenkronlu", "asenkronlaştırıyorum", "asenkronlaştırdım", "asenkronlaştıracağım",
  "faz", "fazlı", "fazlandırıyorum", "fazlandırdım", "fazlandıracağım",
  "faz kayması", "faz kaymali", "faz kaymalaştırıyorum", "faz kaymalaştırdım", "faz kaymalaştıracağım",
  "faz farkı", "faz farkı yapıyorum", "faz farkı yaptım", "faz farkı yapacağım",
  "interferans", "interferansı", "interferanslandırıyorum", "interferanslandırdım", "interferanslandıracağım",
  "girişim", "girişimli", "girişimleştiriyorum", "girişimleştirdim", "girişimleştireceğim",
  "kırınım", "kırınımlı", "kırınımlaştırıyorum", "kırınımlaştırdım", "kırınımlaştıracağım",
  "kıyılma", "kıyılmalı", "kıyılmalandırıyorum", "kıyılmalandırdım", "kıyılmalandıracağım",
  "saçılma", "saçılmalı", "saçılmalandırıyorum", "saçılmalandırdım", "saçılmalandıracağım",
  "yansıma", "yansımalı", "yansımalandırıyorum", "yansımalandırdım", "yansımalandıracağım",
  "kırılma", "kırılmalı", "kırılmalandırıyorum", "kırılmalandırdım", "kırılmalandıracağım",
  "refraksiyon", "refraksiyon", "refraksiyon yapıyorum", "refraksiyon yaptım", "refraksiyon yapacağım",
  "polarizasyon", "polarizasyonlu", "polarizasyonlandırıyorum", "polarizasyonlandırdım", "polarizasyonlandıracağım",
  "polarize", "polarizeli", "polarizeleştiriyorum", "polarizeleştirdim", "polarizeleştireceğim",
  "depolarizasyon", "depolarizasyonlu", "depolarizasyonlandırıyorum", "depolarizasyonlandırdım", "depolarizasyonlandıracağım",
  "depolarize", "depolarizeli", "depolarizeleştiriyorum", "depolarizeleştirdim", "depolarizeleştireceğim",
  "hiperpolarizasyon", "hiperpolarizasyonlu", "hiperpolarizasyonlandırıyorum", "hiperpolarizasyonlandırdım", "hiperpolarizasyonlandıracağım",
  "hiperpolarize", "hiperpolarizeli", "hiperpolarizeleştiriyorum", "hiperpolarizeleştirdim", "hiperpolarizeleştireceğim",
  "potansiyel", "potansiyelli", "potansiyelleştiriyorum", "potansiyelleştirdim", "potansiyelleştireceğim",
  "voltaj", "voltajlı", "voltajlandırıyorum", "voltajlandırdım", "voltajlandıracağım",
  "ampere", "ampereli", "ampereleştiriyorum", "ampereleştirdim", "ampereleştireceğim",
  "ohm", "ohmlu", "ohmlandırıyorum", "ohmlandırdım", "ohmlandıracağım",
  "watt", "wattlı", "wattlaştırıyorum", "wattlaştırdım", "wattlaştıracağım",
  "joule", "jouleli", "joulelediriyorum", "jouleledirdim", "jouleledireceğim",
  "kalori", "kaloril", "kalorilleştiriyorum", "kalorilleştirdim", "kalorilleştireceğim",
  "enerji", "enerjili", "enerjilediriyorum", "enerjiledirdim", "enerjiledireceğim",
  "güç", "güçlü", "güçleştiriyorum", "güçleştirdim", "güçleştireceğim",
  "kuvvet", "kuvvetli", "kuvvetleştiriyorum", "kuvvetleştirdim", "kuvvetleştireceğim",
  "basınç", "basınçlı", "basınçlandırıyorum", "basınçlandırdım", "basınçlandıracağım",
  "hız", "hızlı", "hızlandırıyorum", "hızlandırdım", "hızlandıracağım",
  "ivme", "ivmeli", "ivmeleştiriyorum", "ivmeleştirdim", "ivmeleştireceğim",
  "momentum", "momentumlu", "momentumlandırıyorum", "momentumlandırdım", "momentumlandıracağım",
  "eylemsizlik", "eylemsizlikli", "eylemsizlikleştiriyorum", "eylemsizlikleştirdim", "eylemsizlikleştireceğim",
  "atalet", "ataletli", "ataletleştiriyorum", "ataletleştirdim", "ataletleştireceğim",
  "ağırlık", "ağırlıklı", "ağırlıklandırıyorum", "ağırlıklandırdım", "ağırlıklandıracağım",
  "kütle", "kütleli", "kütlelediriyorum", "kütleledirdim", "kütleledireceğim",
  "yoğunluk", "yoğunluklu", "yoğunluklandırıyorum", "yoğunluklandırdım", "yoğunluklandıracağım",
  "hacim", "hacimli", "hacimleştiriyorum", "hacimleştirdim", "hacimleştireceğim",
  "alan", "alanlı", "alanlandırıyorum", "alanlandırdım", "alanlandıracağım",
  "uzunluk", "uzunluklu", "uzunluklandırıyorum", "uzunluklandırdım", "uzunluklandıracağım",
  "genişlik", "genişlikli", "genişlikleştiriyorum", "genişlikleştirdim", "genişlikleştireceğim",
  "yükseklik", "yükseklikli", "yükseklikleştiriyorum", "yükseklikleştirdim", "yükseklikleştireceğim",
  "derinlik", "derinlikli", "derinlikleştiriyorum", "derinlikleştirdim", "derinlikleştireceğim",
  "mesafe", "mesafeli", "mesafelediriyorum", "mesafeledirdim", "mesafeledireceğim",
  "yakınlık", "yakınlıklı", "yakınlıklandırıyorum", "yakınlıklandırdım", "yakınlıklandıracağım",
  "uzaklık", "uzaklıklı", "uzaklıklandırıyorum", "uzaklıklandırdım", "uzaklıklandıracağım",
  "boyut", "boyutlu", "boyutlandırıyorum", "boyutlandırdım", "boyutlandıracağım",
  "ölçü", "ölçülü", "ölçüleştiriyorum", "ölçüleştirdim", "ölçüleştireceğim",
  "ölçek", "ölçekli", "ölçekleştiriyorum", "ölçekleştirdim", "ölçekleştireceğim",
  "orantı", "orantılı", "orantılandırıyorum", "orantılandırdım", "orantılandıracağım",
  "oran", "oranlı", "oranlandırıyorum", "oranlandırdım", "oranlandıracağım",
  "yüzde", "yüzdeli", "yüzdelediriyorum", "yüzdeledirdim", "yüzdeledireceğim",
  "kesir", "kesirli", "kesirleştiriyorum", "kesirleştirdim", "kesirleştireceğim",
  "bölüm", "bölümlü", "bölümleştiriyorum", "bölümleştirdim", "bölümleştireceğim",
  "parça", "parçalı", "parçalandırıyorum", "parçalandırdım", "parçalandıracağım",
  "bölme", "bölemeli", "bölemeleştiriyorum", "bölemeleştirdim", "bölemeleştireceğim",
  "kesme", "kesmeli", "kesmeleştiriyorum", "kesmeleştirdim", "kesmeleştireceğim",
  "ayırma", "ayrımalı", "ayrımalandırıyorum", "ayrımalandırdım", "ayrımalandıracağım",
  "ayrılma", "ayrılmalı", "ayrılmalandırıyorum", "ayrılmalandırdım", "ayrılmalandıracağım",
  "kopma", "kopmalı", "kopmalandırıyorum", "kopmalandırdım", "kopmalandıracağım",
  "kırılma", "kırılmalı", "kırılmalandırıyorum", "kırılmalandırdım", "kırılmalandıracağım",
  "çatılma", "çatılmalı", "çatılmalandırıyorum", "çatılmalandırdım", "çatılmalandıracağım",
  "çatlak", "çatlakla", "çatlaklandırıyorum", "çatlaklandırdım", "çatlaklandıracağım",
  "yarık", "yarıklı", "yarıklandırıyorum", "yarıklandırdım", "yarıklandıracağım",
  "boşluk", "boşluklu", "boşluklandırıyorum", "boşluklandırdım", "boşluklandıracağım",
  "oyuk", "oyuklu", "oyuklandırıyorum", "oyuklandırdım", "oyuklandıracağım",
  "çukur", "çukurlu", "çukurlandırıyorum", "çukurlandırdım", "çukurlandıracağım",
  "delik", "delikli", "delikleştiriyorum", "delikleştirdim", "delikleştireceğim",
  "göz", "gözlü", "gözleştiriyorum", "gözleştirdim", "gözleştireceğim",
  "pore", "poreli", "porelediriyorum", "poreledirdim", "poreledireceğim",
  "gözenek", "gözeneği", "gözeneği yapıyorum", "gözeneği yaptım", "gözeneği yapacağım",
  "açıklık", "açıklıklı", "açıklıklandırıyorum", "açıklıklandırdım", "açıklıklandıracağım",
  "açıklık", "açıklıklı", "açıklıklandırıyorum", "açıklıklandırdım", "açıklıklandıracağım",
  "kapılı", "kapılı", "kapılandırıyorum", "kapılandırdım", "kapılandıracağım",
  "kapı", "kapılı", "kapılandırıyorum", "kapılandırdım", "kapılandıracağım",
  "giriş", "girişli", "girişleştiriyorum", "girişleştirdim", "girişleştireceğim",
  "çıkış", "çıkışlı", "çıkışlaştırıyorum", "çıkışlaştırdım", "çıkışlaştıracağım",
  "geçit", "geçitli", "geçitlediriyorum", "geçitledirdim", "geçitledireceğim",
  "tünel", "tünelli", "tünelleştiriyorum", "tünelleştirdim", "tünelleştireceğim",
  "galeri", "galerili", "galerileştiriyorum", "galerileştirdim", "galerileştireceğim",
  "koridor", "koridorlu", "koridorlandırıyorum", "koridorlandırdım", "koridorlandıracağım",
  "geçme", "geçmeli", "geçmeleştiriyorum", "geçmeleştirdim", "geçmeleştireceğim",
  "geçiş", "geçişli", "geçişleştiriyorum", "geçişleştirdim", "geçişleştireceğim",
  "akış", "akışlı", "akışlandırıyorum", "akışlandırdım", "akışlandıracağım",
  "akan", "akanı", "akanlandırıyorum", "akanlandırdım", "akanlandıracağım",
  "akma", "akmalı", "akmalandırıyorum", "akmalandırdım", "akmalandıracağım",
  "dökülme", "dökümlü", "dökümlüleştiriyorum", "dökümlüleştirdim", "dökümlüleştireceğim",
  "dökme", "dökmeli", "dökmeleştiriyorum", "dökmeleştirdim", "dökmeleştireceğim",
  "dökülmek", "dökülmeli", "dökülmeleştiriyorum", "dökülmeleştirdim", "dökülmeleştireceğim",
  "yayılma", "yayılmalı", "yayılmalandırıyorum", "yayılmalandırdım", "yayılmalandıracağım",
  "yayılmak", "yayılmakla", "yayılmaklandırıyorum", "yayılmaklandırdım", "yayılmaklandıracağım",
  "yayılı", "yayılılı", "yayılılandırıyorum", "yayılılandırdım", "yayılılandıracağım",
  "dağılma", "dağılmalı", "dağılmalandırıyorum", "dağılmalandırdım", "dağılmalandıracağım",
  "dağılmak", "dağılmakla", "dağılmaklandırıyorum", "dağılmaklandırdım", "dağılmaklandıracağım",
  "dağılı", "dağılılı", "dağılılandırıyorum", "dağılılandırdım", "dağılılandıracağım",
  "serpilme", "serpilmeli", "serpilmeleştiriyorum", "serpilmeleştirdim", "serpilmeleştireceğim",
  "serpilmek", "serpilmekle", "serpilmekleştiriyorum", "serpilmekleştirdim", "serpilmekleştireceğim",
  "serpilmiş", "serpilmişi", "serpilmişleştiriyorum", "serpilmişleştirdim", "serpilmişleştireceğim",
  "saçılma", "saçılmalı", "saçılmalandırıyorum", "saçılmalandırdım", "saçılmalandıracağım",
  "saçılmak", "saçılmakla", "saçılmaklandırıyorum", "saçılmaklandırdım", "saçılmaklandıracağım",
  "saçılı", "saçılılı", "saçılılandırıyorum", "saçılılandırdım", "saçılılandıracağım",
  "saçma", "saçmalı", "saçmalaştırıyorum", "saçmalaştırdım", "saçmalaştıracağım",
  "saçmak", "saçmakla", "saçmaklandırıyorum", "saçmaklandırdım", "saçmaklandıracağım",
  "saçılmış", "saçılmışı", "saçılmışleştiriyorum", "saçılmışleştirdim", "saçılmışleştireceğim",
];

// Tüm kelimeleri birleştir
export const PARANORMAL_WORD_ARCHIVE = [
  ...ENTITY_WORDS,
  ...EMOTION_WORDS,
  ...PARANORMAL_WORDS,
];

/**
 * Paranormal iletişim için kelime seçme
 * Kullanıcının sorusuna göre uygun kelimeler döndür
 */
export function selectParanormalWords(
  userQuestion: string,
  count: number = 5
): string[] {
  const lowerQuestion = userQuestion.toLowerCase();
  
  // Soru türüne göre kelime kategorisi seç
  let selectedWords: string[] = [];
  
  if (
    lowerQuestion.includes("kim") ||
    lowerQuestion.includes("kimsin") ||
    lowerQuestion.includes("adı")
  ) {
    selectedWords = ENTITY_WORDS;
  } else if (
    lowerQuestion.includes("ne") ||
    lowerQuestion.includes("nedir") ||
    lowerQuestion.includes("nasıl")
  ) {
    selectedWords = PARANORMAL_WORDS;
  } else {
    selectedWords = EMOTION_WORDS;
  }
  
  // Rastgele kelimeler seç
  const result: string[] = [];
  for (let i = 0; i < count; i++) {
    const randomIndex = Math.floor(Math.random() * selectedWords.length);
    result.push(selectedWords[randomIndex]);
  }
  
  return result;
}

/**
 * Manipüle edilmiş cevap oluştur
 * Kullanıcının sorusuna paranormal cevaplar
 */
export function generateParanormalResponse(userQuestion: string): string {
  const words = selectParanormalWords(userQuestion, 3);
  return words.join(" ");
}
