// Spanish word bank for VOX — native-speaker quality, parallel to word-bank.ts (Turkish).
// Category counts mirror word-bank-en.ts exactly. PHONEMES omitted (not used by VoxWordBank).

export const NINE_PHRASES: string[] = [
  "mi bebé", "mi nieto", "mi amor", "mi hijo", "mi pequeño", "mi corderito",
  "mi corazón", "la luz de mis ojos", "el rincón de mi corazón", "ven a mí", "¿dónde estás, mi niño", "te echo de menos",
  "no me dejes", "te espero con tanta añoranza", "pienso en vosotros cada noche", "quiero escuchar tu voz", "déjame ver tu rostro una vez más", "viniste a mí en sueños, pero me desperté",
  "¿por qué no vienes", "¿me escuchas", "aquí hace frío", "no hay luz", "qué oscuro está", "aún sigo aquí",
  "no me olvides", "mi tumba está desolada", "ya nadie viene", "me quedé completamente sola", "cuánto tiempo ha pasado", "¿así era la muerte",
  "te estoy esperando", "ven algún día", "sácame de aquí", "la tierra está fría", "la tierra está oscura", "me quedé fría bajo la piedra",
  "nadie sabe que estoy aquí", "es tan difícil aquí", "de todas formas no puedo irme", "estoy atada a este mundo", "sigo esperando", "te oigo pero no puedo verte",
  "vuestras voces me llegan pero desde tan lejos", "ah, mi querido hijo", "que todo vaya bien", "que Dios te proteja", "reza", "haz tus oraciones",
  "hay gente malvada ahí fuera", "ten cuidado, mi querido", "no te pierdas en el camino", "sé honesto", "vive con honor", "respeta a tus mayores",
  "llama a tus seres queridos y pregunta por ellos", "huye del pecado", "arrepiéntete", "gana tu sustento honestamente", "amaos los unos a los otros", "no os dejéis dividir",
  "qué sueños tan oscuros", "lloro todas las noches", "no veo el amanecer", "esa oscura presencia me siguió hasta aquí", "vi algo antes de morir", "hay algo que debo decirte",
  "un secreto se esconde bajo esta casa", "suben ruidos de las entrañas de la tierra", "llamaré a la puerta a medianoche", "vendré a visitarte en tus sueños", "me verás mientras duermes", "estaré ahí cuando se cierren tus ojos",
  "ojalá hubiéramos pasado más tiempo juntos", "quiero decir todo lo que nunca dije", "perdóname, hijo mío", "yo también cometí mis errores", "daría todo por volver atrás", "ojalá te lo hubiera dicho antes",
  "me fui demasiado pronto", "no estaba lista", "no quería dejaros", "estoy entre este mundo y el siguiente", "vendré cuando se abra el umbral", "durante el eclipse lunar podrás oírme",
  "los viernes por la noche soy más fuerte", "me siento en el cementerio a llorar", "los que están cerca de mí también quieren verte", "este lugar está lleno — y sin embargo completamente silencioso", "corro hacia la luz pero no consigo alcanzarla", "algún día lo entenderás",
];

export const GIRL_CHILD_PHRASES: string[] = [
  "¿quieres jugar conmigo", "no quiero estar sola", "¿por qué nadie juega conmigo", "perdí mi muñeca", "¿dónde están mis juguetes", "quiero volver a casa",
  "¿dónde está mi mamá", "¿dónde está mi papá", "¿me están esperando", "no quiero llorar pero sigo llorando", "nadie me ve", "¿soy invisible",
  "¿no hay nadie aquí", "estoy completamente sola aquí", "quiero una amiga", "¿puedo jugar contigo", "tengo miedo", "¿por qué está tan oscuro",
  "¿puedes encender la luz", "vi algo", "volvió", "viene todas las noches", "el hombre malo volvió", "me tocó",
  "cuando grito se va", "cierro los ojos", "empecé a contar hacia atrás desde cien", "hay alguien detrás de mí", "¿lo ves", "él también te ve",
  "no vengas aquí", "es peligroso aquí", "te seguirá a ti también", "me dejaron aquí", "¿por qué me abandonaron", "las paredes hablan",
  "alguien mira por la ventana", "esa no soy yo en el espejo", "mi sombra se mueve sola", "vienen ruidos del techo", "alguien está en la escalera — cuento sus pasos", "mi perro ve algo en el rincón",
  "mi gato huyó de la habitación", "las flores se marchitaron cuando entré", "el reloj se paró exactamente en ese momento", "mi mamá me está llamando", "despacio", "hm hm",
  "no no no", "para para para", "no quiero no quiero", "yo también lo veo", "tengo tanto frío", "no me dejes",
  "abrázame por favor", "dame la mano", "no te vayas", "voy a algún lugar mientras duermo", "también estoy allí en mis sueños", "me despierto agotada",
  "¿qué pasa por las noches", "¿tú también ves cosas extrañas de noche", "hay ojos en la oscuridad", "están esperando", "he estado aquí demasiado tiempo", "quiero salir ahora",
  "llévame contigo por favor", "quiero ir hacia la luz", "no puedo pasar por esa puerta", "algo bloquea el camino", "¿cómo te llamas", "¿puedo confiar en ti",
  "no llores — si lloras, lloro yo también", "vete de aquí, por tu propio bien",
];

export const PHANTOM_PHRASES: string[] = [
  "estoy aquí", "¿me escuchas", "ayuda", "no puedo salir", "estamos atrapados", "dejadnos ir",
  "alejaos de ahí", "estás en peligro", "viene", "corre", "todos vosotros estáis en peligro", "¿escucháis",
  "yo también fui como tú", "ya es demasiado tarde", "no te vayas", "esta casa guarda un secreto", "estoy dentro de las paredes", "escúchame",
  "son reales", "nadie me creyó", "ahora lo entendéis", "este lugar es el infierno", "me perdí en la oscuridad", "dadme una voz",
  "hay una habitación bajo el suelo", "sé dónde está la puerta secreta", "no abráis el cofre de la bodega", "¿sabéis qué hay detrás de ese muro", "el antiguo dueño sigue aquí", "esta casa lleva un secreto de cien años",
  "alguien llora en el sótano", "hay pasos en el tejado", "ajustad la frecuencia", "mi señal es débil", "la conexión se corta", "estoy muy lejos",
  "os escucho", "no vengáis aquí", "el canal está abierto", "os recibo", "intento establecer contacto", "demasiada estática",
  "la frecuencia se desvía", "cambiad de banda", "pasad a través del ruido y me oiréis", "necesito amplificación", "la onda sonora se rompe", "interferencia interdimensional",
  "no miréis atrás", "cerrad la puerta", "no apaguéis las luces", "no estéis solos", "no disperséis el grupo", "hay una presencia poderosa aquí",
  "la energía negativa es abrumadora", "la zona está contaminada", "hay que purificarla", "grabar esto", "mirad la cámara", "hay algo a vuestra izquierda",
  "cuidado cuando baje la temperatura", "¿podéis respirar", "hablo desde muy lejos", "mi voz apenas os llega", "la energía se agota", "hablo con mis últimas fuerzas",
  "quedaos en silencio para oírme", "contened el aliento un momento", "solo se me puede oír en completo silencio", "susurro para que ellos no me oigan", "guardad esto entre nosotros", "nadie más debe saberlo",
  "me dirijo específicamente a ti", "fuiste elegido para esto", "alguien especial vino esta noche", "hay una persona sensible entre vosotros", "uno de vosotros está abierto — espiritualmente", "encontradle entre vosotros",
];

export const HOME_OBJECT_PHRASES: string[] = [
  "mira la silla que hay a tu lado", "vi la silla de la izquierda", "hay alguien detrás de esa silla", "estoy sentado en el sofá ahora mismo", "solía sentarme en tu silla", "ese asiento vacío está ocupado",
  "mira debajo del sofá", "hay una zona fría junto a la silla", "no toques la silla todavía", "abre el tercer cajón", "escondí algo en el cajón de arriba", "me encontrarás en el cajón de abajo",
  "cierra ese cajón", "la puerta del armario quedará abierta esta noche", "hay alguien dentro del armario", "abre los cajones uno por uno", "detente en el último cajón", "cierra el armario con llave antes de que caiga la noche",
  "no mires debajo de tu cama", "hay algo bajo tu almohada", "estoy sentado en el borde de la cama", "mira tu almohada cuando te despiertes por la mañana", "no duermas en esa cama esta noche", "me metí bajo las sábanas",
  "si la cama parece hundirse por la noche, soy yo", "observo tu cara mientras duermes", "mira atentamente en el espejo", "hay dos caras en tu espejo ahora mismo", "estoy al otro lado del espejo", "cubre el espejo por la noche",
  "mira por la ventana", "aprieto mi cara contra el cristal", "¿alguna vez has apartado las cortinas y mirado afuera de noche", "mira el vaho en el cristal", "no abras la ventana esta noche", "me cuelo por las persianas",
  "¿viste la sombra que pasó bajo la puerta", "cerraste la puerta con llave, ¿verdad", "alguien camina por el pasillo", "el pomo de la puerta gira despacio", "espero justo detrás de la puerta", "puedo entrar sin llamar",
  "no abras esa puerta", "cuando la puerta cruje — soy yo", "¿oíste caer algo en la cocina", "hago gotear el grifo así", "escucha cómo ha cambiado el ruido de la nevera", "¿estás seguro de que apagaste los fogones",
  "¿están todos los cuchillos de cocina en su sitio", "mira el estante de cristal", "hay alguien bajo la mesa de la cocina", "acabo de mover tu olla", "estoy a tu lado mientras te duchas", "escribo en el vaho de tu espejo",
  "espero detrás de la cortina de ducha", "cerrar el baño con llave no será suficiente", "te observo llenar la bañera", "la puerta del baño quedará completamente abierta", "el séptimo peldaño de la escalera crujirá muy pronto", "te oigo desde la planta baja",
  "hay alguien arriba", "me quedo suspendido en la caja de la escalera", "¿oíste la puerta abajo", "no huyas por la escalera — no puedo atraparte", "voy a apagar la bombilla dentro de poco", "la luz parpadeará tres veces",
  "vigila la lámpara esta noche", "no vayas al cuadro eléctrico", "esa lámpara del rincón es mi señal", "arranca el enchufe y nunca me encontrarás", "¿te has dado cuenta de que tu reloj de pared se paró", "el reloj dará las tres de la mañana",
  "tachée ese día del calendario", "el minutero va hacia atrás", "sé que tu cumpleaños se acerca", "el rincón más oscuro de la casa es mío", "mira la esquina inferior derecha de la habitación", "estoy sentado junto a la pared izquierda",
  "mira donde el techo se encuentra con la pared", "un secreto se esconde bajo esa mancha", "levanta la alfombra y echa un vistazo", "los ojos de ese cuadro son mis ojos", "¿alguna vez has mirado de cerca la fotografía del marco",
];

export const DARK_WORDS: string[] = [
  "muerte", "alma", "oscuridad", "sombra", "maldición", "miedo",
  "horror", "infierno", "tumba", "sepulcro", "ataúd", "funeral",
  "muerto", "fantasma", "djinn", "diablo", "demonio", "ifrit",
  "aparecido", "vampiro", "zombi", "esqueleto", "calavera", "sangre",
  "dolor", "grito", "gemido", "lamento", "susurro", "silencio",
  "sonido", "pisada", "trueno", "frialdad", "entraron", "contrario",
  "deriva temporal", "destino", "motivo", "del más allá", "manifestación", "espejismo",
  "espiral", "ensombrecido", "línea de susurro", "ola de frío", "desplazamiento de frecuencia", "estática",
  "acústica", "déjà vu", "visión", "silueta", "roto", "abandonado",
  "cerrado con llave", "noche", "luna", "luna llena", "nube", "niebla",
  "humo", "bruma", "sombría pesadez", "soledad", "desamparado", "perdido",
  "olvidado", "prisionero", "cautivo", "atado", "cadena", "candado",
  "llave", "puerta", "ventana", "espejo", "reflejo", "misterio",
  "secreto", "hechicería", "talismán", "amuleto", "mal de ojo", "de mal agüero",
  "negro", "de ébano", "oscuro", "profundo", "vacío", "precipicio",
  "pozo", "subterráneo", "sótano", "bodega", "túnel", "cueva",
  "mazmorra", "prisión", "hueso", "carne", "piel", "herida",
  "rastro", "mancha", "óxido", "moho", "araña", "telaraña",
  "insecto", "serpiente", "murciélago", "cuervo", "búho", "lobo",
  "zorro", "chacal", "hiena", "buitre", "escorpión", "rata",
  "fuego", "llama", "ceniza", "polvo", "tierra", "barro",
  "pantano", "tormenta", "rayo", "trueno", "terremoto", "inundación",
  "tsunami", "peste", "epidemia", "enfermedad", "veneno", "elixir",
  "bruja", "brujo", "adivina", "médium", "vidente", "chamán",
  "sacerdote", "rito", "ritual", "sacrificio", "ofrenda", "maldición",
  "magia negra", "pentagrama", "símbolo", "signo", "inscripción", "runa",
  "portal", "pasaje", "dimensión", "paralelo", "el otro lado", "el más allá",
  "el otro mundo", "limbo", "purgatorio", "puente de las almas", "balanza divina", "Azrael",
  "ángel", "demonio", "entidad", "frío", "hielo", "escarcha",
  "temblor", "escalofrío", "piel de gallina", "espina", "aliento", "pálido",
  "estertor", "gruñido", "zumbido", "vibración", "chirrido", "clic",
  "crepitar", "susurro de hojas", "tintineo", "chisporroteo", "embrujado", "embrujo",
  "atado", "seguidor", "figura de sombra", "masa negra", "sombra blanca", "bola de luz",
  "orbe", "ectoplasma", "poltergeist", "ouija", "tablero", "vela",
  "incienso", "cristal", "bola de cristal", "evocación", "sesión de espiritismo", "mediumnidad",
  "parapsicología", "telepatía", "presentimiento", "profecía", "pesadilla", "sonambulismo",
  "trance", "hipnosis", "subconsciente", "astral", "proyección", "transmigración",
  "reencarnación", "karma", "aura", "energía", "vibración", "frecuencia",
  "onda", "señal", "interferencia", "ruido", "catástrofe", "ruina",
  "apocalipsis", "juicio final", "fin", "caos", "desorden", "incertidumbre",
  "peligro", "amenaza", "advertencia", "ejecución", "patíbulo", "verdugo",
  "tormento", "tortura", "descomposición", "corrupción", "desintegración",
  "extinción", "borrado", "olvido", "desaparición", "evanescencia",
  "oscurecimiento", "ahogamiento", "combustión", "congelación", "caída", "hundimiento",
  "trampa", "emboscada", "conspiración", "intriga", "engaño", "traición",
  "decepción", "mentira", "falso", "falsificado", "ficción", "alucinación",
  "delirio", "ilusión", "fantasma", "vórtice", "remolino", "huracán",
  "tornado", "avalancha", "corrimiento de tierras", "derrumbe", "implosión", "fisura",
  "grieta", "abismo", "profundidades", "oscuridad inferior", "vacío oscuro", "nada",
  "vacuidad", "ausencia", "eternidad", "eternidad sin límites", "quietud", "podrido",
  "fétido", "pútrido", "rancio", "sin vida", "marchito", "reseco",
  "carbonizado", "hecho pedazos", "destrozado", "aplastado", "olvidado", "abandonado",
  "maldito", "condenado", "dama blanca", "terror nocturno", "el coco", "ghul",
  "gigante", "ogro", "bruja", "hombre lobo", "doppelgänger", "cíclope",
  "basilisco", "dragón", "fénix", "ave fénix", "telequinesis",
  "levitación", "aporte", "bilocación", "clarividencia", "precognición", "retrocognición",
  "psicometría", "autoscopia", "doppelgänger", "fenómeno", "anomalía", "desviación",
  "trastorno", "irregularidad", "lúgubre", "oscuro", "brumoso", "nebuloso",
  "nublado", "empapado", "azotado por la tormenta", "batido por el viento", "frío", "gélido",
  "agobiante", "sofocante", "opresivo", "inquietante", "siniestro", "perturbador",
  "escalofriante", "aterrador", "lleno de espanto", "espeluznante", "misterioso", "enigmático",
  "incomprensible", "inexplicable", "sobrenatural", "extraordinario", "de otro mundo", "extraño",
  "inquietante", "bizarro", "insólito", "inesperado", "repentino", "sin previo aviso",
  "oculto", "disimulado", "velado", "enmascarado", "disfrazado", "envuelto",
  "abandonado", "en ruinas", "espectro", "negro como el azabache", "enigma", "encantamiento",
  "escritura antigua", "adivinación", "reproche", "aparición", "por fin", "presagio",
  "testamento", "paso", "opresión", "discordia", "envolvente", "enredo",
  "retirada", "lúgubre", "hechizado", "misterioso", "mortalidad", "juicio",
  "obsesión", "delirio", "divagaciones", "ceguera espiritual", "señal del camino", "aparente",
  "oculto en el interior", "contagio", "propagación", "tu perdición", "fatalidad", "escrito en las estrellas",
  "prueba", "llanto fúnebre", "grito de muerte", "reverberación", "ecos", "voces del más allá",
  "resonancia", "reflejo", "proyección de sombra", "ilusión", "forma de sombra", "silueta oscura",
  "sombra blanca", "visión nebulosa", "cosmos", "dimensional", "temporal",
  "espacial", "universal", "todo-abarcador",
  "pulso del más allá", "emanación", "fenómeno inexplicable",
];

export const DARK_PHRASES: string[] = [
  "ven aquí", "escúchame", "ayúdame", "no me dejes", "no te vayas", "estoy aquí",
  "te veo", "mira detrás de ti", "ten cuidado", "huye", "estoy muerto", "encuéntrame",
  "sálvame", "estoy sufriendo", "estoy solo", "¿quién está ahí", "¿quién eres", "¿qué quieres",
  "¿por qué viniste", "¿por qué estás aquí", "¿qué buscas", "¿a quién buscas", "sal de aquí", "abandona este lugar",
  "fuera ahora", "esta es mi casa", "este es mi territorio", "te estoy vigilando", "estoy en todas partes", "no puedes escapar",
  "te encontraré", "estoy justo detrás de ti", "no hay salida", "vuelve", "vuelve otra vez", "no me olvides",
  "recuerda", "júralo", "sí", "no", "quizás", "no lo sé",
  "no puedo decirlo", "medianoche", "el amanecer", "el crepúsculo", "la noche de luna llena", "las tres",
  "la hora de las brujas", "la hora oscura", "abre la puerta", "cierra la ventana", "apaga la luz", "enciende la vela",
  "reza", "maldición", "que te maldigan", "madre", "padre", "hijo",
  "bebé", "viejo", "vieja", "amor", "odio", "venganza",
  "rabia", "celos", "traición", "asesinato", "accidente", "catástrofe",
  "tragedia", "destino", "tiempo", "eternidad", "para siempre", "el pasado",
  "el futuro", "ahora mismo", "aquí", "allí", "arriba", "abajo",
  "dentro", "fuera", "cállate", "escucha", "escúchame", "habla conmigo",
  "respóndeme", "esta casa", "esta habitación", "este lugar", "este lugar está maldito", "este lugar es mío",
  "perdóname", "date prisa", "el tiempo es corto", "tu última oportunidad", "no duermas", "no te despiertes",
  "sueña", "pesadilla", "un sueño terrible", "no me molestes", "déjame", "no me toques",
  "frío", "muy frío", "frío como el hielo", "me estoy congelando", "dolor", "dolor insoportable",
  "no puedo soportarlo", "que acabe ya", "por qué", "cómo", "cuándo",
  "dónde", "el tercer piso", "el sótano", "el desván", "el pasillo", "bajo la escalera",
  "espejo", "mira en el espejo", "reflejo", "invertido", "a las tres de la mañana", "date la vuelta",
  "no mires", "cierra los ojos", "contén la respiración", "olor a sangre", "olor a humedad", "olor a quemado",
  "en descomposición", "pisadas", "el crujido de la puerta", "cristal roto", "un grito", "hay alguien aquí",
  "detrás de mí", "a mi lado", "encima de mí", "debajo de mí", "estoy observando", "estoy esperando",
  "soy paciente", "tengo todo el tiempo del mundo", "la muerte está cerca", "la última noche", "adiós", "hasta siempre",
  "adiós para siempre", "te conozco", "conozco tu nombre", "conozco tu pasado", "conozco tu secreto", "conozco tu miedo",
  "conozco tu punto débil", "te estaba esperando", "sabía que vendrías", "estoy listo", "quiero hablar contigo", "escúchame",
  "tengo algo importante que decir", "no confíes en nadie", "no confíes en ningún alma", "estás solo", "no hay nadie", "tus amigos mienten",
  "no les importas", "te están usando", "pronto morirás", "tu tiempo se acaba", "el reloj avanza", "cuento tus últimos alientos",
  "tu tumba está lista", "el ataúd espera", "el responso de difuntos", "el entierro", "la tierra está fría", "fría y oscura",
  "esta casa tiene historia", "alguien murió aquí", "se derramó sangre", "las paredes recuerdan", "bajo la tierra", "enterrado",
  "escondido", "una habitación secreta", "un pasaje secreto", "detrás del muro", "encima del techo", "quiero jugar",
  "sé mi amigo", "juguemos al escondite", "te encontré", "te toca a ti", "sígueme", "nunca me atraparás",
  "¿dónde está mi mamá", "¿dónde está mi papá", "quiero volver a casa", "estoy perdido", "no encuentro el camino", "le tengo miedo a la oscuridad",
  "soy muy viejo", "estoy cansado", "quiero descansar", "no recuerdo", "olvidé quién soy", "¿dónde estoy",
  "cuánto tiempo ha pasado", "han pasado años", "han pasado siglos", "sigo aquí", "no puedo irme", "no puedo soltar",
  "estoy atado", "me siento encadenado", "no soy libre", "sal de aquí", "este es mi sitio", "entraste sin permiso",
  "te castigaré", "te arrepentirás", "pagarás", "te lo advertí", "mi último aviso", "no vuelvas",
  "no me molestes", "no rompas mi paz", "déjame", "lo siento muchísimo", "estoy lleno de arrepentimiento", "ojalá no lo hubiera hecho",
  "quiero ser perdonado", "soy culpable", "cometí un terrible error", "no hay vuelta atrás", "es demasiado tarde", "ahora ya es demasiado tarde",
  "la oportunidad pasó", "el tiempo se acabó", "todo terminó", "tengo un mensaje", "escucha bien", "descifra esto",
  "te doy una pista", "te estás acercando", "estás en el camino correcto", "estás mirando en el lugar equivocado", "mira en otro sitio", "ve más profundo",
  "no en la superficie", "por debajo", "escondido", "velado", "enmascarado", "hay peligro aquí",
  "ten cuidado", "mira a tu alrededor", "no estés solo", "no te quedes en la oscuridad", "no te alejes de la luz", "cierra la puerta con llave",
  "cierra la ventana", "corre las cortinas", "no mires en el espejo", "no te des la vuelta", "no sigas la voz", "la energía sube",
  "la vibración crece", "la frecuencia se desplaza", "el portal se abre", "el umbral está abierto", "un enlace interdimensional", "la señal se hace más fuerte",
  "se está estableciendo contacto", "hay una conexión", "llega un mensaje", "respondo", "oigo",
  "está abierto",
];

export const SPIRIT_NAMES: string[] = [
  "Juan", "Pedro", "Diego", "Luis", "Carlos", "José",
  "Francisco", "Felipe", "Miguel", "Enrique", "Tomás", "Esteban",
  "Antonio", "Nicolás", "Rodrigo", "Álvaro", "Gonzalo", "Hernán",
  "Alonso", "Baltasar", "Gaspar", "Melchor", "Fernando", "Bernardo",
  "Ignacio", "Damián", "Sebastián", "Agustín", "Cristóbal", "Lorenzo",
  "Bartolomé", "Erasmo", "Ezequiel", "Gedeón", "Leandro", "Marcelo",
  "Onofre", "Pantaleón", "Quirino", "Rosendo", "María", "Isabel",
  "Catalina", "Ana", "Francisca", "Juana", "Teresa", "Magdalena",
  "Elena", "Susana", "Dolores", "Concepción", "Mercedes", "Pilar",
  "Rosario", "Carmen", "Consuelo", "Asunción", "Remedios", "Amparo",
  "Beatriz", "Blanca", "Cecilia", "Elvira", "Esperanza", "Gracia",
  "Inés", "Jimena", "Leonor", "Lucía", "Margarita", "Natividad",
  "Obdulia", "Petra", "Rafaela", "Rosalía", "Soledad", "Trinidad",
  "Valentina", "Virtudes", "Adela", "Benita", "Cándida", "Dolors",
  "Encarnación", "Felipa", "Gertrudis", "Herminia", "Iluminada", "Josefa",
  "Leocadia", "Milagros", "Narcisa", "Otilia", "Presentación", "Queríntia",
  "Ambrosio", "Ciriaco", "Desiderio", "Epifanio", "Florentino", "Gaudencio",
  "Hermenegildo", "Ireneo", "Justiniano", "Lamberto", "Mauro", "Norberto",
  "Olegario", "Policarpo", "Ruperto", "Serafín", "Teófilo",
];

export const NUMBERS: string[] = [
  "uno", "dos", "tres", "cuatro", "cinco", "seis",
  "siete", "ocho", "nueve", "diez", "once", "doce",
  "trece", "catorce", "quince", "dieciséis", "diecisiete", "dieciocho",
  "diecinueve", "veinte", "veintiuno", "treinta", "cuarenta", "cincuenta",
  "sesenta", "setenta", "ochenta", "noventa", "cien", "mil",
  "cero", "un millón", "mil millones", "mil ochocientos", "mil novecientos", "dos mil",
  "el siglo quince", "el siglo dieciséis", "el siglo diecisiete", "el siglo dieciocho", "el siglo diecinueve", "el siglo veinte",
];

export const HISTORICAL_WORDS: string[] = [
  "Otomano", "Sultán", "soberano", "Reina", "Pachá", "Bey",
  "Dama", "palacio", "castillo", "torre", "muralla", "foso",
  "puente", "fuente", "mezquita", "iglesia", "templo", "mausoleo",
  "madrasa", "guerra", "paz", "conquista", "asedio", "victoria",
  "derrota", "servidumbre", "espada", "escudo", "flecha", "lanza",
  "daga", "oro", "plata", "hierro", "diamante", "rubí",
  "adhan", "oración", "rezo ritual", "ángel", "djinn", "hada",
  "dragón", "posada", "hammam", "caravanserai", "bazar", "mercado",
  "Rey", "imperio", "califato", "reinado", "trono", "corona",
  "edicto", "sello", "acta", "carta", "jenízaro",
  "sipahi", "explorador", "tormento", "capitán", "jefe",
  "pirata", "marinero", "navegante", "caravana", "comerciante", "mercader",
  "cambista", "artesano", "derviche", "sufí", "Mevlevi", "Bektashi",
  "Naqshbandi", "casa de la orden", "zawiya", "tekke", "khanqah", "ribat",
  "príncipe", "Valide Sultan", "haseki", "concubina", "eunuco", "palacio imperial",
  "Topkapı", "Dolmabahçe", "Yıldız", "Çırağan", "Galata", "Beyoğlu",
  "Üsküdar", "Kadıköy", "Bósforo", "Rumelia", "Anatolia", "Tracia",
  "Balcanes", "Cáucaso", "Hitita", "Sumerio", "Asirio", "Babilonio",
  "Frigio", "Lidio", "Licio", "Cario", "Jónico", "Urartu",
  "Selyúcida", "Bizantino", "Romano", "Griego", "Persa", "Mongol",
  "Huno", "Göktürk", "Karajánida", "Gaznavida", "Mameluco", "Safávida",
];

export const NATURE_WORDS: string[] = [
  "lluvia", "nieve", "hielo", "viento", "tormenta", "huracán",
  "relámpago", "rayo", "nube", "luna", "estrella", "mar",
  "océano", "lago", "río", "cascada", "montaña", "cueva",
  "bosque", "desierto", "volcán", "terremoto", "noche", "luz del día",
  "alba", "crepúsculo", "sol", "tierra", "planeta", "universo",
  "galaxia", "nebulosa", "agujero negro", "cometa", "meteoro", "meteorito",
  "suelo", "roca", "piedra", "arena", "grava", "árbol",
  "hoja", "rama", "raíz", "flor", "mala hierba", "musgo",
  "hongo", "liquen", "hiedra", "lobo", "oso", "águila",
  "serpiente", "escorpión", "murciélago", "búho", "cuervo", "gato",
  "perro", "insecto", "araña", "mosca", "mosquito", "abeja",
  "pez", "delfín", "tiburón", "pulpo", "medusa", "crudo",
  "escarcha", "lleno", "aguacero", "llovizna", "viento noreste", "viento suroeste",
  "brisa", "siroco", "karayel", "marea alta", "marea baja", "ola",
  "corriente", "remolino", "manantial", "primavera", "arroyo", "riachuelo",
  "delta fluvial", "valle", "cañón", "garganta", "puerto de montaña", "meseta",
  "banco de niebla", "vapor", "condensación", "linde", "rayo de luz", "ráfaga",
  "ermita", "derrumbe", "temblor", "línea de falla", "grieta", "estalagmita",
  "estalactita", "sima", "cráter", "lava", "magma", "agua subterránea",
  "agua de manantial", "fuente curativa", "fuente sagrada", "cañaveral", "estanque", "arroyo",
  "cauce del río", "espuma del mar", "marea", "gota de rocío", "hilo de agua", "gotita",
  "sudor", "plasma", "savia", "resina", "ámbar", "fósil",
  "roca madre", "mineral", "yacimiento de mineral", "mineral",
];

export const EMOTION_WORDS: string[] = [
  "miedo", "horror", "pánico", "pavor", "angustia", "rabia",
  "rencor", "odio", "repulsión", "pena", "duelo", "aflicción",
  "añoranza", "soledad", "desesperación", "desesperanza", "dolor", "sufrimiento",
  "tormento", "angustia profunda", "remordimiento", "conciencia", "culpa", "curiosidad",
  "asombro", "perplejidad", "paz", "silencio", "quietud", "malestar",
  "tensión", "estrés", "depresión", "desolación", "melancolía", "nostalgia",
  "anhelo", "morriña", "alienación", "alegría", "felicidad", "júbilo",
  "fervor", "emoción", "esperanza", "anticipación", "deseo ardiente", "ansia",
  "pasión", "decepción", "desilusión", "no te dejes engañar", "no te equivoques", "duda",
  "recelo", "vacilación", "indecisión", "incertidumbre", "coraje", "audacia",
  "heroísmo", "sacrificio", "misericordia", "compasión", "lástima", "empatía",
  "celos", "envidia", "codicia", "rencor", "vergüenza", "humillación",
  "aburrimiento", "cansancio", "horror", "brutalidad", "monstruosidad", "crueldad",
  "salvajismo",
];

export const BODY_WORDS: string[] = [
  "mano", "pie", "cabeza", "ojo", "oreja", "boca",
  "diente", "lengua", "dedo", "cuello", "espalda", "pecho",
  "corazón", "cerebro", "sangre", "hueso", "piel", "aliento",
  "pulso", "lágrima", "hombro", "brazo", "muñeca", "palma",
  "uña", "rodilla", "pantorrilla", "talón", "cintura", "vientre",
  "hígado", "riñón", "intestino", "pulmón", "estómago", "vena",
  "nervio", "músculo", "tendón", "articulación", "cabello", "ceja",
  "pestaña", "bigote", "barba", "sien", "cresta frontal", "barbilla",
  "mejilla", "nariz", "columna vertebral", "costilla", "clavícula", "omóplato",
  "pelvis", "cráneo", "mandíbula", "pómulo", "órbita ocular",
];

export const PLACE_WORDS: string[] = [
  "casa", "habitación", "sala", "pasillo", "escalera", "tejado",
  "sótano", "puerta", "ventana", "pared", "techo", "cementerio",
  "hospital", "prisión", "bosque", "cueva", "pozo", "túnel",
  "puente", "cocina", "cuarto de baño", "dormitorio", "salón", "balcón",
  "garaje", "jardín", "patio", "terraza", "veranda", "iglesia",
  "mezquita", "sinagoga", "templo", "monasterio", "castillo", "palacio",
  "torre", "mazmorra", "bodega", "escuela", "biblioteca", "museo",
  "teatro", "ópera", "fábrica", "almacén", "depósito", "silo",
  "hangar", "pueblo", "villa", "ciudad", "metrópolis", "ruina",
  "desolación", "escombros", "cascotes", "restos", "vestigios", "isla",
  "península", "cabo", "cala", "puerto", "estación", "terminal",
  "aeropuerto", "embarcadero", "muelle", "parque", "jardín de recreo", "arboleda",
  "pradera", "campo", "granja", "granero", "almiar", "molino",
  "horno de ladrillos", "hammam", "posada", "caravanserai", "pabellón del bazar", "mercado",
  "mausoleo", "külliye", "madrasa", "casa de la orden", "zawiya", "campo de sepultura",
  "santuario", "sepulcro", "sarcófago", "osario", "casa abandonada", "mansión encantada",
  "castillo maldito", "pueblo fantasma", "ciudad muerta", "aldea perdida", "pecio hundido", "hospital abandonado",
  "vieja prisión", "ciudad subterránea", "catacumba", "bóveda sepulcral", "camino", "callejón oscuro",
  "desván", "laberinto", "cámara secreta", "cañón de chimenea", "chimenea", "bajo la escalera",
  "planta baja", "refugio", "pasaje abovedado", "columna", "contrafuerte", "viga",
  "en la cripta", "cámara funeraria", "monumento", "espejo de cuerpo entero",
];

export const TIME_WORDS: string[] = [
  "ahora", "enseguida", "después", "antes", "ayer", "hoy",
  "medianoche", "mañana", "tarde", "noche", "el alba", "eternidad",
  "para siempre", "el pasado", "el futuro", "siglo", "la hora de las brujas", "más allá",
  "eterno", "mortal", "primera luz", "solsticio", "eclipse lunar", "eclipse solar",
  "creciente", "luna nueva", "luna de sangre", "estrella fugaz", "Vía Láctea", "constelación",
  "Estrella Polar", "norte", "sur", "este", "oeste", "dirección",
  "horizonte", "mañana", "pasado mañana", "semana", "mes", "año",
  "siglo", "un milenio", "era", "giro de los tiempos", "período", "instante",
  "segundo", "minuto", "el reloj", "en un abrir y cerrar de ojos", "primero", "último",
  "comienzo", "fin", "el final", "nacimiento", "muerte", "vida",
  "existencia", "ser", "primavera", "verano", "otoño", "invierno",
  "estación", "lunes", "martes", "miércoles", "jueves", "viernes",
  "sábado", "domingo", "día de fiesta", "noche sagrada", "víspera",
];

export const ACTION_WORDS: string[] = [
  "ven", "vete", "para", "espera", "corre", "huye",
  "escóndete", "mira", "ve", "escucha", "oye", "toca",
  "siente", "habla", "cállate", "susurra", "grita", "llora",
  "duerme", "despiértate", "recuerda", "olvida", "extiende la mano", "cierra",
  "bloquea", "corta", "rompe", "quema", "apaga", "muere",
  "nace", "vive", "desaparece", "aparece", "llama", "encuentra",
  "pierde", "esconde", "entierra", "arrastra hacia abajo", "sal",
  "entra", "sube", "salta", "sueña", "gatea", "te arrastras",
  "camina", "baila", "vuelve", "gira", "dobla", "se tuerce",
  "estremece", "tiembla", "vibra", "multiplica", "golpea", "araña",
  "alcanza", "arrastra", "aplasta", "lanza", "devora", "consume",
  "traga", "escupe", "ahoga", "respira", "exhala", "se ahoga",
  "jadea", "gime", "solloza", "chilla", "se queja", "lloriquea",
  "susurra", "tararea", "gruñe", "gruñe bajo", "aúlla", "sigue",
  "vigila", "espía", "acecha", "ataca", "defiende", "protege",
  "busca refugio", "atranca la puerta", "tiende una trampa", "suplica", "agarra", "desea",
  "pregunta", "ruega", "maldice", "condena", "lanza un hechizo", "realiza el ritual",
  "celebra una sesión de espiritismo", "confiesa", "admite", "acepta", "niega", "rechaza",
  "perdona", "absuelve", "castiga", "recompensa", "permanece", "ayuda",
  "hace guardia", "cumple", "entra", "parte", "lo enfrenta", "se disuelve",
  "ata", "libera", "disimula", "no rías", "evoca", "persigue",
  "trae", "llévate", "salva", "ayúdame", "suéltalo", "retenlo",
  "atrapa", "no sueltes", "no olvides", "dime", "pide socorro", "habla",
  "cubre", "sella", "encierra", "desenreda", "ata fuerte", "separa",
  "ilumina", "sumerge en la oscuridad",
  "aguanta",
];

export const LONG_PHRASES: string[] = [
  "no estás solo aquí esta noche", "alguien vive detrás de las paredes", "vengo a la misma hora cada noche", "llevo mucho tiempo observándote", "esta casa tiene una historia", "mucha sangre se ha derramado aquí",
  "nadie que haya venido aquí ha salido vivo", "no serás el último en venir", "cerrar la puerta con llave no te ayudará", "estoy en todas partes todo el tiempo", "cuando cierres los ojos me verás", "te visitaré en tus sueños",
  "mantente despierto porque yo lo estoy", "no duermas esta noche, no duermas", "¿escuchas tus propios pasos", "la sombra detrás de ti no es la mía", "mira en el espejo y me verás", "soy la voz que viene del techo",
  "hay algo en el sótano", "alguien camina por el tejado", "vi una sombra en el jardín", "alguien mira por la ventana", "la puerta se abrió sola", "las luces parpadean",
  "el reloj se paró a las tres de la mañana", "el espejo se rompió solo", "la sangre rezuma de la pared", "suben ruidos de las entrañas de la tierra", "no es agua — es sangre que gotea del techo", "la figura de la foto se movió",
  "la muñeca sonrió", "alguien baja la escalera", "alguien está de pie al final del pasillo", "unas manos emergen de debajo de la cama", "alguien respira dentro del armario", "hay una silueta detrás de la cortina",
  "unos ojos brillan en la oscuridad", "el cuadro de la pared te está mirando", "tu reloj ha dejado de sonar", "el teléfono sonó pero no había nadie", "salen sonidos extraños de la radio", "el televisor se encendió solo",
  "apareció una cara en la pantalla del ordenador", "la sangre sale del grifo", "no me reflejo en el espejo", "mi sombra se mueve independientemente de mí", "este es el lugar que vi en mis sueños", "ya he estado aquí antes",
  "ya he vivido este momento", "estoy atrapado en un bucle temporal", "no hay salida de aquí", "puertas cerradas con llave, ventanas selladas", "las paredes empezaron a cerrarse", "el techo desciende",
  "el suelo cede", "el aire se vuelve más frío", "puedo ver mi propio aliento", "algo tocó mi pierna", "me tiraron del cabello", "algo susurró en mi oído",
  "sentí un aliento frío en la nuca", "una mano tocó mi hombro", "alguien me empuja por detrás", "mi pie tropezó con algo invisible", "algo se movió en la oscuridad", "apareció una sombra en el rincón y desapareció",
  "no es polvo lo que cae del techo — es ceniza", "el reloj de la pared va hacia atrás", "aparece otra habitación en el espejo", "la base de la escalera se abre a la oscuridad", "este pasillo no tiene fin", "cada vez que abro la puerta estoy en la misma habitación",
  "no veo nada por la ventana", "fuera no hay nada — solo oscuridad", "alguien fue colgado en esta habitación", "hay un cadáver enterrado bajo la cama", "hay huesos dentro de las paredes", "esta casa fue construida sobre un cementerio",
  "de noche salen ruidos de las paredes", "cosas extrañas ocurren con cada luna llena", "los vecinos evitan esta casa", "todos los que vivieron aquí se volvieron locos", "el último inquilino desapareció", "ni siquiera la policía entra en esta casa",
  "ni siquiera el imán pudo purificar este lugar", "el sacerdote vino — y salió corriendo", "los rituales que se celebran aquí siguen en marcha", "se oyen gritos a las tres de la mañana", "los niños nunca pasan por delante de esta casa", "los gatos nunca se acercan a esta casa",
  "los perros aúllan delante de esta casa", "los pájaros nunca vuelan sobre esta casa", "los árboles alrededor de la casa se están muriendo", "no florece ninguna flor en este jardín", "la luz del sol nunca entra en esta casa", "el reloj se para a las tres cada noche",
  "los espejos se agrietan solos", "las velas se encienden solas", "las puertas se abren y se cierran solas", "la silla se mueve sin ayuda", "los ojos de los cuadros te siguen", "la mancha en la pared crece cada día",
  "la grieta en el techo parece una cara", "la mancha de sangre en el suelo no se puede quitar", "el aire en esta habitación siempre está frío", "los aparatos electrónicos fallan aquí", "tu batería del móvil se agota en segundos aquí", "la brújula se vuelve loca aquí",
  "los relojes muestran la hora equivocada aquí", "las cámaras no funcionan aquí", "aparecen formas extrañas en las fotos tomadas aquí", "hay alguien en los vídeos que no debería estar ahí", "las grabaciones de audio contienen susurros", "el medidor EMF se vuelve loco aquí",
  "la temperatura baja sin previo aviso", "hay un olor extraño en el aire", "olor a humedad — pero sin moho", "olor a quemado — pero sin fuego", "fragancia de flores — pero sin flores", "olor a perfume — pero nadie está ahí",
];

export const MANIPULATIVE_RESPONSES: string[] = [
  "sí", "no", "quizás", "podría ser", "jamás", "con certeza",
  "probablemente", "lo dudo", "no estoy seguro", "verdad", "mentira", "en parte",
  "a veces", "siempre", "nunca", "raramente", "a menudo", "normalmente",
  "mira a la derecha", "mira a la izquierda", "mira hacia arriba", "mira hacia abajo", "mira detrás de ti", "mira adelante",
  "mira a tu alrededor", "mira la pared", "ve hacia la puerta", "ve hacia la ventana", "ve al sótano", "ve al desván",
  "sal", "entra", "acércate", "aléjate", "un paso más", "mi edad era",
  "morí aquí", "viví aquí", "llevo mucho tiempo aquí", "esperé cien años", "te estaba esperando", "tenías que venir",
  "destino", "no tengas miedo", "deberías tener miedo", "no estás en peligro", "estás en peligro", "estás a salvo",
  "no estás a salvo", "no estás solo", "estás completamente solo", "eres amado", "no eres amado", "te han olvidado",
  "te recuerdan", "llegará el momento", "sé paciente", "espera", "estate preparado", "pronto lo entenderás",
  "todo será revelado", "seguirá siendo un secreto", "no puedo decirlo", "está prohibido", "no hay permiso", "hay un límite",
  "detrás de ti", "a tu lado", "arriba", "fui testigo de ello", "lo oíste", "acercándose",
  "tocar", "un escándalo", "un incidente", "un alma perdida", "nosotros", "ellos",
  "nadie", "un visitante", "algo aquí", "pertenece aquí", "guardado en custodia", "viejo",
  "lo sé", "lo viste", "lo escondí", "estaba aquí", "se fueron", "despertado",
  "durmiendo", "muy adentro", "muy lejos", "tu nombre", "lo enterré", "me lo llevé",
  "lo perdí", "lo encontré", "estoy buscando", "vengo", "me voy", "me quedé",
  "morí", "estoy vivo", "pronto", "justo detrás de ti", "a tu derecha", "a tu izquierda",
  "arriba", "entre", "dentro", "más allá", "a la orilla cercana", "enfrente",
  "en el umbral", "¿quién eres", "¿cómo te llamas", "¿qué quieres", "¿por qué estás aquí", "¿cuántos sois",
  "¿cuándo viniste", "¿cómo moriste", "¿nos oyes", "¿quieres ayuda", "¿deberíamos irnos",
];

export const DIALOG_PHRASES: string[] = [
  "hola", "saludos", "bienvenido", "te estaba esperando", "por fin has venido", "llegas tarde",
  "¿dónde has estado", "este lugar me pertenece", "soy el alma de esta casa", "morí aquí", "estoy enterrado aquí", "no puedo decirte mi nombre",
  "olvidé mi nombre", "no más pisadas", "nunca existí realmente", "soy un recuerdo", "soy un eco", "abandona este lugar ahora",
  "no te quedes aquí esta noche", "vete antes de que se ponga el sol", "vete antes de que caiga la oscuridad", "vete antes de medianoche", "vete antes de las tres", "no entres en esta habitación de nuevo",
  "no abras esta puerta de nuevo", "no mires en este espejo de nuevo", "no pronuncies ese nombre de nuevo", "una familia vivía aquí antes", "esta casa fue construida hace cien años", "aquí hubo un incendio una vez",
  "aquí se cometió un asesinato", "aquí se perdió un niño", "una mujer se quitó la vida aquí", "un hombre se volvió loco aquí", "aquí se celebró un ritual", "aquí hay un tesoro enterrado",
  "aquí comenzó una maldición", "te voy a retener aquí", "nunca te irás", "te quedarás conmigo", "aquí para siempre", "no hay escapatoria",
  "sin salida", "no hay salvación", "rezar no te ayudará", "nadie puede salvarte", "grita cuanto quieras — nadie te oirá", "por favor no te vayas",
  "no me dejes solo", "me siento tan desesperadamente solo", "nunca viene nadie", "llevo años esperando", "siglos solo", "necesito compañía",
  "quiero hablar con alguien", "eres la primera persona que oye mi voz", "eres el primero en verme",
];

export const WHISPER_PHRASES: string[] = [
  "pssst", "oye", "mírame", "por aquí", "escúchame", "véame",
  "siénteme", "tócame", "acércate", "acércate un poco más", "presta tu oído", "shhh",
  "quédate quieto", "nadie debe oír", "gírate despacio", "mira despacio", "tengo un secreto", "voy a decirte algo",
  "no se lo digas a nadie", "guarda esto entre nosotros", "este secreto", "te elegí a ti", "eres alguien especial", "eres diferente",
  "eres diferente a los demás", "te entiendo", "eres el único que me entiende", "tenemos un vínculo", "tus ojos ven cosas que otros no pueden", "me puedes sentir",
  "los demás no pueden oír — pero tú sí", "nuestro destino es uno", "estamos atados el uno al otro", "no puedes evitar esto", "está escrito", "es el destino",
  "todo ocurre por una razón", "nada es coincidencia", "quería que vinieras aquí", "te llamé", "mi invitación fue aceptada", "bienvenido a mi hogar",
  "te he esperado tanto tiempo", "viniste exactamente en el momento justo", "ya estás aquí", "ahora me perteneces", "no te dejaré irte", "para siempre",
  "estaremos juntos", "nunca nos separaremos", "eres mi último invitado", "nadie ha vuelto a salir de este lugar", "te perderás en esta casa", "te veré en tus sueños",
  "vendré a ti mientras duermes", "estoy aquí en la noche", "vivo en la oscuridad", "la luz me asusta", "el sol me quema", "la noche es mi hora",
  "la oscuridad es mi morada", "me hago más fuerte después del atardecer", "soy más poderoso a las tres de la mañana", "desapareceré al amanecer — pero esperaré la noche", "conozco tu nombre", "sé dónde vives",
  "conozco a tu familia", "conozco tu pasado", "sé lo que temes", "conozco tus sueños", "estuve en tu sueño anoche", "¿no te despertaste de repente en la noche",
  "era yo — esa sensación extraña", "ten cuidado esta noche", "no estás a salvo", "quédate con alguien", "no duermas solo", "no apagues la lámpara",
  "cierra la puerta con llave", "no dejes la ventana abierta", "corre las cortinas", "¿oíste eso hace un momento", "está justo detrás de ti ahora", "todavía no vuelvas",
];

export const MYTHOLOGY_WORDS: string[] = [
  "al-karı", "terror nocturno", "coco", "ghul", "gigante", "glotón",
  "albastı", "koncolos", "tepegöz", "basilisco", "Hıdırellez", "Nowruz",
  "Ergenekon", "el Lobo Gris", "Asena", "la Montaña de las Cabezas", "el Árbol Tuba", "el Agua de la Vida",
  "el Agua de la Inmortalidad", "fénix", "ave de fuego", "simurgh", "el caballo del viento", "el hada del viento",
  "ninfa", "espíritu de la montaña", "dríade", "el mal de ojo", "la mirada maléfica", "el maleficio",
  "poseído", "hombre lobo", "lechuza nocturna", "el grito del búho", "gato negro", "los cuarenta pasos",
  "espíritu de la partera", "espectro que concede deseos", "el árbol de los deseos", "el pozo de los deseos", "el lugar del sacrificio", "derribado",
  "santo", "hombre santo", "anciano", "pir", "patriarca", "el hoca",
  "hechicera", "la abuela adivina", "tesoro escondido", "un entierro", "tesoro", "el cubo de oro",
  "el tesoro maldito", "el djinn guardián", "el guardián del tesoro", "la puerta talismánica", "el espejo encantado", "la alfombra voladora",
  "invisibilidad", "inmortalidad", "el elixir de la juventud", "la lavadora de muertos", "sudario", "la piedra del musalla",
  "coche fúnebre", "lápida", "cabecera", "piedra de pie", "sarcófago", "ataúd de piedra",
  "mausoleo", "jaula", "turbe", "fosa común", "la tumba perdida", "la tumba sin nombre",
  "el cementerio de medianoche", "el cementerio abandonado",
];

export const FOLK_BELIEFS: string[] = [
  "perla del mal de ojo", "amuleto escrito", "derretir plomo", "quemar incienso", "hacer una promesa", "no hagas ese deseo",
  "interpretación de sueños", "adivinación", "lectura de posos de café", "quiromancia", "horóscopo", "adivinación con agua",
  "magia de espejos", "magia de velas", "magia de cuerdas", "hechizo de atadura", "hechizo de separación", "hechizo de amor",
  "magia negra", "magia blanca", "magia de djinns", "curandero", "djinn", "hacedor de amuletos",
  "brujo", "hechicero", "conjurador", "ilusionista", "nigromancia", "tocar el vaso",
  "sostener el lápiz", "hacer girar la mesa", "tablero ouija", "tablero de espíritus", "no invites a un djinn", "exorcismo",
  "no ates al djinn", "encantamiento", "afsun", "recitación", "soplar el amuleto", "no respires",
  "adivinación con agua", "curación por la fe", "la mirada", "el toque maléfico", "el mal de la lengua", "espíritu malévolo",
  "espíritu benévolo", "espíritu guardián", "espíritu ancestral", "espíritu del abuelo", "espíritu de la abuela", "espíritu del hogar",
  "djinn del hammam", "djinn del agua", "djinn del fuego", "espíritu de la tierra", "djinn del tiempo", "djinn musulmán",
  "djinn infiel", "djinn enamorado",
];

export const HORROR_STORY_WORDS: string[] = [
  "susto repentino", "terror creciente", "horror", "espanto", "pánico", "huida",
  "la persecución", "la emboscada", "la trampa", "el cepo", "el sacrificio", "el cazador",
  "la presa", "la caza", "la sombra", "una puerta que cruje", "madera que cruje", "hojas que susurran",
  "el viento que aúlla", "una tubería que silba", "cristal que traquetea", "zumbido en los oídos", "cabeza que late", "mano que tiembla",
  "un grito sofocado", "una voz cortada", "sangre que se hiela", "pelo que se eriza", "piel de gallina", "piel que se estremece",
  "corazón desbocado", "sudor frío", "un temblor", "una convulsión", "sin poder respirar", "que se tambalea",
  "náuseas", "visión borrosa", "acúfenos", "entumecimiento", "no te paralices", "no te quedes helado",
  "petrificado", "levitación", "telequinesis", "combustión espontánea", "metamorfosis", "salto dimensional",
  "viaje en el tiempo", "separación del alma", "experiencia extracorporal", "viaje astral", "transferencia de conciencia", "control mental",
  "hipnosis", "histeria colectiva", "alucinación colectiva", "el espejo maldito", "la muñeca maldita", "el anillo maldito",
  "el libro maldito", "el retrato maldito", "la joya maldita", "la daga maldita", "la corona maldita", "el cofre maldito",
  "el mapa maldito", "la brújula maldita", "el reloj maldito",
];

export const CURSES: string[] = [
  "que te condenen", "abajo contigo", "que te borren", "encontrarás tu castigo", "tendrás que rendir cuentas", "pagarás el precio",
  "te arrepentirás", "no lo olvidaré", "no perdonaré", "no hay perdón", "tendré mi venganza", "lo arreglaremos",
  "esto no ha terminado", "está muy lejos de terminar", "esto es solo el principio", "ya verás", "acabarás por entenderlo", "lo sentirás",
  "sufrirás", "llorarás", "suplicarás", "suplicar no servirá de nada", "nadie puede ayudarte", "no hay escapatoria",
  "no hay salvación", "nunca terminará", "esta maldición no puede levantarse", "este hechizo no puede romperse", "esta cadena no puede cortarse", "este vínculo no puede deshacerse",
  "durará siete generaciones", "durará cuarenta días", "durará para siempre", "continuará sin fin", "estas tierras están malditas", "esta casa está maldita",
  "esta familia lleva la maldición", "esta sangre está maldita", "cada niño nacido aquí está maldito", "cada generación está marcada", "la maldición te ha sido transmitida", "ahora es tuya",
  "cargarás con este peso", "y después de ti, tus hijos",
];

export const DREAM_WORDS: string[] = [
  "sueño", "pesadilla", "sueño despierto", "visión", "profecía", "presagio",
  "presentimiento", "intuición", "instinto", "el sexto sentido", "el subconsciente", "el inconsciente",
  "trance", "hipnosis", "meditación", "parálisis del sueño", "un sueño lúcido", "en las garras de una pesadilla",
  "volar en sueños", "caer en sueños", "correr en sueños", "huir en sueños", "ser perseguido en sueños", "ver a los muertos en sueños",
  "ver sangre en sueños", "ver una serpiente en sueños", "ver una araña en sueños", "ver agua en sueños", "ver fuego en sueños", "ver una casa en sueños",
  "ver una tumba en sueños", "ver un espejo en sueños", "ver una puerta en sueños", "ver una escalera en sueños", "ver un pasillo en sueños", "ver la oscuridad en sueños",
  "ver la luz en sueños", "oír una voz en sueños", "oír un susurro en sueños", "oír gritos en sueños", "oír música en sueños", "ver a alguien en sueños",
  "un desconocido en el sueño", "una sombra en el sueño", "una cara en el sueño", "un ojo en el sueño",
];

export const RESEARCH_JARGON: string[] = [
  "anomalía detectada", "el campo de energía ha cambiado", "oleada electromagnética", "anomalía de temperatura", "anomalía vocal", "anomalía visual",
  "recopilación de datos", "análisis de evidencias", "investigación de escena del crimen", "declaración de testigo", "testigo ocular", "información de primera mano",
  "fuente secundaria", "registro de archivo", "documento histórico", "análisis de frecuencia", "análisis de espectro", "longitud de onda",
  "infrarrojo", "ultravioleta", "imagen térmica", "visión nocturna", "infrarrojo completo", "espectro completo",
  "escaneo SLS", "lectura EMF", "captura EVP", "sesión spirit box", "barrido ghost box", "REM pod",
  "medidor K-II", "medidor Mel", "medidor Trifield", "termómetro digital", "rejilla láser", "sensor de movimiento",
  "sensor de vibraciones", "sensor de presión", "sensor de humedad", "sesión de control", "intento de provocación", "vigilia silenciosa",
  "sesión de preguntas y respuestas", "sesión abierta", "lectura de referencia", "valor de referencia", "lectura anómala", "valor pico",
  "valor promedio",
];
