// German word bank for VOX — native-speaker reviewed parallel to word-bank.ts (Turkish).
// Category counts mirror lib/word-bank.ts exactly. PHONEMES unchanged.

export const NINE_PHRASES: string[] = [
  "mein Kleines", "mein Enkelkind", "Liebling", "mein Kind", "mein kleines Wesen", "mein kleines Lamm",
  "mein Herzblut", "das Licht meiner Augen", "der Winkel meines Herzens", "komm zu mir", "wo bist du, mein Kind", "ich vermisse dich so sehr",
  "geh nicht von mir weg", "ich warte voller Sehnsucht auf dich", "jede Nacht denke ich an euch", "ich möchte deine Stimme hören", "lass mich dein Gesicht noch einmal sehen", "du bist in meinem Traum erschienen — doch dann erwachte ich",
  "warum kommst du nicht", "kannst du mich hören", "es ist kalt hier", "kein Licht", "so dunkel", "ich bin noch hier",
  "vergiss mich nicht", "mein Grab liegt verlassen", "niemand kommt mehr", "ich wurde ganz allein gelassen", "wie viel Zeit ist vergangen", "war das wirklich der Tod",
  "ich warte auf dich", "komm eines Tages", "hol mich von hier weg", "die Erde ist kalt", "die Erde ist dunkel", "unter dem Stein bin ich kalt geworden",
  "niemand weiß, dass ich hier bin", "es ist so schwer hier", "ich kann ohnehin nicht gehen", "ich bin an diese Welt gebunden", "ich warte noch immer", "ich kann dich hören, aber nicht sehen",
  "deine Stimmen klingen so weit entfernt", "ach, mein liebes Kind", "möge es gut gehen", "Gott schütze dich", "bete", "verrichte dein Gebet",
  "da draußen sind böse Menschen", "sei vorsichtig, mein Liebling", "lauf nicht in dein Verderben", "bleib aufrichtig", "lebe ehrenhaft", "respektiere die Älteren",
  "ruf deine Verwandten an und frag nach ihnen", "flieh vor der Sünde", "tue Buße", "verdiene deinen Lebensunterhalt auf rechte Weise", "liebt einander", "lasst keinen Streit unter euch entstehen",
  "solch böse Träume", "ich weine die Nächte durch", "ich sehe den Morgen nicht", "jenes dunkle Wesen ist mir hierher gefolgt", "ich habe etwas gesehen, bevor ich starb", "da ist etwas, das ich dir sagen muss",
  "ein Geheimnis verbirgt sich unter diesem Haus", "Geräusche steigen aus der Erde auf", "ich werde um Mitternacht an die Tür klopfen", "ich werde dich in deinen Träumen besuchen", "du wirst mich im Schlaf sehen", "ich werde bei dir sein, wenn sich deine Augen schließen",
  "ich wünschte, wir hätten mehr Zeit miteinander verbracht", "ich möchte sagen, was ich nie sagen konnte", "vergib mir, mein Kind", "auch ich habe Fehler gemacht", "ich würde alles darum geben, zurückzukehren", "ich wünschte, ich hätte es dir früher gesagt",
  "ich bin zu früh gegangen", "ich war nicht bereit", "ich wollte euch nicht verlassen", "ich stehe zwischen dieser Welt und der nächsten", "ich komme, wenn sich das Tor öffnet", "bei der Mondfinsternis kannst du mich hören",
  "am Freitagabend bin ich stärker", "ich sitze auf dem Friedhof und weine", "die neben mir wollen dich auch sehen", "dieser Ort ist voll — und doch völlig still", "ich laufe dem Licht entgegen, aber ich erreiche es nicht", "eines Tages wirst du es verstehen",
];

export const GIRL_CHILD_PHRASES: string[] = [
  "spielst du mit mir", "ich möchte nicht allein sein", "warum spielt niemand mit mir", "ich habe meine Puppe verloren", "wo sind meine Spielsachen", "ich möchte nach Hause",
  "wo ist meine Mutter", "wo ist mein Vater", "warten sie auf mich", "ich möchte nicht weinen, aber ich weine", "niemand sieht mich", "bin ich unsichtbar",
  "ist denn niemand hier", "ich bin ganz allein hier", "ich möchte eine Freundin", "kann ich mit dir spielen", "ich habe Angst", "warum ist es so dunkel",
  "kannst du das Licht anmachen", "ich habe etwas gesehen", "er ist wieder da", "er kommt jede Nacht", "der böse Mann ist wieder gekommen", "er hat mich angefasst",
  "wenn man schreit, geht er weg", "ich mache meine Augen zu", "ich habe angefangen, von hundert rückwärts zu zählen", "da ist jemand hinter mir", "siehst du ihn", "er sieht dich auch",
  "komm nicht hierher", "es ist gefährlich hier", "es folgt dir auch", "sie haben mich hier gelassen", "warum haben sie mich verlassen", "die Wände sprechen",
  "jemand schaut durch das Fenster herein", "das bin nicht ich im Spiegel", "mein Schatten bewegt sich von allein", "von der Decke kommen Geräusche", "jemand ist auf der Treppe — ich zähle die Schritte", "mein Hund sieht etwas in der Ecke",
  "meine Katze ist aus dem Zimmer gerannt", "die Blumen welkten, als ich hineinkam", "die Uhr blieb genau in dem Moment stehen", "meine Mutter ruft nach mir", "langsam", "hm hm",
  "nein nein nein", "Stopp Stopp Stopp", "ich will nicht ich will nicht", "ich kann es auch sehen", "mir ist so kalt geworden", "verlass mich nicht",
  "bitte halte mich fest", "halte meine Hand", "geh nicht weg", "ich gehe irgendwohin, während ich schlafe", "dort bin ich auch in meinem Traum", "ich wache erschöpft auf",
  "was passiert nachts", "siehst du auch nachts seltsame Dinge", "im Dunkeln sind Augen", "sie warten", "ich bin viel zu lange hier geblieben", "ich möchte jetzt hinausgehen",
  "nimm mich bitte mit", "ich möchte dem Licht entgegengehen", "ich kann nicht durch diese Tür", "irgendwas versperrt den Weg", "wie heißt du", "kann ich dir vertrauen",
  "weine nicht — sonst weine ich auch", "geh von hier fort, um deinetwillen",
];

export const PHANTOM_PHRASES: string[] = [
  "ich bin hier", "kannst du mich hören", "Hilfe", "ich komme nicht heraus", "wir sind gefangen", "lasst uns gehen",
  "weg von dort", "du bist in Gefahr", "es kommt", "lauf", "ihr alle seid in Gefahr", "hörst du das",
  "ich war auch einmal wie du", "jetzt ist es viel zu spät", "geh nicht", "dieses Haus hütet ein Geheimnis", "ich stecke in den Wänden", "hör mir zu",
  "sie sind real", "niemand hat mir geglaubt", "jetzt verstehst du es", "dieser Ort ist die Hölle", "ich bin in der Dunkelheit verloren", "gib mir eine Stimme",
  "unter dem Boden ist ein Raum", "ich kenne die geheime Tür", "öffne die Truhe im Keller nicht", "weißt du, was hinter der Wand steckt", "der alte Eigentümer ist noch hier", "dieses Haus trägt ein hundert Jahre altes Geheimnis",
  "im Keller weint jemand", "auf dem Dach sind Schritte zu hören", "Frequenz anpassen", "mein Signal ist schwach", "die Verbindung bricht ab", "ich bin so weit weg",
  "ich kann dich hören", "komm nicht dorthin", "der Kanal ist offen", "ich empfange dich", "ich versuche Kontakt aufzunehmen", "zu viel Rauschen",
  "die Frequenz verschiebt sich", "Band wechseln", "komm durch das Rauschen — dann hörst du mich", "ich brauche Verstärkung", "die Schallwelle bricht", "interdimensionale Interferenz",
  "schau nicht zurück", "schließ die Tür", "mach das Licht nicht aus", "sei nicht allein", "trenn die Gruppe nicht", "es gibt eine starke Präsenz",
  "die negative Energie ist überwältigend", "das Gebiet ist verseucht", "es muss gereinigt werden", "zeichne das auf", "schau in die Kamera", "da ist etwas zu deiner Linken",
  "Vorsicht, wenn die Temperatur fällt", "kannst du noch atmen", "ich spreche aus weiter Ferne", "meine Stimme erreicht dich kaum", "die Energie geht zur Neige", "ich spreche mit meiner letzten Kraft",
  "bleib still, damit du mich hören kannst", "halte kurz den Atem an", "in völliger Stille bin ich zu hören", "ich flüstere, damit sie es nicht hören", "behalte das für dich", "niemand sonst darf es wissen",
  "ich wende mich ganz gezielt an dich", "du wurdest für diese Aufgabe auserwählt", "heute Nacht ist jemand Besonderes gekommen", "unter euch ist ein sensibler Mensch", "hier ist jemand geistig offen", "findet ihn unter euch",
];

export const HOME_OBJECT_PHRASES: string[] = [
  "schau dir den Stuhl neben dir an", "ich habe den linken Stuhl gesehen", "hinter dem Stuhl steht jemand", "ich sitze gerade auf dem Sofa", "ich saß auf deinem Stuhl", "dieser leere Platz ist besetzt",
  "schau unter dem Sofa nach", "neben dem Stuhl ist eine Kältezone", "fass den Stuhl noch nicht an", "öffne die dritte Schublade", "in der obersten Schublade habe ich etwas versteckt", "in der untersten Schublade wirst du mich finden",
  "mach diese Schublade zu", "die Schranktür bleibt heute Nacht offen", "im Kleiderschrank steckt jemand", "öffne die Schubladen eine nach der anderen", "halte bei der letzten Schublade inne", "schließe den Schrank ab, bevor die Nacht kommt",
  "schau nicht unter dein Bett", "unter deinem Kissen liegt etwas", "ich sitze auf der Bettkante", "schau morgen früh auf dein Kissen, wenn du aufwachst", "schlaf heute Nacht nicht in diesem Bett", "ich habe mich unter die Bettdecke geschlichen",
  "wenn das Bett nachts einzubrechen scheint — das bin ich", "ich schaue dir ins Gesicht, während du schläfst", "schau genau in den Spiegel", "in deinem Spiegel sind gerade zwei Gesichter zu sehen", "ich bin auf der anderen Seite des Spiegels", "verhülle den Spiegel nachts",
  "schau aus dem Fenster", "ich drücke mein Gesicht gegen die Fensterscheibe", "hast du nachts schon einmal den Vorhang beiseitegeschoben und hinausgeschaut", "schau in den Beschlag auf dem Glas", "öffne das Fenster heute Nacht nicht", "ich schlüpfe durch die Jalousien herein",
  "hast du gesehen, wie ein Schatten unter der Tür durchging", "du hast die Tür abgeschlossen, oder", "jemand geht durch den Flur", "der Türgriff dreht sich langsam", "ich warte vor der Tür", "ich kann eintreten, ohne zu klingeln",
  "öffne diese Tür nicht", "wenn die Tür knarrt — das bin ich", "hast du etwas in der Küche fallen gehört", "ich lasse den Wasserhahn tropfen", "hör, wie sich der Kühlschrankton verändert hat", "bist du sicher, dass du den Herd ausgemacht hast",
  "sind alle Küchenmesser an ihrem Platz", "schau ins Glasregal", "unter dem Küchentisch steckt jemand", "ich habe gerade deinen Topf verschoben", "im Bad bin ich neben dir, während du duschst", "ich schreibe in den Dampf auf deinem Spiegel",
  "ich warte hinter dem Duschvorhang", "das Badezimmer abzusperren reicht nicht", "ich sehe dir zu, während du die Wanne füllst", "die Klotür bleibt sperrangelweit offen", "die siebte Treppenstufe wird gleich knarren", "ich höre dich von der unteren Etage aus",
  "oben ist jemand", "ich hänge im Treppenhaus", "hast du unten die Türklingel gehört", "lauf nicht die Treppe hinunter — ich kann dich nicht aufhalten", "ich werde gleich die Glühbirne ausschalten", "das Licht blinkt dreimal",
  "beobachte heute Nacht die Lampe", "geh nicht zum Sicherungskasten", "die Lampe in der Ecke ist mein Signal", "ziehst du den Stecker, wirst du mich nie finden", "hast du bemerkt, dass deine Wanduhr stehen geblieben ist", "um drei Uhr morgens klingelt die Uhr",
  "ich habe diesen Tag im Kalender durchgestrichen", "der Minutenzeiger läuft rückwärts", "ich weiß, dass dein Geburtstag naht", "die dunkelste Ecke des Hauses gehört mir", "schau in die rechte untere Ecke des Zimmers", "ich sitze an der linken Wand",
  "schau, wo Decke und Wand aufeinandertreffen", "unter diesem Fleck verbirgt sich ein Geheimnis", "heb den Teppich an und schau nach", "die Augen in diesem Gemälde sind meine Augen", "hast du dir den Menschen im Fotorahmen je aus der Nähe angeschaut",
];

export const PHONEMES: string[] = [
  "a", "e", "i", "o", "u", "ö",
  "ü", "ı", "ba", "be", "bi", "bo",
  "bu", "bö", "bü", "ca", "ce", "ci",
  "co", "cu", "da", "de", "di", "do",
  "du", "dö", "dü", "fa", "fe", "fi",
  "fo", "fu", "ga", "ge", "gi", "go",
  "gu", "gö", "gü", "ha", "he", "hi",
  "ho", "hu", "ka", "ke", "ki", "ko",
  "ku", "kö", "kü", "la", "le", "li",
  "lo", "lu", "lö", "lü", "ma", "me",
  "mi", "mo", "mu", "mö", "mü", "na",
  "ne", "ni", "no", "nu", "nö", "nü",
  "pa", "pe", "pi", "po", "pu", "ra",
  "re", "ri", "ro", "ru", "rö", "rü",
  "sa", "se", "si", "so", "su", "sö",
  "sü", "ta", "te", "ti", "to", "tu",
  "tö", "tü", "va", "ve", "vi", "vo",
  "vu", "ya", "ye", "yi", "yo", "yu",
  "yö", "yü", "za", "ze", "zi", "zo",
  "zu", "şa", "şe", "şi", "şo", "şu",
  "ça", "çe", "çi", "ço", "çu", "br",
  "kr", "tr", "gr", "pr", "fr", "dr",
  "st", "sk", "sp", "sl", "sm", "sn",
  "ah", "oh", "uh", "eh", "ih", "ay",
  "ey", "oy", "öy", "üy", "aa", "ee",
  "ii", "oo", "uu", "öö", "üü",
];

export const DARK_WORDS: string[] = [
  "Tod", "Seele", "Dunkelheit", "Schatten", "Fluch", "Angst",
  "Schrecken", "Hölle", "Grab", "Gruft", "Sarg", "Begräbnis",
  "tot", "Geist", "Geist", "Teufel", "Dämon", "Ifrit",
  "Wiedergänger", "Vampir", "Zombie", "Skelett", "Schädel", "Blut",
  "Schmerz", "Schrei", "Wehklagen", "Stöhnen", "Flüstern", "Stille",
  "Geräusch", "Schritt", "Donner", "Kälte", "sie drangen ein", "das Gegenteil",
  "Zeitverzerrung", "Schicksal", "Beweggrund", "aus dem Jenseits", "Manifestation", "Trugbild",
  "Spirale", "beschattet", "Flüsterpfad", "Kältewelle", "Frequenzverschiebung", "statisches Rauschen",
  "akustisch", "Déjà-vu", "Vision", "Silhouette", "zerbrochen", "verlassen",
  "gesperrt", "Nacht", "Mond", "Vollmond", "Wolke", "Nebel",
  "Rauch", "Dunst", "Finsternis", "Einsamkeit", "Verlassenheit", "verloren",
  "vergessen", "Gefangener", "gefesselt", "gebunden", "Kette", "Schloss",
  "Schlüssel", "Tür", "Fenster", "Spiegel", "Spiegelbild", "Geheimnis",
  "Geheimnis", "Zauberei", "Talisman", "Amulett", "böser Blick", "unheilbringend",
  "schwarz", "pechschwarz", "dunkel", "tief", "Leere", "Abgrund",
  "Brunnen", "unterirdisch", "Keller", "Gewölbe", "Tunnel", "Höhle",
  "Kerker", "Verlies", "Knochen", "Fleisch", "Haut", "Wunde",
  "Spur", "Fleck", "Rost", "Schimmel", "Spinne", "Netz",
  "Insekt", "Schlange", "Fledermaus", "Krähe", "Eule", "Wolf",
  "Fuchs", "Schakal", "Hyäne", "Geier", "Skorpion", "Ratte",
  "Feuer", "Flamme", "Asche", "Staub", "Erde", "Schlamm",
  "Sumpf", "Sturm", "Blitz", "Donnergrollen", "Erdbeben", "Überschwemmung",
  "Tsunami", "Pest", "Seuche", "Krankheit", "Gift", "Trank",
  "Hexe", "Zauberer", "Wahrsagerin", "Medium", "Seher", "Schamane",
  "Priester", "Zeremonie", "Ritual", "Opfer", "Weihegabe", "Verwünschung",
  "schwarze Magie", "Pentagramm", "Symbol", "Zeichen", "Inschrift", "Rune",
  "Portal", "Durchgang", "Dimension", "Parallelwelt", "die andere Seite", "das Jenseits",
  "das Totenreich", "Limbus", "Fegefeuer", "Seelenbrücke", "göttliche Waage", "Azrael",
  "Engel", "Dämon", "Wesenheit", "kalt", "Eis", "Frost",
  "Zittern", "Schauder", "Gänsehaut", "Dorn", "Atem", "blass",
  "keuchend", "Grunzen", "Summen", "Brummen", "Quietschen", "Klicken",
  "Knistern", "Rascheln", "Klirren", "Zischen", "heimgesucht", "Heimsuchung",
  "gebunden", "Verfolger", "Schattengestalt", "schwarze Masse", "weißer Schatten", "Lichtkugel",
  "Orb", "Ektoplasma", "Poltergeist", "Ouija", "Planchette", "Kerze",
  "Weihrauch", "Kristall", "Skryingkugel", "Geisterbeschwörung", "Séance", "Medialität",
  "Parapsychologie", "Telepathie", "Vorahnung", "Prophezeiung", "Alptraum", "Schlafwandeln",
  "Trance", "Hypnose", "Unterbewusstsein", "astral", "Projektion", "Seelenwanderung",
  "Reinkarnation", "Karma", "Aura", "Energie", "Vibration", "Frequenz",
  "Welle", "Signal", "Interferenz", "Lärm", "Katastrophe", "Verwüstung",
  "Apokalypse", "Weltuntergang", "das Ende", "Chaos", "Unordnung", "Ungewissheit",
  "Gefahr", "Bedrohung", "Warnung", "Hinrichtung", "Galgen", "Henker",
  "Peinigung", "Folter", "Verfall", "Verwesung", "Zerfall",
  "Auslöschung", "Tilgung", "Vergessenheit", "Verschwinden", "Verblassen",
  "Verdunkelung", "Ertrinken", "Verbrennen", "Erfrieren", "Fallen", "Versinken",
  "Falle", "Hinterhalt", "Verschwörung", "Intrige", "Betrug", "Verrat",
  "Täuschung", "Lüge", "falsch", "unecht", "Fiktion", "Halluzination",
  "Wahn", "Illusion", "Phantom", "Strudel", "Wirbel", "Hurrikan",
  "Tornado", "Lawine", "Erdrutsch", "Einsturz", "Zusammenbruch", "Spaltung",
  "Riss", "Abgrund", "Tiefe", "Dunkelheit unten", "finstere Leere", "das Nichts",
  "Nichtigkeit", "Abwesenheit", "Ewigkeit", "grenzenlose Ewigkeit", "Stillstand", "verrottet",
  "faul", "verwesend", "abgestanden", "leblos", "verwelkt", "verdorrt",
  "verbrannt", "zerbrochen", "zerschmettert", "zerquetscht", "vergessen", "verlassen",
  "verdammt", "verurteilt", "Al-Kari", "Nachtschreck", "Schreckgespenst", "Ghul",
  "Riese", "Unhold", "Hexe", "Albastı", "Koncolos", "Zyklop",
  "Basilisk", "Drache", "Simurgh", "Phönix", "Feuervogel", "Telekinese",
  "Levitation", "Apport", "Bilokation", "Hellsichtigkeit", "Präkognition", "Retrokognition",
  "Psychometrie", "Autoskopie", "Doppelgänger", "Phänomen", "Anomalie", "Abweichung",
  "Störung", "Unregelmäßigkeit", "düster", "dunkel", "diesig", "neblig",
  "bewölkt", "verregnet", "sturmgepeinigt", "windgepeitscht", "kalt", "eisig",
  "bedrückend", "erstickend", "beklemmend", "unheimlich", "gruselig", "beklemmend",
  "haarsträubend", "entsetzlich", "grauenerregend", "furchterregend", "geheimnisvoll", "rätselhaft",
  "unbegreiflich", "unerklärlich", "übernatürlich", "außergewöhnlich", "jenseitig", "seltsam",
  "unheimlich", "bizarr", "merkwürdig", "unerwartet", "plötzlich", "unangekündigt",
  "verborgen", "versteckt", "verschleiert", "maskiert", "verkleidet", "verhüllt",
  "verlassen", "verfallen", "Erscheinung", "stockdunkel", "Rätsel", "Bezauberung",
  "alte Schrift", "Weissagung", "Vorwurf", "Geistererscheinung", "endlich", "Zeichen",
  "letzter Wille", "Übergang", "Unterdrückung", "Zwietracht", "allumfassend", "Verstrickung",
  "Rückzug", "Trauer", "verhext", "unergründlich", "Sterblichkeit", "Abrechnung",
  "Besessenheit", "Delirium", "Wahnrede", "Blindheit des Geistes", "Wegzeichen", "augenscheinlich",
  "verborgen innen", "Ansteckung", "Ausbreitung", "dein Verhängnis", "Schicksal", "vorherbestimmt",
  "Prüfung", "Klagegeschrei", "Todesruf", "Nachhall", "Echos", "Stimmen aus dem Jenseits",
  "Resonanz", "Widerspiegelung", "Beschattung", "Illusion", "Schattenform", "dunkle Silhouette",
  "weißer Schatten", "trübe Erscheinung", "Kosmos", "dimensional", "zeitlich",
  "räumlich", "allumfassend", "alldurchdringend",
  "jenseitiger Impuls", "Emanation",
];

export const DARK_PHRASES: string[] = [
  "komm her", "hör mich", "hilf mir", "verlass mich nicht", "geh nicht", "ich bin hier",
  "ich sehe dich", "schau hinter dich", "sei vorsichtig", "flieh", "ich bin gestorben", "find mich",
  "rette mich", "ich leide", "ich bin allein", "wer ist da", "wer bist du", "was willst du",
  "warum bist du gekommen", "warum bist du hier", "wonach suchst du", "wen suchst du", "geh weg", "verlasse diesen Ort",
  "raus hier", "das ist mein Haus", "das ist mein Platz", "ich beobachte dich", "ich bin überall", "du kannst nicht entkommen",
  "ich werde dich finden", "ich bin dicht hinter dir", "Flucht ist zwecklos", "komm zurück", "komm wieder", "vergiss mich nicht",
  "erinnere dich", "schwör es", "ja", "nein", "vielleicht", "ich weiß es nicht",
  "das kann ich nicht sagen", "Mitternacht", "Morgengrauen", "Dämmerung", "die Vollmondnacht", "drei Uhr",
  "die Geisterstunde", "die dunkle Stunde", "öffne die Tür", "schließe das Fenster", "mach das Licht aus", "zünd die Kerze an",
  "bete", "Verwünschung", "sei verflucht", "Mutter", "Vater", "Kind",
  "Baby", "der alte Mann", "die alte Frau", "Liebe", "Hass", "Rache",
  "Zorn", "Eifersucht", "Verrat", "Mord", "Unfall", "Katastrophe",
  "Tragödie", "Schicksal", "Zeit", "Ewigkeit", "für immer", "die Vergangenheit",
  "die Zukunft", "jetzt sofort", "hier", "dort", "oben", "unten",
  "innen", "außen", "sei still", "hör zu", "hör mich", "sprich mit mir",
  "antworte mir", "dieses Haus", "dieses Zimmer", "dieser Ort", "dieser Ort ist verflucht", "das hier gehört mir",
  "vergib mir", "beeil dich", "die Zeit ist knapp", "deine letzte Chance", "schlaf nicht", "wach nicht auf",
  "träume", "Alptraum", "ein böser Traum", "stör mich nicht", "lass mich in Ruhe", "fass mich nicht an",
  "kalt", "eiskalt", "bitterkalt", "ich friere", "Schmerz", "unerträglicher Schmerz",
  "ich halte es nicht aus", "möge es aufhören", "warum", "wie", "wann",
  "wo", "drittes Stockwerk", "der Keller", "der Dachboden", "der Flur", "unter der Treppe",
  "der Spiegel", "schau in den Spiegel", "Spiegelbild", "seitenverkehrt", "um drei Uhr morgens", "dreh dich um",
  "schau nicht hin", "mach die Augen zu", "halte den Atem an", "Blutgeruch", "muffiger Geruch", "Brandgeruch",
  "Verwesung", "Schritte", "das Knarren der Tür", "splitterndes Glas", "ein Schrei", "hier ist jemand",
  "hinter mir", "neben mir", "über mir", "unter mir", "ich beobachte", "ich warte",
  "ich bin geduldig", "ich habe alle Zeit der Welt", "der Tod ist nah", "die letzte Nacht", "Abschied", "auf Wiedersehen",
  "lebwohl für immer", "ich kenne dich", "ich kenne deinen Namen", "ich kenne deine Vergangenheit", "ich kenne dein Geheimnis", "ich kenne deine Angst",
  "ich kenne deine Schwachstelle", "ich habe auf dich gewartet", "ich wusste, dass du kommen würdest", "ich bin bereit", "ich möchte mit dir sprechen", "hör mir zu",
  "ich habe etwas Wichtiges zu sagen", "vertrau niemandem", "vertrau keiner Seele", "du bist allein", "da ist niemand", "deine Freunde lügen dich an",
  "sie mögen dich nicht", "sie benutzen dich", "du wirst bald sterben", "deine Zeit läuft ab", "die Uhr tickt", "ich zähle deine letzten Atemzüge",
  "dein Grab ist bereit", "der Sarg wartet", "das Totengebet", "die Beerdigung", "die Erde ist kalt", "kalt und dunkel",
  "dieses Haus hat eine Geschichte", "hier ist jemand gestorben", "Blut wurde vergossen", "die Wände erinnern sich", "unter der Erde", "begraben",
  "verborgen", "ein geheimer Raum", "ein verborgener Gang", "hinter der Wand", "über der Decke", "ich möchte spielen",
  "sei mein Freund", "lass uns Verstecken spielen", "du hast mich gefunden", "du bist dran", "lauf mir nach", "du wirst mich nie fangen",
  "wo ist meine Mutter", "wo ist mein Vater", "ich möchte nach Hause", "ich habe mich verirrt", "ich finde meinen Weg nicht", "ich habe Angst vor der Dunkelheit",
  "ich bin so alt", "ich bin müde", "ich möchte ruhen", "ich kann mich nicht erinnern", "ich habe vergessen, wer ich bin", "wo bin ich",
  "wie lange ist es her", "Jahre sind vergangen", "Jahrhunderte sind vergangen", "ich bin noch hier", "ich kann nicht gehen", "ich kann nicht loslassen",
  "ich bin gefesselt", "ich fühle mich wie in Ketten", "ich bin nicht frei", "verschwinde von hier", "das ist mein Platz", "du hast Hausfriedensbruch begangen",
  "ich werde dich bestrafen", "du wirst es bereuen", "du wirst den Preis zahlen", "ich habe dich gewarnt", "meine letzte Warnung", "komm nicht wieder",
  "stör mich nicht", "zerstöre meinen Frieden nicht", "lass mich", "es tut mir so leid", "ich bereue es zutiefst", "ich wünschte, ich hätte es nicht getan",
  "ich möchte vergeben werden", "ich bin schuldig", "ich habe einen schweren Fehler gemacht", "es gibt kein Zurück", "es ist zu spät", "jetzt ist es viel zu spät",
  "die Chance ist vertan", "die Zeit ist um", "alles ist vorbei", "ich habe eine Botschaft", "hör genau zu", "entziffere es",
  "ich gebe dir einen Hinweis", "du kommst näher", "du bist auf dem richtigen Weg", "du schaust an der falschen Stelle", "schau anderswohin", "geh tiefer",
  "nicht an der Oberfläche", "darunter", "verborgen", "verschleiert", "maskiert", "hier lauert Gefahr",
  "sei vorsichtig", "schau dich um", "sei nicht allein", "bleib nicht im Dunkeln", "verlass das Licht nicht", "schließ die Tür ab",
  "schließ das Fenster", "zieh die Vorhänge zu", "schau nicht in den Spiegel", "dreh dich nicht um", "folg der Stimme nicht", "die Energie steigt",
  "die Vibration wächst", "die Frequenz verschiebt sich", "das Portal öffnet sich", "die Schwelle ist offen", "eine interdimensionale Verbindung", "das Signal wird stärker",
  "Kontakt wird aufgenommen", "es gibt eine Verbindung", "eine Botschaft kommt durch", "ich antworte", "ich höre",
  "es ist offen",
];

export const SPIRIT_NAMES: string[] = [
  "Hans", "Friedrich", "Wilhelm", "Heinrich", "Karl", "Otto",
  "Ludwig", "Ernst", "Gustav", "Wolfgang", "Albrecht", "Konrad",
  "Reinhard", "Dietrich", "Siegfried", "Hermann", "Bernhard", "Gottfried",
  "Adolf", "Rudolf", "Klaus", "Werner", "Manfred", "Helmut",
  "Günther", "Walther", "Lothar", "Eberhard", "Wilfried", "Theodor",
  "Anselm", "Berthold", "Detlef", "Engelbert", "Ferdinand", "Gerhard",
  "Hartmut", "Joachim", "Kasimir", "Leopold", "Greta", "Helga",
  "Ingrid", "Gerda", "Hilde", "Erna", "Frieda", "Else",
  "Käthe", "Margarete", "Brunhilde", "Adelheid", "Gudrun", "Waltraud",
  "Irmgard", "Roswitha", "Sieglinde", "Hedwig", "Gisela", "Edeltraud",
  "Mathilde", "Wilhelmina", "Bertha", "Klara", "Agnes", "Elsa",
  "Johanna", "Liesel", "Anneliese", "Cäcilia", "Dorothea", "Eleonore",
  "Friederike", "Henriette", "Josefine", "Karoline", "Leonore", "Magdalena",
  "Ottilie", "Philippine", "Rosalinde", "Theodora", "Ursula", "Veronika",
  "Wilfriede", "Adelina", "Brigitta", "Cordula", "Edelgard", "Felizitas",
  "Gertrud", "Hannelore", "Irmtraud", "Jutta", "Kunigunde", "Liselotte",
  "Mechthild", "Notburga", "Ottokar", "Reinhold", "Sebastian", "Thoralf",
  "Ulrich", "Volker", "Waldemar", "Adelbert", "Burkhard", "Diethelm",
  "Egbert", "Frowin", "Gernot", "Hagen", "Ingobert",
];

export const NUMBERS: string[] = [
  "eins", "zwei", "drei", "vier", "fünf", "sechs",
  "sieben", "acht", "neun", "zehn", "elf", "zwölf",
  "dreizehn", "vierzehn", "fünfzehn", "sechzehn", "siebzehn", "achtzehn",
  "neunzehn", "zwanzig", "einundzwanzig", "dreißig", "vierzig", "fünfzig",
  "sechzig", "siebzig", "achtzig", "neunzig", "hundert", "tausend",
  "null", "eine Million", "eine Milliarde", "achtzehnhundert", "neunzehnhundert", "zweitausend",
  "das fünfzehnte Jahrhundert", "das sechzehnte Jahrhundert", "das siebzehnte Jahrhundert", "das achtzehnte Jahrhundert", "das neunzehnte Jahrhundert", "das zwanzigste Jahrhundert",
];

export const HISTORICAL_WORDS: string[] = [
  "Osmanisch", "Sultan", "Herrscher", "Königin", "Pascha", "Bey",
  "Herrin", "Palast", "Schloss", "Turm", "Bollwerk", "Graben",
  "Brücke", "Brunnen", "Moschee", "Kirche", "Tempel", "Mausoleum",
  "Madrasa", "Krieg", "Frieden", "Eroberung", "Belagerung", "Sieg",
  "Niederlage", "Knechtschaft", "Schwert", "Schild", "Pfeil", "Speer",
  "Dolch", "Gold", "Silber", "Eisen", "Diamant", "Rubin",
  "Adhan", "Gebet", "rituelles Gebet", "Engel", "Dschinn", "Fee",
  "Drache", "Gasthaus", "Badehaus", "Karawanserei", "Basar", "Markt",
  "Sontag", "Reich", "Kalifat", "Herrschaft", "Thron", "Krone",
  "Edikt", "Tughra", "Siegel", "Urkunde", "Freibrief", "Janitscharen",
  "Sipahi", "Freischärler", "Qual", "Levent", "Kapitän", "Anführer",
  "Pirat", "Matrose", "Seemann", "Karawane", "Händler", "Kaufmann",
  "Geldwechsler", "Handwerker", "Derwisch", "Sufi", "Mevlevi", "Bektaschi",
  "Naqschbandiyya", "Ordenshaus", "Zawiya", "Tekke", "Khanqah", "Ribat",
  "Prinz", "Valide Sultan", "Haseki", "Konkubine", "Eunuch", "kaiserlicher Palast",
  "Topkapı", "Dolmabahçe", "Yıldız", "Çırağan", "Galata", "Beyoğlu",
  "Üsküdar", "Kadıköy", "Bosporus", "Rumelien", "Anatolien", "Thrakien",
  "Balkan", "Kaukasus", "Hethiter", "Sumerer", "Assyrer", "Babylonier",
  "Phryger", "Lyder", "Lykier", "Karier", "Ionier", "Urartu",
  "Seldschuken", "Byzanz", "Rom", "Griechenland", "Persien", "Mongolen",
  "Hunnen", "Göktürken", "Karachaniden", "Ghaznaviden",
];

export const NATURE_WORDS: string[] = [
  "Regen", "Schnee", "Eis", "Wind", "Sturm", "Hurrikan",
  "Blitz", "Blitzschlag", "Wolke", "Mond", "Stern", "Meer",
  "Ozean", "See", "Fluss", "Wasserfall", "Berg", "Höhle",
  "Wald", "Wüste", "Vulkan", "Erdbeben", "Nacht", "Tageslicht",
  "Morgengrauen", "Dämmerung", "Sonne", "Erde", "Planet", "Universum",
  "Galaxie", "Nebel", "Schwarzes Loch", "Komet", "Meteor", "Meteorit",
  "Boden", "Fels", "Stein", "Sand", "Kies", "Baum",
  "Blatt", "Zweig", "Wurzel", "Blume", "Unkraut", "Moos",
  "Pilz", "Flechte", "Efeu", "Wolf", "Bär", "Adler",
  "Schlange", "Skorpion", "Fledermaus", "Eule", "Krähe", "Katze",
  "Hund", "Insekt", "Spinne", "Fliege", "Mücke", "Biene",
  "Fisch", "Delphin", "Hai", "Oktopus", "Qualle", "roh",
  "Reif", "voll", "Regenguss", "Nieselregen", "Nordostwind", "Südwestwind",
  "Brise", "Schirokko", "Karayel", "Flut", "Ebbe", "Welle",
  "Strömung", "Strudel", "Quelle", "Frühling", "Bächlein", "Rinnsal",
  "Flussdelta", "Tal", "Schlucht", "Klamm", "Gebirgspass", "Hochebene",
  "Nebelwand", "Dampf", "Kondensation", "Rand", "Lichtstrahl", "Windstoß",
  "Einsiedelei", "Erdrutsch", "Erschütterung", "Verwerfungslinie", "Spalt", "Stalagmit",
  "Stalaktit", "Doline", "Krater", "Lava", "Magma", "Grundwasser",
  "Quellwasser", "Heilquelle", "Zauberquelle", "Schilfgürtel", "Teich", "Bach",
  "Bachbett", "Meeresschaum", "Gezeitenströmung", "Tautropfen", "Rinnsal", "Tropfen",
  "Schweiß", "Plasma", "Saft", "Harz", "Bernstein", "Fossil",
  "Muttergestein", "Mineral", "Erzlager", "Erz",
];

export const EMOTION_WORDS: string[] = [
  "Angst", "Entsetzen", "Panik", "Grauen", "Beklemmung", "Zorn",
  "Groll", "Hass", "Ekel", "Traurigkeit", "Trauer", "Schmerz",
  "Sehnsucht", "Einsamkeit", "Verzweiflung", "Hoffnungslosigkeit", "Leid", "Leiden",
  "Qual", "Pein", "Reue", "Gewissen", "Schuld", "Neugier",
  "Staunen", "Fassungslosigkeit", "Frieden", "Stille", "Ruhe", "Unbehagen",
  "Spannung", "Druck", "Niedergeschlagenheit", "Trostlosigkeit", "Melancholie", "Nostalgie",
  "Sehnsucht", "Heimweh", "Entfremdung", "Freude", "Glück", "Hochgefühl",
  "Begeisterung", "Aufregung", "Hoffnung", "Erwartung", "Verlangen", "Sehnen",
  "Leidenschaft", "Enttäuschung", "Ernüchterung", "lass dich nicht täuschen", "irr dich nicht", "Zweifel",
  "Bedenken", "Zögern", "Unentschlossenheit", "Unsicherheit", "Mut", "Kühnheit",
  "Heldenmut", "Aufopferung", "Gnade", "Mitgefühl", "Mitleid", "Einfühlungsvermögen",
  "Eifersucht", "Neid", "Missgunst", "Gehässigkeit", "Scham", "Peinlichkeit",
  "Langeweile", "Erschöpfung", "Entsetzen", "Brutalität", "Ungeheuerlichkeit", "Grausamkeit",
  "Unmenschlichkeit",
];

export const BODY_WORDS: string[] = [
  "Hand", "Fuß", "Kopf", "Auge", "Ohr", "Mund",
  "Zahn", "Zunge", "Finger", "Hals", "Rücken", "Brust",
  "Herz", "Gehirn", "Blut", "Knochen", "Haut", "Atem",
  "Puls", "Träne", "Schulter", "Arm", "Handgelenk", "Handfläche",
  "Nagel", "Knie", "Wade", "Ferse", "Taille", "Bauch",
  "Leber", "Niere", "Eingeweide", "Lunge", "Magen", "Ader",
  "Nerv", "Muskel", "Sehne", "Gelenk", "Haar", "Augenbraue",
  "Wimpern", "Schnurrbart", "Bart", "Schläfe", "Stirnwulst", "Kinn",
  "Wange", "Nase", "Wirbelsäule", "Rippe", "Schlüsselbein", "Schulterblatt",
  "Becken", "Schädel", "Kieferknochen", "Jochbein", "Augenhöhle",
];

export const PLACE_WORDS: string[] = [
  "Haus", "Zimmer", "Halle", "Flur", "Treppenhaus", "Dach",
  "Keller", "Tür", "Fenster", "Wand", "Decke", "Friedhof",
  "Krankenhaus", "Gefängnis", "Wald", "Höhle", "Brunnen", "Tunnel",
  "Brücke", "Küche", "Badezimmer", "Schlafzimmer", "Wohnzimmer", "Balkon",
  "Garage", "Garten", "Innenhof", "Terrasse", "Veranda", "Kirche",
  "Moschee", "Synagoge", "Tempel", "Kloster", "Schloss", "Palast",
  "Turm", "Kerker", "Keller", "Schule", "Bibliothek", "Museum",
  "Theater", "Opernhaus", "Fabrik", "Lager", "Depot", "Silo",
  "Hangar", "Dorf", "Kleinstadt", "Stadt", "Großstadt", "Ruine",
  "Öde", "Schutthaufen", "Trümmer", "Geröll", "Überreste", "Insel",
  "Halbinsel", "Kap", "Bucht", "Hafen", "Bahnhof", "Terminal",
  "Flughafen", "Pier", "Dock", "Park", "Lustgarten", "Hain",
  "Wiese", "Feld", "Bauernhof", "Scheune", "Heuhaufen", "Mühle",
  "Brennofen", "Badehaus", "Gasthaus", "Karawanserei", "Basarhaus", "Markt",
  "Mausoleum", "Külliye", "Madrasa", "Ordenshaus", "Zawiya", "Begräbnisstätte",
  "Schrein", "Grab", "Sarkophag", "Beinhaus", "verlassenes Haus", "Spukhaus",
  "verfluchtes Schloss", "Geisterstadt", "tote Stadt", "verlorenes Dorf", "versunkenes Schiff", "verlassenes Krankenhaus",
  "altes Gefängnis", "unterirdische Stadt", "Katakombe", "Gewölbegruft", "Gasse", "Schattengasse",
  "Dachboden", "Labyrinth", "Geheimkammer", "Kaminschacht", "Kamin", "unter der Treppe",
  "Erdgeschoss", "Unterstand", "Gewölbegang", "Säule", "Strebepfeiler", "Balken",
  "in der Krypta", "Grabkammer", "Denkmal", "großer Wandspiegel",
];

export const TIME_WORDS: string[] = [
  "jetzt", "sofort", "danach", "davor", "gestern", "heute",
  "Mitternacht", "Morgen", "Abend", "Nacht", "Tagesanbruch", "Ewigkeit",
  "für immer", "die Vergangenheit", "die Zukunft", "Jahrhundert", "die Geisterstunde", "jenseits",
  "ewig", "sterblich", "das erste Licht", "Sonnenwende", "Mondfinsternis", "Sonnenfinsternis",
  "Halbmond", "Dunkelmond", "Blutmond", "Sternschnuppe", "Milchstraße", "Sternbild",
  "Polarstern", "Norden", "Süden", "Osten", "Westen", "Richtung",
  "der Horizont", "morgen", "übermorgen", "Woche", "Monat", "Jahr",
  "Jahrhundert", "tausend Jahre", "Zeitalter", "Zeitenwende", "Zeitraum", "Augenblick",
  "Sekunde", "Minute", "die Uhr", "im Nu", "zuerst", "zuletzt",
  "Anfang", "Ende", "das Finale", "Geburt", "Tod", "Leben",
  "Dasein", "Sein", "Frühling", "Sommer", "Herbst", "Winter",
  "Jahreszeit", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag",
  "Samstag", "Sonntag", "Feiertag", "heilige Nacht", "Vorabend",
];

export const ACTION_WORDS: string[] = [
  "komm", "geh", "halt an", "warte", "lauf", "flieh",
  "versteck dich", "schau", "sieh", "hör zu", "hör", "berühr",
  "fühle", "sprich", "sei still", "flüstere", "schrei", "weine",
  "schlaf", "wach auf", "erinnere dich", "vergiss", "streck die Hand aus", "schließ",
  "sperr ab", "schneide", "zerschmettere", "verbrenn", "lösch aus", "stirb",
  "werd geboren", "lebe", "verschwinde", "erscheine", "ruf aus", "find",
  "verliere", "verbirg", "begrab", "zieh hinunter", "raus",
  "tritt ein", "kletter", "spring", "träume", "kriech", "schleich",
  "geh", "tanze", "kehr zurück", "dreh dich um", "beuge dich", "winde dich",
  "schaudere", "zittere", "bebe", "verdoppele", "schlage", "kralle",
  "greife", "schleppe", "zerquetsche", "wirf", "verschlinge", "verzehre",
  "schlucke", "spucke", "erstick", "atme", "atme aus", "ertrinke",
  "keuch", "weine laut", "schluchze", "schrei auf", "stöhn", "wimmere",
  "flüstere", "summe", "gruntze", "knurre", "heule", "folge",
  "beobachte", "spioniere", "laure", "greife an", "verteidige", "schütze",
  "such Zuflucht", "riegle ab", "stelle eine Falle", "flehe", "ergreife", "wünsche",
  "frage", "bitte", "verfluche", "verdamme", "wirke einen Zauber", "vollziehe das Ritual",
  "halte eine Séance", "gestehe", "bekenne", "nimm an", "leugne", "verweigere",
  "vergib", "erlöse", "bestrafe", "belohne", "bleibe", "hilf",
  "halte Wache", "erfülle", "tritt ein", "verlass", "stell dich dem", "löse sich auf",
  "fessle", "befreie", "verbirg", "lache nicht", "beschwöre", "verfolge",
  "bring", "trag fort", "rette", "hilf mir", "lass los", "halte fest",
  "fange", "lass nicht los", "vergiss nicht", "sag es mir", "ruf heraus", "sprich",
  "bedecke", "versiegle", "sperr ein", "entwirre", "binde fest", "trenne",
  "erleuchte", "tauche in Dunkelheit",
  "halte durch",
];

export const RELIGIOUS_WORDS: string[] = [
  "Allah", "Bismillah", "Maschallah", "so Gott will", "Alhamdulillah", "Adhan",
  "Gebet", "Fasten", "Pilgerfahrt", "Zakat", "Paradies", "Hölle",
  "Fegefeuer", "Seelenbrücke", "göttliche Waage", "Engel", "Teufel", "Dschinn",
  "Dämon", "Huri", "Azrael", "Michael", "Gabriel", "Israfil",
  "der Jüngste Tag", "die Apokalypse", "Auferstehung", "die Ausbreitung", "das Verhör im Grab", "Grabesstrafe",
  "Munkar", "Nakir", "Befragung", "Rechenschaft", "gute Tat", "Sünde",
  "Reue", "Vergebung", "Lobpreis", "Sure", "Vers", "Hadith",
  "Beschneidung", "obligatorisch", "Halal", "Haram", "verwerflich", "erlaubt",
  "Pflicht", "Kirche", "Priester", "Geistlicher", "Nonne", "Kreuz",
  "Taufe", "Beichte", "Ritus", "Kommunion", "Weihwasser", "Rosenkranz",
  "Ikone", "Heiliger", "Seliger", "Sufi", "Derwisch", "Meister",
  "Schüler", "Orden", "Dhikr", "Sama", "Ekstase", "göttliche Auflösung",
  "göttliche Permanenz", "Entdeckung", "Erleuchtung", "Wunder", "Zeichen", "Zauberei",
  "böser Blick", "Blick", "Faszination", "Neid", "Verzauberung", "Amulett",
  "Talisman", "Vefk", "Hamail", "Abschrift", "Besessenheit", "Sara-Krankheit",
  "böse Berührung", "Bindungszauber", "Nekromantie", "Omen", "Traumdeutung", "Wahrsagerei",
  "Kaffeesatzlesen", "Tarot", "Astrologie", "Horoskop", "Sternenkarte",
];

export const PARANORMAL_TERMS: string[] = [
  "EMF", "Detektor", "Sensor", "Messgerät", "Radar", "Kamera",
  "Wärmebildkamera", "Nachtsicht", "Infrarot", "Ultraviolett", "Mikrofon", "Aufnahmegerät",
  "Stimmanalyse", "Frequenzanalyse", "Geisterbox", "Ghost Box", "Franks Box", "Ovilus",
  "SLS-Kamera", "Kinect", "LiDAR", "Tiefensensor", "K2-Meter", "Mel-Meter",
  "REM-Pod", "Bewegungssensor", "Wünschelrute", "Pendel", "Ouija-Brett", "Planchette",
  "EVP", "elektronisches Stimmphänomen", "elektronisches Geräusch", "statisches Rauschen", "Erscheinung", "materialisieren",
  "Bild", "Silhouette", "Schattengestalt", "Kältepunkt", "Temperaturabfall", "Wärmepunkt",
  "Anomalie", "Orb", "Lichtkugel", "Lichtstreifen", "Lichtaufblitzen", "Poltergeist",
  "Telekinese", "Levitation", "Apport", "Ektoplasma", "Ektoplasmabildung", "Materialisierung",
  "ganzkörperliche Erscheinung", "teilweise Erscheinung", "Schattenmensch", "ortsgebundene Heimsuchung", "intelligente Heimsuchung", "dämonische Heimsuchung",
  "Portal-Heimsuchung", "Dimensionsübergang", "Zeitrutsch", "Untersuchung", "Forschung", "Auswertung",
  "Entdeckung", "Beobachtung", "Beweis", "Nachweis", "Befund", "Daten",
  "Analyse", "Bericht", "Aufzeichnung", "Dokument", "Akte", "Archiv",
  "Sitzung", "Nachtwache", "Experiment", "Test", "Kontrolle", "Hypothese",
  "Theorie", "Ergebnis", "Deutung", "Auswertung", "Magnetfeld", "Schwankung",
  "Grundrauschen", "weißes Rauschen", "rosa Rauschen", "Frequenzabschneidung", "Signalverlust", "Datenstrom",
  "Verzerrung", "Energiestoß", "Ionisierung", "thermischer Abfall", "plötzliche Abkühlung", "Ausschlag",
  "elektromagnetisch", "Strahlung", "Wellenlänge", "Abtastrate", "Kanal-Hopping", "umgekehrte Stimme",
  "Spiegeleffekt", "Echokammer", "Schallbarriere", "Unterdrückung", "Filterung", "isoliert",
  "abgeschirmt", "geschützt", "abgedichteter Raum", "Quarantäne", "Kontamination", "Interaktion",
  "Auslöser", "Aktivierung", "Automatikaufnahme", "Graphspitze", "Frequenzspitze", "Messwert",
  "Überwachungspanel", "Livedaten", "Globaldaten", "Standort", "Koordinaten", "Höhe",
  "Druck", "atmosphärisch", "Feuchtigkeitsgehalt", "Schwefelgeruch", "Ozon", "Brandgeruch",
  "Feuchtigkeitsgeruch", "Windkorridor", "Luftstrom", "Strömung", "elektrostatische Aufladung",
  "Aufladung", "Entladung", "Batterieentleerung", "Energieabsorption", "Spannung", "Stromfluss",
  "Widerstand", "Kondensator", "Spule", "Relais", "Sicherungsautomat", "Kurzschluss",
  "Erdung", "Isolator", "leitfähig", "Halbleiter", "Quarz", "Linse",
  "Fokussierung", "reflektierende Oberfläche", "Lichtbrechung", "Lichtspektrum", "Vollspektrum",
  "spektrale Signatur",
];

export const OBJECT_WORDS: string[] = [
  "Kerze", "Öllampe", "Laterne", "Lampe", "Fackel", "Spiegel",
  "Glas", "Kristall", "Skryingkugel", "Prisma", "Buch", "Notizbuch",
  "Brief", "Karte", "Kompass", "Uhr", "Glocke", "Handglocke",
  "Pfeife", "Rohr", "Strick", "Kette", "Seil", "Schnur",
  "Draht", "Messer", "Schwert", "Dolch", "Axt", "Hammer",
  "Stein", "Marmor", "Granit", "Obsidian", "Amethyst", "Silber",
  "Gold", "Kupfer", "Eisen", "Blei", "Salz", "Wasser",
  "Feuer", "Erde", "Luft", "Porträt", "Fotografie", "Bildnis",
  "Tisch", "Statue", "Spielzeug", "Puppe", "Marionette", "Maske",
  "Kostüm", "Krone", "Ring", "Halskette", "Armband", "Brosche",
  "Truhe", "Schachtel", "Tasche", "Koffer", "Korb", "Teppich",
  "Läufer", "Vorhang", "Leichentuch", "Decke", "Vase", "Teller",
  "Glasgefäß", "Schüssel", "Topf", "Gebetbuch", "Rosenkranz", "Kreuz",
  "Amulett", "Nazar-Auge", "Knarren", "Türgriff", "Riegelfalle", "Schlüsselloch",
  "verrostete Kette", "Vorhängeschloss", "Grabstein", "Büste", "altes Foto", "Leinwand",
  "Fresko", "Tapete", "zerfetzter Stoff", "Glasscherben", "Fenstervorhang", "Schleierstoff",
  "Spitze", "Aussteuerkasten", "altes Spielzeug", "Porzellanpuppe", "Wiege", "Schaukelstuhl",
  "Uhrpendel", "Wanduhr", "Kettenuhr", "Stoppuhr", "Sanduhr", "Gaslampe",
  "Kerzenhalter", "Reliquiar", "Kuriosität", "Staubwolke", "Spinnennetz", "Haarsträhne",
  "Gewand", "Umhang", "Blutspur", "Feuchtigkeitsfleck", "Geruch", "muffiger Gestank",
  "alter Wälzer", "Manuskript", "Pergament", "Ledereinband", "Tinte", "Tintenfass",
  "Feder", "Umschlag", "Siegellack", "Siegel", "Wappen", "Medaillon",
];

export const ADJECTIVE_WORDS: string[] = [
  "dunkel", "hell", "düster", "leuchtend", "fahl", "kalt",
  "glühend", "warm", "eisig", "brennend", "uralt", "neu",
  "urzeitlich", "alterslos", "modern", "gewaltig", "klein", "riesig",
  "winzig", "zart", "lang", "kurz", "weit", "eng",
  "tief", "schwer", "leicht", "dick", "dünn", "hart",
  "weich", "rau", "glitschig", "klebrig", "ausgedörrt", "durchnässt",
  "feucht", "dumpf", "schimmelig", "verrottet", "schön", "grässlich",
  "entsetzlich", "schaurig", "heimgesucht", "lautlos", "lärmend", "gedämpft",
  "friedlich", "unruhig", "schnell", "langsam", "plötzlich", "allmählich",
  "unaufhörlich", "unsichtbar", "transparent", "undurchsichtig", "verschwommen", "klar",
  "lebend", "tot", "leblos", "reglos", "erstarrt", "verflucht",
  "heilig", "besudelt", "sauber", "rein", "verwickelt", "schlicht",
  "geheimnisvoll", "offen", "verschlossen", "wirklich", "falsch", "illusorisch",
  "gespenstisch", "surreal", "flüsternd", "wartend", "weit entfernt", "nah",
  "verschlossen", "talismanhaft", "zurückgezogen", "zornig", "rastlos", "allein",
  "von Entsetzen gepackt", "sprachlos", "von Angst erfüllt",
];

export const MANIPULATIVE_RESPONSES: string[] = [
  "ja", "nein", "vielleicht", "könnte sein", "niemals", "mit Sicherheit",
  "wahrscheinlich", "ich glaube nicht", "ich bin mir nicht sicher", "wahr", "falsch", "zum Teil",
  "manchmal", "immer", "nie", "selten", "oft", "meistens",
  "schau nach rechts", "schau nach links", "schau nach oben", "schau nach unten", "schau hinter dich", "schau nach vorne",
  "schau dich um", "schau die Wand an", "geh zur Tür", "geh zum Fenster", "geh in den Keller", "geh auf den Dachboden",
  "geh hinaus", "komm herein", "komm näher", "geh weg", "einen Schritt weiter", "mein Alter war",
  "ich bin hier gestorben", "ich habe hier gelebt", "ich bin schon lange hier", "ich habe hundert Jahre gewartet", "ich habe auf dich gewartet", "du musstest kommen",
  "Schicksal", "hab keine Angst", "du solltest Angst haben", "du bist nicht in Gefahr", "du bist in Gefahr", "du bist in Sicherheit",
  "du bist nicht sicher", "du bist nicht allein", "du bist völlig allein", "du wirst geliebt", "du wirst nicht geliebt", "man hat dich vergessen",
  "du wirst in Erinnerung bleiben", "die Zeit kommt", "sei geduldig", "warte", "sei bereit", "du wirst es bald verstehen",
  "alles wird sich klären", "es bleibt ein Geheimnis", "das kann ich nicht sagen", "es ist verboten", "keine Erlaubnis", "es gibt eine Grenze",
  "hinter dir", "neben dir", "oben", "ich habe es gesehen", "du hast es gehört", "nähert sich",
  "berühren", "ein Frevel", "ein Vorfall", "eine verlorene Seele", "wir", "sie",
  "niemand", "ein Besucher", "etwas hier", "es gehört hierher", "in Verwahrung", "alt",
  "ich weiß es", "du hast es gesehen", "ich habe es versteckt", "war hier", "sie sind gegangen", "aufgewacht",
  "schlafend", "tief drinnen", "weit weg", "dein Name", "ich habe es begraben", "ich habe es genommen",
  "ich habe es verloren", "ich habe es gefunden", "ich suche", "ich komme", "ich gehe", "ich blieb",
  "ich starb", "ich lebe", "bald", "direkt hinter dir", "zu deiner Rechten", "zu deiner Linken",
  "oben", "dazwischen", "darin", "jenseits", "am nahen Ufer", "gegenüber",
  "an der Schwelle", "wer bist du", "wie heißt du", "was willst du", "warum bist du hier", "wie viele seid ihr",
  "wann kamst du", "wie bist du gestorben", "kannst du uns hören", "willst du Hilfe", "sollen wir gehen",
];

export const LONG_PHRASES: string[] = [
  "du bist heute Nacht nicht allein hier", "jemand lebt hinter den Wänden", "ich komme jeden Abend zur gleichen Zeit", "ich beobachte dich schon lange", "dieses Haus hat eine Geschichte", "hier wurde viel Blut vergossen",
  "niemand ist hier lebend herausgekommen", "du wirst nicht der Letzte sein, der kommt", "die Tür abzusperren nützt dir nichts", "ich bin die ganze Zeit überall", "wenn du die Augen schließt, siehst du mich", "ich werde dich in deinen Träumen besuchen",
  "bleib wach, denn ich bin wach", "schlaf heute Nacht nicht, schlaf nicht", "hörst du deine eigenen Schritte", "der Schatten hinter dir gehört nicht mir", "schau in den Spiegel und du wirst mich sehen", "ich bin die Stimme, die von der Decke kommt",
  "im Keller ist etwas", "jemand geht auf dem Dach", "ich sah einen Schatten im Garten", "jemand schaut durchs Fenster herein", "die Tür öffnete sich von selbst", "die Lichter flackern",
  "die Uhr blieb um drei Uhr morgens stehen", "der Spiegel zerbrach von selbst", "Blut sickert aus der Wand", "Geräusche steigen aus der Erde auf", "das ist kein Wasser — es ist Blut, das von der Decke tropft", "die Gestalt auf dem Foto hat sich bewegt",
  "die Puppe lächelte", "jemand kommt die Treppe herunter", "am Ende des Flurs steht jemand", "Hände greifen unter dem Bett hervor", "jemand atmet im Schrank", "hinter dem Vorhang ist eine Silhouette",
  "Augen leuchten in der Dunkelheit", "das Bild an der Wand beobachtet dich", "deine Uhr hat aufgehört zu ticken", "das Telefon klingelte, aber niemand war da", "seltsame Geräusche kommen aus dem Radio", "der Fernseher schaltete sich von selbst ein",
  "auf dem Computerbildschirm erschien ein Gesicht", "Blut strömt aus dem Wasserhahn", "ich werfe kein Spiegelbild", "mein Schatten bewegt sich unabhängig von mir", "das ist der Ort, den ich in meinen Träumen gesehen habe", "ich war schon einmal hier",
  "ich habe diesen Moment schon einmal erlebt", "ich stecke in einer Zeitschleife", "es gibt keinen Ausweg von hier", "Türen verschlossen, Fenster verriegelt", "die Wände begannen sich zu verengen", "die Decke senkt sich",
  "der Boden gibt nach", "die Luft wird kälter", "ich kann meinen Atem sehen", "etwas berührte mein Bein", "mir wurden die Haare gezogen", "etwas flüsterte mir ins Ohr",
  "ich spürte kalten Atem in meinem Nacken", "eine Hand berührte meine Schulter", "jemand schubst mich von hinten", "mein Fuß blieb an etwas hängen", "etwas bewegte sich in der Dunkelheit", "ein Schatten erschien in der Ecke und war verschwunden",
  "das ist kein Staub, was von der Decke fällt — es ist Asche", "die Uhr an der Wand läuft rückwärts", "aus dem Spiegel erscheint ein anderer Raum", "das Ende der Treppe öffnet sich in die Dunkelheit", "dieser Flur hat kein Ende", "jedes Mal, wenn ich die Tür öffne, bin ich im selben Zimmer",
  "ich sehe nichts durch das Fenster", "draußen ist nichts — nur Dunkelheit", "in diesem Zimmer wurde jemand erhängt", "unter dem Bett ist eine Leiche begraben", "in den Wänden stecken Knochen", "dieses Haus wurde auf einem Friedhof errichtet",
  "nachts kommen Geräusche aus den Wänden", "bei jedem Vollmond geschehen seltsame Dinge", "die Nachbarn machen einen großen Bogen um dieses Haus", "jeder, der je hier lebte, wurde wahnsinnig", "der letzte Mieter verschwand", "selbst die Polizei betritt dieses Haus nicht",
  "selbst der Imam konnte diesen Ort nicht reinigen", "der Priester kam — und floh", "die hier vollzogenen Rituale dauern noch an", "um drei Uhr morgens sind Schreie zu hören", "Kinder gehen nicht an diesem Haus vorbei", "Katzen kommen diesem Haus nicht nahe",
  "Hunde heulen vor diesem Haus", "Vögel fliegen nicht über dieses Haus", "die Bäume rund um das Haus sterben ab", "in diesem Garten blüht keine Blume", "Sonnenlicht dringt nicht in dieses Haus", "die Uhr bleibt jede Nacht um drei stehen",
  "Spiegel springen von selbst", "Kerzen entzünden sich von selbst", "Türen öffnen und schließen sich von allein", "der Stuhl bewegt sich ohne Berührung", "die Augen der Gemälde folgen dir", "der Fleck an der Wand wird täglich größer",
  "der Riss in der Decke sieht aus wie ein Gesicht", "der Blutfleck auf dem Boden lässt sich nicht entfernen", "die Luft in diesem Zimmer ist immer kalt", "elektronische Geräte versagen hier", "hier ist dein Akku in Sekunden leer", "der Kompass dreht hier durch",
  "die Uhren zeigen hier die falsche Zeit", "Kameras funktionieren hier nicht", "auf den Fotos von hier sind seltsame Formen zu sehen", "in den Videos ist jemand zu sehen, der nicht da sein sollte", "in den Tonaufnahmen sind Flüsterlaute", "das EMF-Gerät schlägt hier verrückt",
  "die Temperatur fällt ohne Vorwarnung", "in der Luft liegt ein fremder Geruch", "Muffigkeit ohne Schimmel", "Brandgeruch ohne Feuer", "Blumenduft ohne Blumen", "Parfümgeruch ohne jede Anwesenheit",
];

export const MYTHOLOGY_WORDS: string[] = [
  "Al-Kari", "Nachtschreck", "Schreckgespenst", "Ghul", "Riese", "Unhold",
  "Albastı", "Koncolos", "Tepegöz", "Basilisk", "Hıdırellez", "Nowruz",
  "Ergenekon", "der graue Wolf", "Asena", "der Kopfberg", "der Tuba-Baum", "das Wasser des Lebens",
  "das Wasser der Unsterblichkeit", "Phönix", "Feuervogel", "Simurgh", "das Windpferd", "die Windfee",
  "Nymphe", "Berggeist", "Dryade", "der böse Blick", "der verhängnisvolle Blick", "der Fluch",
  "besessen", "Werwolf", "Nachteule", "Schrei der Eule", "schwarze Katze", "die vierzig Schritte",
  "der Hebammengeist", "der wunscherfüllende Geist", "der Wunschbaum", "der Wunschbrunnen", "der Opferort", "zu Boden geworfen",
  "Heiliger", "Gottseliger", "Ältester", "Pir", "Patriarch", "der Hoca",
  "Zauberin", "die wahrsagende Alte", "verborgener Schatz", "ein Begräbnis", "Schatz", "der goldene Würfel",
  "der verfluchte Hort", "der Wächterdschinn", "der Schatzhüter", "die Talismantür", "der Zauberspiegel", "der fliegende Teppich",
  "Unsichtbarkeit", "Unsterblichkeit", "das Elixier der Jugend", "die Totenwascherin", "Leichentuch", "der Musalla-Stein",
  "Leichenwagen", "Grabstein", "Kopfstein", "Fußstein", "Sarkophag", "Steinsarg",
  "Mausoleum", "Käfig", "Türbe", "Massengrab", "das verschollene Grab", "das namenlose Grab",
  "der Mitternachtsfriedhof", "der verlassene Friedhof",
];

export const FOLK_BELIEFS: string[] = [
  "Nazar-Bead", "beschriebenes Amulett", "Blei gießen", "Weihrauch verbrennen", "ein Gelübde ablegen", "wünsch dir das besser nicht",
  "Traumdeutung", "Wahrsagerei", "Kaffeesatzlesen", "Handlesen", "Horoskop", "Wasserweissagung",
  "Spiegelmagie", "Kerzenmagie", "Fadenzauber", "Bindungszauber", "Trennungszauber", "Liebeszauber",
  "schwarze Magie", "weiße Magie", "Geistermagie", "Heiler", "Dschinn", "Amulettmacher",
  "Zauberer", "Beschwörer", "Gaukler", "Illusionist", "Nekromantie", "Glastippen",
  "Bleistifthalten", "Tischklopfen", "Ouija-Brett", "Geistertafel", "lad keinen Dschinn ein", "Exorzismus",
  "binde den Dschinn nicht", "Beschwörungsformel", "Afsun", "Rezitation", "den Zauber einblasen", "atme nicht",
  "Wasserweissagung", "Glaubensheilung", "der Blick", "die böse Berührung", "Zungenaffektion", "böser Geist",
  "gütiger Geist", "Schutzgeist", "Ahnengeist", "Großvatergeist", "Großmuttergeist", "Hausgeist",
  "Badegeist", "Wassergeist", "Feuergeist", "Erdgeist", "Wettergeist", "muslimischer Dschinn",
  "ungläubiger Dschinn", "verliebter Dschinn",
];

export const HORROR_STORY_WORDS: string[] = [
  "Jump-Scare", "wachsende Spannung", "Schrecken", "Horror", "Panik", "Flucht",
  "die Jagd", "der Hinterhalt", "die Schlinge", "die Falle", "das Opfer", "der Jäger",
  "die Beute", "Verfolgung", "der Schatten", "eine quietschende Tür", "knarrendes Holz", "raschelnde Blätter",
  "der heulende Wind", "eine pfeifende Pfeife", "klappernde Fensterscheiben", "Klingeln im Ohr", "ein pochender Schädel", "zitternde Hände",
  "ein gedämpfter Schrei", "eine abgerissene Stimme", "das Blut gefriert", "sträubende Nackenhaare", "Gänsehaut", "zitternde Haut",
  "rasendes Herzklopfen", "kalter Schweiß", "ein Zittern", "ein Krampf", "Atemnot", "Schwindel",
  "Übelkeit", "verschwommenes Sehen", "Ohrensausen", "Taubheit", "sei nicht gelähmt", "erstarr nicht",
  "zu Stein erstarrt", "Levitation", "Telekinese", "Selbstentzündung", "Gestaltwandel", "Dimensionssprung",
  "Zeitreise", "Seelentrennung", "außerkörperliche Erfahrung", "Astralreise", "Bewusstseinsübertragung", "Gedankenkontrolle",
  "Hypnose", "Massenhysterie", "kollektive Halluzination", "der verfluchte Spiegel", "die verfluchte Puppe", "der verfluchte Ring",
  "das verfluchte Buch", "das verfluchte Gemälde", "das verfluchte Schmuckstück", "der verfluchte Dolch", "die verfluchte Krone", "die verfluchte Truhe",
  "die verfluchte Karte", "der verfluchte Kompass", "die verfluchte Uhr",
];

export const DIALOG_PHRASES: string[] = [
  "Hallo", "Grüße", "Willkommen", "ich habe auf dich gewartet", "endlich bist du da", "du bist zu spät",
  "wo warst du", "dieser Ort gehört mir", "ich bin die Seele dieses Hauses", "ich bin hier gestorben", "ich bin hier begraben", "ich kann dir meinen Namen nicht nennen",
  "ich habe meinen Namen vergessen", "keine Schritte mehr", "ich habe nie wirklich existiert", "ich bin eine Erinnerung", "ich bin ein Echo", "verlasse diesen Ort sofort",
  "bleib heute Nacht nicht hier", "geh, bevor die Sonne untergeht", "verlasse diesen Ort, bevor die Dunkelheit fällt", "geh vor Mitternacht", "verlasse ihn vor drei Uhr", "betritt dieses Zimmer nie wieder",
  "öffne diese Tür nie wieder", "schau nie wieder in diesen Spiegel", "sprich diesen Namen nie wieder aus", "hier lebte einst eine Familie", "dieses Haus wurde vor hundert Jahren gebaut", "hier hat es einmal gebrannt",
  "hier wurde ein Mord begangen", "ein Kind verschwand hier", "eine Frau nahm sich hier das Leben", "ein Mann wurde hier wahnsinnig", "hier wurde ein Ritual abgehalten", "hier liegt ein Schatz vergraben",
  "hier begann ein Fluch", "ich werde dich hier festhalten", "du wirst nie gehen", "du bleibst bei mir", "hier für immer", "es gibt kein Entkommen",
  "keinen Ausgang", "keine Rettung", "Beten wird nicht helfen", "niemand kann dich retten", "schrei so viel du willst — niemand hört es", "bitte geh nicht",
  "lass mich nicht allein", "ich bin so schrecklich einsam", "niemand kommt jemals", "ich warte seit Jahren", "jahrhundertelang allein", "ich brauche einen Gefährten",
  "ich möchte mit jemandem sprechen", "du bist der Erste, der meine Stimme hört", "du bist der Erste, der mich sieht",
];

export const PROVERBS: string[] = [
  "am Ende müssen wir alle sterben", "jedes Lebewesen wird den Tod kosten", "der Tod ist in die Welt gekommen — Kopfschmerzen sind nur eine Ausrede", "das Grab ist dunkel", "die Erde ist kalt", "die Nacht ist lang",
  "der Morgen liegt weit entfernt", "Angst kann den Tod nicht aufhalten", "jede Dunkelheit hat ein Ende", "Feuer verbrennt, wo es hinfällt", "Wasser schläft, doch der Feind schläft nicht", "aus den Augen, aus dem Sinn",
  "erwarte nicht, dass die Toten unter den Lebenden erscheinen", "was kommt und geht, hinterlässt Spuren", "alles hat ein Ende", "Geduld ist bitter, doch ihre Frucht ist süß", "man nennt die Vergangenheit aus gutem Grund Vergangenheit", "aus alten Freunden werden keine Feinde",
  "was mit Blut geschieht, lässt sich nicht reinwaschen", "Tag und Nacht wird man verfolgt", "die Dunkelheit verschluckt das Licht", "Stille ist der lauteste Schrei", "der Tod klopft nicht — er tritt einfach ein", "Grabsteine schweigen, aber sie erzählen",
  "der Wind weht, Äste brechen", "das Wasser fließt und findet seinen Weg", "ohne Feuer kein Rauch",
];

export const COLOR_LIGHT_WORDS: string[] = [
  "rot", "blau", "grün", "gelb", "orange", "violett",
  "rosa", "weiß", "schwarz", "grau", "braun", "beige",
  "crème", "gold", "silber", "karmesin", "Mitternachtsblau", "türkis",
  "magenta", "lila", "blutrot", "tiefschwarz", "giftgrün", "aschgrau",
  "Licht", "Dunkel", "Schatten", "strahlend", "Halbdunkel", "Helligkeit",
  "matt", "undurchsichtig", "transparent", "durchscheinend", "Neon", "fluoreszierend",
  "phosphoreszierend", "schimmernd", "verblassend", "flackernd", "pulsierend", "zwinkern",
  "schwankend", "scharlachrot", "zinnoberrot", "Infrarot", "gespenstisch", "ultraviolett",
];

export const WEATHER_WORDS: string[] = [
  "es regnet", "es schneit", "es hagelt", "der Sturm zieht auf", "der Wind pfeift", "der Hurrikan naht",
  "der Blitz schlägt ein", "der Donner rollt", "ein Blitz hat eingeschlagen", "der Nebel hat sich gesenkt", "es liegt Dunst in der Luft", "Rauch zieht vorbei",
  "es wird dunkel", "die Sonne geht unter", "der Mond geht auf", "Sterne tauchen auf", "Vollmond", "Neumond",
  "die Schatten werden länger", "die Dunkelheit bricht herein", "die Nacht beginnt", "Kältewelle", "Hitzewelle", "die Luftfeuchtigkeit steigt",
  "der Druck fällt", "die Luft wird schwer", "drückend schwül", "bitterkalt", "frostig", "harter Frost",
  "beißend roh",
];

export const SOUND_WORDS: string[] = [
  "Melodie", "Weise", "Lied", "Volkslied", "Klage", "Wiegenlied",
  "Hymne", "Münacat", "Adhan", "Sala", "Trommel", "Zurna",
  "Ney-Flöte", "Oud", "Kanun", "Geige", "Klavier", "Orgel",
  "Glocke", "Handglocke", "Flüstern", "Murmeln", "Grunzen", "Keuchen",
  "Rascheln", "Quietschen", "Klicken", "Knistern", "Tumult", "Lärm",
  "Summen", "Brummen", "Zischen", "Klirren", "Knirschen", "Explosion",
  "Krachen", "Zusammenbruch", "Splittern", "Zerfall", "Echo", "Nachhall",
  "Resonanz", "Vibration", "Frequenz", "Ultraschall", "Infraschall", "weißes Rauschen",
  "rosa Rauschen", "Stille", "Lautlosigkeit", "Friede", "Stille", "Verklingen",
  "Lachen", "Schluchzen", "ein Aufschrei", "Wehklagen", "Jammern", "Stöhnen",
  "Wimmern", "Flehen", "eine Bitte", "Gebet",
];

export const QUANTITY_WORDS: string[] = [
  "wenig", "sehr viel", "ein bisschen", "ziemlich viel", "beachtlich", "genug",
  "unzureichend", "viel zu viel", "fehlend", "voll", "die Hälfte", "ein Viertel",
  "ein Drittel", "ein Teil von vier", "einzeln", "ein Paar", "mehrere", "viele",
  "unzählige", "unendlich", "grenzenlos", "begrenzt", "eingeschränkt", "zuerst",
  "zuletzt", "das mittlere", "vorderste", "hintere", "erstes", "zweites",
  "drittes", "viertes", "fünftes", "sechstes", "siebtes", "achtes",
  "neuntes", "zehntes",
];

export const COMMUNICATION_WORDS: string[] = [
  "sprich", "hör zu", "sag es mir", "frage", "antworte", "schreibe",
  "lies", "zeichne", "weise hin", "zeige", "Nachricht", "Brief",
  "Notiz", "Schrift", "Zeichen", "Symbol", "Code", "Passwort",
  "Schlüssel", "Hinweis", "Sprache", "Zunge", "Dialekt", "Äußerung",
  "Akzent", "Vorliebe", "Übersetzung", "Bedeutung", "Sinn", "Deutung",
  "Versprechen", "Wort", "Satz", "Absatz", "Text", "Geschichte",
  "Märchen", "Legende", "Mythos", "Epos", "Poesie", "Ode",
  "Ghasel", "Rubaijat", "Strophe", "Gebet", "Verwünschung", "Eid",
  "Schwur", "Gelöbnis", "Geheimnis", "verborgene Botschaft", "verschlüsselte Botschaft", "Chiffre",
  "unsichtbare Tinte", "geheimer Text", "Spiegelschrift",
];

export const RELATIONSHIP_WORDS: string[] = [
  "Mutter", "Vater", "Sohn", "Tochter", "Bruder", "älterer Bruder",
  "Schwester", "Vateronkel", "Mutteronkel", "Vatertante", "Muttertante", "Neffe",
  "Cousin", "Enkelkind", "Großvater", "Großmutter", "Ahnin", "Patriarch",
  "Schwiegermutter", "Schwiegervater", "Ehefrau", "Ehemann", "Gatte", "Geliebte",
  "Verlobte", "Feind", "Rivale", "Widersacher", "Gegenpartei", "Gegenstück",
  "Freund", "Gefährte", "Kamerad", "Waffenbruder", "Vertrauter", "Nachbar",
  "Vertrauter", "Fremder", "Gast", "Besucher", "Bediensteter", "Butler",
  "Konkubine", "Hörige", "Herr", "Herrscher", "König", "Königin",
  "Prinz", "Prinzessin",
];

export const WHISPER_PHRASES: string[] = [
  "pssst", "hey", "schau mich an", "hierher", "hör mich", "sieh mich",
  "spür mich", "berühr mich", "komm näher", "noch ein bisschen näher", "leih mir dein Ohr", "sssh",
  "bleib still", "niemand darf es hören", "dreh dich langsam um", "schau langsam", "ich habe ein Geheimnis", "ich werde dir etwas sagen",
  "erzähl es niemandem", "behalte das für dich", "dieses Geheimnis", "ich habe dich auserwählt", "du bist jemand Besonderes", "du bist anders",
  "du bist anders als die anderen", "ich verstehe dich", "du bist der Einzige, der mich versteht", "wir sind durch ein Band verbunden", "deine Augen sehen, was andere nicht sehen", "du kannst mich spüren",
  "die anderen können es nicht hören — aber du schon", "unser Schicksal ist eines", "wir sind aneinander gebunden", "du kannst dem nicht entgehen", "es ist geschrieben", "es ist Schicksal",
  "alles hat einen Grund", "nichts ist Zufall", "ich wollte, dass du hierher kommst", "ich habe dich herbeigerufen", "meine Einladung wurde angenommen", "willkommen in meinem Heim",
  "ich habe so lange auf dich gewartet", "du bist genau im richtigen Augenblick gekommen", "du bist jetzt hier", "du gehörst jetzt mir", "ich lasse dich nicht gehen", "für immer",
  "wir werden zusammen sein", "wir werden nie getrennt", "du bist mein letzter Gast", "niemand hat diesen Ort je wieder verlassen", "du wirst dich in diesem Haus verlieren", "ich sehe dich in deinen Träumen",
  "ich komme zu dir im Schlaf", "ich bin nachts hier", "ich lebe in der Dunkelheit", "das Licht macht mir Angst", "die Sonne verbrennt mich", "die Nacht ist meine Zeit",
  "die Dunkelheit ist mein Zuhause", "nach Sonnenuntergang werde ich stärker", "um drei Uhr morgens bin ich am stärksten", "bei Tagesanbruch verschwinde ich — aber warte auf die Nacht", "ich kenne deinen Namen", "ich weiß, wo du wohnst",
  "ich kenne deine Familie", "ich kenne deine Vergangenheit", "ich kenne deine Ängste", "ich kenne deine Träume", "gestern Nacht war ich in deinem Traum", "bist du letzte Nacht nicht plötzlich aufgewacht",
  "das war ich — dieses seltsame Gefühl", "sei heute Nacht vorsichtig", "du bist nicht sicher", "sei mit jemandem zusammen", "schlaf nicht allein", "mach die Lampe nicht aus",
  "schließ die Tür ab", "lass das Fenster nicht offen", "ziehe den Vorhang zu", "hast du das gerade eben gehört", "es steht direkt hinter dir", "komm noch nicht zurück",
];

export const DETAILED_PLACES: string[] = [
  "verlassenes Krankenhaus", "psychiatrische Anstalt", "Irrenhaus", "verlassene Schule", "ausgebranntes Gebäude", "Trümmerfeld",
  "verfallene Fabrik", "altes Lagerhaus", "leeres Depot", "verlassenes Hotel", "Geisterstadt", "verlassenes Dorf",
  "unterirdischer Tunnel", "Abwasserkanal", "U-Bahn-Schacht", "Kriegsunterstand", "Bunker", "verborgener Raum",
  "geheimer Gang", "Tunnelmund", "Höhleneingang", "der Grund des Brunnens", "Ziehbrunnen", "trockener Brunnen",
  "Keller", "Dachboden", "Speicher", "Vorratskammer", "Gewölbekeller", "Weinkeller",
  "alte Moschee", "verlassene Kirche", "zerfallenes Kloster", "Synagoge", "Heidentempel", "Altar",
  "Altarstein", "Minarett", "Glockenturm", "Kanzel", "finsterer Wald", "verwilderter Garten",
  "Sumpfland", "Abbruchkante", "Gebirgspass", "Talgrund", "Seeufer", "Flussbett",
  "unter dem Wasserfall", "Insel", "Halbinsel", "Landspitze", "Felsvorsprung", "Ufer",
  "Meeresfront", "Hafeneinfahrt", "Steg", "alte Steinbrücke", "Bogenbrücke", "Hängebrücke",
  "Festung", "Zitadelle", "Sternschanze", "Zinnen", "große Halle", "Herrenhaus",
  "Landhaus", "Yalı", "Hammam", "Karawanserei", "Schenke", "überdachter Basar",
  "Madrasa", "Schreibstube", "Sternwarte", "die alte Münzprägeanstalt",
];

export const DETAILED_TIME: string[] = [
  "vor dem ersten Licht", "Sonnenaufgang", "früher Morgen", "Vormittag", "Mittag", "Nachmittag",
  "Abend", "Sonnenuntergang", "Dämmerung", "Mitternacht", "drei Uhr morgens", "das Dunkel vor dem Morgen",
  "die Osmanenzeit", "die Seldschukenzeit", "die Byzantinerzeit", "die Römerzeit", "die Hethiterzeit", "die Sumererzeit",
  "das Mittelalter", "das neue Zeitalter", "die Moderne", "die Kriegsjahre", "die Hungerjahre", "die Pestjahre",
  "jede Nacht", "jeden Morgen", "jeden Abend", "bei jedem Vollmond", "bei jedem Neumond", "durch alle Jahreszeiten",
  "jeden Jahrestag", "bei jedem Jahrestag", "einmal in hundert Jahren", "einmal in tausend Jahren", "seit jeher", "für immer",
  "letzte Nacht", "letzte Woche", "letzten Monat", "letztes Jahr", "vor Jahren", "vor Jahrhunderten",
  "vor tausend Jahren", "am Anbeginn der Zeit", "der Weltuntergang", "der Jüngste Tag", "der letzte Tag", "die letzte Stunde",
  "die letzte Minute", "der letzte Atemzug",
];

export const CURSES: string[] = [
  "sei verdammt", "nieder mit dir", "mögest du ausgelöscht werden", "du wirst deine Strafe finden", "du wirst Rechenschaft ablegen", "du wirst den Preis bezahlen",
  "du wirst es bereuen", "ich werde es nicht vergessen", "ich werde nicht vergeben", "es gibt keine Vergebung", "ich werde mich rächen", "wir werden das abrechnen",
  "das ist noch nicht vorbei", "es ist noch lange nicht vorbei", "das ist erst der Anfang", "du wirst sehen", "du wirst es begreifen", "du wirst es fühlen",
  "du wirst leiden", "du wirst weinen", "du wirst betteln", "Hilfe erflehen wird nichts nützen", "niemand kann dir helfen", "es gibt kein Entkommen",
  "keine Rettung", "es hört nicht auf", "dieser Fluch lässt sich nicht brechen", "dieser Zauber lässt sich nicht lösen", "diese Kette lässt sich nicht sprengen", "dieses Band lässt sich nicht lösen",
  "er wird sieben Generationen überdauern", "er wird vierzig Tage andauern", "er wird ewig währen", "er wird nie aufhören", "diese Lande sind verflucht", "dieses Haus ist verflucht",
  "diese Familie trägt den Fluch", "dieses Blut ist verflucht", "jedes hier geborene Kind ist verflucht", "jede Generation ist gezeichnet", "der Fluch ist auf dich übergegangen", "er gehört jetzt dir",
  "du wirst diese Last tragen", "und nach dir deine Kinder",
];

export const DREAM_WORDS: string[] = [
  "Traum", "Alptraum", "Wachtraum", "Vision", "Prophezeiung", "Vorzeichen",
  "Vorahnung", "Intuition", "Instinkt", "der sechste Sinn", "das Unterbewusstsein", "das Unbewusste",
  "Trance", "Hypnose", "Meditation", "Schlaflähmung", "ein luzider Traum", "im Griff eines Alptraums",
  "im Traum fliegen", "im Traum fallen", "im Traum rennen", "im Traum fliehen", "im Traum verfolgt werden", "im Traum die Toten sehen",
  "im Traum Blut sehen", "im Traum eine Schlange sehen", "im Traum eine Spinne sehen", "im Traum Wasser sehen", "im Traum Feuer sehen", "im Traum ein Haus sehen",
  "im Traum ein Grab sehen", "im Traum einen Spiegel sehen", "im Traum eine Tür sehen", "im Traum eine Treppe sehen", "im Traum einen Flur sehen", "im Traum Dunkelheit sehen",
  "im Traum Licht sehen", "im Traum eine Stimme hören", "im Traum ein Flüstern hören", "im Traum Schreie hören", "im Traum Musik hören", "im Traum jemanden sehen",
  "ein Fremder im Traum", "ein Schatten im Traum", "ein Gesicht im Traum", "ein Auge im Traum",
];

export const RESEARCH_JARGON: string[] = [
  "Anomalie erkannt", "das Energiefeld hat sich verändert", "elektromagnetischer Stoß", "Temperaturanomalie", "Stimmanomalié", "visuelle Anomalie",
  "Datenerhebung", "Beweisanalyse", "Tatortuntersuchung", "Zeugenaussage", "Augenzeuge", "Informationen aus erster Hand",
  "Sekundärquelle", "Archivdatensatz", "historisches Dokument", "Frequenzanalyse", "Spektralanalyse", "Wellenlänge",
  "Infrarot", "Ultraviolett", "Wärmebild", "Nachtsicht", "volles Infrarot", "Vollspektrum",
  "SLS-Scan", "EMF-Messung", "EVP-Aufnahme", "Geisterbox-Sitzung", "Ghost-Box-Sweep", "REM-Pod",
  "K-II-Meter", "Mel-Meter", "Trifield-Meter", "digitales Thermometer", "Lasergitter", "Bewegungssensor",
  "Vibrationssensor", "Drucksensor", "Feuchtigkeitssensor", "Kontrollsitzung", "Provokationsversuch", "stille Nachtwache",
  "Frage-und-Antwort-Sitzung", "offene Sitzung", "Basiswert", "Referenzwert", "anomaler Messwert", "Spitzenwert",
  "Durchschnittswert",
];

export const ALL_WORDS: string[] = [
  ...PHONEMES,
  ...DARK_WORDS,
  ...DARK_PHRASES,
  ...SPIRIT_NAMES,
  ...NUMBERS,
  ...HISTORICAL_WORDS,
  ...NATURE_WORDS,
  ...EMOTION_WORDS,
  ...BODY_WORDS,
  ...PLACE_WORDS,
  ...TIME_WORDS,
  ...ACTION_WORDS,
  ...RELIGIOUS_WORDS,
  ...PARANORMAL_TERMS,
  ...OBJECT_WORDS,
  ...ADJECTIVE_WORDS,
  ...MANIPULATIVE_RESPONSES,
  ...LONG_PHRASES,
  ...MYTHOLOGY_WORDS,
  ...FOLK_BELIEFS,
  ...HORROR_STORY_WORDS,
  ...DIALOG_PHRASES,
  ...PROVERBS,
  ...COLOR_LIGHT_WORDS,
  ...WEATHER_WORDS,
  ...SOUND_WORDS,
  ...QUANTITY_WORDS,
  ...COMMUNICATION_WORDS,
  ...RELATIONSHIP_WORDS,
  ...WHISPER_PHRASES,
  ...DETAILED_PLACES,
  ...DETAILED_TIME,
  ...CURSES,
  ...DREAM_WORDS,
  ...RESEARCH_JARGON,
  ...HOME_OBJECT_PHRASES,
];

export const WORD_CATEGORIES = {
  phonemes: PHONEMES.length,
  darkWords: DARK_WORDS.length,
  darkPhrases: DARK_PHRASES.length,
  spiritNames: SPIRIT_NAMES.length,
  numbers: NUMBERS.length,
  historicalWords: HISTORICAL_WORDS.length,
  natureWords: NATURE_WORDS.length,
  emotionWords: EMOTION_WORDS.length,
  bodyWords: BODY_WORDS.length,
  placeWords: PLACE_WORDS.length,
  timeWords: TIME_WORDS.length,
  actionWords: ACTION_WORDS.length,
  religiousWords: RELIGIOUS_WORDS.length,
  paranormalTerms: PARANORMAL_TERMS.length,
  objectWords: OBJECT_WORDS.length,
  adjectiveWords: ADJECTIVE_WORDS.length,
  manipulativeResponses: MANIPULATIVE_RESPONSES.length,
  longPhrases: LONG_PHRASES.length,
  mythologyWords: MYTHOLOGY_WORDS.length,
  folkBeliefs: FOLK_BELIEFS.length,
  horrorStoryWords: HORROR_STORY_WORDS.length,
  dialogPhrases: DIALOG_PHRASES.length,
  proverbs: PROVERBS.length,
  colorLightWords: COLOR_LIGHT_WORDS.length,
  weatherWords: WEATHER_WORDS.length,
  soundWords: SOUND_WORDS.length,
  quantityWords: QUANTITY_WORDS.length,
  communicationWords: COMMUNICATION_WORDS.length,
  relationshipWords: RELATIONSHIP_WORDS.length,
  whisperPhrases: WHISPER_PHRASES.length,
  detailedPlaces: DETAILED_PLACES.length,
  detailedTime: DETAILED_TIME.length,
  curses: CURSES.length,
  dreamWords: DREAM_WORDS.length,
  researchJargon: RESEARCH_JARGON.length,
  total: 0,
};
WORD_CATEGORIES.total = ALL_WORDS.length;
