// English word bank for VOX — native-speaker reviewed parallel to word-bank.ts (Turkish).
// Category counts mirror lib/word-bank.ts exactly. PHONEMES unchanged.

export const NINE_PHRASES: string[] = [
  "my baby", "my grandchild", "dearest", "my child", "my little one", "my little lamb",
  "my heart", "the light of my eyes", "the corner of my heart", "come to me", "where are you, my child", "I miss you",
  "don't leave me", "I wait for you with longing", "I think of you every night", "I want to hear your voice", "let me see your face one more time", "you came to me in a dream, but I woke",
  "why won't you come", "can you hear me", "it is cold here", "there is no light", "so dark", "I am still here",
  "don't forget me", "my grave lies desolate", "no one comes anymore", "I was left all alone", "so much time has passed", "was this how death feels",
  "I am waiting for you", "come one day", "take me from this place", "the earth is cold", "the earth is dark", "I went cold beneath the stone",
  "no one knows I am here", "it is so hard here", "I cannot leave no matter what", "I am bound to this world", "I still wait", "I can hear you but I cannot see you",
  "your voices reach me but from so far away", "oh dear child", "may it all go well", "God protect you", "pray", "pray the namaz",
  "there are wicked ones out there", "be careful my darling", "do not stray from the path", "be true", "live with honour", "respect your elders",
  "call on your kin, ask after them", "flee from sin", "repent", "earn what is lawful", "love one another", "do not let discord between you",
  "such dark dreams", "I weep through the night", "I cannot see the morning", "that dark presence followed me here", "I saw something before I died", "there is something I must tell you",
  "a secret hides beneath the house", "sounds rise up from beneath the ground", "I will knock at midnight", "I will come to visit you in your dreams", "you will see me in your sleep", "I will be there when your eyes close",
  "I wish we had spent more time together", "I want to say all the things I left unsaid", "forgive me, my child", "I made my share of mistakes", "I would give anything to go back", "I wish I had told you sooner",
  "I left too soon", "I was not ready", "I did not want to leave you", "I stand between this world and the next", "I will come when the threshold opens", "you can hear me during the lunar eclipse",
  "I am stronger on Friday nights", "I sit in the graveyard and weep", "the ones beside me also wish to see you", "this place is crowded but utterly silent", "I run toward the light but cannot reach it", "one day you will understand",
];

export const GIRL_CHILD_PHRASES: string[] = [
  "will you play with me", "I don't want to be alone", "why won't anyone play with me", "I lost my doll", "where are my toys", "I want to go home",
  "where is my mother", "where is my father", "are they waiting for me", "I don't want to cry but I keep crying", "no one can see me", "am I invisible",
  "is there no one here", "I am all alone here", "I want a friend", "can I play with you", "I am frightened", "why is it so dark",
  "can you turn the light on", "I saw something", "he came back", "he comes every night", "that bad man came again", "he touched me",
  "he goes away when I scream", "I shut my eyes", "I started counting down from a hundred", "there is someone behind me", "can you see him", "he can see you too",
  "don't come here", "it is dangerous here", "it will follow you too", "they left me here", "why did they leave me", "the walls are speaking",
  "someone is looking in through the window", "that is not me in the mirror", "my shadow moves on its own", "sounds come from the ceiling", "someone is on the stairs — I count their footsteps", "my dog sees something in the corner",
  "my cat fled from the room", "the flowers withered when I walked in", "the clock stopped at that exact moment", "my mother is calling me", "slowly", "hm hm",
  "no no no", "stop stop stop", "I don't want to I don't want to", "I can see it too", "I feel so cold", "don't leave me",
  "hold me please", "take my hand", "don't go away from me", "I go somewhere while I sleep", "I am there even in my dreams", "I wake up exhausted",
  "what happens in the night", "do you see strange things at night too", "there are eyes in the darkness", "they are waiting", "I have stayed here far too long", "I want to get out now",
  "please take me with you", "I want to move toward the light", "I cannot pass through that door", "something is blocking the way", "what is your name", "can I trust you",
  "don't cry — if you cry, I'll cry too", "leave this place, for your own sake",
];

export const PHANTOM_PHRASES: string[] = [
  "I am here", "can you hear me", "help", "I cannot get out", "we are trapped", "let us go",
  "get away from there", "you are in danger", "it is coming", "run", "you are all in danger", "do you hear",
  "I was like you once", "it is far too late now", "do not go", "this house holds a secret", "I am inside the walls", "listen to me",
  "they are real", "no one believed me", "now you understand", "this place is hell", "I am lost in the dark", "give me a voice",
  "there is a room beneath the floor", "I know where the hidden door is", "do not open the chest in the cellar", "do you know what lies behind that wall", "the old owner is still here", "this house carries a century-old secret",
  "someone is weeping in the cellar", "there are footsteps on the roof", "adjust the frequency", "my signal is weak", "the connection is fading", "I am so far away",
  "I can hear you", "do not come here", "the channel is open", "I am receiving you", "I am trying to make contact", "too much static",
  "the frequency is drifting", "change the band", "push through the noise and you will hear me", "I need amplification", "the sound wave is breaking apart", "interdimensional interference",
  "do not look back", "close the door", "do not turn off the lights", "do not be alone", "do not scatter the group", "there is a powerful presence here",
  "the negative energy is overwhelming", "the area is tainted", "it must be cleansed", "record this", "look at the camera", "there is something to your left",
  "watch out as the temperature drops", "can you breathe", "I am speaking from far away", "my voice barely reaches you", "the energy is running out", "I speak with my last strength",
  "stay silent so you can hear me", "hold your breath for just a moment", "I can only be heard in complete silence", "I whisper so they do not hear", "keep this between us", "no one else must know",
  "I am calling to you specifically", "you were chosen for this", "someone special came tonight", "there is a sensitive one among you", "one of you is open — spiritually", "find them among you",
];

export const HOME_OBJECT_PHRASES: string[] = [
  "look at the chair beside you", "I saw the chair on the left", "there is someone behind that chair", "I am sitting on the sofa right now", "I used to sit in your chair", "that empty seat has been filled",
  "check beneath the sofa", "there is a cold patch beside the chair", "do not touch the chair yet", "open the third drawer", "I hid something in the top drawer", "you will find me in the bottom drawer",
  "close that drawer", "the wardrobe door will stay open tonight", "there is someone inside the wardrobe", "open the drawers one by one", "stop at the last drawer", "lock the wardrobe before night falls",
  "do not look under your bed", "there is something under your pillow", "I am sitting on the edge of the bed", "look at your pillow when you wake in the morning", "do not sleep in that bed tonight", "I crept under the covers",
  "if your bed seems to sink in the night, that is me", "I watch your face while you sleep", "look carefully in the mirror", "there are two faces in your mirror right now", "I am on the other side of the mirror", "cover the mirror at night",
  "look out the window", "I press my face against the glass", "have you ever parted the curtains and looked out in the night", "look at the fog on the glass", "do not open the window tonight", "I slip in through the blinds",
  "did you see the shadow that passed under the door", "you locked the door, didn't you", "someone is walking through the corridor", "the door handle is slowly turning", "I am waiting just outside the door", "I can enter without knocking",
  "do not open that door", "when the door creaks — that is me", "did you hear something fall in the kitchen", "I make the tap drip like that", "listen to how the fridge has changed", "are you certain you turned off the hob",
  "are the kitchen knives all accounted for", "look at the glass shelf", "there is someone under the kitchen table", "I just moved your pot", "I am beside you while you shower", "I am writing in the steam on your mirror",
  "I am waiting behind the shower curtain", "locking the bathroom will not be enough", "I watch you fill the bathtub", "the toilet door will remain wide open", "the seventh step on the stairs will creak very soon", "I can hear you from the ground floor",
  "there is someone upstairs", "I hang in the stairwell", "did you hear the door downstairs", "do not run from the stairs — I cannot catch you", "I am about to turn off the light bulb", "the light will flicker three times",
  "watch the lamp tonight", "do not go to the fuse box", "that lamp in the corner is my signal", "pull the plug and you will never find me", "have you noticed your wall clock has stopped", "the clock will strike at three in the morning",
  "I crossed off that day on the calendar", "the minute hand is moving backwards", "I know your birthday is drawing near", "the darkest corner of the house is mine", "look at the bottom right corner of the room", "I am sitting beside the left wall",
  "look where the ceiling meets the wall", "a secret hides beneath that stain", "lift the rug and take a look", "the eyes in that painting are my eyes", "have you ever looked closely at the photograph in the frame",
];

export const PHONEMES: string[] = [
  "a", "e", "i", "o", "u", "ö",
  "ü", "ı", "ba", "be", "bi", "bo",
  "bu", "bö", "bü", "ca", "ce", "ci",
  "co", "cu", "da", "de", "di", "do",
  "du", "dö", "dü", "fa", "fe", "fi",
  "fo", "fu", "ga", "ge", "gi", "go",
  "gu", "gö", "gü", "ha", "he", "hi",
  "ho", "hu", "ka", "ke", "ki", "ko",
  "ku", "kö", "kü", "la", "le", "li",
  "lo", "lu", "lö", "lü", "ma", "me",
  "mi", "mo", "mu", "mö", "mü", "na",
  "ne", "ni", "no", "nu", "nö", "nü",
  "pa", "pe", "pi", "po", "pu", "ra",
  "re", "ri", "ro", "ru", "rö", "rü",
  "sa", "se", "si", "so", "su", "sö",
  "sü", "ta", "te", "ti", "to", "tu",
  "tö", "tü", "va", "ve", "vi", "vo",
  "vu", "ya", "ye", "yi", "yo", "yu",
  "yö", "yü", "za", "ze", "zi", "zo",
  "zu", "şa", "şe", "şi", "şo", "şu",
  "ça", "çe", "çi", "ço", "çu", "br",
  "kr", "tr", "gr", "pr", "fr", "dr",
  "st", "sk", "sp", "sl", "sm", "sn",
  "ah", "oh", "uh", "eh", "ih", "ay",
  "ey", "oy", "öy", "üy", "aa", "ee",
  "ii", "oo", "uu", "öö", "üü",
];

export const DARK_WORDS: string[] = [
  "death", "soul", "darkness", "shadow", "curse", "fear",
  "horror", "hell", "grave", "tomb", "coffin", "funeral",
  "dead", "ghost", "djinn", "devil", "demon", "ifrit",
  "revenant", "vampire", "zombie", "skeleton", "skull", "blood",
  "pain", "scream", "wail", "moan", "whisper", "silence",
  "sound", "footfall", "thunder", "coldness", "they entered", "contrary",
  "temporal drift", "fate", "motive", "from beyond", "manifestation", "mirage",
  "spiral", "shadowed", "whisper-line", "cold-wave", "frequency-shift", "static",
  "acoustic", "déjà vu", "vision", "silhouette", "broken", "abandoned",
  "locked", "night", "moon", "full moon", "cloud", "fog",
  "smoke", "haze", "gloom", "loneliness", "forsaken", "lost",
  "forgotten", "prisoner", "captive", "bound", "chain", "lock",
  "key", "door", "window", "mirror", "reflection", "mystery",
  "secret", "sorcery", "talisman", "amulet", "evil eye", "ill-omened",
  "black", "ebony", "dark", "deep", "void", "cliff",
  "well", "underground", "basement", "cellar", "tunnel", "cave",
  "dungeon", "prison", "bone", "flesh", "skin", "wound",
  "trace", "stain", "rust", "mould", "spider", "web",
  "insect", "serpent", "bat", "crow", "owl", "wolf",
  "fox", "jackal", "hyena", "vulture", "scorpion", "rat",
  "fire", "flame", "ash", "dust", "earth", "mud",
  "swamp", "storm", "lightning", "thunder clap", "earthquake", "flood",
  "tsunami", "plague", "epidemic", "sickness", "poison", "elixir",
  "witch", "sorcerer", "fortune teller", "medium", "soothsayer", "shaman",
  "priest", "rite", "ritual", "sacrifice", "offering", "curse",
  "dark magic", "pentagram", "symbol", "sign", "inscription", "rune",
  "portal", "gateway", "dimension", "parallel", "the other side", "afterlife",
  "afterworld", "limbo", "purgatory", "bridge of souls", "divine scales", "Azrael",
  "angel", "demon", "entity", "cold", "ice", "frost",
  "trembling", "chill", "gooseflesh", "thorn", "breath", "pale",
  "wheezing", "grunt", "hum", "buzz", "squeak", "click",
  "crackle", "rustle", "clink", "sizzle", "haunted", "haunting",
  "attached", "follower", "shadow figure", "black mass", "white shadow", "ball of light",
  "orb", "ectoplasm", "poltergeist", "ouija", "planchette", "candle",
  "incense", "crystal", "scrying sphere", "conjuring", "séance", "mediumship",
  "parapsychology", "telepathy", "premonition", "prophecy", "nightmare", "sleepwalking",
  "trance", "hypnosis", "subconscious", "astral", "projection", "transmigration",
  "reincarnation", "karma", "aura", "energy", "vibration", "frequency",
  "wave", "signal", "interference", "noise", "calamity", "ruin",
  "apocalypse", "doomsday", "end", "chaos", "disorder", "uncertainty",
  "danger", "threat", "warning", "execution", "gallows", "executioner",
  "torment", "torture", "decay", "corruption", "disintegration",
  "extinction", "erasure", "oblivion", "vanishing", "fading",
  "darkening", "drowning", "burning", "freezing", "falling", "sinking",
  "trap", "ambush", "conspiracy", "intrigue", "deceit", "betrayal",
  "deception", "lie", "false", "counterfeit", "fiction", "hallucination",
  "delusion", "illusion", "phantom", "vortex", "whirlpool", "hurricane",
  "twister", "avalanche", "landslide", "collapse", "implosion", "fissure",
  "crack", "abyss", "depths", "darkness below", "dark void", "emptiness",
  "nothingness", "absence", "eternity", "eternity unbounded", "stillness", "rotten",
  "fetid", "putrid", "stale", "lifeless", "withered", "desiccated",
  "charred", "shattered", "broken apart", "crushed", "forgotten", "abandoned",
  "damned", "condemned", "al-karı", "night terror", "bogey", "ghoul",
  "giant", "ogre", "witch", "albastı", "koncolos", "cyclops",
  "basilisk", "dragon", "simurgh", "phoenix", "firebird", "telekinesis",
  "levitation", "apport", "bilocation", "clairvoyance", "precognition", "retrocognition",
  "psychometry", "autoscopy", "doppelgänger", "phenomenon", "anomaly", "deviation",
  "disorder", "irregularity", "dim", "dark", "hazy", "foggy",
  "overcast", "rain-soaked", "storm-wracked", "wind-battered", "cold", "freezing",
  "overwhelming", "suffocating", "oppressive", "uncanny", "eerie", "unsettling",
  "hair-raising", "terrifying", "dread-filled", "frightening", "mysterious", "enigmatic",
  "incomprehensible", "inexplicable", "supernatural", "extraordinary", "otherworldly", "strange",
  "uncanny", "bizarre", "unusual", "unexpected", "sudden", "unannounced",
  "hidden", "concealed", "veiled", "masked", "disguised", "cloaked",
  "forsaken", "derelict", "wraith", "pitch-black", "riddle", "enchantment",
  "ancient script", "divination", "reproach", "apparition", "at last", "omen",
  "testament", "passage", "oppression", "discord", "encompassing", "entanglement",
  "withdrawal", "mournful", "bewitched", "mysterious", "mortality", "reckoning",
  "obsession", "delirium", "ravings", "blindness", "waymark", "apparent",
  "hidden within", "contagion", "spreading", "your doom", "destiny", "fate written",
  "ordeal", "keening", "death-cry", "reverberation", "echoes", "voices from beyond",
  "resonance", "reflection", "shadowing", "illusion", "shadow form", "dark silhouette",
  "white shadow", "hazy vision", "cosmos", "dimensional", "temporal",
  "spatial", "universal", "all-encompassing",
  "otherworldly pulse", "emanation",
];

export const DARK_PHRASES: string[] = [
  "come here", "hear me", "help me", "don't leave me", "don't go", "I'm here",
  "I see you", "look behind you", "be careful", "flee", "I died", "find me",
  "save me", "I'm in agony", "I'm alone", "who is there", "who are you", "what do you want",
  "why did you come", "why are you here", "what are you searching for", "who are you looking for", "get out", "leave this place",
  "get out now", "this is my house", "this is my ground", "I'm watching you", "I'm everywhere", "you cannot escape",
  "I will find you", "I am right behind you", "there is no running", "come back", "come again", "don't forget me",
  "remember", "swear it", "yes", "no", "perhaps", "I don't know",
  "I cannot say", "midnight", "dawn", "dusk", "the full moon night", "three o'clock",
  "the witching hour", "the dark hour", "open the door", "close the window", "turn off the light", "light the candle",
  "pray", "curse", "be damned", "mother", "father", "child",
  "baby", "old man", "old woman", "love", "hatred", "revenge",
  "rage", "jealousy", "betrayal", "murder", "accident", "catastrophe",
  "tragedy", "fate", "time", "eternity", "forever", "the past",
  "the future", "right now", "here", "there", "above", "below",
  "inside", "outside", "be quiet", "listen", "hear me", "speak to me",
  "answer me", "this house", "this room", "this place", "this place is cursed", "this place is mine",
  "forgive me", "hurry", "time is short", "your last chance", "do not sleep", "do not wake",
  "dream", "nightmare", "a terrible dream", "do not disturb me", "leave me be", "do not touch me",
  "cold", "so very cold", "cold as ice", "I am freezing", "pain", "unbearable pain",
  "I cannot endure it", "let it end", "why", "how", "when",
  "where", "the third floor", "the cellar", "the attic", "the corridor", "beneath the stairs",
  "mirror", "look in the mirror", "reflection", "reversed", "at three in the morning", "turn around",
  "do not look", "close your eyes", "hold your breath", "the smell of blood", "the smell of damp", "the smell of burning",
  "rotting", "footsteps", "the creak of the door", "shattering glass", "a scream", "someone is here",
  "behind me", "beside me", "above me", "below me", "I am watching", "I am waiting",
  "I am patient", "I have all the time in the world", "death is close", "the last night", "farewell", "goodbye",
  "goodbye forever", "I know you", "I know your name", "I know your past", "I know your secret", "I know your fear",
  "I know your weakness", "I was waiting for you", "I knew you would come", "I am ready", "I want to speak with you", "listen to me",
  "I have something important to say", "trust no one", "do not trust a soul", "you are alone", "there is no one", "your friends are lying",
  "they do not care for you", "they are using you", "you will die soon", "your time is running out", "the clock is ticking", "I am counting your last breaths",
  "your grave is ready", "the coffin is waiting", "the funeral prayer", "burial", "the earth is cold", "cold and dark",
  "this house has a history", "someone died here", "blood was shed", "the walls remember", "beneath the ground", "buried",
  "hidden away", "a secret room", "a hidden passage", "behind the wall", "above the ceiling", "I want to play",
  "be my friend", "let us play hide-and-seek", "you found me", "your turn now", "chase me", "you will never catch me",
  "where is my mother", "where is my father", "I want to go home", "I am lost", "I cannot find my way", "I am afraid of the dark",
  "I am so very old", "I am tired", "I want to rest", "I cannot remember", "I have forgotten who I am", "where am I",
  "how long has it been", "years have passed", "centuries have passed", "I am still here", "I cannot leave", "I cannot let go",
  "I am bound", "I feel as though I am in chains", "I am not free", "get out of here", "this is my place", "you are trespassing",
  "I will punish you", "you will regret this", "you will pay", "I warned you", "my final warning", "do not come back",
  "do not disturb me", "do not shatter my peace", "leave me", "I am so sorry", "I am filled with regret", "I wish I had not",
  "I want to be forgiven", "I am guilty", "I made a terrible mistake", "there is no turning back", "it is too late", "far too late now",
  "the chance is gone", "time has run out", "it is all over", "I have a message", "listen closely", "decipher this",
  "I am giving you a clue", "you are getting closer", "you are on the right path", "you are looking in the wrong place", "look elsewhere", "go deeper",
  "not on the surface", "beneath it", "hidden", "veiled", "masked", "there is danger here",
  "be careful", "look around you", "do not be alone", "do not linger in the dark", "do not leave the light", "lock the door",
  "close the window", "draw the curtains", "do not look in the mirror", "do not turn around", "do not follow the voice", "the energy is rising",
  "the vibration is growing", "the frequency is shifting", "the portal is opening", "the threshold is open", "an interdimensional link", "the signal grows stronger",
  "contact is being made", "there is a connection", "a message is coming through", "I answer", "I can hear",
  "it is open",
];

export const SPIRIT_NAMES: string[] = [
  "John", "William", "James", "Henry", "Charles", "George",
  "Edward", "Thomas", "Arthur", "Albert", "Walter", "Frederick",
  "Edmund", "Samuel", "Joseph", "Benjamin", "Francis", "Harold",
  "Ernest", "Victor", "Oliver", "Theodore", "Nathaniel", "Cornelius",
  "Bartholomew", "Reginald", "Mortimer", "Percival", "Ambrose", "Silas",
  "Jasper", "Ezekiel", "Josiah", "Obadiah", "Barnabas", "Phineas",
  "Horace", "Leopold", "Clement", "Rupert", "Sarah", "Mary",
  "Margaret", "Elizabeth", "Catherine", "Anne", "Jane", "Emily",
  "Charlotte", "Alice", "Eleanor", "Beatrice", "Agnes", "Edith",
  "Mabel", "Florence", "Harriet", "Lillian", "Rosalind", "Cordelia",
  "Constance", "Prudence", "Tabitha", "Winifred", "Hester", "Bridget",
  "Maud", "Ada", "Clara", "Dorothea", "Evelyn", "Genevieve",
  "Isadora", "Lavinia", "Marguerite", "Ophelia", "Rowena", "Seraphina",
  "Theodora", "Vivienne", "Abigail", "Beatrix", "Cecilia", "Delphine",
  "Esther", "Felicity", "Gwendolyn", "Honoria", "Isabella", "Josephine",
  "Katharine", "Lenore", "Millicent", "Nora", "Octavia", "Penelope",
  "Roderick", "Bram", "Crispin", "Desmond", "Ellis", "Gideon",
  "Hamish", "Ignatius", "Lucius", "Magnus", "Nigel", "Oswald",
  "Quentin", "Roland", "Tobias", "Ulysses", "Wilfred",
];

export const NUMBERS: string[] = [
  "one", "two", "three", "four", "five", "six",
  "seven", "eight", "nine", "ten", "eleven", "twelve",
  "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen",
  "nineteen", "twenty", "twenty-one", "thirty", "forty", "fifty",
  "sixty", "seventy", "eighty", "ninety", "hundred", "thousand",
  "zero", "million", "billion", "eighteen hundred", "nineteen hundred", "two thousand",
  "the fifteenth century", "the sixteenth century", "the seventeenth century", "the eighteenth century", "the nineteenth century", "the twentieth century",
];

export const HISTORICAL_WORDS: string[] = [
  "Ottoman", "Sultan", "sovereign", "Queen", "Pasha", "Bey",
  "Lady", "palace", "castle", "tower", "rampart", "moat",
  "bridge", "fountain", "mosque", "church", "temple", "mausoleum",
  "madrasa", "war", "peace", "conquest", "siege", "victory",
  "defeat", "bondage", "sword", "shield", "arrow", "spear",
  "dagger", "gold", "silver", "iron", "diamond", "ruby",
  "adhan", "prayer", "ritual prayer", "angel", "djinn", "fairy",
  "dragon", "inn", "bathhouse", "caravanserai", "bazaar", "market",
  "Sunday", "empire", "caliphate", "reign", "throne", "crown",
  "edict", "tughra", "seal", "deed", "charter", "Janissary",
  "sipahi", "raider", "torment", "levent", "captain", "chieftain",
  "pirate", "sailor", "mariner", "caravan", "merchant", "trader",
  "money changer", "artisan", "dervish", "Sufi", "Mevlevi", "Bektashi",
  "Naqshbandi", "lodge", "zawiya", "tekke", "khanqah", "ribat",
  "prince", "Valide Sultan", "haseki", "concubine", "eunuch", "imperial palace",
  "Topkapı", "Dolmabahçe", "Yıldız", "Çırağan", "Galata", "Beyoğlu",
  "Üsküdar", "Kadıköy", "Bosphorus", "Rumelia", "Anatolia", "Thrace",
  "Balkans", "Caucasus", "Hittite", "Sumerian", "Assyrian", "Babylonian",
  "Phrygian", "Lydian", "Lycian", "Carian", "Ionian", "Urartian",
  "Seljuk", "Byzantine", "Roman", "Greek", "Persian", "Mongol",
  "Hun", "Göktürk", "Karakhanid", "Ghaznavid",
];

export const NATURE_WORDS: string[] = [
  "rain", "snow", "ice", "wind", "storm", "hurricane",
  "lightning", "bolt", "cloud", "moon", "star", "sea",
  "ocean", "lake", "river", "waterfall", "mountain", "cave",
  "forest", "desert", "volcano", "earthquake", "night", "daylight",
  "dawn", "dusk", "sun", "earth", "planet", "universe",
  "galaxy", "nebula", "black hole", "comet", "meteor", "meteorite",
  "soil", "rock", "stone", "sand", "gravel", "tree",
  "leaf", "branch", "root", "flower", "weed", "moss",
  "mushroom", "lichen", "ivy", "wolf", "bear", "eagle",
  "serpent", "scorpion", "bat", "owl", "crow", "cat",
  "dog", "insect", "spider", "fly", "mosquito", "bee",
  "fish", "dolphin", "shark", "octopus", "jellyfish", "raw",
  "hoarfrost", "full", "downpour", "drizzle", "north-easterly", "south-westerly",
  "breeze", "sirocco", "karayel", "high tide", "low tide", "wave",
  "current", "whirlpool", "source", "spring", "stream", "brook",
  "river delta", "valley", "canyon", "gorge", "mountain pass", "plateau",
  "fog-bank", "steam", "condensation", "fringe", "shaft of light", "gust",
  "hermitage", "landslide", "tremor", "fault-line", "crevice", "stalagmite",
  "stalactite", "sinkhole", "crater", "lava", "magma", "groundwater",
  "spring-water", "healing-spring", "sacred-spring", "reed bed", "pond", "beck",
  "stream-bed", "sea-foam", "tide", "dew drop", "trickle", "droplet",
  "sweat", "plasma", "sap", "resin", "amber", "fossil",
  "bedrock", "mineral", "ore deposit", "ore",
];

export const EMOTION_WORDS: string[] = [
  "fear", "horror", "panic", "dread", "anxiety", "rage",
  "grudge", "hatred", "revulsion", "sorrow", "grief", "anguish",
  "longing", "loneliness", "despair", "hopelessness", "pain", "suffering",
  "torment", "anguish", "remorse", "conscience", "guilt", "curiosity",
  "astonishment", "bewilderment", "peace", "silence", "stillness", "unease",
  "tension", "stress", "depression", "desolation", "melancholy", "nostalgia",
  "yearning", "homesickness", "estrangement", "joy", "happiness", "elation",
  "fervour", "excitement", "hope", "anticipation", "desire", "longing",
  "passion", "disappointment", "disillusionment", "do not be deceived", "do not be mistaken", "doubt",
  "misgiving", "hesitation", "indecision", "uncertainty", "courage", "boldness",
  "heroism", "sacrifice", "mercy", "compassion", "pity", "empathy",
  "jealousy", "envy", "covetousness", "spite", "shame", "mortification",
  "boredom", "weariness", "horror", "brutality", "monstrousness", "cruelty",
  "savagery",
];

export const BODY_WORDS: string[] = [
  "hand", "foot", "head", "eye", "ear", "mouth",
  "tooth", "tongue", "finger", "neck", "back", "chest",
  "heart", "brain", "blood", "bone", "skin", "breath",
  "pulse", "tear", "shoulder", "arm", "wrist", "palm",
  "nail", "knee", "calf", "heel", "waist", "belly",
  "liver", "kidney", "gut", "lung", "stomach", "vein",
  "nerve", "muscle", "tendon", "joint", "hair", "brow",
  "eyelash", "moustache", "beard", "temple", "brow ridge", "chin",
  "cheek", "nose", "spine", "rib", "collarbone", "shoulder blade",
  "pelvis", "skull", "jawbone", "cheekbone", "eye socket",
];

export const PLACE_WORDS: string[] = [
  "house", "room", "hall", "corridor", "staircase", "roof",
  "basement", "door", "window", "wall", "ceiling", "cemetery",
  "hospital", "prison", "forest", "cave", "well", "tunnel",
  "bridge", "kitchen", "bathroom", "bedroom", "sitting room", "balcony",
  "garage", "garden", "courtyard", "terrace", "veranda", "church",
  "mosque", "synagogue", "temple", "monastery", "castle", "palace",
  "tower", "dungeon", "cellar", "school", "library", "museum",
  "theatre", "opera house", "factory", "warehouse", "storehouse", "silo",
  "hangar", "village", "town", "city", "metropolis", "ruin",
  "desolation", "rubble", "debris", "wreckage", "remnants", "island",
  "peninsula", "cape", "cove", "harbour", "station", "terminal",
  "airport", "pier", "dock", "park", "pleasure garden", "grove",
  "meadow", "field", "farm", "barn", "haystack", "mill",
  "kiln", "bathhouse", "inn", "caravanserai", "bazaar hall", "market",
  "mausoleum", "külliye", "madrasa", "lodge", "zawiya", "burial ground",
  "shrine", "tomb", "sarcophagus", "ossuary", "abandoned house", "haunted mansion",
  "cursed castle", "ghost town", "dead city", "lost village", "sunken wreck", "abandoned hospital",
  "old prison", "underground city", "catacomb", "ossuary vault", "road", "shadow-alley",
  "attic", "labyrinth", "secret chamber", "chimney shaft", "fireplace", "beneath the stairs",
  "ground floor", "shelter", "arched passage", "column", "buttress", "beam",
  "in the crypt", "burial vault", "monument", "full-length mirror",
];

export const TIME_WORDS: string[] = [
  "now", "at once", "after", "before", "yesterday", "today",
  "midnight", "morning", "evening", "night", "daybreak", "eternity",
  "forever", "the past", "the future", "century", "the witching hour", "beyond",
  "eternal", "mortal", "first light", "solstice", "lunar eclipse", "solar eclipse",
  "crescent", "dark moon", "blood moon", "shooting star", "Milky Way", "constellation",
  "Pole Star", "north", "south", "east", "west", "direction",
  "horizon", "tomorrow", "the day after", "week", "month", "year",
  "century", "a thousand years", "era", "turning of ages", "period", "moment",
  "second", "minute", "the clock", "in an instant", "first", "last",
  "beginning", "ending", "the final", "birth", "death", "life",
  "existence", "being", "spring", "summer", "autumn", "winter",
  "season", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday",
  "Saturday", "Sunday", "feast day", "sacred night", "eve",
];

export const ACTION_WORDS: string[] = [
  "come", "go", "stop", "wait", "run", "flee",
  "hide", "look", "see", "listen", "hear", "touch",
  "feel", "speak", "be silent", "whisper", "shout", "weep",
  "sleep", "wake", "remember", "forget", "reach out", "close",
  "lock", "cut", "shatter", "burn", "extinguish", "die",
  "be born", "live", "vanish", "appear", "call out", "find",
  "lose", "conceal", "bury", "drag down", "get out",
  "enter", "climb", "leap", "dream", "crawl", "creep",
  "walk", "dance", "return", "turn", "bend", "writhe",
  "shudder", "quiver", "tremble", "multiply", "strike", "claw",
  "reach", "drag", "crush", "throw", "devour", "consume",
  "swallow", "spit", "choke", "breathe", "exhale", "drown",
  "gasp", "wail", "sob", "scream", "moan", "whimper",
  "whisper", "hum", "grunt", "growl", "howl", "follow",
  "watch", "spy", "lurk", "attack", "defend", "protect",
  "take shelter", "bar the door", "ensnare", "plead", "seize", "wish",
  "ask", "beg", "curse", "damn", "cast a spell", "perform the ritual",
  "hold a séance", "confess", "admit", "accept", "deny", "refuse",
  "forgive", "absolve", "punish", "reward", "remain", "help",
  "stand watch", "fulfill", "enter", "leave", "face it", "dissolve",
  "bind", "set free", "conceal", "do not laugh", "call forth", "pursue",
  "bring", "take away", "save", "help me", "release it", "hold it",
  "catch", "do not let go", "do not forget", "tell me", "cry out", "speak",
  "cover", "seal", "lock away", "unravel", "bind tight", "sever",
  "illuminate", "plunge into darkness",
  "endure",
];

export const RELIGIOUS_WORDS: string[] = [
  "Allah", "bismillah", "mashallah", "God willing", "alhamdulillah", "adhan",
  "prayer", "fasting", "pilgrimage", "zakat", "paradise", "hell",
  "purgatory", "bridge of souls", "divine scales", "angel", "devil", "djinn",
  "demon", "houri", "Azrael", "Michael", "Gabriel", "Israfil",
  "the Day of Reckoning", "the Apocalypse", "resurrection", "the Spreading", "the grave's questioning", "torment of the grave",
  "Munkar", "Nakir", "interrogation", "account", "good deed", "sin",
  "repentance", "forgiveness", "praise", "surah", "verse", "hadith",
  "circumcision", "obligatory", "halal", "haram", "repugnant", "permissible",
  "compulsory", "church", "priest", "clergy", "nun", "cross",
  "baptism", "confession", "rite", "communion", "holy water", "rosary",
  "icon", "saint", "blessed", "Sufi", "dervish", "master",
  "disciple", "order", "dhikr", "sama", "ecstasy", "divine annihilation",
  "divine permanence", "discovery", "inspiration", "miracle", "wonder", "sorcery",
  "evil eye", "gaze", "fascination", "envy", "enchantment", "amulet",
  "talisman", "vefk", "hamail", "transcription", "possession", "Sara illness",
  "evil touch", "binding", "necromancy", "omen", "dream interpretation", "divination",
  "coffee reading", "tarot", "astrology", "horoscope", "star chart",
];

export const PARANORMAL_TERMS: string[] = [
  "EMF", "detector", "sensor", "meter", "radar", "camera",
  "thermal camera", "night vision", "infrared", "ultraviolet", "microphone", "recorder",
  "voice analysis", "frequency analysis", "spirit box", "ghost box", "Frank's Box", "Ovilus",
  "SLS camera", "Kinect", "LiDAR", "depth sensor", "K2 meter", "Mel meter",
  "REM pod", "motion sensor", "dowsing rod", "pendulum", "Ouija board", "planchette",
  "EVP", "electronic voice phenomenon", "electronic audio", "static noise", "apparition", "materialise",
  "image", "silhouette", "shadow figure", "cold spot", "temperature drop", "hot spot",
  "anomaly", "orb", "ball of light", "light streak", "light burst", "poltergeist",
  "telekinesis", "levitation", "apport", "ectoplasm", "ectoplasm formation", "materialisation",
  "full-body apparition", "partial apparition", "shadow person", "residual haunting", "intelligent haunting", "demonic haunting",
  "portal haunting", "dimensional transition", "time slip", "investigation", "research", "review",
  "discovery", "observation", "evidence", "proof", "finding", "data",
  "analysis", "report", "registration", "document", "file", "archive",
  "session", "vigil", "experiment", "test", "control", "hypothesis",
  "theory", "result", "interpretation", "evaluation", "magnetic field", "fluctuation",
  "static noise", "white noise", "pink noise", "frequency cut-off", "signal loss", "data stream",
  "distortion", "energy surge", "ionisation", "thermal drop", "sudden cold", "swing",
  "electromagnetic", "radiation", "wavelength", "scan rate", "channel-hopping", "reverse voice",
  "mirror effect", "echo chamber", "sound barrier", "suppression", "filtering", "isolated",
  "insulated", "protected", "sealed space", "quarantine", "contamination", "interaction",
  "trigger", "activation", "auto-record", "graph spike", "frequency peak", "sensor reading",
  "monitoring panel", "live data feed", "global data", "location", "coordinates", "altitude",
  "pressure", "atmospheric", "humidity level", "sulphur smell", "ozone", "burning smell",
  "damp smell", "wind corridor", "air flow", "current", "static charge",
  "charging", "discharge", "battery drain", "energy absorption", "voltage", "current flow",
  "resistance", "capacitor", "coil", "relay", "circuit breaker", "short circuit",
  "earthing", "insulator", "conductive", "semiconductor", "quartz", "lens",
  "focusing", "reflective surface", "refraction", "light spectrum", "full spectrum",
  "spectral signature",
];

export const OBJECT_WORDS: string[] = [
  "candle", "oil lamp", "lantern", "lamp", "torch", "mirror",
  "glass", "crystal", "scrying globe", "prism", "book", "notebook",
  "letter", "map", "compass", "clock", "bell", "hand bell",
  "whistle", "pipe", "rope", "chain", "cord", "twine",
  "wire", "knife", "sword", "dagger", "axe", "hammer",
  "stone", "marble", "granite", "obsidian", "amethyst", "silver",
  "gold", "copper", "iron", "lead", "salt", "water",
  "fire", "earth", "air", "portrait", "photograph", "likeness",
  "table", "statue", "toy", "doll", "puppet", "mask",
  "costume", "crown", "ring", "necklace", "bracelet", "brooch",
  "chest", "box", "satchel", "trunk", "basket", "rug",
  "carpet", "curtain", "shroud", "blanket", "vase", "plate",
  "glass vessel", "bowl", "pot", "prayer book", "rosary", "cross",
  "amulet", "evil-eye bead", "creak", "door-handle", "latch-tongue", "keyhole",
  "rusted chain", "padlock", "tombstone", "bust", "old photograph", "canvas",
  "fresco", "wallpaper", "torn cloth", "broken glass", "window drape", "net curtain",
  "lacework", "dowry chest", "old toy", "porcelain doll", "cradle", "rocking chair",
  "clock pendulum", "wall clock", "chain clock", "stopwatch", "hourglass", "gas lamp",
  "candlestick", "reliquary", "curio", "cloud of dust", "cobweb", "strand of hair",
  "garment", "cloak", "bloodstain", "damp patch", "smell", "musty odour",
  "ancient tome", "manuscript", "parchment", "leather binding", "ink", "inkwell",
  "quill", "envelope", "sealing wax", "seal stamp", "coat of arms", "locket",
];

export const ADJECTIVE_WORDS: string[] = [
  "dark", "bright", "dim", "luminous", "dull", "cold",
  "scalding", "warm", "icy", "searing", "ancient", "new",
  "primordial", "age-old", "modern", "vast", "small", "enormous",
  "tiny", "slight", "long", "short", "wide", "narrow",
  "deep", "heavy", "light", "thick", "thin", "hard",
  "soft", "rough", "slick", "sticky", "parched", "sodden",
  "damp", "moist", "mouldering", "rotting", "beautiful", "hideous",
  "terrifying", "dreadful", "haunted", "silent", "clamorous", "hushed",
  "peaceful", "unsettled", "swift", "slow", "sudden", "gradual",
  "unceasing", "invisible", "transparent", "opaque", "blurred", "clear",
  "living", "dead", "lifeless", "motionless", "frozen", "accursed",
  "holy", "defiled", "clean", "pure", "intricate", "plain",
  "mysterious", "open", "shut", "real", "false", "illusory",
  "spectral", "surreal", "whispering", "waiting", "distant", "near",
  "withdrawn", "talismanic", "reclusive", "wrathful", "restless", "alone",
  "terrified", "struck speechless", "gripped by dread",
];

export const MANIPULATIVE_RESPONSES: string[] = [
  "yes", "no", "perhaps", "could be", "never", "certainly",
  "probably", "I doubt it", "I am not sure", "true", "false", "partly",
  "sometimes", "always", "never", "rarely", "often", "usually",
  "look right", "look left", "look up", "look down", "look behind you", "look ahead",
  "look around you", "look at the wall", "go to the door", "go to the window", "go to the cellar", "go to the attic",
  "go out", "come in", "come closer", "get away", "one step closer", "my age was",
  "I died here", "I lived here", "I have been here a long time", "I have waited a hundred years", "I was waiting for you", "you were always going to come",
  "fate", "do not be afraid", "you should be afraid", "you are not in danger", "you are in danger", "you are safe",
  "you are not safe", "you are not alone", "you are utterly alone", "you are loved", "you are not loved", "you have been forgotten",
  "you are remembered", "the time will come", "be patient", "wait", "be ready", "you will understand soon",
  "all will be revealed", "it will remain a secret", "I cannot say", "it is forbidden", "there is no permission", "there is a limit",
  "behind you", "beside you", "above", "I witnessed it", "you heard it", "drawing closer",
  "touch", "an outrage", "an incident", "a lost soul", "we", "they",
  "nobody", "a visitor", "something here", "it belongs here", "held in trust", "old",
  "I know", "you saw it", "I hid it", "was here", "they have gone", "woken",
  "sleeping", "deep within", "far away", "your name", "I buried it", "I took it",
  "I lost it", "I found it", "I am searching", "I am coming", "I am going", "I remained",
  "I died", "I am alive", "soon", "right behind you", "to your right", "to your left",
  "above", "between", "within", "beyond", "on the near shore", "opposite",
  "at the threshold", "who are you", "what is your name", "what do you want", "why are you here", "how many of you are there",
  "when did you come", "how did you die", "can you hear us", "do you want help", "should we leave",
];

export const LONG_PHRASES: string[] = [
  "you are not alone here tonight", "someone lives behind the walls", "I come at the same time every night", "I have been watching you for a long time", "this house has a story", "much blood has been spilled here",
  "no one who came here ever left alive", "you will not be the last to come", "locking the door will not help you", "I am everywhere all the time", "when you close your eyes you will see me", "I will visit you in your dreams",
  "stay awake, for I am awake", "do not sleep tonight, do not sleep", "do you hear your own footsteps", "the shadow behind you is not mine", "look in the mirror and you will see me", "I am the voice that comes from the ceiling",
  "there is something in the cellar", "someone is walking on the roof", "I saw a shadow in the garden", "someone is looking in through the window", "the door opened by itself", "the lights are flickering",
  "the clock stopped at three in the morning", "the mirror shattered on its own", "blood seeps from the wall", "sounds rise up from beneath the ground", "it is not water — it is blood dripping from the ceiling", "the figure in the photograph moved",
  "the doll smiled", "someone is coming down the stairs", "someone stands at the far end of the corridor", "hands are reaching from under the bed", "someone is breathing inside the wardrobe", "there is a silhouette behind the curtain",
  "eyes gleam in the darkness", "the painting on the wall is watching you", "your clock has stopped ticking", "the phone rang but there was no one there", "strange sounds come from the radio", "the television switched on by itself",
  "a face appeared on the computer screen", "blood flows from the tap", "I cast no reflection in the mirror", "my shadow moves independently of me", "this is the place I saw in my dreams", "I have been here before",
  "I have lived this moment before", "I am caught in a time loop", "there is no way out of here", "doors locked, windows sealed", "the walls began to close in", "the ceiling is descending",
  "the floor is giving way", "the air grows colder", "I can see my own breath", "something touched my leg", "my hair was pulled", "something whispered in my ear",
  "I felt cold breath on the back of my neck", "a hand touched my shoulder", "someone is shoving me from behind", "my foot caught on something unseen", "something moved in the dark", "a shadow appeared in the corner and was gone",
  "it is not dust falling from the ceiling — it is ash", "the clock on the wall is running backwards", "another room appears in the mirror", "the foot of the staircase opens into darkness", "this corridor has no end", "every time I open the door I am in the same room",
  "I cannot see anything through the window", "there is nothing outside — only darkness", "someone was hanged in this room", "a body is buried under the bed", "there are bones inside the walls", "this house was built on a graveyard",
  "at night, sounds come from inside the walls", "strange things happen every full moon", "the neighbours give this house a wide berth", "everyone who ever lived here went mad", "the last tenant vanished", "even the police will not enter this house",
  "even the imam could not cleanse this place", "the priest came — and ran", "the rituals held here are still continuing", "screams are heard at three in the morning", "children never pass this house", "cats never come near this house",
  "dogs howl outside this house", "birds never fly over this house", "the trees around this house are dying", "no flowers bloom in this garden", "sunlight never enters this house", "the clock stops at three every night",
  "mirrors crack on their own", "candles ignite on their own", "doors open and close by themselves", "the chair moves unaided", "the eyes of the paintings follow you", "the stain on the wall grows larger each day",
  "the crack in the ceiling looks like a face", "the bloodstain on the floor cannot be removed", "the air in this room is always cold", "electronic devices fail here", "your phone battery drains in moments here", "the compass goes wild here",
  "clocks show the wrong time here", "cameras malfunction here", "strange shapes appear in photographs taken here", "there is someone in the videos who should not be there", "the audio recordings carry whispers", "the EMF meter goes haywire here",
  "the temperature drops without warning", "there is a strange smell in the air", "damp odour — but no mould", "the smell of burning — but no fire", "the scent of flowers — but there are no flowers", "the smell of perfume — but no one is there",
];

export const MYTHOLOGY_WORDS: string[] = [
  "al-karı", "night terror", "bogey", "ghoul", "giant", "glutton",
  "albastı", "koncolos", "tepegöz", "basilisk", "Hıdırellez", "Nowruz",
  "Ergenekon", "the Grey Wolf", "Asena", "Headstone Mountain", "the Tuba tree", "the Water of Life",
  "the Water of Immortality", "phoenix", "firebird", "simurgh", "the wind-horse", "the wind-fairy",
  "nymph", "mountain spirit", "dryad", "the evil eye", "the malefic gaze", "the hex",
  "possessed", "werewolf", "night owl", "the owl's screech", "black cat", "the forty steps",
  "midwifery spirit", "wish-granting wraith", "the wishing tree", "the wishing well", "the place of sacrifice", "laid low",
  "saint", "holy one", "elder", "pir", "patriarch", "the hoca",
  "enchantress", "the fortune-telling grandmother", "hidden treasure", "a burial", "treasure", "the golden cube",
  "the cursed hoard", "the guardian djinn", "the treasure-keeper", "the talismanic door", "the enchanted mirror", "the flying carpet",
  "invisibility", "immortality", "the elixir of youth", "washer of the dead", "shroud", "the musalla stone",
  "hearse", "tombstone", "headstone", "footstone", "sarcophagus", "stone coffin",
  "mausoleum", "cage", "turbe", "mass grave", "the lost tomb", "the unmarked grave",
  "the midnight graveyard", "the forsaken cemetery",
];

export const FOLK_BELIEFS: string[] = [
  "evil-eye bead", "written amulet", "lead-pouring", "burning incense", "making a vow", "do not make that wish",
  "dream interpretation", "divination", "coffee-ground reading", "palm reading", "horoscope", "water divination",
  "mirror magic", "candle magic", "cord magic", "binding spell", "separation spell", "love spell",
  "black magic", "white magic", "djinn magic", "healer", "djinn", "amulet-maker",
  "sorcerer", "enchanter", "conjuror", "illusionist", "necromancy", "glass-tipping",
  "pencil-holding", "table-turning", "Ouija board", "spirit board", "do not invite a djinn", "exorcism",
  "do not bind the djinn", "incantation", "afsun", "recitation", "blowing the charm", "do not breathe",
  "water scrying", "faith healing", "the gaze", "the evil touch", "tongue affliction", "malevolent spirit",
  "benevolent spirit", "guardian spirit", "ancestral spirit", "grandfather spirit", "grandmother spirit", "house spirit",
  "hammam djinn", "water djinn", "fire djinn", "earth spirit", "weather djinn", "Muslim jinn",
  "infidel jinn", "lovesick djinn",
];

export const HORROR_STORY_WORDS: string[] = [
  "jump scare", "mounting dread", "terror", "horror", "panic", "flight",
  "the chase", "the ambush", "the snare", "the trap", "the sacrifice", "the hunter",
  "the prey", "pursuit", "the shadow", "a squealing door", "cracking timber", "rustling leaves",
  "the howling wind", "a howling pipe", "rattling glass", "ringing in the ear", "a throbbing head", "a shaking hand",
  "a muffled cry", "a voice cut short", "blood run cold", "hair standing on end", "skin like gooseflesh", "trembling skin",
  "heart hammering", "cold sweat", "a tremor", "a convulsion", "unable to breathe", "reeling",
  "nausea", "blurred sight", "tinnitus", "numbness", "do not be paralysed", "do not freeze",
  "petrified", "levitation", "telekinesis", "spontaneous combustion", "shapeshifting", "dimensional leap",
  "time travel", "soul separation", "out-of-body experience", "astral travel", "consciousness transfer", "mind control",
  "hypnosis", "mass hysteria", "collective hallucination", "the accursed mirror", "the accursed doll", "the accursed ring",
  "the accursed book", "the accursed portrait", "the accursed jewel", "the accursed dagger", "the accursed crown", "the accursed chest",
  "the accursed map", "the accursed compass", "the accursed clock",
];

export const DIALOG_PHRASES: string[] = [
  "hello", "greetings", "welcome", "I was waiting for you", "you have finally come", "you are late",
  "where have you been", "this place belongs to me", "I am the soul of this house", "I died here", "I am buried here", "I cannot tell you my name",
  "I have forgotten my name", "no more footsteps", "I never truly existed", "I am a memory", "I am an echo", "leave this place now",
  "do not stay here tonight", "go before the sun sets", "leave before dark falls", "go before midnight", "leave before three o'clock", "do not enter this room again",
  "do not open this door again", "do not look in this mirror again", "do not speak that name again", "a family once lived here", "this house was built a hundred years ago", "there was a fire here once",
  "a murder was committed here", "a child was lost here", "a woman took her own life here", "a man went mad here", "a ritual was held here", "a treasure lies buried here",
  "a curse began here", "I will keep you here", "you will never leave", "you will stay with me", "here forever", "there is no escape",
  "no exit", "there is no salvation", "prayer will not help you", "no one can save you", "scream all you like — no one will hear", "please do not go",
  "do not leave me alone", "I am so desperately lonely", "no one ever comes", "I have been waiting years", "centuries alone", "I need a companion",
  "I want to talk to someone", "you are the first person to hear my voice", "you are the first to see me",
];

export const PROVERBS: string[] = [
  "all must die in the end", "every living thing shall taste death", "death has come into the world — a headache is just an excuse", "the grave is dark", "the earth is cold", "the night is long",
  "the morning is far off", "fear cannot ward off death", "every darkness comes to an end", "fire burns wherever it falls", "water sleeps but the enemy does not", "out of sight, out of mind",
  "do not expect the dead to return among the living", "what comes and goes leaves its mark", "everything has an end", "patience is bitter but its fruit is sweet", "they call the past the past for a reason", "old friends do not become enemies",
  "what is done in blood cannot be washed clean", "day and night it pursues you", "darkness swallows the light", "silence is the loudest scream", "death does not knock — it simply enters", "tombstones do not speak but they tell their stories",
  "the wind blows and branches break", "water flows and finds its way", "there is no smoke without fire",
];

export const COLOR_LIGHT_WORDS: string[] = [
  "red", "blue", "green", "yellow", "orange", "purple",
  "pink", "white", "black", "grey", "brown", "beige",
  "cream", "gold", "silver", "crimson", "midnight blue", "turquoise",
  "magenta", "lilac", "blood red", "midnight black", "poison green", "ash grey",
  "light", "dark", "shadow", "gleaming", "dimness", "radiance",
  "matte", "opaque", "transparent", "translucent", "neon", "fluorescent",
  "phosphorescent", "shimmering", "fading", "flickering", "pulsing", "blinking",
  "wavering", "scarlet", "vermilion", "infrared", "spectral", "ultraviolet",
];

export const WEATHER_WORDS: string[] = [
  "it is raining", "it is snowing", "it is hailing", "the storm is coming", "the wind is blowing", "the hurricane approaches",
  "lightning strikes", "thunder rolls", "a bolt has struck", "the fog has descended", "there is a haze", "smoke drifts",
  "it is growing dark", "the sun is setting", "the moon is rising", "stars emerge", "there is a full moon", "new moon",
  "the shadows lengthen", "darkness falls", "the night begins", "a cold wave", "a heat wave", "the humidity rises",
  "the pressure drops", "the air grows heavy", "unbearably close", "freezing cold", "frosty", "a hard frost",
  "bitter raw",
];

export const SOUND_WORDS: string[] = [
  "melody", "tune", "song", "folk song", "lament", "lullaby",
  "hymn", "münacat", "adhan", "sala", "drum", "zurna",
  "ney flute", "oud", "kanun", "violin", "piano", "organ",
  "bell", "hand bell", "whisper", "murmur", "grunt", "wheezing",
  "rustle", "squeak", "click", "crackle", "commotion", "din",
  "hum", "buzz", "sizzle", "clink", "crunch", "explosion",
  "crash", "collapse", "shattering", "disintegration", "echo", "reverberation",
  "resonance", "vibration", "frequency", "ultrasound", "infrasound", "white noise",
  "pink noise", "silence", "stillness", "peace", "quiet", "fading out",
  "laughter", "sobbing", "a wail", "keening", "wailing", "a moan",
  "whimpering", "supplication", "a plea", "prayer",
];

export const QUANTITY_WORDS: string[] = [
  "little", "a great deal", "a small amount", "quite a bit", "considerably", "enough",
  "insufficient", "far too much", "lacking", "full", "half", "a quarter",
  "a third", "one part in four", "single", "a pair", "several", "many",
  "countless", "infinite", "boundless", "limited", "constrained", "first",
  "last", "the middle one", "foremost", "trailing", "primary", "secondary",
  "third", "fourth", "fifth", "sixth", "seventh", "eighth",
  "ninth", "tenth",
];

export const COMMUNICATION_WORDS: string[] = [
  "speak", "listen", "tell me", "ask", "reply", "write",
  "read", "draw", "point", "show", "message", "letter",
  "note", "writing", "sign", "symbol", "code", "password",
  "key", "clue", "language", "tongue", "dialect", "utterance",
  "accent", "preference", "translation", "meaning", "significance", "interpretation",
  "promise", "word", "sentence", "paragraph", "text", "story",
  "fairy tale", "legend", "myth", "epic", "poetry", "ode",
  "ghazal", "rubaiyat", "couplet", "prayer", "curse", "oath",
  "vow", "pledge", "secret", "hidden message", "coded message", "cipher",
  "invisible ink", "secret text", "mirror writing",
];

export const RELATIONSHIP_WORDS: string[] = [
  "mother", "father", "son", "daughter", "brother", "elder brother",
  "sister", "paternal uncle", "maternal uncle", "paternal aunt", "maternal aunt", "nephew",
  "cousin", "grandchild", "grandfather", "grandmother", "grand-dame", "patriarch",
  "mother-in-law", "father-in-law", "wife", "husband", "spouse", "beloved",
  "betrothed", "enemy", "rival", "adversary", "opposition", "counterpart",
  "friend", "companion", "comrade", "brother-in-arms", "confidant", "neighbour",
  "familiar", "stranger", "guest", "visitor", "servant", "butler",
  "concubine", "bondservant", "master", "ruler", "king", "queen",
  "prince", "princess",
];

export const WHISPER_PHRASES: string[] = [
  "pssst", "hey", "look at me", "over here", "hear me", "see me",
  "feel me", "touch me", "come closer", "come a little closer", "lend me your ear", "sssh",
  "stay quiet", "no one must hear", "turn slowly", "look slowly", "I have a secret", "I am going to tell you something",
  "do not tell a soul", "keep this between us", "this secret", "I chose you", "you are someone special", "you are different",
  "you are different from the rest", "I understand you", "you are the only one who understands me", "we share a bond", "your eyes see things others cannot", "you can sense me",
  "the others cannot hear — but you can", "our destiny is one", "we are bound to one another", "you cannot avoid this", "it is written", "it is fate",
  "everything happens for a reason", "nothing is coincidence", "I wanted you to come here", "I called to you", "my invitation was accepted", "welcome to my home",
  "I have waited so long for you", "you came at precisely the right moment", "you are here now", "you belong to me now", "I will not let you leave", "forever",
  "we will be together", "we will never part", "you are my final guest", "no one has ever left this place again", "you will lose yourself in this house", "I will see you in your dreams",
  "I will come to you in your sleep", "I am here in the night", "I live in the darkness", "the light frightens me", "the sun burns me", "the night is my time",
  "darkness is my dwelling", "I grow stronger after sunset", "I am at my most powerful at three in the morning", "I will vanish at daybreak — but wait for the night", "I know your name", "I know where you live",
  "I know your family", "I know your past", "I know what you fear", "I know your dreams", "I was in your dream last night", "did you not wake suddenly in the night",
  "that was me — that strange feeling", "be careful tonight", "you are not safe", "stay with someone", "do not sleep alone", "do not turn off the lamp",
  "lock the door", "do not leave the window open", "draw the curtains", "did you hear that just now", "it is right behind you now", "do not come back yet",
];

export const DETAILED_PLACES: string[] = [
  "abandoned hospital", "psychiatric ward", "madhouse", "abandoned school", "burned-out building", "rubble",
  "derelict factory", "old warehouse", "empty depot", "abandoned hotel", "ghost town", "forsaken village",
  "underground tunnel", "sewer", "metro tunnel", "wartime shelter", "bomb shelter", "hidden room",
  "secret passage", "tunnel mouth", "cave entrance", "the bottom of the well", "water well", "dry well",
  "cellar", "attic", "loft space", "pantry", "undercroft", "wine cellar",
  "old mosque", "abandoned church", "ruined monastery", "synagogue", "pagan temple", "altar",
  "the altar stone", "minaret", "bell tower", "pulpit", "dark forest", "overgrown garden",
  "marshland", "cliff edge", "mountain pass", "valley floor", "lakeshore", "river bed",
  "beneath the waterfall", "island", "peninsula", "headland", "rocky outcrop", "shore",
  "seafront", "harbour mouth", "jetty", "old stone bridge", "arch bridge", "suspension bridge",
  "fortress", "citadel", "star fortress", "battlements", "great hall", "manor house",
  "country house", "yalı", "hammam", "caravanserai", "tavern", "covered bazaar",
  "madrasa", "scriptorium", "observatory", "the old mint",
];

export const DETAILED_TIME: string[] = [
  "before first light", "sunrise", "early morning", "mid-morning", "noon", "afternoon",
  "evening", "sunset", "twilight", "midnight", "three in the morning", "the dark before dawn",
  "the Ottoman era", "the Seljuk era", "the Byzantine era", "the Roman era", "the Hittite era", "the Sumerian era",
  "the Middle Ages", "the new age", "the modern age", "the years of war", "the famine years", "the plague years",
  "every night", "every morning", "every evening", "every full moon", "every new moon", "through every season",
  "on the same day each year", "on every anniversary", "once in a hundred years", "once in a thousand years", "since before time began", "forever",
  "last night", "last week", "last month", "last year", "years ago", "centuries past",
  "a thousand years ago", "at the dawn of time", "the end of days", "the day of judgement", "the last day", "the final hour",
  "the final minute", "the last breath",
];

export const CURSES: string[] = [
  "be damned", "down with you", "may you be erased", "you will meet your punishment", "you will be called to account", "you will pay the price",
  "you will regret this", "I will not forget", "I will not forgive", "there is no forgiveness", "I will have my revenge", "we will settle this",
  "this is not over", "it is far from over", "this is only the beginning", "you will see", "you will come to understand", "you will feel it",
  "you will suffer", "you will weep", "you will beg", "begging for help will do nothing", "no one can help you", "there is no escape",
  "there is no salvation", "it will never end", "this curse cannot be lifted", "this spell cannot be broken", "this chain cannot be severed", "this bond cannot be undone",
  "it will last seven generations", "it will run for forty days", "it will last forever", "it will continue without end", "these lands are cursed", "this house is accursed",
  "this family carries the curse", "this blood is cursed", "every child born here is accursed", "every generation is marked", "the curse has passed to you", "it is yours now",
  "you will carry this burden", "and after you, your children",
];

export const DREAM_WORDS: string[] = [
  "dream", "nightmare", "waking dream", "vision", "prophecy", "portent",
  "premonition", "intuition", "instinct", "the sixth sense", "the subconscious", "the unconscious",
  "trance", "hypnosis", "meditation", "sleep paralysis", "a lucid dream", "in the grip of a nightmare",
  "flying in a dream", "falling in a dream", "running in a dream", "fleeing in a dream", "being pursued in a dream", "seeing the dead in a dream",
  "seeing blood in a dream", "seeing a serpent in a dream", "seeing a spider in a dream", "seeing water in a dream", "seeing fire in a dream", "seeing a house in a dream",
  "seeing a grave in a dream", "seeing a mirror in a dream", "seeing a door in a dream", "seeing a staircase in a dream", "seeing a corridor in a dream", "seeing darkness in a dream",
  "seeing light in a dream", "hearing a voice in a dream", "hearing a whisper in a dream", "hearing screaming in a dream", "hearing music in a dream", "seeing someone in a dream",
  "a stranger in the dream", "a shadow in the dream", "a face in the dream", "an eye in the dream",
];

export const RESEARCH_JARGON: string[] = [
  "anomaly detected", "the energy field has changed", "electromagnetic surge", "temperature anomaly", "voice anomaly", "visual anomaly",
  "data collection", "evidence analysis", "crime scene investigation", "witness statement", "eyewitness", "first-hand information",
  "secondary source", "archive record", "historical document", "frequency analysis", "spectrum analysis", "wavelength",
  "infrared", "ultraviolet", "thermal image", "night vision", "full infrared", "full spectrum",
  "SLS scan", "EMF reading", "EVP capture", "spirit box session", "ghost box sweep", "REM pod",
  "K-II meter", "Mel meter", "Trifield meter", "digital thermometer", "laser grid", "motion sensor",
  "vibration sensor", "pressure sensor", "humidity sensor", "control session", "provocation attempt", "silent vigil",
  "question-and-answer session", "open session", "baseline reading", "reference value", "anomalous reading", "peak value",
  "average value",
];

export const ALL_WORDS: string[] = [
  ...PHONEMES,
  ...DARK_WORDS,
  ...DARK_PHRASES,
  ...SPIRIT_NAMES,
  ...NUMBERS,
  ...HISTORICAL_WORDS,
  ...NATURE_WORDS,
  ...EMOTION_WORDS,
  ...BODY_WORDS,
  ...PLACE_WORDS,
  ...TIME_WORDS,
  ...ACTION_WORDS,
  ...RELIGIOUS_WORDS,
  ...PARANORMAL_TERMS,
  ...OBJECT_WORDS,
  ...ADJECTIVE_WORDS,
  ...MANIPULATIVE_RESPONSES,
  ...LONG_PHRASES,
  ...MYTHOLOGY_WORDS,
  ...FOLK_BELIEFS,
  ...HORROR_STORY_WORDS,
  ...DIALOG_PHRASES,
  ...PROVERBS,
  ...COLOR_LIGHT_WORDS,
  ...WEATHER_WORDS,
  ...SOUND_WORDS,
  ...QUANTITY_WORDS,
  ...COMMUNICATION_WORDS,
  ...RELATIONSHIP_WORDS,
  ...WHISPER_PHRASES,
  ...DETAILED_PLACES,
  ...DETAILED_TIME,
  ...CURSES,
  ...DREAM_WORDS,
  ...RESEARCH_JARGON,
  ...HOME_OBJECT_PHRASES,
];

export const WORD_CATEGORIES = {
  phonemes: PHONEMES.length,
  darkWords: DARK_WORDS.length,
  darkPhrases: DARK_PHRASES.length,
  spiritNames: SPIRIT_NAMES.length,
  numbers: NUMBERS.length,
  historicalWords: HISTORICAL_WORDS.length,
  natureWords: NATURE_WORDS.length,
  emotionWords: EMOTION_WORDS.length,
  bodyWords: BODY_WORDS.length,
  placeWords: PLACE_WORDS.length,
  timeWords: TIME_WORDS.length,
  actionWords: ACTION_WORDS.length,
  religiousWords: RELIGIOUS_WORDS.length,
  paranormalTerms: PARANORMAL_TERMS.length,
  objectWords: OBJECT_WORDS.length,
  adjectiveWords: ADJECTIVE_WORDS.length,
  manipulativeResponses: MANIPULATIVE_RESPONSES.length,
  longPhrases: LONG_PHRASES.length,
  mythologyWords: MYTHOLOGY_WORDS.length,
  folkBeliefs: FOLK_BELIEFS.length,
  horrorStoryWords: HORROR_STORY_WORDS.length,
  dialogPhrases: DIALOG_PHRASES.length,
  proverbs: PROVERBS.length,
  colorLightWords: COLOR_LIGHT_WORDS.length,
  weatherWords: WEATHER_WORDS.length,
  soundWords: SOUND_WORDS.length,
  quantityWords: QUANTITY_WORDS.length,
  communicationWords: COMMUNICATION_WORDS.length,
  relationshipWords: RELATIONSHIP_WORDS.length,
  whisperPhrases: WHISPER_PHRASES.length,
  detailedPlaces: DETAILED_PLACES.length,
  detailedTime: DETAILED_TIME.length,
  curses: CURSES.length,
  dreamWords: DREAM_WORDS.length,
  researchJargon: RESEARCH_JARGON.length,
  total: 0,
};
WORD_CATEGORIES.total = ALL_WORDS.length;
