// French word bank for VOX — native-speaker quality, parallel to word-bank.ts (Turkish).
// Category counts mirror word-bank-en.ts exactly. PHONEMES omitted (not used by VoxWordBank).

export const NINE_PHRASES: string[] = [
  "mon enfant", "mon petit-enfant", "ma chérie", "mon bébé", "mon petit", "mon petit agneau",
  "mon cœur", "la lumière de mes yeux", "le coin de mon cœur", "viens près de moi", "où es-tu, mon enfant", "tu me manques",
  "ne me laisse pas", "je t'attends avec tant de désir", "je pense à vous chaque nuit", "je veux entendre ta voix", "laisse-moi voir ton visage encore une fois", "tu es venu dans mon rêve, mais je me suis réveillée",
  "pourquoi ne viens-tu pas", "tu m'entends", "il fait froid ici", "il n'y a pas de lumière", "c'est si sombre", "je suis encore là",
  "ne m'oublie pas", "ma tombe est désolée", "personne ne vient plus", "je suis restée toute seule", "comme le temps a passé", "était-ce vraiment la mort",
  "je t'attends", "viens un jour", "emmène-moi d'ici", "la terre est froide", "la terre est sombre", "je suis devenue froide sous la pierre",
  "personne ne sait que je suis là", "c'est si difficile ici", "je ne peux pas partir de toute façon", "je suis liée à ce monde", "j'attends encore", "je t'entends mais je ne peux pas te voir",
  "vos voix me parviennent mais de si loin", "ah, mon cher enfant", "que tout aille bien", "que Dieu te protège", "prie", "fais ta prière",
  "il y a des gens mauvais dehors", "fais attention, mon chéri", "ne t'égare pas", "reste honnête", "vis avec honneur", "respecte tes aînés",
  "appelle tes proches et prends de leurs nouvelles", "fuis le péché", "fais pénitence", "gagne ta vie honnêtement", "aimez-vous les uns les autres", "ne vous laissez pas diviser",
  "de si sombres rêves", "je pleure toutes les nuits", "je ne vois pas le matin", "cette présence obscure m'a suivie jusqu'ici", "j'ai vu quelque chose avant de mourir", "il y a quelque chose que je dois te dire",
  "un secret se cache sous cette maison", "des bruits montent des entrailles de la terre", "je frapperai à la porte à minuit", "je viendrai te rendre visite dans tes rêves", "tu me verras dans ton sommeil", "je serai là lorsque tes yeux se fermeront",
  "j'aurais tant aimé passer plus de temps avec toi", "je veux dire tout ce que je n'ai jamais dit", "pardonne-moi, mon enfant", "moi aussi j'ai fait mes erreurs", "je donnerais tout pour revenir en arrière", "j'aurais voulu te le dire plus tôt",
  "je suis partie trop tôt", "je n'étais pas prête", "je ne voulais pas vous quitter", "je me tiens entre ce monde et le suivant", "je viendrai lorsque le seuil s'ouvrira", "lors de l'éclipse lunaire tu pourras m'entendre",
  "je suis plus forte les vendredis soir", "je reste assise dans le cimetière à pleurer", "ceux qui sont près de moi veulent aussi te voir", "cet endroit est plein — et pourtant totalement silencieux", "je cours vers la lumière mais je n'arrive pas à l'atteindre", "un jour tu comprendras",
];

export const GIRL_CHILD_PHRASES: string[] = [
  "tu veux jouer avec moi", "je ne veux pas être seule", "pourquoi personne ne joue avec moi", "j'ai perdu ma poupée", "où sont mes jouets", "je veux rentrer à la maison",
  "où est ma mère", "où est mon père", "est-ce qu'ils m'attendent", "je ne veux pas pleurer mais je pleure quand même", "personne ne me voit", "est-ce que je suis invisible",
  "il n'y a donc personne ici", "je suis toute seule ici", "je veux une amie", "je peux jouer avec toi", "j'ai peur", "pourquoi fait-il si sombre",
  "tu peux allumer la lumière", "j'ai vu quelque chose", "il est revenu", "il revient chaque nuit", "le méchant homme est revenu", "il m'a touchée",
  "quand je crie il s'en va", "je ferme les yeux", "j'ai commencé à compter à rebours depuis cent", "il y a quelqu'un derrière moi", "tu le vois", "il te voit aussi",
  "ne viens pas ici", "c'est dangereux ici", "ça te suivra aussi", "ils m'ont laissée ici", "pourquoi ils m'ont abandonnée", "les murs parlent",
  "quelqu'un regarde par la fenêtre", "ce n'est pas moi dans le miroir", "mon ombre bouge toute seule", "des bruits viennent du plafond", "quelqu'un est dans l'escalier — je compte les pas", "mon chien voit quelque chose dans le coin",
  "mon chat s'est enfui de la pièce", "les fleurs se sont fanées quand je suis entrée", "l'horloge s'est arrêtée à cet instant précis", "ma mère m'appelle", "doucement", "hm hm",
  "non non non", "arrête arrête arrête", "je ne veux pas je ne veux pas", "moi aussi je le vois", "j'ai si froid", "ne me laisse pas",
  "tiens-moi s'il te plaît", "prends ma main", "ne t'en va pas", "je vais quelque part pendant que je dors", "j'y suis même dans mes rêves", "je me réveille épuisée",
  "que se passe-t-il la nuit", "toi aussi tu vois des choses étranges la nuit", "il y a des yeux dans l'obscurité", "ils attendent", "je suis restée ici bien trop longtemps", "je veux sortir maintenant",
  "emmène-moi s'il te plaît", "je veux aller vers la lumière", "je ne peux pas passer par cette porte", "quelque chose bloque le chemin", "comment tu t'appelles", "est-ce que je peux te faire confiance",
  "ne pleure pas — si tu pleures, je pleure aussi", "pars d'ici, pour ton propre bien",
];

export const PHANTOM_PHRASES: string[] = [
  "je suis ici", "tu m'entends", "à l'aide", "je ne peux pas sortir", "nous sommes prisonniers", "laissez-nous partir",
  "éloignez-vous de là", "tu es en danger", "ça arrive", "fuis", "vous êtes tous en danger", "vous entendez",
  "j'étais comme toi autrefois", "il est bien trop tard maintenant", "ne pars pas", "cette maison cache un secret", "je suis dans les murs", "écoutez-moi",
  "ils sont réels", "personne ne m'a cru", "maintenant vous comprenez", "cet endroit est l'enfer", "je me suis perdu dans l'obscurité", "donnez-moi une voix",
  "il y a une pièce sous le plancher", "je connais la porte secrète", "n'ouvrez pas le coffre dans la cave", "savez-vous ce qu'il y a derrière ce mur", "l'ancien propriétaire est encore ici", "cette maison porte un secret vieux de cent ans",
  "quelqu'un pleure dans la cave", "il y a des pas sur le toit", "ajustez la fréquence", "mon signal est faible", "la connexion se coupe", "je suis si loin",
  "je vous entends", "ne venez pas ici", "le canal est ouvert", "je vous reçois", "j'essaie d'établir le contact", "trop de parasites",
  "la fréquence dérive", "changez de bande", "passez à travers les parasites et vous m'entendrez", "j'ai besoin d'amplification", "l'onde sonore se brise", "interférence interdimensionnelle",
  "ne regardez pas derrière vous", "fermez la porte", "n'éteignez pas les lumières", "ne restez pas seul", "ne dispersez pas le groupe", "il y a une présence puissante ici",
  "l'énergie négative est accablante", "la zone est souillée", "il faut la purifier", "enregistrez ceci", "regardez la caméra", "il y a quelque chose à votre gauche",
  "méfiez-vous quand la température chute", "vous pouvez encore respirer", "je parle de très loin", "ma voix vous parvient à peine", "l'énergie s'épuise", "je parle avec mes dernières forces",
  "restez silencieux pour m'entendre", "retenez votre souffle un instant", "je ne suis audible qu'en silence total", "je chuchote pour qu'ils ne m'entendent pas", "gardez cela entre nous", "personne d'autre ne doit savoir",
  "je m'adresse spécifiquement à toi", "tu as été choisi pour cela", "quelqu'un de spécial est venu ce soir", "il y a une personne sensible parmi vous", "l'un de vous est ouvert — spirituellement", "trouvez-le parmi vous",
];

export const HOME_OBJECT_PHRASES: string[] = [
  "regarde le fauteuil à côté de toi", "j'ai vu le fauteuil de gauche", "il y a quelqu'un derrière ce fauteuil", "je suis assis sur le canapé en ce moment", "j'avais l'habitude de m'asseoir dans ton fauteuil", "cette place vide est occupée",
  "regarde sous le canapé", "il y a une zone froide à côté du fauteuil", "ne touche pas encore le fauteuil", "ouvre le troisième tiroir", "j'ai caché quelque chose dans le tiroir du haut", "tu me trouveras dans le tiroir du bas",
  "ferme ce tiroir", "la porte de l'armoire restera ouverte cette nuit", "il y a quelqu'un dans l'armoire", "ouvre les tiroirs l'un après l'autre", "arrête-toi au dernier tiroir", "ferme l'armoire à clé avant la tombée de la nuit",
  "ne regarde pas sous ton lit", "il y a quelque chose sous ton oreiller", "je suis assis au bord du lit", "regarde ton oreiller quand tu te réveilles le matin", "ne dors pas dans ce lit cette nuit", "je me suis glissé sous les couvertures",
  "si ton lit semble s'enfoncer dans la nuit, c'est moi", "je regarde ton visage pendant que tu dors", "regarde attentivement dans le miroir", "il y a deux visages dans ton miroir en ce moment", "je suis de l'autre côté du miroir", "couvre le miroir la nuit",
  "regarde par la fenêtre", "je colle mon visage contre le verre", "as-tu jamais écarté les rideaux pour regarder dehors la nuit", "regarde la buée sur le verre", "n'ouvre pas la fenêtre cette nuit", "je me glisse par les volets",
  "as-tu vu l'ombre qui est passée sous la porte", "tu as bien fermé la porte à clé, n'est-ce pas", "quelqu'un marche dans le couloir", "la poignée de porte tourne lentement", "j'attends juste derrière la porte", "je peux entrer sans frapper",
  "n'ouvre pas cette porte", "quand la porte grince — c'est moi", "tu as entendu quelque chose tomber dans la cuisine", "je fais goutter le robinet comme ça", "écoute comme le réfrigérateur a changé de bruit", "es-tu sûr d'avoir éteint les plaques",
  "tous les couteaux de cuisine sont-ils en place", "regarde l'étagère en verre", "il y a quelqu'un sous la table de cuisine", "je viens de déplacer ta casserole", "je suis à côté de toi sous la douche", "j'écris dans la buée de ton miroir",
  "j'attends derrière le rideau de douche", "fermer la salle de bain à clé ne suffira pas", "je te regarde remplir la baignoire", "la porte des toilettes restera grande ouverte", "la septième marche de l'escalier va bientôt craquer", "je t'entends depuis le rez-de-chaussée",
  "il y a quelqu'un à l'étage", "je reste suspendu dans la cage d'escalier", "tu as entendu la porte en bas", "ne fuis pas par l'escalier — je ne peux pas t'attraper", "je vais éteindre l'ampoule tout à l'heure", "la lumière clignotera trois fois",
  "surveille la lampe cette nuit", "ne va pas au tableau électrique", "cette lampe dans le coin est mon signal", "arrache la fiche et tu ne me trouveras jamais", "as-tu remarqué que ton horloge murale s'est arrêtée", "l'horloge sonnera à trois heures du matin",
  "j'ai coché ce jour sur le calendrier", "la minute tourne à l'envers", "je sais que ton anniversaire approche", "le coin le plus sombre de la maison m'appartient", "regarde le coin inférieur droit de la pièce", "je suis assis contre le mur de gauche",
  "regarde là où le plafond rejoint le mur", "un secret se cache sous cette tache", "soulève le tapis et jette un coup d'œil", "les yeux dans ce tableau sont mes yeux", "as-tu déjà regardé de près la photographie dans le cadre",
];

export const DARK_WORDS: string[] = [
  "mort", "âme", "obscurité", "ombre", "malédiction", "peur",
  "horreur", "enfer", "tombe", "sépulcre", "cercueil", "funérailles",
  "mort", "fantôme", "djinn", "diable", "démon", "ifrit",
  "revenant", "vampire", "zombie", "squelette", "crâne", "sang",
  "douleur", "cri", "lamentation", "gémissement", "chuchotement", "silence",
  "son", "pas", "tonnerre", "froideur", "ils sont entrés", "contraire",
  "dérive temporelle", "destin", "motif", "de l'au-delà", "manifestation", "mirage",
  "spirale", "ombré", "ligne de murmure", "vague de froid", "glissement de fréquence", "statique",
  "acoustique", "déjà-vu", "vision", "silhouette", "brisé", "abandonné",
  "verrouillé", "nuit", "lune", "pleine lune", "nuage", "brouillard",
  "fumée", "brume", "obscurité pesante", "solitude", "délaissé", "perdu",
  "oublié", "prisonnier", "captif", "lié", "chaîne", "cadenas",
  "clé", "porte", "fenêtre", "miroir", "reflet", "mystère",
  "secret", "sorcellerie", "talisman", "amulette", "mauvais œil", "de mauvais augure",
  "noir", "d'ébène", "sombre", "profond", "vide", "précipice",
  "puits", "souterrain", "cave", "cellier", "tunnel", "caverne",
  "cachot", "prison", "os", "chair", "peau", "blessure",
  "trace", "tache", "rouille", "moisissure", "araignée", "toile",
  "insecte", "serpent", "chauve-souris", "corbeau", "chouette", "loup",
  "renard", "chacal", "hyène", "vautour", "scorpion", "rat",
  "feu", "flamme", "cendre", "poussière", "terre", "boue",
  "marécage", "tempête", "foudre", "coup de tonnerre", "tremblement de terre", "inondation",
  "tsunami", "peste", "épidémie", "maladie", "poison", "élixir",
  "sorcière", "sorcier", "diseuse de bonne aventure", "médium", "devin", "chaman",
  "prêtre", "rite", "rituel", "sacrifice", "offrande", "malédiction",
  "magie noire", "pentagramme", "symbole", "signe", "inscription", "rune",
  "portail", "passage", "dimension", "parallèle", "l'autre côté", "l'au-delà",
  "l'autre monde", "limbes", "purgatoire", "pont des âmes", "balance divine", "Azraël",
  "ange", "démon", "entité", "froid", "glace", "givre",
  "tremblement", "frisson", "chair de poule", "épine", "souffle", "pâle",
  "râlement", "grognement", "bourdonnement", "vrombissement", "couinement", "cliquetis",
  "crépitement", "bruissement", "tintement", "grésillement", "hanté", "hantise",
  "attaché", "suiveur", "silhouette d'ombre", "masse noire", "ombre blanche", "boule de lumière",
  "orbe", "ectoplasme", "poltergeist", "ouija", "planchette", "bougie",
  "encens", "cristal", "boule de cristal", "évocation", "séance", "médiumnité",
  "parapsychologie", "télépathie", "pressentiment", "prophétie", "cauchemar", "somnambulisme",
  "transe", "hypnose", "subconscient", "astral", "projection", "transmigration",
  "réincarnation", "karma", "aura", "énergie", "vibration", "fréquence",
  "onde", "signal", "interférence", "bruit", "catastrophe", "ruine",
  "apocalypse", "jugement dernier", "fin", "chaos", "désordre", "incertitude",
  "danger", "menace", "avertissement", "exécution", "potence", "bourreau",
  "tourment", "torture", "décomposition", "corruption", "désintégration",
  "extinction", "effacement", "oubli", "disparition", "effacement progressif",
  "obscurcissement", "noyade", "combustion", "congélation", "chute", "engloutissement",
  "piège", "embuscade", "complot", "intrigue", "tromperie", "trahison",
  "duperie", "mensonge", "faux", "contrefait", "fiction", "hallucination",
  "délire", "illusion", "fantôme", "vortex", "tourbillon", "ouragan",
  "tornade", "avalanche", "glissement de terrain", "effondrement", "implosion", "fissure",
  "faille", "abîme", "profondeurs", "obscurité inférieure", "vide sombre", "néant",
  "rien", "absence", "éternité", "éternité infinie", "immobilité", "pourri",
  "fétide", "putride", "rassis", "sans vie", "flétri", "desséché",
  "carbonisé", "brisé en morceaux", "fracassé", "écrasé", "oublié", "abandonné",
  "damné", "condamné", "dame blanche", "terreur nocturne", "croquemitaine", "goule",
  "géant", "ogre", "sorcière", "loup-garou", "doppelgänger", "cyclope",
  "basilic", "dragon", "phénix", "oiseau de feu", "télékinésie",
  "lévitation", "apport", "bilocation", "clairvoyance", "précognition", "rétrocognition",
  "psychométrie", "autoscopie", "doppelgänger", "phénomène", "anomalie", "déviation",
  "désordre", "irrégularité", "lugubre", "sombre", "brumeux", "nébuleux",
  "couvert", "détrempé", "battu par la tempête", "fouetté par le vent", "froid", "glacial",
  "accablant", "étouffant", "oppressif", "inquiétant", "sinistre", "perturbant",
  "à faire dresser les cheveux", "terrifiant", "plein d'effroi", "effrayant", "mystérieux", "énigmatique",
  "incompréhensible", "inexplicable", "surnaturel", "extraordinaire", "d'un autre monde", "étrange",
  "inquiétant", "bizarre", "inhabituel", "inattendu", "soudain", "sans prévenir",
  "caché", "dissimulé", "voilé", "masqué", "déguisé", "enveloppé",
  "délaissé", "délabré", "spectre", "d'un noir de poix", "énigme", "enchantement",
  "vieille écriture", "divination", "reproche", "apparition", "enfin", "présage",
  "testament", "passage", "oppression", "discorde", "englobant", "enchevêtrement",
  "retrait", "morne", "ensorcelé", "mystérieux", "mortalité", "jugement",
  "obsession", "délire", "divagations", "aveuglement spirituel", "repère", "apparent",
  "caché à l'intérieur", "contagion", "propagation", "ton destin", "fatalité", "écrit dans le marbre",
  "épreuve", "lamentation funèbre", "cri de mort", "réverbération", "échos", "voix de l'au-delà",
  "résonance", "reflet", "projection d'ombre", "illusion", "forme d'ombre", "silhouette obscure",
  "ombre blanche", "vision brumeuse", "cosmos", "dimensionnel", "temporel",
  "spatial", "universel", "tout-englobant",
  "pulsation de l'au-delà", "émanation", "phénomène inexpliqué",
];

export const DARK_PHRASES: string[] = [
  "viens ici", "entends-moi", "aide-moi", "ne me laisse pas", "ne pars pas", "je suis là",
  "je te vois", "regarde derrière toi", "fais attention", "fuis", "je suis mort", "trouve-moi",
  "sauve-moi", "je souffre", "je suis seul", "qui est là", "qui es-tu", "que veux-tu",
  "pourquoi es-tu venu", "pourquoi es-tu ici", "que cherches-tu", "qui cherches-tu", "sors d'ici", "quitte cet endroit",
  "dehors maintenant", "c'est ma maison", "c'est mon territoire", "je te surveille", "je suis partout", "tu ne peux pas t'échapper",
  "je te trouverai", "je suis juste derrière toi", "il n'y a pas d'issue", "reviens", "reviens encore", "ne m'oublie pas",
  "souviens-toi", "jure-le", "oui", "non", "peut-être", "je ne sais pas",
  "je ne peux pas le dire", "minuit", "l'aube", "le crépuscule", "la nuit de pleine lune", "trois heures",
  "l'heure des sorcières", "l'heure sombre", "ouvre la porte", "ferme la fenêtre", "éteins la lumière", "allume la bougie",
  "prie", "malédiction", "sois maudit", "mère", "père", "enfant",
  "bébé", "vieil homme", "vieille femme", "amour", "haine", "vengeance",
  "rage", "jalousie", "trahison", "meurtre", "accident", "catastrophe",
  "tragédie", "destin", "temps", "éternité", "pour toujours", "le passé",
  "le futur", "maintenant", "ici", "là", "en haut", "en bas",
  "à l'intérieur", "à l'extérieur", "tais-toi", "écoute", "entends-moi", "parle-moi",
  "réponds-moi", "cette maison", "cette pièce", "cet endroit", "cet endroit est maudit", "cet endroit est à moi",
  "pardonne-moi", "dépêche-toi", "le temps est court", "ta dernière chance", "ne dors pas", "ne te réveille pas",
  "rêve", "cauchemar", "un rêve terrible", "ne me dérange pas", "laisse-moi", "ne me touche pas",
  "froid", "très froid", "froid comme la glace", "je me gèle", "douleur", "douleur insupportable",
  "je ne peux pas l'endurer", "que ça finisse", "pourquoi", "comment", "quand",
  "où", "le troisième étage", "la cave", "le grenier", "le couloir", "sous l'escalier",
  "miroir", "regarde dans le miroir", "reflet", "inversé", "à trois heures du matin", "retourne-toi",
  "ne regarde pas", "ferme les yeux", "retiens ton souffle", "odeur de sang", "odeur d'humidité", "odeur de brûlé",
  "en décomposition", "pas", "le grincement de la porte", "verre brisé", "un cri", "quelqu'un est là",
  "derrière moi", "à côté de moi", "au-dessus de moi", "en dessous de moi", "j'observe", "j'attends",
  "je suis patient", "j'ai tout mon temps", "la mort est proche", "la dernière nuit", "adieu", "au revoir",
  "adieu pour toujours", "je te connais", "je connais ton nom", "je connais ton passé", "je connais ton secret", "je connais ta peur",
  "je connais ta faiblesse", "je t'attendais", "je savais que tu viendrais", "je suis prêt", "je veux te parler", "écoute-moi",
  "j'ai quelque chose d'important à dire", "ne fais confiance à personne", "ne fais confiance à aucune âme", "tu es seul", "il n'y a personne", "tes amis te mentent",
  "ils ne t'aiment pas", "ils t'utilisent", "tu vas bientôt mourir", "ton temps s'écoule", "le compte à rebours tourne", "je compte tes derniers souffles",
  "ta tombe est prête", "le cercueil t'attend", "la prière des morts", "l'enterrement", "la terre est froide", "froide et sombre",
  "cette maison a une histoire", "quelqu'un est mort ici", "du sang a été versé", "les murs se souviennent", "sous la terre", "enterré",
  "caché", "une pièce secrète", "un passage secret", "derrière le mur", "au-dessus du plafond", "je veux jouer",
  "sois mon ami", "jouons à cache-cache", "tu m'as trouvé", "c'est ton tour", "cours après moi", "tu ne m'attraperas jamais",
  "où est ma mère", "où est mon père", "je veux rentrer à la maison", "je suis perdu", "je ne retrouve pas mon chemin", "j'ai peur du noir",
  "je suis très vieux", "je suis fatigué", "je veux me reposer", "je ne me souviens pas", "j'ai oublié qui je suis", "où suis-je",
  "depuis combien de temps", "des années ont passé", "des siècles ont passé", "je suis encore là", "je ne peux pas partir", "je ne peux pas lâcher prise",
  "je suis lié", "je me sens comme en chaînes", "je ne suis pas libre", "sors d'ici", "c'est mon endroit", "tu t'es introduit sans permission",
  "je te punirai", "tu regretteras", "tu paieras", "je t'avais prévenu", "mon dernier avertissement", "ne reviens pas",
  "ne me dérange pas", "ne brise pas ma paix", "laisse-moi", "je suis tellement désolé", "je suis rempli de regrets", "j'aurais aimé ne pas l'avoir fait",
  "je veux être pardonné", "je suis coupable", "j'ai fait une terrible erreur", "il n'y a pas de retour en arrière", "il est trop tard", "il est bien trop tard maintenant",
  "la chance est passée", "le temps s'est écoulé", "tout est fini", "j'ai un message", "écoute bien", "déchiffre ceci",
  "je te donne un indice", "tu t'approches", "tu es sur la bonne voie", "tu regardes au mauvais endroit", "regarde ailleurs", "va plus profond",
  "pas en surface", "en dessous", "caché", "voilé", "masqué", "il y a du danger ici",
  "fais attention", "regarde autour de toi", "ne reste pas seul", "ne t'attarde pas dans l'obscurité", "ne quitte pas la lumière", "ferme la porte à clé",
  "ferme la fenêtre", "tire les rideaux", "ne regarde pas dans le miroir", "ne te retourne pas", "ne suis pas la voix", "l'énergie monte",
  "la vibration grandit", "la fréquence se déplace", "le portail s'ouvre", "le seuil est ouvert", "un lien interdimensionnel", "le signal se renforce",
  "le contact est en cours", "il y a une connexion", "un message arrive", "je réponds", "j'entends",
  "c'est ouvert",
];

export const SPIRIT_NAMES: string[] = [
  "Jean", "Pierre", "Jacques", "Louis", "Henri", "Charles",
  "François", "Philippe", "Guillaume", "Édouard", "Thomas", "Étienne",
  "Michel", "Nicolas", "Antoine", "Clément", "Théodore", "Gaston",
  "Armand", "Léon", "Émile", "Victor", "Raoul", "Gustave",
  "Hippolyte", "Alphonse", "Edmond", "Fernand", "Eugène", "Adolphe",
  "Octave", "Sébastien", "Bertrand", "Gilles", "Rémi", "Clovis",
  "Thibaud", "Godefroy", "Renaud", "Arnaud", "Marie", "Jeanne",
  "Marguerite", "Élisabeth", "Catherine", "Anne", "Françoise", "Madeleine",
  "Hélène", "Suzanne", "Geneviève", "Blanche", "Isabelle", "Adèle",
  "Mathilde", "Céleste", "Cécile", "Rosalie", "Berthe", "Clothilde",
  "Thérèse", "Victoire", "Pauline", "Adrienne", "Amélie", "Camille",
  "Delphine", "Eugénie", "Félicité", "Honorine", "Joséphine", "Laure",
  "Léonie", "Lucie", "Noémie", "Odette", "Raymonde", "Solange",
  "Angèle", "Baptistine", "Clémentine", "Dorothée", "Émilienne", "Flore",
  "Germaine", "Henriette", "Irène", "Juliette", "Louisette", "Marcelline",
  "Nadine", "Olympe", "Philomène", "Renée", "Sidonie", "Ursule",
  "Valentin", "Ambroise", "Cyprien", "Damien", "Eustache", "Florent",
  "Gontran", "Hyacinthe", "Isidore", "Jérôme", "Lazare", "Magloire",
  "Noël", "Odilon", "Prosper", "Séraphin", "Théophile",
];

export const NUMBERS: string[] = [
  "un", "deux", "trois", "quatre", "cinq", "six",
  "sept", "huit", "neuf", "dix", "onze", "douze",
  "treize", "quatorze", "quinze", "seize", "dix-sept", "dix-huit",
  "dix-neuf", "vingt", "vingt et un", "trente", "quarante", "cinquante",
  "soixante", "soixante-dix", "quatre-vingts", "quatre-vingt-dix", "cent", "mille",
  "zéro", "un million", "un milliard", "mille huit cents", "mille neuf cents", "deux mille",
  "le quinzième siècle", "le seizième siècle", "le dix-septième siècle", "le dix-huitième siècle", "le dix-neuvième siècle", "le vingtième siècle",
];

export const HISTORICAL_WORDS: string[] = [
  "Ottoman", "Sultan", "souverain", "Reine", "Pacha", "Bey",
  "Dame", "palais", "château", "tour", "rempart", "douve",
  "pont", "fontaine", "mosquée", "église", "temple", "mausolée",
  "madrasa", "guerre", "paix", "conquête", "siège", "victoire",
  "défaite", "servitude", "épée", "bouclier", "flèche", "lance",
  "dague", "or", "argent", "fer", "diamant", "rubis",
  "adhan", "prière", "prière rituelle", "ange", "djinn", "fée",
  "dragon", "auberge", "bain maure", "caravansérail", "bazar", "marché",
  "Roi", "empire", "califat", "règne", "trône", "couronne",
  "édit", "sceau", "acte", "charte", "janissaire",
  "sipahi", "éclaireur", "tourment", "capitaine", "chef",
  "pirate", "marin", "navigateur", "caravane", "marchand", "commerçant",
  "changeur de monnaie", "artisan", "derviche", "soufi", "Mévilevi", "Bektashi",
  "Naqshbandi", "maison de l'ordre", "zawiya", "tekke", "khanqah", "ribat",
  "prince", "Valide Sultan", "haseki", "concubine", "eunuque", "palais impérial",
  "Topkapı", "Dolmabahçe", "Yıldız", "Çırağan", "Galata", "Beyoğlu",
  "Üsküdar", "Kadıköy", "Bosphore", "Roumélie", "Anatolie", "Thrace",
  "Balkans", "Caucase", "Hittite", "Sumérien", "Assyrien", "Babylonien",
  "Phrygien", "Lydien", "Lycien", "Carien", "Ionien", "Ourartien",
  "Seldjoukide", "Byzantin", "Romain", "Grec", "Perse", "Mongol",
  "Hun", "Göktürk", "Karakhanide", "Ghaznévide", "Mamelouk", "Safavide",
];

export const NATURE_WORDS: string[] = [
  "pluie", "neige", "glace", "vent", "tempête", "ouragan",
  "foudre", "éclair", "nuage", "lune", "étoile", "mer",
  "océan", "lac", "rivière", "cascade", "montagne", "caverne",
  "forêt", "désert", "volcan", "tremblement de terre", "nuit", "lumière du jour",
  "aube", "crépuscule", "soleil", "terre", "planète", "univers",
  "galaxie", "nébuleuse", "trou noir", "comète", "météore", "météorite",
  "sol", "roche", "pierre", "sable", "gravier", "arbre",
  "feuille", "branche", "racine", "fleur", "mauvaise herbe", "mousse",
  "champignon", "lichen", "lierre", "loup", "ours", "aigle",
  "serpent", "scorpion", "chauve-souris", "chouette", "corbeau", "chat",
  "chien", "insecte", "araignée", "mouche", "moustique", "abeille",
  "poisson", "dauphin", "requin", "pieuvre", "méduse", "cru",
  "givre", "plein", "averse", "bruine", "vent du nord-est", "vent du sud-ouest",
  "brise", "sirocco", "karayel", "marée haute", "marée basse", "vague",
  "courant", "tourbillon", "source", "printemps", "ruisseau", "filet d'eau",
  "delta fluvial", "vallée", "canyon", "gorge", "col de montagne", "plateau",
  "banc de brouillard", "vapeur", "condensation", "lisière", "rayon de lumière", "rafale",
  "ermitage", "glissement de terrain", "secousse", "ligne de faille", "crevasse", "stalagmite",
  "stalactite", "gouffre", "cratère", "lave", "magma", "eau souterraine",
  "eau de source", "source guérisseuse", "source sacrée", "roselière", "étang", "ruisseau",
  "lit de rivière", "écume de mer", "marée", "goutte de rosée", "filet d'eau", "gouttelette",
  "sueur", "plasma", "sève", "résine", "ambre", "fossile",
  "socle rocheux", "minéral", "gisement de minerai", "minerai",
];

export const EMOTION_WORDS: string[] = [
  "peur", "horreur", "panique", "effroi", "angoisse", "rage",
  "rancœur", "haine", "répulsion", "chagrin", "deuil", "détresse",
  "désir", "solitude", "désespoir", "désespérance", "douleur", "souffrance",
  "tourment", "angoisse profonde", "remords", "conscience", "culpabilité", "curiosité",
  "stupéfaction", "perplexité", "paix", "silence", "quiétude", "malaise",
  "tension", "stress", "dépression", "désolation", "mélancolie", "nostalgie",
  "aspiration", "mal du pays", "aliénation", "joie", "bonheur", "allégresse",
  "ferveur", "excitation", "espoir", "anticipation", "désir ardent", "envie",
  "passion", "déception", "désillusion", "ne te laisse pas tromper", "ne te méprends pas", "doute",
  "crainte", "hésitation", "indécision", "incertitude", "courage", "audace",
  "héroïsme", "sacrifice", "pitié", "compassion", "commisération", "empathie",
  "jalousie", "envie", "convoitise", "rancune", "honte", "humiliation",
  "ennui", "lassitude", "horreur", "brutalité", "monstruosité", "cruauté",
  "sauvagerie",
];

export const BODY_WORDS: string[] = [
  "main", "pied", "tête", "œil", "oreille", "bouche",
  "dent", "langue", "doigt", "cou", "dos", "poitrine",
  "cœur", "cerveau", "sang", "os", "peau", "souffle",
  "pouls", "larme", "épaule", "bras", "poignet", "paume",
  "ongle", "genou", "mollet", "talon", "taille", "ventre",
  "foie", "rein", "intestin", "poumon", "estomac", "veine",
  "nerf", "muscle", "tendon", "articulation", "cheveux", "sourcil",
  "cil", "moustache", "barbe", "tempe", "bourrelet frontal", "menton",
  "joue", "nez", "colonne vertébrale", "côte", "clavicule", "omoplate",
  "bassin", "crâne", "mâchoire", "pommette", "orbite",
];

export const PLACE_WORDS: string[] = [
  "maison", "pièce", "salle", "couloir", "escalier", "toit",
  "cave", "porte", "fenêtre", "mur", "plafond", "cimetière",
  "hôpital", "prison", "forêt", "caverne", "puits", "tunnel",
  "pont", "cuisine", "salle de bain", "chambre à coucher", "salon", "balcon",
  "garage", "jardin", "cour", "terrasse", "véranda", "église",
  "mosquée", "synagogue", "temple", "monastère", "château", "palais",
  "tour", "cachot", "cellier", "école", "bibliothèque", "musée",
  "théâtre", "opéra", "usine", "entrepôt", "dépôt", "silo",
  "hangar", "village", "bourg", "ville", "métropole", "ruine",
  "désolation", "décombres", "gravats", "épave", "vestiges", "île",
  "péninsule", "cap", "crique", "port", "gare", "terminal",
  "aéroport", "jetée", "quai", "parc", "jardin d'agrément", "bosquet",
  "prairie", "champ", "ferme", "grange", "meule de foin", "moulin",
  "four à briques", "hammam", "auberge", "caravansérail", "halle du bazar", "marché",
  "mausolée", "külliye", "madrasa", "maison de l'ordre", "zawiya", "terre de sépulture",
  "sanctuaire", "tombeau", "sarcophage", "ossuaire", "maison abandonnée", "manoir hanté",
  "château maudit", "ville fantôme", "ville morte", "village perdu", "épave engloutie", "hôpital abandonné",
  "vieille prison", "ville souterraine", "catacombe", "voûte funéraire", "route", "ruelle obscure",
  "grenier", "labyrinthe", "chambre secrète", "gaine de cheminée", "cheminée", "sous l'escalier",
  "rez-de-chaussée", "abri", "passage voûté", "colonne", "contrefort", "poutre",
  "dans la crypte", "caveau", "monument", "miroir en pied",
];

export const TIME_WORDS: string[] = [
  "maintenant", "immédiatement", "après", "avant", "hier", "aujourd'hui",
  "minuit", "matin", "soir", "nuit", "point du jour", "éternité",
  "pour toujours", "le passé", "l'avenir", "siècle", "l'heure des sorcières", "au-delà",
  "éternel", "mortel", "première lueur", "solstice", "éclipse lunaire", "éclipse solaire",
  "croissant", "nouvelle lune", "lune de sang", "étoile filante", "Voie lactée", "constellation",
  "étoile Polaire", "nord", "sud", "est", "ouest", "direction",
  "horizon", "demain", "après-demain", "semaine", "mois", "année",
  "siècle", "un millénaire", "ère", "tournant des âges", "période", "instant",
  "seconde", "minute", "l'horloge", "en un clin d'œil", "premier", "dernier",
  "début", "fin", "le final", "naissance", "mort", "vie",
  "existence", "être", "printemps", "été", "automne", "hiver",
  "saison", "lundi", "mardi", "mercredi", "jeudi", "vendredi",
  "samedi", "dimanche", "jour de fête", "nuit sacrée", "veille",
];

export const ACTION_WORDS: string[] = [
  "viens", "va", "arrête", "attends", "cours", "fuis",
  "cache-toi", "regarde", "vois", "écoute", "entends", "touche",
  "ressens", "parle", "tais-toi", "chuchote", "crie", "pleure",
  "dors", "réveille-toi", "souviens-toi", "oublie", "tends la main", "ferme",
  "verrouille", "coupe", "brise", "brûle", "éteins", "meurs",
  "nais", "vis", "disparais", "apparais", "appelle", "trouve",
  "perds", "dissimule", "enterre", "entraîne vers le bas", "sors",
  "entre", "grimpe", "saute", "rêve", "rampe", "te glisses",
  "marche", "danse", "reviens", "tourne", "courbe", "tords",
  "frémis", "tremble", "vibres", "multiplie", "frappe", "griffe",
  "atteins", "traîne", "écrase", "lance", "dévore", "consume",
  "avale", "crache", "suffoque", "respire", "expire", "noie",
  "halète", "gémit", "sanglote", "crie", "geint", "pleurniche",
  "chuchote", "fredonne", "grogne", "grogne sourdement", "hurle", "suis",
  "surveille", "espionne", "guette", "attaque", "défends", "protège",
  "cherche refuge", "barre la porte", "tend un piège", "supplie", "saisit", "souhaite",
  "demande", "implore", "maudit", "damne", "jette un sort", "accomplit le rituel",
  "tient une séance", "confesse", "admet", "accepte", "nie", "refuse",
  "pardonne", "absout", "punit", "récompense", "reste", "aide",
  "monte la garde", "accomplit", "entre", "pars", "y fait face", "se dissout",
  "lie", "libère", "dissimule", "ne ris pas", "évoque", "poursuit",
  "apporte", "emporte", "sauve", "aide-moi", "libère-le", "retiens-le",
  "attrape", "ne lâche pas", "n'oublie pas", "dis-moi", "appelle à l'aide", "parle",
  "couvre", "scelle", "enferme", "démêle", "lie fermement", "sépare",
  "illumine", "plonge dans l'obscurité",
  "endure",
];

export const LONG_PHRASES: string[] = [
  "tu n'es pas seul ici ce soir", "quelqu'un vit derrière les murs", "je viens à la même heure chaque nuit", "je t'observe depuis longtemps", "cette maison a une histoire", "beaucoup de sang a été versé ici",
  "personne qui est venu ici n'en est jamais reparti vivant", "tu ne seras pas le dernier à venir", "fermer la porte à clé ne t'aidera pas", "je suis partout tout le temps", "quand tu fermes les yeux tu me verras", "je te rendrai visite dans tes rêves",
  "reste éveillé car je le suis", "ne dors pas cette nuit, ne dors pas", "tu entends tes propres pas", "l'ombre derrière toi n'est pas la mienne", "regarde dans le miroir et tu me verras", "je suis la voix qui vient du plafond",
  "il y a quelque chose dans la cave", "quelqu'un marche sur le toit", "j'ai vu une ombre dans le jardin", "quelqu'un regarde par la fenêtre", "la porte s'est ouverte toute seule", "les lumières clignotent",
  "l'horloge s'est arrêtée à trois heures du matin", "le miroir s'est brisé tout seul", "du sang suinte du mur", "des bruits montent de sous la terre", "ce n'est pas de l'eau — c'est du sang qui coule du plafond", "la silhouette dans la photo a bougé",
  "la poupée a souri", "quelqu'un descend l'escalier", "quelqu'un se tient à l'autre bout du couloir", "des mains émergent de sous le lit", "quelqu'un respire dans l'armoire", "il y a une silhouette derrière le rideau",
  "des yeux brillent dans l'obscurité", "le tableau sur le mur te regarde", "ton horloge a cessé de battre", "le téléphone a sonné mais il n'y avait personne", "des sons étranges viennent de la radio", "la télévision s'est allumée toute seule",
  "un visage est apparu sur l'écran d'ordinateur", "du sang coule du robinet", "je ne me reflète pas dans le miroir", "mon ombre bouge indépendamment de moi", "c'est l'endroit que j'ai vu dans mes rêves", "j'ai déjà été ici",
  "j'ai déjà vécu cet instant", "je suis pris dans une boucle temporelle", "il n'y a pas d'issue d'ici", "portes fermées à clé, fenêtres scellées", "les murs ont commencé à se refermer", "le plafond descend",
  "le plancher cède", "l'air devient plus froid", "je peux voir mon souffle", "quelque chose a touché ma jambe", "on m'a tiré les cheveux", "quelque chose a chuchoté à mon oreille",
  "j'ai senti un souffle froid dans la nuque", "une main a touché mon épaule", "quelqu'un me pousse par derrière", "mon pied a accroché quelque chose d'invisible", "quelque chose a bougé dans l'obscurité", "une ombre est apparue dans le coin puis a disparu",
  "ce n'est pas de la poussière qui tombe du plafond — c'est de la cendre", "l'horloge sur le mur tourne à l'envers", "une autre pièce apparaît dans le miroir", "le bas de l'escalier s'ouvre sur l'obscurité", "ce couloir n'a pas de fin", "chaque fois que j'ouvre la porte je suis dans la même pièce",
  "je ne vois rien par la fenêtre", "dehors il n'y a rien — que l'obscurité", "quelqu'un a été pendu dans cette pièce", "un corps est enterré sous le lit", "il y a des os dans les murs", "cette maison a été construite sur un cimetière",
  "la nuit des bruits viennent de l'intérieur des murs", "des choses étranges se produisent à chaque pleine lune", "les voisins évitent cette maison", "tous ceux qui ont vécu ici sont devenus fous", "le dernier locataire a disparu", "même la police ne rentre pas dans cette maison",
  "même l'imam n'a pas pu purifier cet endroit", "le prêtre est venu — et il s'est enfui", "les rituels qui se tiennent ici se poursuivent encore", "des cris se font entendre à trois heures du matin", "les enfants ne passent jamais devant cette maison", "les chats ne s'approchent jamais de cette maison",
  "les chiens hurlent devant cette maison", "les oiseaux ne volent jamais au-dessus de cette maison", "les arbres autour de cette maison meurent", "aucune fleur ne fleurit dans ce jardin", "la lumière du soleil ne pénètre jamais dans cette maison", "l'horloge s'arrête à trois heures chaque nuit",
  "les miroirs se fissures tout seuls", "les bougies s'allument toutes seules", "les portes s'ouvrent et se ferment d'elles-mêmes", "la chaise se déplace sans aide", "les yeux des tableaux te suivent", "la tache sur le mur grandit chaque jour",
  "la fissure dans le plafond ressemble à un visage", "la tache de sang sur le sol ne peut pas être effacée", "l'air dans cette pièce est toujours froid", "les appareils électroniques tombent en panne ici", "ta batterie de téléphone se vide en quelques secondes ici", "la boussole s'affole ici",
  "les horloges affichent la mauvaise heure ici", "les caméras ne fonctionnent pas ici", "des formes étranges apparaissent dans les photos prises ici", "il y a quelqu'un dans les vidéos qui ne devrait pas être là", "les enregistrements audio contiennent des chuchotements", "le détecteur EMF devient fou ici",
  "la température chute sans prévenir", "il y a une odeur étrange dans l'air", "odeur d'humidité — mais pas de moisissure", "odeur de brûlé — mais pas de feu", "parfum de fleurs — mais pas de fleurs", "odeur de parfum — mais personne n'est là",
];

export const MANIPULATIVE_RESPONSES: string[] = [
  "oui", "non", "peut-être", "c'est possible", "jamais", "certainement",
  "probablement", "j'en doute", "je ne suis pas sûr", "vrai", "faux", "en partie",
  "parfois", "toujours", "jamais", "rarement", "souvent", "généralement",
  "regarde à droite", "regarde à gauche", "regarde en haut", "regarde en bas", "regarde derrière toi", "regarde devant",
  "regarde autour de toi", "regarde le mur", "va vers la porte", "va vers la fenêtre", "va dans la cave", "va dans le grenier",
  "sors", "entre", "approche-toi", "éloigne-toi", "un pas de plus", "mon âge était",
  "je suis mort ici", "j'ai vécu ici", "je suis là depuis longtemps", "j'ai attendu cent ans", "je t'attendais", "tu devais venir",
  "destin", "n'aie pas peur", "tu devrais avoir peur", "tu n'es pas en danger", "tu es en danger", "tu es en sécurité",
  "tu n'es pas en sécurité", "tu n'es pas seul", "tu es tout à fait seul", "tu es aimé", "tu n'es pas aimé", "on t'a oublié",
  "on se souvient de toi", "le moment viendra", "sois patient", "attends", "sois prêt", "tu comprendras bientôt",
  "tout sera révélé", "cela restera un secret", "je ne peux pas le dire", "c'est interdit", "il n'y a pas de permission", "il y a une limite",
  "derrière toi", "à côté de toi", "au-dessus", "j'en ai été témoin", "tu l'as entendu", "qui se rapproche",
  "toucher", "un scandale", "un incident", "une âme perdue", "nous", "ils",
  "personne", "un visiteur", "quelque chose ici", "ça appartient ici", "détenu en garde", "vieux",
  "je sais", "tu l'as vu", "je l'ai caché", "était ici", "ils sont partis", "réveillé",
  "endormi", "profondément à l'intérieur", "très loin", "ton nom", "je l'ai enterré", "je l'ai pris",
  "je l'ai perdu", "je l'ai trouvé", "je cherche", "j'arrive", "je pars", "je suis resté",
  "je suis mort", "je suis vivant", "bientôt", "juste derrière toi", "à ta droite", "à ta gauche",
  "au-dessus", "entre", "à l'intérieur", "au-delà", "sur la rive proche", "en face",
  "au seuil", "qui es-tu", "comment t'appelles-tu", "que veux-tu", "pourquoi es-tu ici", "combien êtes-vous",
  "quand es-tu venu", "comment es-tu mort", "tu nous entends", "tu veux de l'aide", "on devrait partir",
];

export const DIALOG_PHRASES: string[] = [
  "bonjour", "salutations", "bienvenue", "je t'attendais", "tu es enfin venu", "tu es en retard",
  "où étais-tu", "cet endroit m'appartient", "je suis l'âme de cette maison", "je suis mort ici", "je suis enterré ici", "je ne peux pas te dire mon nom",
  "j'ai oublié mon nom", "plus aucun pas", "je n'ai jamais vraiment existé", "je suis un souvenir", "je suis un écho", "quitte cet endroit maintenant",
  "ne reste pas ici cette nuit", "pars avant que le soleil se couche", "pars avant que l'obscurité tombe", "pars avant minuit", "pars avant trois heures", "ne rentre plus dans cette pièce",
  "n'ouvre plus cette porte", "ne regarde plus dans ce miroir", "ne prononce plus ce nom", "une famille vivait autrefois ici", "cette maison a été construite il y a cent ans", "il y a eu un incendie ici autrefois",
  "un meurtre a été commis ici", "un enfant s'est perdu ici", "une femme s'est donné la mort ici", "un homme est devenu fou ici", "un rituel a eu lieu ici", "un trésor est enterré ici",
  "une malédiction a commencé ici", "je vais te garder ici", "tu ne partiras jamais", "tu resteras avec moi", "ici pour toujours", "il n'y a pas d'échappatoire",
  "pas de sortie", "il n'y a pas de salut", "la prière ne t'aidera pas", "personne ne peut te sauver", "crie tant que tu veux — personne n'entendra", "s'il te plaît ne pars pas",
  "ne me laisse pas seul", "je me sens si désespérément seul", "personne ne vient jamais", "j'attends depuis des années", "des siècles seul", "j'ai besoin d'un compagnon",
  "je veux parler à quelqu'un", "tu es la première personne à entendre ma voix", "tu es le premier à me voir",
];

export const WHISPER_PHRASES: string[] = [
  "pssst", "hé", "regarde-moi", "par ici", "entends-moi", "vois-moi",
  "sens-moi", "touche-moi", "approche-toi", "approche encore un peu", "prête-moi ton oreille", "chut",
  "reste tranquille", "personne ne doit entendre", "tourne-toi lentement", "regarde lentement", "j'ai un secret", "je vais te dire quelque chose",
  "n'en parle à personne", "garde ça entre nous", "ce secret", "je t'ai choisi", "tu es quelqu'un de spécial", "tu es différent",
  "tu es différent des autres", "je te comprends", "tu es le seul qui me comprend", "nous avons un lien", "tes yeux voient des choses que les autres ne peuvent pas", "tu peux me sentir",
  "les autres ne peuvent pas entendre — mais toi tu peux", "notre destin est un", "nous sommes liés l'un à l'autre", "tu ne peux pas éviter cela", "c'est écrit", "c'est le destin",
  "tout arrive pour une raison", "rien n'est une coïncidence", "je voulais que tu viennes ici", "je t'ai appelé", "mon invitation a été acceptée", "bienvenue chez moi",
  "je t'ai attendu si longtemps", "tu es venu exactement au bon moment", "tu es là maintenant", "tu m'appartiens maintenant", "je ne te laisserai pas partir", "pour toujours",
  "nous serons ensemble", "nous ne nous séparerons jamais", "tu es mon dernier invité", "personne n'a jamais quitté cet endroit", "tu vas te perdre dans cette maison", "je te verrai dans tes rêves",
  "je viendrai à toi pendant ton sommeil", "je suis là dans la nuit", "je vis dans l'obscurité", "la lumière me fait peur", "le soleil me brûle", "la nuit est mon heure",
  "l'obscurité est ma demeure", "je deviens plus fort après le coucher du soleil", "je suis le plus puissant à trois heures du matin", "je disparaîtrai à l'aube — mais j'attendrai la nuit", "je connais ton nom", "je sais où tu habites",
  "je connais ta famille", "je connais ton passé", "je sais ce que tu crains", "je connais tes rêves", "j'étais dans ton rêve la nuit dernière", "tu ne t'es pas réveillé brusquement la nuit",
  "c'était moi — ce sentiment étrange", "fais attention ce soir", "tu n'es pas en sécurité", "reste avec quelqu'un", "ne dors pas seul", "n'éteins pas la lampe",
  "ferme la porte à clé", "ne laisse pas la fenêtre ouverte", "tire les rideaux", "tu as entendu ça tout à l'heure", "c'est juste derrière toi maintenant", "ne reviens pas encore",
];

export const MYTHOLOGY_WORDS: string[] = [
  "al-karı", "terreur nocturne", "croquemitaine", "goule", "géant", "glouton",
  "albastı", "koncolos", "tepegöz", "basilic", "Hıdırellez", "Norouz",
  "Ergenekon", "le Loup Gris", "Asena", "la Montagne des Têtes", "l'Arbre Tuba", "l'Eau de la Vie",
  "l'Eau de l'Immortalité", "phénix", "oiseau de feu", "simurgh", "le cheval du vent", "la fée du vent",
  "nymphe", "esprit de la montagne", "dryade", "le mauvais œil", "le regard maléfique", "le sort",
  "possédé", "loup-garou", "chouette de nuit", "le cri de la chouette", "chat noir", "les quarante marches",
  "esprit de la sage-femme", "spectre accordant les vœux", "l'arbre des vœux", "le puits des vœux", "le lieu du sacrifice", "terrassé",
  "saint", "homme saint", "ancien", "pir", "patriarche", "le hoca",
  "enchanteresse", "la grand-mère diseuse de bonne aventure", "trésor caché", "un enterrement", "trésor", "le cube d'or",
  "le trésor maudit", "le djinn gardien", "le gardien du trésor", "la porte talismanique", "le miroir enchanté", "le tapis volant",
  "invisibilité", "immortalité", "l'élixir de jouvence", "la laveuse de morts", "linceul", "la pierre du musalla",
  "corbillard", "pierre tombale", "tête de mort", "pierre de pied", "sarcophage", "cercueil de pierre",
  "mausolée", "cage", "turbe", "fosse commune", "la tombe perdue", "la tombe sans nom",
  "le cimetière de minuit", "le cimetière abandonné",
];

export const FOLK_BELIEFS: string[] = [
  "perle du mauvais œil", "amulette écrite", "plombée fondue", "brûler de l'encens", "faire un vœu", "ne fais pas ce vœu",
  "interprétation des rêves", "divination", "lecture du marc de café", "lecture de la paume", "horoscope", "divination par l'eau",
  "magie des miroirs", "magie des bougies", "magie des cordes", "sort de liaison", "sort de séparation", "sort d'amour",
  "magie noire", "magie blanche", "magie des djinns", "guérisseur", "djinn", "fabricant d'amulettes",
  "sorcier", "enchanteur", "conjurateur", "illusionniste", "nécromancie", "toucher le verre",
  "tenir le crayon", "faire tourner la table", "planche ouija", "planche des esprits", "n'invite pas un djinn", "exorcisme",
  "ne lie pas le djinn", "incantation", "afsun", "récitation", "souffler le charme", "ne respire pas",
  "divination par l'eau", "guérison par la foi", "le regard", "le toucher maléfique", "l'affliction de la langue", "esprit malveillant",
  "esprit bienveillant", "esprit gardien", "esprit ancestral", "esprit du grand-père", "esprit de la grand-mère", "esprit de la maison",
  "djinn du hammam", "djinn de l'eau", "djinn du feu", "esprit de la terre", "djinn de la météo", "djinn musulman",
  "djinn infidèle", "djinn amoureux",
];

export const HORROR_STORY_WORDS: string[] = [
  "sursaut d'effroi", "terreur montante", "horreur", "épouvante", "panique", "fuite",
  "la poursuite", "l'embuscade", "le piège", "le traquenard", "le sacrifice", "le chasseur",
  "la proie", "la traque", "l'ombre", "une porte qui grince", "bois qui craque", "feuilles qui bruissent",
  "le vent qui hurle", "un tuyau qui siffle", "verre qui tremble", "bourdonnement dans les oreilles", "tête qui bat", "main qui tremble",
  "un cri étouffé", "une voix coupée net", "sang qui se glace", "cheveux qui se dressent", "peau de poule", "peau qui frissonne",
  "cœur qui bat la chamade", "sueur froide", "un frémissement", "une convulsion", "ne pas pouvoir respirer", "qui vacille",
  "nausée", "vue brouillée", "acouphènes", "engourdissement", "ne te paralyse pas", "ne te fige pas",
  "pétrifié", "lévitation", "télékinésie", "combustion spontanée", "métamorphose", "saut dimensionnel",
  "voyage dans le temps", "séparation de l'âme", "expérience de mort imminente", "voyage astral", "transfert de conscience", "contrôle de l'esprit",
  "hypnose", "hystérie collective", "hallucination collective", "le miroir maudit", "la poupée maudite", "la bague maudite",
  "le livre maudit", "le portrait maudit", "le bijou maudit", "le poignard maudit", "la couronne maudite", "le coffre maudit",
  "la carte maudite", "la boussole maudite", "l'horloge maudite",
];

export const CURSES: string[] = [
  "sois maudit", "à bas toi", "que tu sois effacé", "tu rencontreras ta punition", "tu devras rendre des comptes", "tu paieras le prix",
  "tu regretteras", "je n'oublierai pas", "je ne pardonnerai pas", "il n'y a pas de pardon", "j'aurai ma vengeance", "on réglera ça",
  "ce n'est pas fini", "c'est loin d'être fini", "ce n'est que le début", "tu verras", "tu finiras par comprendre", "tu le ressentiras",
  "tu souffriras", "tu pleureras", "tu supplieras", "supplier ne servira à rien", "personne ne peut t'aider", "il n'y a pas d'échappatoire",
  "il n'y a pas de salut", "ça ne finira jamais", "cette malédiction ne peut être levée", "ce sort ne peut être brisé", "cette chaîne ne peut être coupée", "ce lien ne peut être défait",
  "ça durera sept générations", "ça durera quarante jours", "ça durera pour toujours", "ça continuera sans fin", "ces terres sont maudites", "cette maison est maudite",
  "cette famille porte la malédiction", "ce sang est maudit", "chaque enfant né ici est maudit", "chaque génération est marquée", "la malédiction t'a été transmise", "elle t'appartient maintenant",
  "tu porteras ce fardeau", "et après toi, tes enfants",
];

export const DREAM_WORDS: string[] = [
  "rêve", "cauchemar", "rêve éveillé", "vision", "prophétie", "présage",
  "pressentiment", "intuition", "instinct", "le sixième sens", "le subconscient", "l'inconscient",
  "transe", "hypnose", "méditation", "paralysie du sommeil", "un rêve lucide", "en proie à un cauchemar",
  "voler en rêve", "tomber en rêve", "courir en rêve", "fuir en rêve", "être poursuivi en rêve", "voir les morts en rêve",
  "voir du sang en rêve", "voir un serpent en rêve", "voir une araignée en rêve", "voir de l'eau en rêve", "voir du feu en rêve", "voir une maison en rêve",
  "voir une tombe en rêve", "voir un miroir en rêve", "voir une porte en rêve", "voir un escalier en rêve", "voir un couloir en rêve", "voir l'obscurité en rêve",
  "voir la lumière en rêve", "entendre une voix en rêve", "entendre un chuchotement en rêve", "entendre des cris en rêve", "entendre de la musique en rêve", "voir quelqu'un en rêve",
  "un étranger dans le rêve", "une ombre dans le rêve", "un visage dans le rêve", "un œil dans le rêve",
];

export const RESEARCH_JARGON: string[] = [
  "anomalie détectée", "le champ énergétique a changé", "surge électromagnétique", "anomalie de température", "anomalie vocale", "anomalie visuelle",
  "collecte de données", "analyse de preuves", "investigation de scène de crime", "déclaration de témoin", "témoin oculaire", "information de première main",
  "source secondaire", "archive", "document historique", "analyse de fréquence", "analyse de spectre", "longueur d'onde",
  "infrarouge", "ultraviolet", "image thermique", "vision nocturne", "infrarouge complet", "spectre complet",
  "scan SLS", "lecture EMF", "capture EVP", "session spirit box", "balayage ghost box", "REM pod",
  "K-II mètre", "Mel mètre", "Trifield mètre", "thermomètre numérique", "grille laser", "capteur de mouvement",
  "capteur de vibrations", "capteur de pression", "capteur d'humidité", "session de contrôle", "tentative de provocation", "veille silencieuse",
  "session questions-réponses", "session ouverte", "lecture de référence", "valeur de référence", "lecture anormale", "valeur de pointe",
  "valeur moyenne",
];
