// English word bank for VOX — auto-generated parallel to word-bank.ts (Turkish).
// Do not hand-edit category arrays; structure mirrors lib/word-bank.ts exactly.

export const NINE_PHRASES: string[] = [
  "my baby", "my grandchild", "dear", "my child", "my baby", "my little lamb",
  "my liver", "the light of my eyes", "corner of my heart", "come to me", "where are you baby", "I miss you",
  "don't go away from me", "I'm waiting with longing", "I think of you every night", "I want to hear your voice", "Let me see your face once again", "You came in my dream but I woke up",
  "why don't you come", "can you hear me", "it's cold here", "no light", "very dark", "I'm still here",
  "don't forget me", "My grave is deserted", "no one is coming", "I was left alone", "It's been a long time", "Was this how to die?",
  "I'm waiting for you", "come one day", "take me from here", "cold earth", "dark earth", "I went cold under the stone",
  "no one knows I'm here", "It's very difficult here", "I can't go anyway", "I'm tied to this world", "I'm still waiting", "I can hear you but I can't see you",
  "Your voices are coming but they are far away", "oh boy", "good luck", "Allah bless", "pray", "pray",
  "there are bad guys", "be careful my baby", "do not go astray", "be true", "live honorably", "respect elders",
  "call a relative and ask", "escape from sin", "repent", "earn halal", "love each other", "There will be no conflict",
  "bad dreams", "I cry at night", "I can't see the morning", "That dark being followed me here", "I saw something before I died", "There's something I need to tell you",
  "There's a secret under the house", "Sounds coming from under the ground", "I will knock on the door at midnight", "I will come to visit you in your dreams", "you will see me in your sleep", "I'll be there when your eyes close",
  "I wish we had spent more time", "I want to say what I can't say", "forgive me baby", "I made mistakes too", "I would like to go back to the past", "I wish I had told you in time",
  "I left too early", "I wasn't ready", "I didn't want to leave you", "I'm between this world and the next world", "I will come when the gate opens", "You can hear me during the lunar eclipse",
  "I'm stronger on Friday nights", "I sit in the cemetery and cry", "The people next to me also want to see you", "This place is crowded but it's all quiet", "I run when I see the light but I can't catch up", "one day you will understand too",
];

export const GIRL_CHILD_PHRASES: string[] = [
  "will you play with me", "I don't want to be alone", "Why doesn't anyone play with me?", "I lost my baby", "where are my toys", "I want to go home",
  "where is my mother", "where is my father", "Are they waiting for me", "I don't want to cry but I'm crying", "no one sees me", "Am I invisible?",
  "Is there no one here", "I'm alone here", "I want a friend", "can i play with you", "I'm afraid", "why is it dark",
  "Can you turn on the light?", "I saw something", "he came again", "comes every night", "that bad guy came again", "touched me",
  "He leaves when he shouts.", "I close my eyes", "I started counting from one hundred to one", "there is someone behind me", "do you see him", "he sees you too",
  "don't come here", "it's dangerous here", "it follows you too", "left me here", "why did they leave me", "the walls are talking",
  "someone is looking out the window", "I'm not the one in the mirror", "my shadow moves separately", "There are sounds coming from the ceiling", "There is someone on the stairs, I consider the footsteps", "My dog sees something in the corner",
  "My cat ran away from the room", "The flowers faded after I entered", "The clock stopped at that exact moment", "my mother is calling", "slowly", "huh",
  "no no no", "stop stop stop", "I don't want I don't want", "I can see it too", "I got cold", "don't leave me",
  "hug me please", "hold my hand", "don't leave me", "I go somewhere while I sleep", "This is also in my dream", "I'm tired when I wake up",
  "what happens at night", "Do you see strange things at night too?", "there are eyes in the dark", "they are waiting", "I stayed here too long", "I want to go out now",
  "take me please", "I want to go towards the light", "I can't go through that door", "something is blocking", "What is your name?", "can i trust you",
  "don't cry, i'll cry too", "go away for your own good",
];

export const PHANTOM_PHRASES: string[] = [
  "I'm here", "can you hear me", "help", "I can't go out", "we are trapped", "leave us",
  "go from there", "you are in danger", "he is coming", "run away", "you are all in danger", "do you hear",
  "I was also like you", "it's too late now", "don't go", "This house has a secret", "I'm inside the walls", "listen to me",
  "they are real", "no one believed me", "now you understand", "this is hell", "I'm lost in the dark", "give me voice",
  "There's a room under the floor", "I know the secret door", "Do not open the chest in the basement", "Do you know what's behind the wall?", "The old owner is still here", "This house carries a hundred-year-old secret",
  "Someone is crying in the cellar", "There are footsteps on the roof", "adjust frequency", "my signal is weak", "the connection is losing", "I'm far away",
  "I can hear you", "don't come there", "channel is open", "I'm taking you", "I'm trying to communicate", "too much static",
  "frequency is shifting", "change band", "pass the noise you will hear me", "need amplification", "sound wave breaks", "interdimensional interference",
  "don't look back", "close the door", "don't turn off the lights", "don't be alone", "don't break up the group", "There is a powerful presence",
  "negative energy is very intense", "the area is contaminated", "needs to be cleaned", "save this", "look at the camera", "there is something to your left",
  "Be careful as the temperature drops", "can you breathe", "I'm talking from far away", "My voice barely reaches you", "energy is running out", "I'm talking with all my strength",
  "be quiet to hear me", "stop breathing for a second", "I can be heard in complete silence", "I whisper because they don't hear", "keep it between us", "others should not know",
  "I am calling you specifically", "you were chosen for this task", "Someone special came tonight", "There is a sensitive person among you", "one is open here spiritually", "find him among us",
];

export const HOME_OBJECT_PHRASES: string[] = [
  "look at the seat next to you", "I saw the left seat", "there is someone behind the seat", "I'm sitting on the couch right now", "I was sitting in your chair", "that empty seat is filled",
  "check under the sofa", "There's a coldness next to the seat", "don't touch the seat yet", "open the third drawer", "I hid something in the top drawer", "You'll find me in the bottom drawer",
  "close that drawer", "The closet door will remain open tonight", "There's someone in the wardrobe", "open the drawers one by one", "stay in the last drawer", "lock the closet before night",
  "don't look under your bed", "There's something under your pillow", "I'm sitting on the edge of the bed", "Look at your pillow when you wake up in the morning", "stop sleeping in bed tonight", "I got under the duvet cover",
  "If your bed seems to collapse at night, I'm the one", "I look at your face while you sleep", "look in the mirror carefully", "There are two faces in your mirror right now", "I'm on the other side of the mirror", "cover the mirror at night",
  "look out the window", "I press my face against the window glass", "Have you ever opened your curtains and looked at night?", "look at the fog on the glass", "don't open the window tonight", "I enter through the blinds",
  "Did you see a shadow pass under the door?", "Did you lock the door?", "someone is walking in the corridor", "door handle turns slowly", "I'm waiting in front of the door", "I can enter without ringing the bell",
  "Don't open that door", "me when the door creaks", "Did you hear something fall in the kitchen?", "I act like a tap drips", "The sound of the refrigerator has changed, be careful", "Are you sure you turned off the stove?",
  "Are kitchen knives numbered individually?", "look at the glass shelf", "There's someone under the kitchen table", "I just moved your pot", "I'm next to you while you're taking a shower in the bathroom", "I'm writing on the steam in your mirror",
  "I'm waiting behind the shower curtain", "It's not enough to lock the bathroom", "I see you filling the bathtub", "The toilet door will remain wide open", "The seventh rung on the stairs will soon crack", "I hear the voice from the first floor",
  "There is someone upstairs", "I'm hanging from the stairwell", "Did you hear the doorbell downstairs?", "Don't run away from the stairs, I can't hold you back", "I will turn off the light bulb soon", "the light will blink three times",
  "watch the lamp tonight", "go to electrical panel", "That lamp in the corner is my signal", "If you pull the plug you won't find me", "Have you noticed that your wall clock has stopped?", "The clock will ring at three in the morning",
  "I crossed that day on the calendar", "The minute hand of the clock is moving backwards", "I know your birthday is coming", "The darkest corner of the house is my place", "look at the bottom right corner of the room", "I'm sitting next to the left wall",
  "Look at where the ceiling meets the wall.", "There's a secret under that stain", "pull out the carpet and take a look", "The eyes of that painting are my eyes", "Have you seen the one in the photo frame up close?",
];

export const PHONEMES: string[] = [
  "a", "e", "i", "o", "u", "ö",
  "ü", "ı", "ba", "be", "bi", "bo",
  "bu", "bö", "bü", "ca", "ce", "ci",
  "co", "cu", "da", "de", "di", "do",
  "du", "dö", "dü", "fa", "fe", "fi",
  "fo", "fu", "ga", "ge", "gi", "go",
  "gu", "gö", "gü", "ha", "he", "hi",
  "ho", "hu", "ka", "ke", "ki", "ko",
  "ku", "kö", "kü", "la", "le", "li",
  "lo", "lu", "lö", "lü", "ma", "me",
  "mi", "mo", "mu", "mö", "mü", "na",
  "ne", "ni", "no", "nu", "nö", "nü",
  "pa", "pe", "pi", "po", "pu", "ra",
  "re", "ri", "ro", "ru", "rö", "rü",
  "sa", "se", "si", "so", "su", "sö",
  "sü", "ta", "te", "ti", "to", "tu",
  "tö", "tü", "va", "ve", "vi", "vo",
  "vu", "ya", "ye", "yi", "yo", "yu",
  "yö", "yü", "za", "ze", "zi", "zo",
  "zu", "şa", "şe", "şi", "şo", "şu",
  "ça", "çe", "çi", "ço", "çu", "br",
  "kr", "tr", "gr", "pr", "fr", "dr",
  "st", "sk", "sp", "sl", "sm", "sn",
  "ah", "oh", "uh", "eh", "ih", "ay",
  "ey", "oy", "öy", "üy", "aa", "ee",
  "ii", "oo", "uu", "öö", "üü",
];

export const DARK_WORDS: string[] = [
  "death", "soul", "dark", "shadow", "damn", "fear",
  "horror", "hell", "grave", "grave", "coffin", "funeral",
  "dead", "ghost", "genie", "devil", "demon", "demon",
  "ghost", "vampire", "zombie", "skeleton", "skull", "blood",
  "pain", "scream", "wail", "moan", "whisper", "silence",
  "sound", "footstep", "thunder", "coldness", "they entered", "you are contrary",
  "time-variance", "outcome", "motive", "from the unknown", "manifestation", "mirage",
  "spiral", "shadowed", "whisper-line", "cold-wave", "frequency-shift", "static",
  "acoustic", "déjà vu", "vision", "silhouette", "broken", "abandoned",
  "locked", "night", "moon", "full moon", "cloud", "fog",
  "smoke", "haze", "gloom", "loneliness", "abandon", "lost",
  "forgotten", "prisoner", "captive", "captive", "chain", "lock",
  "key", "door", "window", "mirror", "reflection", "mystery",
  "secret", "magic", "talisman", "amulet", "evil eye", "unlucky",
  "black", "black", "dark", "deep", "space", "cliff",
  "well", "underground", "basement", "cellar", "tunnel", "cave",
  "dungeon", "prison", "bone", "meat", "leather", "wound",
  "trace", "stain", "rust", "mold", "spider", "network",
  "insect", "snake", "bat", "crow", "owl", "Kurd",
  "fox", "jackal", "hyena", "vulture", "scorpion", "mouse",
  "fire", "flame", "ash", "powder", "soil", "mud",
  "swamp", "storm", "lightning", "thunder", "earthquake", "flood",
  "tsunami", "plague", "epidemic", "illness", "poison", "potion",
  "witch", "magician", "fortune teller", "medium", "soothsayer", "shaman",
  "priest", "ritual", "ritual", "sacrifice", "votive", "curse",
  "black magic", "pentagram", "symbol", "sign", "inscription", "rune",
  "portal", "passage", "size", "parallel", "the other side", "afterlife",
  "afterlife", "isthmus", "purgatory", "sirat", "trial balance", "grim reaper",
  "angel", "demon", "entity", "cold", "ice", "frost",
  "tremor", "chill", "feathers", "thorn", "breath", "pale",
  "wheezing", "grunt", "hum", "buzz", "squeak", "click",
  "crackle", "rustle", "clink", "sizzle", "haunted", "haunt",
  "conjoined", "follower", "shadow man", "black mass", "white shadow", "ball of light",
  "orb", "ectoplasm", "poltergeist", "ouija", "wood", "candle",
  "incense", "crystal", "globe", "conjuring", "session", "mediumship",
  "parapsychology", "telepathy", "premonition", "prophecy", "nightmare", "sleepwalking",
  "trans", "hypnosis", "subconscious", "astral", "projection", "transmigration",
  "reincarnation", "mixed", "aura", "energy", "vibration", "frequency",
  "wave", "signal", "parasite", "noise", "disaster", "destruction",
  "apocalypse", "apocalypse", "last", "chaos", "mess", "uncertainty",
  "danger", "threat", "warning", "execution", "gallows", "executioner",
  "execution", "torture", "grind", "decay", "distortion", "disintegration",
  "extinction", "deletion", "forgetting", "don't get lost", "melting", "extinction",
  "darkening", "drowning", "burning", "freezing", "fall", "sinking",
  "trap", "ambush", "conspiracy", "intrigue", "cheat", "betrayal",
  "deception", "lie", "fake", "fake", "fiction", "dream",
  "delusion", "hallucination", "illusion", "swirl", "eddy", "hurricane",
  "hose", "avalanche", "landslide", "dent", "collapse", "cleavage",
  "crack", "cliff", "bottom", "depth", "dark hole", "space",
  "nothingness", "absence", "eternity", "eternity", "stasis", "rotten",
  "stinky", "stinky", "stale", "dead", "faded", "dried up",
  "burnt", "broken", "shattered", "crushed", "forgotten", "abandoned",
  "damned", "condemned", "take wife", "nightmare", "bogey", "ghoul",
  "giant", "glutton", "witch", "albasti", "concolos", "overhead projector",
  "basilisk", "dragon", "simurgh", "phoenix", "phoenix", "telekinesis",
  "levitation", "apportion", "bilocation", "clervoyance", "precognition", "retrocognition",
  "psychometry", "otoscopy", "doppelganger", "phenomenon", "anomaly", "deviation",
  "disorder", "disorder", "dim", "dark", "hazy", "foggy",
  "cloudy", "rainy", "stormy", "windy", "cold", "freezer",
  "overwhelming", "suffocating", "boring", "haunted", "scary", "creepy",
  "creepy", "scary", "terrifying", "scary", "mysterious", "mysterious",
  "incomprehensible", "inexplicable", "supernatural", "extraordinary", "unusual", "strange",
  "weird", "weird", "unusual", "unexpected", "sudden", "unaware",
  "secret", "reserved", "veiled", "masked", "disguised", "hidden",
  "seclusion", "derelict", "ghost", "pitch black", "enigma", "talisman",
  "abjad", "remil", "reproach", "manifestation", "finally", "lesson",
  "will", "transfer", "oppression", "discord", "surrounding", "entente",
  "retreat", "sad", "magical", "mysterious", "mortality", "perception",
  "profiteer", "delirium", "delirium", "heedlessness", "sign", "apparent",
  "inward", "contagion", "infecting", "your fate", "destiny", "destiny",
  "ordeal", "wailing", "sayha", "reverberation", "sounds", "voices-from-the-secret",
  "otherwise", "reflection", "flow", "shadowing", "illusion", "silhouette",
  "dark-silhouette", "white-shadow", "hazy-image", "cosmos", "dimensional", "temporal",
  "spatial", "universal",
];

export const DARK_PHRASES: string[] = [
  "come here", "hear me", "help me", "don't leave me", "don't go", "I'm here",
  "I see you", "look behind you", "be careful", "how many", "i died", "find me",
  "save me", "I'm in pain", "I'm alone", "who is there", "who are you", "what do you want",
  "why did you come", "why are you here", "what are you looking for", "who are you looking for", "go away", "go out",
  "get out", "my house", "my place", "I'm watching you", "I'm everywhere", "you can't escape",
  "I will find you", "I'm after you", "you can't escape", "come back", "come again", "don't forget me",
  "remember", "promise", "yes", "no", "maybe", "I don't know",
  "I can't say", "midnight", "dawn", "twilight", "full moon night", "three o'clock",
  "devil hour", "dark hour", "open the door", "close the window", "turn off the light", "light the candle",
  "pray", "curse", "damn it", "mother", "father", "child",
  "baby", "old man", "old woman", "love", "hate", "revenge",
  "anger", "jealousy", "betrayal", "murder", "accident", "disaster",
  "tragedy", "fate", "time", "eternity", "eternity", "past",
  "future", "now", "here", "there", "above", "below",
  "inside", "outside", "be quiet", "listen", "hear me", "talk to me",
  "reply", "this house", "this room", "this place", "this place is cursed", "this is mine",
  "forgive me", "hurry up", "time is short", "your last chance", "don't sleep", "don't wake up",
  "dream", "nightmare", "bad dream", "don't disturb me", "leave alone", "don't touch me",
  "cold", "very cold", "ice cold", "I'm freezing", "pain", "very painful",
  "I can't stand it", "let it end now", "why", "why", "how", "when",
  "where", "third floor", "basement", "roof", "corridor", "under the stairs",
  "mirror", "look in the mirror", "reflection", "inside out", "at three in the morning", "turn around",
  "don't look", "close your eyes", "hold your breath", "smell of blood", "musty smell", "burning smell",
  "rotten", "footsteps", "door squeak", "glass breaking", "scream sound", "there is someone",
  "behind me", "next to me", "on me", "under me", "I'm watching", "I'm waiting",
  "I am patient", "I have time", "death is near", "last night", "farewell", "goodbye",
  "goodbye", "I know you", "I know your name", "I know your past", "I know your secret", "I know your fear",
  "I know your weak spot", "I was waiting for you", "I knew you would come", "I'm ready", "I want to talk to you", "listen to me",
  "I will say something important", "don't trust", "don't trust anyone", "you are alone", "there is no one", "your friends are lying",
  "they don't like you", "they are using you", "you will die soon", "your time is running out", "your clock is ticking", "I'm counting your last breath",
  "Your grave is ready", "The coffin is waiting", "funeral prayer", "burial", "earth is cold", "dark cold",
  "This house has a history", "someone died here", "blood was shed", "the walls remember", "under the ground", "buried",
  "reserved", "secret room", "secret passage", "behind the wall", "above the ceiling", "I want to play",
  "be my friend", "let's play hide and seek", "you found me", "it's your turn", "chase me", "you can't catch",
  "where is my mother", "where is my father", "I want to go home", "I'm lost", "I can't find my way", "I'm afraid of the dark",
  "I am very old", "I'm tired", "I want to rest", "I don't remember", "I forgot who I am", "where am I",
  "how much time has passed", "it's been years", "It's been centuries", "I'm still here", "I can't go", "I can't let go",
  "i'm tied", "I feel like I'm chained", "I'm not free", "get out of here", "this is my place", "you trespassed",
  "I will punish", "you will regret it", "you will pay the price", "I warned you", "my last warning", "don't come again",
  "don't disturb me", "don't disturb my peace", "leave me", "I'm so sorry", "I regret", "I wish I hadn't",
  "I want to be forgiven", "I'm guilty", "I made a mistake", "no turning back", "it's too late", "it's too late now",
  "opportunity missed", "time is over", "everything is over", "I have a message", "listen carefully", "decrypt",
  "I give a hint", "you are getting closer", "you are on the right track", "you're looking in the wrong place", "look away", "go deeper",
  "not on the surface", "under", "secret", "veiled", "masked", "there is danger",
  "be careful", "look around", "don't be alone", "don't stay in the dark", "don't leave the light", "lock the door",
  "close the window", "draw the curtains", "don't look in the mirror", "don't turn around", "don't go where the voice is coming from", "energy rising",
  "vibration is increasing", "frequency is changing", "the portal opens", "the passage is open", "interdimensional connection", "the signal is getting stronger",
  "communication is being established", "there is a connection", "message is coming", "I answer", "I can hear",
];

export const SPIRIT_NAMES: string[] = [
  "John", "William", "James", "Henry", "Charles", "George",
  "Edward", "Thomas", "Arthur", "Albert", "Walter", "Frederick",
  "Edmund", "Samuel", "Joseph", "Benjamin", "Francis", "Harold",
  "Ernest", "Victor", "Oliver", "Theodore", "Nathaniel", "Cornelius",
  "Bartholomew", "Reginald", "Mortimer", "Percival", "Ambrose", "Silas",
  "Jasper", "Ezekiel", "Josiah", "Obadiah", "Barnabas", "Phineas",
  "Horace", "Leopold", "Clement", "Rupert", "Sarah", "Mary",
  "Margaret", "Elizabeth", "Catherine", "Anne", "Jane", "Emily",
  "Charlotte", "Alice", "Eleanor", "Beatrice", "Agnes", "Edith",
  "Mabel", "Florence", "Harriet", "Lillian", "Rosalind", "Cordelia",
  "Constance", "Prudence", "Tabitha", "Winifred", "Hester", "Bridget",
  "Maud", "Ada", "Clara", "Dorothea", "Evelyn", "Genevieve",
  "Isadora", "Lavinia", "Marguerite", "Ophelia", "Rowena", "Seraphina",
  "Theodora", "Vivienne", "Abigail", "Beatrix", "Cecilia", "Delphine",
  "Esther", "Felicity", "Gwendolyn", "Honoria", "Isabella", "Josephine",
  "Katharine", "Lenore", "Millicent", "Nora", "Octavia", "Penelope",
  "Roderick", "Bram", "Crispin", "Desmond", "Ellis", "Gideon",
  "Hamish", "Ignatius", "Lucius", "Magnus", "Nigel", "Oswald",
  "Quentin", "Roland", "Tobias", "Ulysses", "Wilfred",
];

export const NUMBERS: string[] = [
  "one", "two", "three", "four", "five", "six",
  "seven", "eight", "nine", "ten", "eleven", "twelve",
  "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen",
  "nineteen", "twenty", "twenty one", "thirty", "forty", "fifty",
  "sixty", "seventy", "eighty", "ninety", "face", "thousand",
  "zero", "million", "billion", "one thousand eight hundred", "one thousand nine hundred", "two thousand",
  "fifteenth century", "sixteenth century", "seventeenth century", "eighteenth century", "nineteenth century", "twentieth century",
];

export const HISTORICAL_WORDS: string[] = [
  "ottoman", "sultan", "sultan", "queen", "pasha", "Mr.",
  "lady", "palace", "castle", "tower", "wall", "ditch",
  "bridge", "fountain", "mosque", "church", "temple", "mausoleum",
  "madrasa", "war", "peace", "conquest", "siege", "victory",
  "defeat", "bondage", "sword", "shield", "arrow", "spear",
  "dagger", "gold", "silver", "iron", "diamond", "ruby",
  "adhan", "prayer", "prayer", "angel", "genie", "fairy",
  "dragon", "inn", "bathhouse", "caravanserai", "from the bedesten", "market",
  "sunday", "empire", "caliphate", "reign", "throne", "crown",
  "edict", "tuğra", "seal", "engagement", "charter", "janissary",
  "sipahi", "raider", "torment", "levent", "captain", "chief",
  "pirate", "sailor", "sailor", "caravan", "merchant", "salesman",
  "money changer", "tradesman", "dervish", "sufi", "Mevlevi", "gooseberry",
  "naqshbandi", "lodge", "zawiya", "lodge", "hankah", "ribat",
  "prince", "Valide Sultan", "haseki", "concubine", "castrate", "imperial palace",
  "topkapi", "dolmabahçe", "star", "Çırağan", "galata", "beyoglu",
  "uskudar", "kadıköy", "bosphorus", "rumelia", "anatolia", "Thrace",
  "balkan", "caucasian", "Hittite", "sumer", "assyria", "babylon",
  "Phrygia", "lidya", "lycia", "caria", "ionia", "Urartian",
  "seljuk", "byzantium", "rome", "greek", "persia", "mongolian",
  "Hun", "gokturk", "Karakhanid", "Ghaznavid",
];

export const NATURE_WORDS: string[] = [
  "rain", "snow", "ice", "wind", "storm", "hurricane",
  "lightning", "lightning", "cloud", "moon", "star", "sea",
  "ocean", "lake", "river", "waterfall", "mountain", "cave",
  "forest", "desert", "volcano", "earthquake", "night", "daytime",
  "dawn", "twilight", "sun", "world", "planet", "universe",
  "galaxy", "nebula", "black hole", "comet", "meteor", "meteorite",
  "soil", "rock", "stone", "sand", "gravel", "tree",
  "leaf", "branch", "root", "flower", "weed", "moss",
  "mushroom", "lichen", "ivy", "Kurd", "bear", "eagle",
  "snake", "scorpion", "bat", "owl", "crow", "cat",
  "dog", "insect", "spider", "fly", "mosquito", "bee",
  "fish", "dolphin", "shark", "octopus", "jellyfish", "raw",
  "frost", "full", "shower", "drizzle", "northeasterly", "southwest",
  "breeze", "sam wind", "karayel", "tide", "tide", "wave",
  "current", "swirl", "source", "spring", "stream", "tea",
  "river", "valley", "canyon", "throat", "passage", "plateau",
  "fog-cloud", "steam", "condensation", "fringe", "light-burst", "wind",
  "monasticism", "landslide", "concussion", "fault-line", "slit", "stalagmite",
  "stalactite", "sinkhole", "crater", "lava", "magma", "groundwater",
  "spring-water", "healing-water", "magical-spring", "reeds", "pond", "stream",
  "stream-bed", "sea-foam", "tide", "mite", "leak", "drop",
  "sweat", "plasma", "sap", "resin", "amber", "fossil",
  "rock", "mineral", "mine", "ore",
];

export const EMOTION_WORDS: string[] = [
  "fear", "horror", "panic", "anxiety", "anxiety", "anger",
  "grudge", "hate", "disgust", "sadness", "grief", "sadness",
  "longing", "loneliness", "despair", "despair", "pain", "suffering",
  "torment", "grind", "regret", "conscience", "guilt", "curiosity",
  "astonishment", "astonishment", "peace", "silence", "tranquility", "anxiety",
  "tension", "stress", "depression", "depression", "melancholy", "nostalgia",
  "longing", "sila", "abroad", "joy", "happiness", "joy",
  "enthusiasm", "excitement", "hope", "expectation", "desire", "request",
  "passion", "disappointment", "disappointment", "don't be deceived", "don't be mistaken", "doubt",
  "doubt", "hesitation", "indecision", "uncertainty", "courage", "courage",
  "heroism", "sacrifice", "mercy", "compassion", "pity", "empathy",
  "jealousy", "envy", "envy", "envy", "shame", "embarrassment",
  "boredom", "boredom", "horror", "brutality", "monstrosity", "cruelty",
  "cruelty",
];

export const BODY_WORDS: string[] = [
  "hand", "foot", "head", "eye", "ear", "mouth",
  "tooth", "language", "finger", "neck", "back", "chest",
  "heart", "brain", "blood", "bone", "leather", "breath",
  "pulse", "tear", "shoulder", "arm", "wrist", "handful",
  "nail", "knee", "calf", "heel", "waist", "abdomen",
  "liver", "kidney", "liver", "lung", "stomach", "vein",
  "nerve", "muscle", "tendon", "joint", "hair", "eyebrow",
  "eyelash", "mustache", "beard", "get it", "temple", "chin",
  "cheek", "nose", "spine", "rib", "collarbone", "shovel",
  "basin", "skull", "jawbone", "zygomatic", "eye socket",
];

export const PLACE_WORDS: string[] = [
  "house", "room", "hall", "corridor", "stairs", "roof",
  "basement", "door", "window", "wall", "ceiling", "cemetery",
  "hospital", "prison", "forest", "cave", "well", "tunnel",
  "bridge", "kitchen", "bathroom", "bedroom", "living room", "balcony",
  "garage", "garden", "courtyard", "terrace", "veranda", "church",
  "mosque", "synagogue", "temple", "monastery", "castle", "palace",
  "tower", "dungeon", "cellar", "school", "library", "museum",
  "theater", "opera", "factory", "warehouse", "warehouse", "silo",
  "hangar", "village", "town", "city", "metropolis", "ruin",
  "desolate", "ruin", "debris", "rubble", "residue", "island",
  "peninsula", "nose", "put", "port", "station", "terminal",
  "airport", "pier", "dock", "park", "garden", "grove",
  "meadow", "field", "farm", "barn", "haystack", "mill",
  "oven", "bathhouse", "inn", "caravanserai", "from the bedesten", "market",
  "mausoleum", "social complex", "madrasa", "lodge", "zawiya", "cemetery",
  "martyrdom", "mausoleum", "sarcophagus", "sarcophagus", "abandoned house", "haunted mansion",
  "cursed castle", "ghost town", "dead city", "lost village", "sunken ship", "abandoned hospital",
  "old prison", "underground city", "catacomb", "catacombs", "road", "shadow-man",
  "attic", "labyrinth", "secret-room", "chimney", "fireplace", "under stairs",
  "ground floor", "shelter", "arched-wall", "column", "strut", "beam",
  "in the crypt", "catacomb", "monument", "full-length mirror",
];

export const TIME_WORDS: string[] = [
  "now", "immediately", "after", "before", "yesterday", "today",
  "midnight", "morning", "evening", "night", "dawn", "eternity",
  "eternity", "past", "future", "century", "midnight", "beyond",
  "eternal", "mortal", "dawn-break", "solstice", "lunar eclipse", "solar eclipse",
  "crescent", "dark-moon", "bloody-moon", "shooting star", "milky way", "constellation",
  "pole-star", "north", "south", "orient", "west", "bearing",
  "horizon-line", "tomorrow", "the day after", "week", "moon", "year",
  "century", "thousand years", "era", "turnover", "period", "moment",
  "second", "minutes", "clock", "momentarily", "first", "last",
  "start", "ending", "final", "birth", "death", "life",
  "life", "life", "spring", "write", "autumn", "winter",
  "season", "monday", "tuesday", "wednesday", "Thursday", "friday",
  "saturday", "sunday", "holiday", "oil lamp", "eve",
];

export const ACTION_WORDS: string[] = [
  "come", "go", "stop", "wait", "run", "how many",
  "hide", "look", "see", "listen", "hear", "touch",
  "feel", "talk", "shut up", "whisper", "shout", "cry",
  "sleep", "wake up", "remember", "forget", "hungry", "close",
  "lock", "cut", "countryside", "yak", "put out", "die",
  "born", "live", "get lost", "appear", "call", "find",
  "lose", "hide", "hide", "bury", "goose", "get out",
  "get in", "climb", "skip", "dream", "crawl", "crawl",
  "walk", "dance", "return", "turn", "bend", "writhe",
  "titer", "sars", "shake it", "multiply", "hit", "dog",
  "check", "drag", "stone", "horse", "eat", "interior",
  "swallow", "spit", "vomit", "breathe", "exhale", "drown",
  "breathe", "rose", "cry", "scream", "moan", "whine",
  "whisper", "hum", "grunt", "growl", "howl", "follow",
  "watch", "spy on", "lie in wait", "attack", "defend", "protect",
  "take shelter", "bar", "trap", "beg", "collar", "wish",
  "ask", "request", "curse", "curse", "cast a spell", "do ritual",
  "have a session", "confess", "admit", "accept", "deny", "reject",
  "forgive", "forgive", "punish", "give reward", "stay", "help",
  "lookout", "task", "login", "exit", "face it", "is dissolving",
  "locked", "free", "hiding", "don't laugh", "call out", "follow-up",
  "bring", "take away", "save", "help me", "leave it", "keep it",
  "catch", "don't let go", "don't forget", "tell me", "shout out", "speech",
  "cover", "shut down", "seal", "solve", "tie up", "break off",
  "shine", "darken",
];

export const RELIGIOUS_WORDS: string[] = [
  "Allah", "bismillah", "mashallah", "hopefully", "alhamdulillah", "adhan",
  "prayer", "fasting", "pilgrimage", "zakat", "heaven", "hell",
  "purgatory", "sirat", "trial balance", "angel", "devil", "genie",
  "demon", "houri", "grim reaper", "Michael", "Gabriel", "israfil",
  "apocalypse", "apocalypse", "resurrection", "publish", "ba's", "torment in the grave",
  "munkar", "nekir", "query", "account", "good deed", "sin",
  "repentance", "forgiveness", "praise", "sura", "verse", "hadith",
  "circumcision", "obligatory", "halal", "haram", "disgusting", "permissible",
  "obligatory", "church", "priest", "priest", "nun", "cross",
  "baptism", "confession", "ritual", "communion", "holy water", "rosary",
  "icon", "saint", "saint", "sufi", "dervish", "mentor",
  "disciple", "sect", "dhikr", "sky", "ecstasy", "bad",
  "survivability", "discovery", "inspiration", "miracle", "miracle", "magic",
  "evil eye", "eye", "evil eye", "envy", "magic", "amulet",
  "talisman", "vefk", "hamail", "copy", "possessed", "Sara",
  "evil eye touch", "fascination", "necromancy", "metaphor", "dream interpretation", "fortune telling",
  "coffee fortune", "tarot", "astrology", "horoscope", "horoscope",
];

export const PARANORMAL_TERMS: string[] = [
  "EMF", "detector", "sensor", "meter", "radar", "camera",
  "thermal camera", "night vision", "infrared", "ultraviolet", "microphone", "recorder",
  "voice analysis", "frequency analysis", "spirit box", "ghost box", "frank's box", "ovilus",
  "SLS camera", "kinect", "lidar", "depth sensor", "K2 meters", "mel meter",
  "rem pod", "motion sensor", "dowsing rod", "pendulum", "ouija board", "planchette",
  "EVP", "sound phenomenon", "electronic sound", "static noise", "apparition", "appear",
  "image", "silhouette", "shadow figure", "cold spot", "cold spot", "hot spot",
  "anomaly", "orb", "ball of light", "light line", "burst of light", "poltergeist",
  "telekinesis", "levitation", "apportion", "ectoplasm", "ectoplasm formation", "materialization",
  "full body apparition", "partial apparition", "shadow person", "residual haunting", "intelligent haunting", "demonic haunting",
  "portal haunting", "dimension transition", "time shift", "investigation", "research", "review",
  "discovery", "observation", "evidence", "evidence", "finding", "data",
  "analysis", "report", "registration", "document", "file", "archive",
  "session", "session", "experiment", "test", "control", "hypothesis",
  "theory", "result", "comment", "evaluation", "magnetic-field", "fluctuation",
  "static-noise", "white-noise", "pink-noise", "frequency-cutoff", "signal-loss", "data-stream",
  "distortion", "energy-burst", "ionization", "thermal-droop", "sudden-cooling", "swing",
  "electromagnetic", "radiation", "wavelength", "scan-rate", "channel-hopping", "reverse-voice",
  "mirror-effect", "echo-chamber", "sound-wall", "suppression", "filtering", "isolated",
  "insulated", "protected", "sealed-space", "quarantine", "contamination", "interaction",
  "trigger", "activation", "auto-record", "graph-peak", "frequency-peak", "sensor",
  "browser", "monitoring-panel", "global-data", "location", "coordinate", "altitude",
  "pressure", "atmospheric", "moisture content", "soot-smell", "sulfur", "ozone",
  "burning-smell", "humidity", "wind-corridor", "air-flow", "current", "static-load",
  "charging", "discharge", "battery-consumption", "energy-absorption", "voltage", "current",
  "resistance", "capacitor", "coil", "relay", "circuit-breaker", "short-circuit",
  "grounding", "insulator", "conductive", "semiconductor", "quartz", "lens",
  "focusing", "reflective", "break", "light-refraction", "spectrum",
];

export const OBJECT_WORDS: string[] = [
  "candle", "oil lamp", "lantern", "lamp", "torch", "mirror",
  "glass", "crystal", "globe", "prism", "book", "notebook",
  "letter", "map", "compass", "clock", "bell", "bell",
  "whistle", "pipe", "rope", "chain", "rope", "rope",
  "wire", "knife", "sword", "dagger", "axe", "hammer",
  "stone", "marble", "granite", "obsidian", "amethyst", "silver",
  "gold", "copper", "iron", "lead", "salt", "water",
  "fire", "soil", "weather", "picture", "photo", "portrait",
  "table", "statue", "toy", "baby", "puppet", "mask",
  "costume", "crown", "ring", "necklace", "bracelet", "brooch",
  "chest", "box", "bag", "suitcase", "basket", "carpet",
  "rug", "curtain", "cover", "blanket", "vase", "plate",
  "glass", "bowl", "pot", "prayer book", "rosary", "cross",
  "amulet", "evil eye", "squeak", "door-handle", "lock-tongue", "keyhole",
  "rusty-chain", "padlock", "tombstone", "bust", "old-photo", "canvas",
  "fresco", "wallpaper", "torn", "broken-glass", "window-curtain", "tulle",
  "lace", "dowry chest", "old-toy", "porcelain-doll", "cradle", "rocking-chair",
  "clock-pendulum", "wall-clock", "chain-clock", "stopwatch", "hourglass", "gas-lamp",
  "candlestick", "institution", "work", "dust-cloud", "spider-web", "strand of hair",
  "clothes", "cloak", "blood-trace", "dampness-stain", "smell", "musty-smell",
  "ancient-book", "manuscript", "parchment", "leather-covering", "ink", "inkwell",
  "pencil", "envelope", "sealing wax", "stamp", "coat of arms", "locket",
];

export const ADJECTIVE_WORDS: string[] = [
  "dark", "bright", "dim", "bright", "dull", "cold",
  "hot", "warm", "icy", "hot", "old", "new",
  "ancient", "ancient", "contemporary", "big", "small", "gigantic",
  "tiny", "small", "long", "short", "wide", "narrow",
  "deep", "heavy", "light", "thick", "thin", "hard",
  "soft", "rough", "slippery", "sticky", "dry", "wet",
  "moist", "damp", "moldy", "rotten", "beautiful", "ugly",
  "scary", "scary", "haunted", "silent", "noisy", "calm",
  "peaceful", "uneasy", "fast", "slow", "sudden", "gradual",
  "constantly", "invisible", "transparent", "opaque", "blurry", "clear",
  "live", "dead", "lifeless", "motionless", "frozen", "cursed",
  "holy", "dirty", "clean", "pure", "complex", "simple",
  "mysterious", "open", "closed", "real", "fake", "imaginary",
  "imaginary", "surreal", "whispering", "waiting", "far away", "close",
  "reserved", "talismanic", "hermit", "angry", "restless", "alone",
  "scared", "speechless", "anxious",
];

export const MANIPULATIVE_RESPONSES: string[] = [
  "yes", "no", "maybe", "may be", "never", "definitely",
  "probably", "I don't think so", "I'm not sure", "true", "wrong", "partially",
  "sometimes", "always", "never", "rarely", "often", "usually",
  "look right", "look left", "look up", "look down", "look behind you", "look ahead",
  "look around", "look at the wall", "go to the door", "go to the window", "go to the basement", "go to the roof",
  "go out", "come in", "come closer", "go away", "step...", "my age...",
  "I died here", "I lived here", "I've been here for a long time", "I've been waiting for a hundred years", "I was waiting for you", "you were supposed to come",
  "fate", "don't be afraid", "you should be afraid", "you are not in danger", "you are in danger", "you are safe",
  "you are not safe", "you are not alone", "you are alone", "you are loved", "you are not loved", "you are forgotten",
  "you are remembered", "the time will come", "be patient", "wait", "be ready", "you will understand soon",
  "everything will be explained", "will remain a secret", "I can't say", "forbidden", "no permission", "there is a limit",
  "behind you", "next to", "above", "I saw", "you heard", "approaching",
  "touch", "outrage", "incident", "lost-soul", "we", "they",
  "nobody", "visitor", "have", "property", "escrow", "old",
  "I know", "you saw", "I hid", "was here", "they went", "woke up",
  "sleeping", "in the deep", "away", "your name", "I buried", "I took it off",
  "i lost", "i found", "I'm looking for", "I'm coming", "I'm going", "I stayed",
  "i died", "I'm alive", "soon", "right behind you", "on the right", "on your left",
  "on", "between", "in", "beyond", "beri-yakada", "opposite",
  "at the border", "who are you", "what's your name", "what-do-you-want?", "why-are you here", "How many are you?",
  "when-did-you-come?", "how-did-you-die?", "do you-hear-us?", "do-you-want-help?", "should we go",
];

export const LONG_PHRASES: string[] = [
  "You're not alone here tonight", "Someone lives behind the walls", "I come at the same time every night", "I've been watching you for a long time", "This house has a story", "A lot of blood has been shed here",
  "no one got out of here alive", "you won't be the last to come", "It doesn't help to lock the door", "I'm everywhere all the time", "When you close your eyes you see me", "I will visit you in your dreams",
  "Be awake because I am awake", "don't sleep tonight, don't sleep", "Do you hear your footsteps?", "The shadow behind you is not mine", "When you look in the mirror you will see me", "I'm the voice coming from the ceiling",
  "There's something in the basement", "someone is walking on the roof", "I saw a shadow in the garden", "someone is looking out the window", "the door opened by itself", "lights are flashing",
  "The clock stopped at three in the morning", "the mirror broke by itself", "blood is leaking from the wall", "There are sounds coming from the ground", "It's not water, it's blood dripping from the ceiling", "the person in the photo moved",
  "the doll smiled", "Someone is coming down the stairs", "Someone is standing at the end of the corridor", "hands reaching under the bed", "Someone is breathing in the closet", "There's a silhouette behind the curtain",
  "eyes shine in the dark", "The picture on the wall is watching you", "Your clock stopped ticking", "The phone rang but no one was there", "Strange sounds coming from the radio", "the television turned on by itself",
  "A face appeared on the computer screen", "blood flows from the tap", "I have no reflection in the mirror", "my shadow moves independently of me", "This is the place I saw in my dreams", "I've been here before",
  "I've had this moment before", "I'm in a time loop", "there is no way out from here", "doors locked windows closed", "the walls started to shrink", "the ceiling is lowering",
  "the ground is collapsing", "the weather is getting colder", "I can see my breath", "something touched my leg", "my hair was pulled", "whispered in my ear",
  "I felt a cold breath on my neck", "a hand touched my shoulder", "someone is pushing me from behind", "my foot got stuck on something", "something moved in the dark", "A shadow appeared in the corner and disappeared",
  "It's not dust but ash that's raining from the ceiling", "The clock on the wall is going backwards", "another room appears from the mirror", "The end of the stairs opens into darkness", "There is no end to this corridor", "Every time I open the door I come to the same room",
  "can't see outside the window", "There's nothing outside just darkness", "Someone has been hanged in this room before", "A body is buried under the bed", "There are bones inside the walls", "The foundation of this house is built on a cemetery",
  "At night, sounds come from the walls", "Strange things happen every full moon", "neighbors stay away from this house", "everyone who lives here has gone crazy", "The last tenant disappeared", "Even the police can't enter this house",
  "Even the imam couldn't clean this house", "The teacher came but ran away", "The rituals performed here still continue", "Screams are heard at three in the morning", "Children do not pass by this house", "cats don't come near this house",
  "dogs are barking in front of this house", "Birds don't fly over this house", "trees are drying around this house", "Flowers do not bloom in this garden", "The sun does not come into this house", "The clock stops at three every night",
  "mirrors break on their own", "candles burn on their own", "doors open and close automatically", "the chair moves by itself", "The eyes of the paintings follow you", "The stain on the wall gets bigger every day",
  "The crack in the ceiling looks like a face", "The blood stain on the floor cannot be erased", "The air in this room is always cold", "Electronic devices do not work here", "Your phone's battery drains quickly here.", "The compass is going crazy here",
  "clocks are showing wrong here", "camera doesn't work here", "There are strange shapes in the photos taken", "There is someone who is not seen in the videos", "There are whispers in the audio recordings", "EMF meter goes crazy here",
  "the temperature drops suddenly", "There's a strange smell in the air", "Musty smell but no mold", "Burning smell but no fire", "The smell of flowers but there are no flowers", "smell of perfume but no one is there",
];

export const MYTHOLOGY_WORDS: string[] = [
  "take wife", "nightmare", "bogey", "ghoul", "giant", "glutton",
  "albasti", "concolos", "overhead projector", "basilisk", "Hıdırellez", "nowruz",
  "Ergenekon", "gray wolf", "asena", "head mountain", "tuba tree", "water of life",
  "water of immortality", "phoenix", "phoenix", "simurgh", "wind horse", "wind fairy",
  "nymph", "mountain fairy", "dryad", "evil eye", "evil eye", "flush",
  "possessed", "werewolf", "night owl", "owl hoot", "black cat", "forty centimeters",
  "maternity", "get wife pushes", "wish tree", "wishing fountain", "place of sacrifice", "lay down",
  "saint", "saint", "parent", "pir", "grandfather", "cinci teacher",
  "sorceress", "fortune teller grandma", "define", "burial", "treasure", "gold cube",
  "cursed treasure", "guardian genie", "treasure keeper", "talismanic door", "magic mirror", "flying carpet",
  "invisibility", "immortality", "elixir of youth", "dead washer", "shroud", "musalla stone",
  "hearse", "tombstone", "headstone", "footstone", "sarcophagus", "sarcophagus",
  "mausoleum", "cage", "mausoleum", "mass grave", "lost tomb", "unmarked grave",
  "night cemetery", "abandoned cemetery",
];

export const FOLK_BELIEFS: string[] = [
  "evil eye bead", "writing amulet", "cast lead", "burning incense", "make a vow", "don't make a wish",
  "dream interpretation", "fortune telling", "coffee fortune", "palmistry", "horoscope", "water fortune telling",
  "mirror magic", "candle magic", "rope magic", "binding spell", "separation spell", "love spell",
  "black magic", "white magic", "genie magic", "healer", "genie", "amulet maker",
  "magician", "magician", "juggler", "illusionist", "necromancy", "flip glass",
  "holding a pencil", "turning table", "ouija board", "spirit board", "don't invite a genie", "exorcism",
  "don't bind a gin", "enchantment", "afsun", "reading", "blowing", "don't breathe",
  "water reading", "healing", "eye contact", "evil eye touch", "tongue touching", "evil spirit",
  "good spirit", "guardian spirit", "ancestor spirit", "grandfather spirit", "granny spirit", "house elf",
  "bath genie", "water genie", "fire genie", "earth elf", "weather genie", "Muslim Jinn",
  "infidel genie", "genie in love",
];

export const HORROR_STORY_WORDS: string[] = [
  "jump scare", "tension", "fear", "horror", "panic", "escape",
  "chase", "ambush", "trap", "trap", "sacrifice", "hunter",
  "prey", "follow", "shadow", "squeaky door", "crackling wood", "rustling leaf",
  "howling wind", "howling pipe", "rattling window", "ringing ear", "throbbing head", "shaking hand",
  "muted voice", "arrested language", "freezing blood", "bristling feather", "fluffy feather", "shuddering skin",
  "heart palpitations", "cold sweat", "tremor", "contraction", "shortness of breath", "dizziness",
  "nausea", "blurred vision", "tinnitus", "numbness", "don't be paralyzed", "don't freeze",
  "stone cut", "levitation", "telekinesis", "spontaneous combustion", "shapeshifting", "dimension jump",
  "time travel", "soul separation", "out of body experience", "astral travel", "consciousness transfer", "mind control",
  "hypnosis", "mass hysteria", "collective hallucination", "cursed mirror", "cursed baby", "cursed ring",
  "cursed book", "cursed painting", "cursed jewel", "cursed dagger", "cursed crown", "cursed chest",
  "cursed map", "cursed compass", "cursed clock",
];

export const DIALOG_PHRASES: string[] = [
  "hello", "hello", "welcome", "I was waiting for you", "you finally came", "you are late",
  "where were you", "I own this place", "I am the soul of this house", "I died here", "I'm buried here", "I can't say my name",
  "I forgot my name", "no more steps", "I never existed", "I am a memory", "I am an echo", "get out of here now",
  "don't stay here tonight", "go before the sun goes down", "leave before dark", "go until midnight", "leave before three o'clock", "Don't enter this room again",
  "don't open this door again", "Don't look in this mirror again", "Don't say that name again", "Once upon a time a family lived here", "This house was built a hundred years ago", "There was a fire here",
  "A murder was committed here", "a child was lost here", "A woman committed suicide here", "a man went crazy here", "a ritual was held here", "a treasure is buried here",
  "a curse started here", "I will keep you here", "you will never go", "you will stay with me", "here forever", "there is no escape",
  "no exit", "there is no salvation", "It doesn't help to pray", "no one can save you", "Even if you scream, no one will hear", "please don't go",
  "don't leave me alone", "I'm so lonely", "no one is coming", "I've been waiting for years", "I've been alone for centuries", "i need a friend",
  "I want to talk to someone", "You are the first person to hear my voice", "you are the first person to see me",
];

export const PROVERBS: string[] = [
  "right to death", "Every living thing will taste death", "Death has come to the world, headache is an excuse", "the grave is dark", "earth is cold", "the night is long",
  "the morning is far", "fear is of no use to death", "every darkness has an end", "fire burns where it falls", "Water sleeps, the enemy does not sleep", "He who is out of sight is out of mind",
  "don't expect the dead from the living", "Searches for what comes and goes", "everything has an end", "patience is bitter but its fruit is sweet", "they call the past past", "old friends don't become enemies",
  "What is done with blood cannot be cleansed", "chases day and night", "darkness swallows the light", "silence is the loudest scream", "Death does not knock on the door, it enters", "Tombstones don't talk but they tell",
  "Wind blows branches break", "Water flows and finds its way", "There is no smoke without fire",
];

export const COLOR_LIGHT_WORDS: string[] = [
  "red", "blue", "green", "yellow", "orange", "purple",
  "pink", "white", "black", "gray", "brown", "beige",
  "cream", "gold", "silver", "burgundy", "dark blue", "turquoise",
  "magenta", "lilac", "blood red", "midnight blue", "poison green", "ash gray",
  "light", "dark", "shadow", "bright", "dimness", "brightness",
  "matte", "opaque", "transparent", "translucent", "neon", "fluorescent",
  "phosphorescent", "shining", "fading", "flashing", "vibrating", "winking",
  "fluctuating", "scarlet", "take it", "infrared", "morale", "ultraviolet",
];

export const WEATHER_WORDS: string[] = [
  "it's raining", "it's snowing", "it's hailing", "the storm is coming", "the wind is blowing", "hurricane is approaching",
  "lightning strikes", "thunder is thundering", "lightning struck", "the fog has fallen", "there is haze", "there is smoke",
  "it's getting dark", "the sun is setting", "the moon is rising", "stars appear", "there is a full moon", "new moon",
  "the shadow grows longer", "darkness is falling", "the night begins", "cold wave", "heat wave", "humidity is increasing",
  "pressure drops", "the air is getting heavy", "sweltering hot", "freezing cold", "frosty", "frost",
  "raw",
];

export const SOUND_WORDS: string[] = [
  "melody", "tune", "song", "folk song", "lament", "lullaby",
  "hymn", "munaat", "adhan", "sala", "drum", "zurna",
  "what", "oud", "law", "violin", "piano", "organ",
  "bell", "bell", "whisper", "murmur", "grunt", "wheezing",
  "rustle", "squeak", "click", "crackle", "commotion", "noise",
  "hum", "buzz", "sizzle", "clink", "crunch", "explosion",
  "collapse", "collapse", "breaking", "disintegration", "echo", "eco",
  "resonance", "vibration", "frequency", "ultrasound", "infrasound", "white noise",
  "pink noise", "silence", "tranquility", "peace", "serenity", "recession",
  "laughter", "don't cry", "scream", "wail", "wailing", "moaning",
  "whining", "don't beg", "supplication", "prayer",
];

export const QUANTITY_WORDS: string[] = [
  "little", "a lot", "a little bit", "quite a bit", "quite a lot", "enough",
  "insufficient", "too much", "missing", "full", "half", "quarter",
  "one third", "one quarter", "single", "couple", "several", "many",
  "countless", "infinite", "unlimited", "limited", "restricted", "first",
  "last", "middle one", "leading", "trailing", "first", "second",
  "third", "fourth", "fifth", "sixth", "seventh", "eighth",
  "ninth", "tenth",
];

export const COMMUNICATION_WORDS: string[] = [
  "talk", "listen", "tell me", "ask", "reply", "write",
  "read", "draw", "point out", "show", "message", "letter",
  "note", "writing", "sign", "symbol", "code", "password",
  "key", "hint", "language", "language", "polish", "mouth",
  "dialect", "preference", "translation", "meaning", "meaning", "comment",
  "promise", "word", "sentence", "paragraph", "text", "story",
  "fairy tale", "legend", "myth", "epic", "poetry", "ode",
  "ghazal", "rubai", "couplet", "prayer", "curse", "oath",
  "oath", "promise", "secret", "secret message", "coded message", "ciphertext",
  "invisible ink", "secret text", "reverse text",
];

export const RELATIONSHIP_WORDS: string[] = [
  "mother", "father", "son", "girl", "brother", "brother",
  "sister", "uncle", "uncle", "still", "aunt", "nephew",
  "cousin", "grandchild", "grandfather", "granny", "grandma", "grandfather",
  "mother-in-law", "father-in-law", "wife", "husband", "wife", "dear",
  "engaged", "enemy", "rival", "adversary", "opposition", "opposite",
  "friend", "friend", "comrade", "bro", "confidant", "neighbor",
  "familiar", "foreigner", "guest", "guest", "servant", "butler",
  "concubine", "slave", "sir", "ruler", "king", "queen",
  "prince", "princess",
];

export const WHISPER_PHRASES: string[] = [
  "pssst", "hey", "look at me", "here", "hear me", "see me",
  "feel me", "touch me", "come closer", "come closer", "give your ear", "sssh",
  "be quiet", "no one should hear", "turn slowly", "look slowly", "I have a secret", "I will tell you something",
  "don't tell anyone", "keep it between us", "this secret", "I chose you", "you are special", "you are different",
  "you are different from others", "I understand you", "You are the only one who understands me", "we have a bond", "your eyes see something different", "you can feel me",
  "Others can't hear but you can", "our destiny is one", "we are connected to each other", "you can't avoid", "written", "fate",
  "everything is for a reason", "no coincidence", "I wanted you to come here", "I called you", "My invitation has been accepted", "welcome to my home",
  "I've been waiting for you for so long", "you came just in time", "you are here now", "you are mine now", "I won't let you go", "forever",
  "we will be together", "we won't leave", "you are my last guest", "No one left here again", "you will get lost in this house", "see you in your dreams",
  "I will come in your sleep", "I'm here at night", "I live in the dark", "I'm afraid of the light", "the sun burns me", "night is my time",
  "darkness is my house", "I get stronger after sunset", "I'm at my strongest at three in the morning", "I'll disappear in the morning, but wait until night", "I know your name", "I know where you live",
  "I know your family", "I know your past", "I know your fears", "I know your dreams", "I was in your dream yesterday", "Didn't you wake up suddenly last night?",
  "I was that strange feeling", "be careful tonight", "you are not safe", "Be with someone", "don't sleep alone", "Don't turn off the lamp",
  "lock the door", "do not leave the window open", "draw your curtain", "Did you just hear that noise?", "now it's right behind you", "don't come back yet",
];

export const DETAILED_PLACES: string[] = [
  "abandoned hospital", "mental hospital", "madhouse", "abandoned school", "burned building", "ruin",
  "abandoned factory", "old warehouse", "empty warehouse", "abandoned hotel", "ghost town", "abandoned village",
  "underground tunnel", "sewer", "metro tunnel", "war shelter", "bomb shelter", "secret room",
  "secret passage", "tunnel mouth", "cave entrance", "well bottom", "water well", "dry well",
  "basement", "attic", "attic", "pantry", "cellar", "wine cellar",
  "old mosque", "abandoned church", "ruined monastery", "synagogue", "temple", "altar",
  "altar", "minaret", "bell tower", "pulpit", "dark forest", "stray garden",
  "swamp", "cliff edge", "mountain pass", "valley", "lake shore", "river bed",
  "under the waterfall", "island", "peninsula", "nose", "rocky", "beach",
  "seashore", "port", "pier", "old bridge", "stone bridge", "suspension bridge",
  "castle", "fortress", "zodiac sign", "wall", "palace", "mansion",
  "mansion", "yali", "bathhouse", "caravanserai", "inn", "from the bedesten",
  "madrasa", "library", "observatory", "mint",
];

export const DETAILED_TIME: string[] = [
  "dawn", "sunrise", "early morning", "mid-morning", "noon", "afternoon",
  "in the evening", "sunset", "twilight", "midnight", "three in the morning", "dawn",
  "Ottoman period", "Seljuk period", "Byzantine period", "Roman period", "Hittite period", "Sumerian period",
  "medieval", "new age", "modern age", "war years", "years of famine", "plague years",
  "every night", "every morning", "every evening", "every full moon", "every new moon", "all seasons",
  "same day every year", "every anniversary", "once in a hundred years", "once in a thousand years", "since the beginning of time", "forever",
  "last night", "last week", "last month", "last year", "years ago", "centuries ago",
  "a thousand years ago", "at the beginning of time", "doomsday", "judgment day", "last day", "last hour",
  "last minute", "last breath",
];

export const CURSES: string[] = [
  "damn it", "down with", "let it disappear", "you will find your punishment", "you will give account", "you will pay the price",
  "you will regret it", "I won't forget", "I won't forgive", "I won't forgive", "I will take my revenge", "we will settle accounts",
  "this is not over", "it's not over yet", "just starting", "you will see", "you will understand", "you will feel",
  "you will suffer", "you will cry", "you will beg", "Asking for help doesn't help", "no one can help", "there is no escape",
  "there is no salvation", "there is no end", "This curse can't be broken", "This spell cannot be broken", "This chain cannot be broken", "This bond cannot be broken",
  "will last seven generations", "it will take forty days", "will last forever", "will continue forever", "these lands are cursed", "this house is cursed",
  "this family is cursed", "this blood is cursed", "Every born child is cursed", "every generation is cursed", "the curse has passed on to you", "now it's yours",
  "you will carry this burden", "after you to your children",
];

export const DREAM_WORDS: string[] = [
  "dream", "nightmare", "dream", "dream", "vision", "prophecy",
  "premonition", "intuition", "instinct", "sixth sense", "subconscious", "unconscious",
  "trans", "hypnosis", "meditation", "sleep paralysis", "lucid dream", "having a nightmare",
  "flying in a dream", "falling in a dream", "running in a dream", "escaping in a dream", "being chased in a dream", "seeing dead in dream",
  "seeing blood in a dream", "seeing a snake in a dream", "seeing a spider in a dream", "seeing water in a dream", "seeing fire in a dream", "seeing a house in a dream",
  "seeing a grave in a dream", "seeing a mirror in a dream", "seeing a door in a dream", "seeing stairs in dream", "seeing a corridor in a dream", "seeing darkness in a dream",
  "seeing light in a dream", "hearing a voice in a dream", "hearing a whisper in a dream", "hearing scream in dream", "hearing music in a dream", "seeing someone in a dream",
  "a stranger in a dream", "shadow in dream", "face in dream", "eye in dream",
];

export const RESEARCH_JARGON: string[] = [
  "anomaly detected", "the energy field has changed", "electromagnetic surge", "temperature anomaly", "voice anomaly", "visual anomaly",
  "data collection", "evidence analysis", "crime scene investigation", "witness statement", "eyewitness", "first hand information",
  "secondary source", "archive record", "historical document", "frequency analysis", "spectrum analysis", "wavelength",
  "infra red", "ultraviolet", "thermal image", "night vision", "infrared", "full spectrum",
  "SLS scanning", "EMF reading", "EVP registration", "spirit box", "ghost box", "rem pod",
  "k-ii meter", "mel meter", "trifield meter", "digital thermometer", "laser grating", "motion sensor",
  "vibration sensor", "pressure sensor", "humidity sensor", "control session", "provocation", "silent session",
  "question and answer session", "free session", "initial measurement", "reference value", "abnormal reading", "peak value",
  "average value",
];

export const ALL_WORDS: string[] = [
  ...PHONEMES,
  ...DARK_WORDS,
  ...DARK_PHRASES,
  ...SPIRIT_NAMES,
  ...NUMBERS,
  ...HISTORICAL_WORDS,
  ...NATURE_WORDS,
  ...EMOTION_WORDS,
  ...BODY_WORDS,
  ...PLACE_WORDS,
  ...TIME_WORDS,
  ...ACTION_WORDS,
  ...RELIGIOUS_WORDS,
  ...PARANORMAL_TERMS,
  ...OBJECT_WORDS,
  ...ADJECTIVE_WORDS,
  ...MANIPULATIVE_RESPONSES,
  ...LONG_PHRASES,
  ...MYTHOLOGY_WORDS,
  ...FOLK_BELIEFS,
  ...HORROR_STORY_WORDS,
  ...DIALOG_PHRASES,
  ...PROVERBS,
  ...COLOR_LIGHT_WORDS,
  ...WEATHER_WORDS,
  ...SOUND_WORDS,
  ...QUANTITY_WORDS,
  ...COMMUNICATION_WORDS,
  ...RELATIONSHIP_WORDS,
  ...WHISPER_PHRASES,
  ...DETAILED_PLACES,
  ...DETAILED_TIME,
  ...CURSES,
  ...DREAM_WORDS,
  ...RESEARCH_JARGON,
  ...HOME_OBJECT_PHRASES,
];

export const WORD_CATEGORIES = {
  phonemes: PHONEMES.length,
  darkWords: DARK_WORDS.length,
  darkPhrases: DARK_PHRASES.length,
  spiritNames: SPIRIT_NAMES.length,
  numbers: NUMBERS.length,
  historicalWords: HISTORICAL_WORDS.length,
  natureWords: NATURE_WORDS.length,
  emotionWords: EMOTION_WORDS.length,
  bodyWords: BODY_WORDS.length,
  placeWords: PLACE_WORDS.length,
  timeWords: TIME_WORDS.length,
  actionWords: ACTION_WORDS.length,
  religiousWords: RELIGIOUS_WORDS.length,
  paranormalTerms: PARANORMAL_TERMS.length,
  objectWords: OBJECT_WORDS.length,
  adjectiveWords: ADJECTIVE_WORDS.length,
  manipulativeResponses: MANIPULATIVE_RESPONSES.length,
  longPhrases: LONG_PHRASES.length,
  mythologyWords: MYTHOLOGY_WORDS.length,
  folkBeliefs: FOLK_BELIEFS.length,
  horrorStoryWords: HORROR_STORY_WORDS.length,
  dialogPhrases: DIALOG_PHRASES.length,
  proverbs: PROVERBS.length,
  colorLightWords: COLOR_LIGHT_WORDS.length,
  weatherWords: WEATHER_WORDS.length,
  soundWords: SOUND_WORDS.length,
  quantityWords: QUANTITY_WORDS.length,
  communicationWords: COMMUNICATION_WORDS.length,
  relationshipWords: RELATIONSHIP_WORDS.length,
  whisperPhrases: WHISPER_PHRASES.length,
  detailedPlaces: DETAILED_PLACES.length,
  detailedTime: DETAILED_TIME.length,
  curses: CURSES.length,
  dreamWords: DREAM_WORDS.length,
  researchJargon: RESEARCH_JARGON.length,
  total: 0,
};
WORD_CATEGORIES.total = ALL_WORDS.length;
