// German word bank for VOX — auto-generated parallel to word-bank.ts (Turkish).
// Do not hand-edit category arrays; structure mirrors lib/word-bank.ts exactly.

export const NINE_PHRASES: string[] = [
  "mein Baby", "mein Enkelkind", "Liebling", "mein Kind", "mein Baby", "mein kleines Lamm",
  "meine Leber", "das Licht meiner Augen", "Ecke meines Herzens", "komm zu mir", "Wo bist du, Baby?", "Ich vermisse dich",
  "geh nicht von mir weg", "Ich warte mit Sehnsucht", "Ich denke jede Nacht an dich", "Ich möchte deine Stimme hören", "Lass mich dein Gesicht noch einmal sehen", "Du bist in meinem Traum gekommen, aber ich bin aufgewacht",
  "Warum kommst du nicht?", "Kannst du mich hören?", "es ist kalt hier", "kein Licht", "sehr dunkel", "Ich bin immer noch hier",
  "vergiss mich nicht", "Mein Grab ist verlassen", "niemand kommt", "Ich wurde allein gelassen", "Es ist lange her", "Konnte man so sterben?",
  "Ich warte auf dich", "komm eines Tages", "Bring mich von hier", "kalte Erde", "dunkle Erde", "Mir wurde unter dem Stein kalt",
  "Niemand weiß, dass ich hier bin", "Es ist hier sehr schwierig", "Ich kann sowieso nicht gehen", "Ich bin an diese Welt gebunden", "Ich warte immer noch", "Ich kann dich hören, aber ich kann dich nicht sehen",
  "Deine Stimmen kommen, aber sie sind weit weg", "Oh Junge", "Viel Glück", "Gott segne", "bete", "bete",
  "Es gibt Bösewichte", "Sei vorsichtig, mein Baby", "geh nicht in die Irre", "wahr sein", "lebe ehrenhaft", "Respektiere die Ältesten",
  "Rufen Sie einen Verwandten an und fragen Sie", "Flucht vor der Sünde", "Buße tun", "Halal verdienen", "liebt einander", "Es wird keinen Konflikt geben",
  "schlechte Träume", "Ich weine nachts", "Ich kann den Morgen nicht sehen", "Dieses dunkle Wesen ist mir hierher gefolgt", "Ich habe etwas gesehen, bevor ich gestorben bin", "Ich muss dir etwas sagen",
  "Unter dem Haus lauert ein Geheimnis", "Geräusche kommen aus der Erde", "Ich werde um Mitternacht an die Tür klopfen", "Ich werde dich in deinen Träumen besuchen", "Du wirst mich im Schlaf sehen", "Ich werde da sein, wenn deine Augen sich schließen",
  "Ich wünschte, wir hätten mehr Zeit verbracht", "Ich möchte sagen, was ich nicht sagen kann", "Vergib mir, Baby", "Ich habe auch Fehler gemacht", "Ich würde gerne in die Vergangenheit zurückkehren", "Ich wünschte, ich hätte es dir rechtzeitig gesagt",
  "Ich bin zu früh gegangen", "Ich war nicht bereit", "Ich wollte dich nicht verlassen", "Ich befinde mich zwischen dieser Welt und der nächsten Welt", "Ich werde kommen, wenn sich das Tor öffnet", "Du kannst mich während der Mondfinsternis hören",
  "Am Freitagabend bin ich stärker", "Ich sitze auf dem Friedhof und weine", "Die Leute neben mir wollen dich auch sehen", "Dieser Ort ist überfüllt, aber es ist alles ruhig", "Ich renne, wenn ich das Licht sehe, aber ich kann nicht aufholen", "Eines Tages wirst du es auch verstehen",
];

export const GIRL_CHILD_PHRASES: string[] = [
  "spielst du mit mir?", "Ich möchte nicht allein sein", "Warum spielt niemand mit mir?", "Ich habe mein Baby verloren", "Wo sind meine Spielsachen?", "Ich möchte nach Hause gehen",
  "Wo ist meine Mutter?", "Wo ist mein Vater?", "Warten sie auf mich?", "Ich möchte nicht weinen, aber ich weine", "niemand sieht mich", "Bin ich unsichtbar?",
  "Ist hier niemand?", "Ich bin allein hier", "Ich möchte einen Freund", "Kann ich mit dir spielen?", "Ich habe Angst", "Warum ist es dunkel?",
  "Kannst du das Licht anmachen?", "Ich habe etwas gesehen", "er kam wieder", "kommt jede Nacht", "Der Bösewicht kam wieder", "hat mich berührt",
  "Er geht, wenn er schreit.", "Ich schließe meine Augen", "Ich fing an, von hundert bis eins zu zählen", "Da ist jemand hinter mir", "siehst du ihn", "er sieht dich auch",
  "Komm nicht hierher", "es ist gefährlich hier", "es folgt dir auch", "ließ mich hier zurück", "Warum haben sie mich verlassen?", "Die Wände reden",
  "jemand schaut aus dem Fenster", "Ich bin nicht derjenige im Spiegel", "Mein Schatten bewegt sich separat", "Von der Decke kommen Geräusche", "Da ist jemand auf der Treppe, ich betrachte die Schritte", "Mein Hund sieht etwas in der Ecke",
  "Meine Katze ist aus dem Zimmer weggelaufen", "Die Blumen verblassten, nachdem ich eingetreten war", "Genau in diesem Moment blieb die Uhr stehen", "Meine Mutter ruft an", "langsam", "huh",
  "nein nein nein", "Stopp, Stopp, Stopp", "Ich will nicht, ich will nicht", "Ich kann es auch sehen", "Mir wurde kalt", "verlass mich nicht",
  "Umarme mich bitte", "halte meine Hand", "verlass mich nicht", "Ich gehe irgendwohin, während ich schlafe", "Das ist auch in meinem Traum", "Ich bin müde, wenn ich aufwache",
  "was passiert nachts", "Sehen Sie auch nachts seltsame Dinge?", "Es gibt Augen im Dunkeln", "sie warten", "Ich bin zu lange hier geblieben", "Ich möchte jetzt ausgehen",
  "Nimm mich bitte", "Ich möchte dem Licht entgegengehen", "Ich kann nicht durch diese Tür gehen", "etwas blockiert", "Wie heißt du?", "Kann ich dir vertrauen?",
  "Weine nicht, ich weine auch", "Geh weg zu deinem eigenen Besten",
];

export const PHANTOM_PHRASES: string[] = [
  "Ich bin hier", "Kannst du mich hören?", "Hilfe", "Ich kann nicht rausgehen", "wir sind gefangen", "verlass uns",
  "Gehen Sie von dort aus", "Du bist in Gefahr", "er kommt", "weglaufen", "Ihr seid alle in Gefahr", "hörst du",
  "Mir ging es auch wie dir", "jetzt ist es zu spät", "geh nicht", "Dieses Haus hat ein Geheimnis", "Ich bin innerhalb der Mauern", "Hör mir zu",
  "sie sind echt", "niemand hat mir geglaubt", "Jetzt verstehst du es", "das ist die Hölle", "Ich bin im Dunkeln verloren", "gib mir eine Stimme",
  "Unter dem Boden ist ein Raum", "Ich kenne die Geheimtür", "Öffnen Sie die Truhe im Keller nicht", "Wissen Sie, was sich hinter der Mauer verbirgt?", "Der alte Besitzer ist immer noch hier", "Dieses Haus birgt ein hundert Jahre altes Geheimnis",
  "Im Keller weint jemand", "Auf dem Dach sind Schritte zu sehen", "Frequenz anpassen", "Mein Signal ist schwach", "die Verbindung geht verloren", "Ich bin weit weg",
  "Ich kann dich hören", "komm nicht dorthin", "Kanal ist offen", "Ich nehme dich mit", "Ich versuche zu kommunizieren", "zu viel statische Aufladung",
  "Die Frequenz verschiebt sich", "Band wechseln", "Geh am Lärm vorbei, du wirst mich hören", "brauchen Verstärkung", "Schallwelle bricht", "interdimensionale Interferenz",
  "Schau nicht zurück", "schließe die Tür", "Mach das Licht nicht aus", "sei nicht allein", "Zerbrich die Gruppe nicht", "Es gibt eine starke Präsenz",
  "negative Energie ist sehr intensiv", "Das Gebiet ist kontaminiert", "muss gereinigt werden", "Speichern Sie dies", "Schau in die Kamera", "da ist etwas zu deiner Linken",
  "Seien Sie vorsichtig, wenn die Temperatur sinkt", "kannst du atmen", "Ich spreche aus der Ferne", "Meine Stimme erreicht dich kaum", "Die Energie geht zur Neige", "Ich rede mit aller Kraft",
  "Sei ruhig, um mich zu hören", "Hören Sie für eine Sekunde auf zu atmen", "Ich kann in völliger Stille gehört werden", "Ich flüstere, weil sie es nicht hören", "Behalte es unter uns", "andere sollten es nicht wissen",
  "Ich rufe Sie ausdrücklich an", "Sie wurden für diese Aufgabe ausgewählt", "Heute Abend kam jemand Besonderes", "Unter Ihnen ist eine sensible Person", "man ist hier geistig offen", "Finde ihn unter uns",
];

export const HOME_OBJECT_PHRASES: string[] = [
  "Schauen Sie sich den Sitz neben Ihnen an", "Ich habe den linken Sitz gesehen", "Da ist jemand hinter dem Sitz", "Ich sitze gerade auf der Couch", "Ich saß auf deinem Stuhl", "dieser freie Platz ist besetzt",
  "Schauen Sie unter dem Sofa nach", "Neben dem Sitz ist eine Kälte", "Berühren Sie den Sitz noch nicht", "Öffne die dritte Schublade", "Ich habe etwas in der obersten Schublade versteckt", "Du findest mich in der untersten Schublade",
  "Mach die Schublade zu", "Die Schranktür bleibt heute Abend offen", "Da ist jemand im Kleiderschrank", "Öffnen Sie die Schubladen nacheinander", "Bleib in der letzten Schublade", "Schließen Sie den Schrank vor Einbruch der Dunkelheit ab",
  "Schauen Sie nicht unter Ihr Bett", "Da ist etwas unter deinem Kissen", "Ich sitze auf der Bettkante", "Schauen Sie auf Ihr Kissen, wenn Sie morgens aufwachen", "Hör heute Nacht auf, im Bett zu schlafen", "Ich bin unter die Bettdecke gegangen",
  "Wenn Ihr Bett nachts zusammenzubrechen scheint, bin ich der Richtige", "Ich schaue in dein Gesicht, während du schläfst", "Schauen Sie genau in den Spiegel", "In deinem Spiegel sind gerade zwei Gesichter zu sehen", "Ich bin auf der anderen Seite des Spiegels", "Decken Sie den Spiegel nachts ab",
  "Schau aus dem Fenster", "Ich drücke mein Gesicht gegen die Fensterscheibe", "Haben Sie schon einmal Ihre Vorhänge geöffnet und in die Nacht geschaut?", "Schauen Sie sich den Nebel auf dem Glas an", "Öffne heute Nacht nicht das Fenster", "Ich gehe durch die Jalousien hinein",
  "Hast du gesehen, wie ein Schatten unter der Tür vorbeiging?", "Hast du die Tür abgeschlossen?", "jemand geht durch den Flur", "Türgriff dreht sich langsam", "Ich warte vor der Tür", "Ich kann eintreten, ohne zu klingeln",
  "Öffne diese Tür nicht", "ich, wenn die Tür knarrt", "Haben Sie etwas in der Küche fallen hören?", "Ich verhalte mich wie ein Wasserhahn, der tropft", "Das Geräusch des Kühlschranks hat sich verändert, seien Sie vorsichtig", "Sind Sie sicher, dass Sie den Herd ausgeschaltet haben?",
  "Sind Küchenmesser einzeln nummeriert?", "Schauen Sie sich das Glasregal an", "Da ist jemand unter dem Küchentisch", "Ich habe gerade deinen Topf verschoben", "Ich bin neben dir, während du im Badezimmer duschst", "Ich schreibe auf den Dampf in deinem Spiegel",
  "Ich warte hinter dem Duschvorhang", "Es reicht nicht aus, das Badezimmer abzuschließen", "Ich sehe, wie du die Badewanne füllst", "Die Toilettentür bleibt weit geöffnet", "Bald bricht die siebte Sprosse der Treppe", "Ich höre die Stimme aus dem ersten Stock",
  "Oben ist jemand", "Ich hänge im Treppenhaus", "Hast du unten die Türklingel gehört?", "Lauf nicht von der Treppe weg, ich kann dich nicht zurückhalten", "Ich werde bald die Glühbirne ausschalten", "Das Licht blinkt dreimal",
  "Pass heute Abend auf die Lampe auf", "Gehen Sie zur Schalttafel", "Die Lampe in der Ecke ist mein Signal", "Wenn du den Stecker ziehst, wirst du mich nicht finden", "Haben Sie bemerkt, dass Ihre Wanduhr stehen geblieben ist?", "Um drei Uhr morgens klingelt die Uhr",
  "Ich habe diesen Tag im Kalender gestrichen", "Der Minutenzeiger der Uhr bewegt sich rückwärts", "Ich weiß, dass dein Geburtstag bald kommt", "Die dunkelste Ecke des Hauses ist mein Platz", "Schauen Sie sich die untere rechte Ecke des Raumes an", "Ich sitze neben der linken Wand",
  "Schauen Sie sich an, wo die Decke auf die Wand trifft.", "Unter diesem Fleck verbirgt sich ein Geheimnis", "Ziehen Sie den Teppich heraus und schauen Sie nach", "Die Augen dieses Gemäldes sind meine Augen", "Hast du das im Fotorahmen aus der Nähe gesehen?",
];

export const PHONEMES: string[] = [
  "a", "e", "i", "o", "u", "ö",
  "ü", "ı", "ba", "be", "bi", "bo",
  "bu", "bö", "bü", "ca", "ce", "ci",
  "co", "cu", "da", "de", "di", "do",
  "du", "dö", "dü", "fa", "fe", "fi",
  "fo", "fu", "ga", "ge", "gi", "go",
  "gu", "gö", "gü", "ha", "he", "hi",
  "ho", "hu", "ka", "ke", "ki", "ko",
  "ku", "kö", "kü", "la", "le", "li",
  "lo", "lu", "lö", "lü", "ma", "me",
  "mi", "mo", "mu", "mö", "mü", "na",
  "ne", "ni", "no", "nu", "nö", "nü",
  "pa", "pe", "pi", "po", "pu", "ra",
  "re", "ri", "ro", "ru", "rö", "rü",
  "sa", "se", "si", "so", "su", "sö",
  "sü", "ta", "te", "ti", "to", "tu",
  "tö", "tü", "va", "ve", "vi", "vo",
  "vu", "ya", "ye", "yi", "yo", "yu",
  "yö", "yü", "za", "ze", "zi", "zo",
  "zu", "şa", "şe", "şi", "şo", "şu",
  "ça", "çe", "çi", "ço", "çu", "br",
  "kr", "tr", "gr", "pr", "fr", "dr",
  "st", "sk", "sp", "sl", "sm", "sn",
  "ah", "oh", "uh", "eh", "ih", "ay",
  "ey", "oy", "öy", "üy", "aa", "ee",
  "ii", "oo", "uu", "öö", "üü",
];

export const DARK_WORDS: string[] = [
  "Tod", "Seele", "dunkel", "Schatten", "Verdammt", "Angst",
  "Horror", "Hölle", "Grab", "Grab", "Sarg", "Beerdigung",
  "tot", "Geist", "Geist", "Teufel", "Dämon", "Dämon",
  "Geist", "Vampir", "Zombie", "Skelett", "Schädel", "Blut",
  "Schmerz", "schrei", "jammern", "stöhnen", "flüstern", "Stille",
  "Ton", "Schritt", "Donner", "Kälte", "sie traten ein", "Du bist im Gegenteil",
  "Zeitvarianz", "Ergebnis", "Motiv", "aus dem Unbekannten", "Manifestation", "Fata Morgana",
  "Spirale", "beschattet", "Flüsterlinie", "Kältewelle", "Frequenzverschiebung", "statisch",
  "akustisch", "Déjà-vu", "Vision", "Silhouette", "kaputt", "aufgegeben",
  "gesperrt", "Nacht", "Mond", "Vollmond", "Wolke", "Nebel",
  "Rauch", "Dunst", "Finsternis", "Einsamkeit", "aufgeben", "verloren",
  "vergessen", "Gefangener", "gefangen", "gefangen", "Kette", "Schloss",
  "Schlüssel", "Tür", "Fenster", "Spiegel", "Reflexion", "Geheimnis",
  "Geheimnis", "Magie", "Talisman", "Amulett", "böser Blick", "Pech",
  "schwarz", "schwarz", "dunkel", "tief", "Raum", "Klippe",
  "Naja", "unterirdisch", "Keller", "Keller", "Tunnel", "Höhle",
  "Kerker", "Gefängnis", "Knochen", "Fleisch", "Leder", "Wunde",
  "Spur", "Fleck", "Rost", "Schimmel", "Spinne", "Netzwerk",
  "Insekt", "Schlange", "Fledermaus", "Krähe", "Eule", "Wolf",
  "Fuchs", "Schakal", "Hyäne", "Geier", "Skorpion", "Maus",
  "Feuer", "Flamme", "Asche", "Pulver", "Boden", "Schlamm",
  "Sumpf", "Sturm", "Blitz", "Donner", "Erdbeben", "Überschwemmung",
  "Tsunami", "Pest", "Epidemie", "Krankheit", "Gift", "Trank",
  "Hexe", "Zauberer", "Wahrsagerin", "mittel", "Wahrsager", "Schamane",
  "Priester", "Ritual", "Ritual", "Opfer", "Votiv", "Fluch",
  "schwarze Magie", "Pentagramm", "Symbol", "Zeichen", "Inschrift", "Rune",
  "Portal", "Durchgang", "Größe", "parallel", "die andere Seite", "Leben nach dem Tod",
  "Leben nach dem Tod", "Isthmus", "Fegefeuer", "Sirat", "Probebilanz", "grimmiger Sensenmann",
  "Engel", "Dämon", "Entität", "kalt", "Eis", "Frost",
  "Zittern", "chillen", "Federn", "Dorn", "Atem", "blass",
  "keuchend", "grunzen", "brumm", "Summen", "quietschen", "klicken",
  "Knistern", "Rascheln", "klirren", "brutzeln", "heimgesucht", "verfolgen",
  "verbunden", "Anhänger", "Schattenmann", "schwarze Masse", "weißer Schatten", "Kugel aus Licht",
  "Kugel", "Ektoplasma", "Poltergeist", "Ouija", "Holz", "Kerze",
  "Weihrauch", "Kristall", "Globus", "zaubern", "Sitzung", "Medialität",
  "Parapsychologie", "Telepathie", "Vorahnung", "Prophezeiung", "Albtraum", "Schlafwandeln",
  "trans", "Hypnose", "Unterbewusstsein", "astral", "Projektion", "Transmigration",
  "Reinkarnation", "gemischt", "Aura", "Energie", "Vibration", "Frequenz",
  "Welle", "Signal", "Parasit", "Lärm", "Katastrophe", "Zerstörung",
  "Apokalypse", "Apokalypse", "zuletzt", "Chaos", "Chaos", "Unsicherheit",
  "Gefahr", "Bedrohung", "Warnung", "Ausführung", "Galgen", "Henker",
  "Ausführung", "Folter", "mahlen", "Verfall", "Verzerrung", "Zerfall",
  "Aussterben", "Löschung", "vergessen", "verlier dich nicht", "schmelzen", "Aussterben",
  "Verdunkelung", "ertrinken", "brennend", "Einfrieren", "fallen", "sinken",
  "Falle", "Hinterhalt", "Verschwörung", "Intrige", "betrügen", "Verrat",
  "Täuschung", "Lüge", "gefälscht", "gefälscht", "Fiktion", "Traum",
  "Täuschung", "Halluzination", "Illusion", "Wirbel", "Wirbel", "Hurrikan",
  "Schlauch", "Lawine", "Erdrutsch", "Delle", "Zusammenbruch", "Spaltung",
  "knacken", "Klippe", "unten", "Tiefe", "dunkles Loch", "Raum",
  "Nichts", "Abwesenheit", "Ewigkeit", "Ewigkeit", "Stasis", "faul",
  "stinkend", "stinkend", "abgestanden", "tot", "verblasst", "ausgetrocknet",
  "verbrannt", "kaputt", "zerschmettert", "zerquetscht", "vergessen", "aufgegeben",
  "verdammt", "verurteilt", "Nimm Frau", "Albtraum", "Schreckgespenst", "Ghul",
  "Riese", "Vielfraß", "Hexe", "albasti", "Concolos", "Overhead-Projektor",
  "Basilisk", "Drache", "simurgh", "Phönix", "Phönix", "Telekinese",
  "Levitation", "Aufteilung", "Bilokation", "Geistlichkeit", "Vorahnung", "Retrokognition",
  "Psychometrie", "Otoskopie", "Doppelgänger", "Phänomen", "Anomalie", "Abweichung",
  "Störung", "Störung", "schwach", "dunkel", "dunstig", "neblig",
  "bewölkt", "regnerisch", "stürmisch", "windig", "kalt", "Gefrierschrank",
  "überwältigend", "erstickend", "langweilig", "heimgesucht", "beängstigend", "gruselig",
  "gruselig", "beängstigend", "erschreckend", "beängstigend", "geheimnisvoll", "geheimnisvoll",
  "unverständlich", "unerklärlich", "übernatürlich", "außergewöhnlich", "ungewöhnlich", "seltsam",
  "seltsam", "seltsam", "ungewöhnlich", "unerwartet", "plötzlich", "ahnungslos",
  "Geheimnis", "reserviert", "verschleiert", "maskiert", "verkleidet", "versteckt",
  "Abgeschiedenheit", "verfallen", "Geist", "pechschwarz", "Rätsel", "Talisman",
  "abjad", "remil", "Vorwurf", "Manifestation", "endlich", "Lektion",
  "wird", "übertragen", "Unterdrückung", "Zwietracht", "Umgebung", "entente",
  "Rückzug", "traurig", "magisch", "geheimnisvoll", "Sterblichkeit", "Wahrnehmung",
  "Profiteur", "Delirium", "Delirium", "Achtlosigkeit", "Zeichen", "offensichtlich",
  "nach innen", "Ansteckung", "ansteckend", "Dein Schicksal", "Schicksal", "Schicksal",
  "Tortur", "jammern", "sagha", "Nachhall", "Geräusche", "Stimmen aus dem Geheimnis",
  "sonst", "Reflexion", "fließen", "Beschattung", "Illusion", "Silhouette",
  "dunkle Silhouette", "Weißschatten", "verschwommenes Bild", "Kosmos", "dimensional", "zeitlich",
  "räumlich", "universell",
];

export const DARK_PHRASES: string[] = [
  "Komm her", "Hör mich", "hilf mir", "verlass mich nicht", "geh nicht", "Ich bin hier",
  "Ich sehe dich", "schau hinter dich", "Sei vorsichtig", "wie viele", "ich bin gestorben", "finde mich",
  "rette mich", "Ich habe Schmerzen", "Ich bin allein", "wer ist da", "Wer bist du?", "Was willst du?",
  "Warum bist du gekommen?", "Warum bist du hier?", "Was suchst du?", "Wen suchen Sie?", "geh weg", "geh raus",
  "geh raus", "mein Haus", "mein Platz", "Ich beobachte dich", "Ich bin überall", "Du kannst nicht entkommen",
  "Ich werde dich finden", "Ich bin hinter dir her", "Du kannst nicht entkommen", "komm zurück", "komm wieder", "vergiss mich nicht",
  "Denken Sie daran", "Versprechen", "ja", "Nein", "vielleicht", "Ich weiß es nicht",
  "Das kann ich nicht sagen", "Mitternacht", "Morgendämmerung", "Dämmerung", "Vollmondnacht", "drei Uhr",
  "Teufelsstunde", "dunkle Stunde", "öffne die Tür", "Schließen Sie das Fenster", "Mach das Licht aus", "Zünde die Kerze an",
  "bete", "Fluch", "Verdammt", "Mutter", "Vater", "Kind",
  "Baby", "Alter Mann", "alte Frau", "Liebe", "hassen", "Rache",
  "Wut", "Eifersucht", "Verrat", "Mord", "Unfall", "Katastrophe",
  "Tragödie", "Schicksal", "Zeit", "Ewigkeit", "Ewigkeit", "Vergangenheit",
  "Zukunft", "jetzt", "hier", "dort", "oben", "unten",
  "drinnen", "draußen", "Sei ruhig", "Hör zu", "Hör mich", "rede mit mir",
  "antworten", "dieses Haus", "dieses Zimmer", "dieser Ort", "Dieser Ort ist verflucht", "Das ist meins",
  "vergib mir", "beeil dich", "Die Zeit ist knapp", "Deine letzte Chance", "schlafe nicht", "Wach nicht auf",
  "Traum", "Albtraum", "böser Traum", "Stör mich nicht", "in Ruhe lassen", "Fass mich nicht an",
  "kalt", "sehr kalt", "eiskalt", "Ich friere", "Schmerz", "sehr schmerzhaft",
  "Ich kann es nicht ertragen", "lass es jetzt enden", "warum", "warum", "wie", "wann",
  "wo", "dritter Stock", "Keller", "Dach", "Korridor", "unter der Treppe",
  "Spiegel", "schau in den Spiegel", "Reflexion", "von innen nach außen", "um drei Uhr morgens", "umdrehen",
  "Schau nicht hin", "Schließe deine Augen", "halte den Atem an", "Geruch von Blut", "muffiger Geruch", "brennender Geruch",
  "faul", "Schritte", "Tür quietscht", "Glasbruch", "Schreigeräusch", "da ist jemand",
  "hinter mir", "neben mir", "auf mich", "unter mir", "Ich schaue zu", "Ich warte",
  "Ich bin geduldig", "Ich habe Zeit", "der Tod ist nahe", "letzte Nacht", "Abschied", "Auf Wiedersehen",
  "Auf Wiedersehen", "Ich kenne dich", "Ich kenne deinen Namen", "Ich kenne deine Vergangenheit", "Ich kenne dein Geheimnis", "Ich kenne deine Angst",
  "Ich kenne deine Schwachstelle", "Ich habe auf dich gewartet", "Ich wusste, dass du kommen würdest", "Ich bin bereit", "Ich möchte mit dir reden", "Hör mir zu",
  "Ich werde etwas Wichtiges sagen", "vertraue nicht", "vertraue niemandem", "du bist allein", "da ist niemand", "Deine Freunde lügen",
  "Sie mögen dich nicht", "Sie benutzen dich", "Du wirst bald sterben", "Deine Zeit wird knapp", "Deine Uhr tickt", "Ich zähle deinen letzten Atemzug",
  "Dein Grab ist fertig", "Der Sarg wartet", "Trauergebet", "Beerdigung", "Die Erde ist kalt", "dunkel kalt",
  "Dieses Haus hat eine Geschichte", "hier ist jemand gestorben", "Blut wurde vergossen", "Die Wände erinnern sich", "unter der Erde", "begraben",
  "reserviert", "geheimer Raum", "Geheimgang", "hinter der Wand", "über der Decke", "Ich möchte spielen",
  "Sei mein Freund", "Lass uns Verstecken spielen", "Du hast mich gefunden", "Du bist dran", "Verfolge mich", "du kannst nicht fangen",
  "Wo ist meine Mutter?", "Wo ist mein Vater?", "Ich möchte nach Hause gehen", "Ich bin verloren", "Ich kann meinen Weg nicht finden", "Ich habe Angst vor der Dunkelheit",
  "Ich bin sehr alt", "Ich bin müde", "Ich möchte mich ausruhen", "Ich erinnere mich nicht", "Ich habe vergessen, wer ich bin", "Wo bin ich?",
  "wie viel Zeit vergangen ist", "es ist Jahre her", "Es ist Jahrhunderte her", "Ich bin immer noch hier", "Ich kann nicht gehen", "Ich kann nicht loslassen",
  "Ich bin gebunden", "Ich fühle mich wie angekettet", "Ich bin nicht frei", "Verschwinde hier", "Das ist mein Platz", "Du hast Hausfriedensbruch begangen",
  "Ich werde bestrafen", "Du wirst es bereuen", "Du wirst den Preis bezahlen", "Ich habe dich gewarnt", "meine letzte Warnung", "komm nicht wieder",
  "Stör mich nicht", "Störe nicht meinen Frieden", "verlass mich", "Es tut mir so leid", "Ich bereue es", "Ich wünschte, ich hätte es nicht getan",
  "Ich möchte vergeben werden", "Ich bin schuldig", "Ich habe einen Fehler gemacht", "kein Zurück", "es ist zu spät", "jetzt ist es zu spät",
  "Gelegenheit verpasst", "Die Zeit ist vorbei", "alles ist vorbei", "Ich habe eine Nachricht", "Hören Sie aufmerksam zu", "entschlüsseln",
  "Ich gebe einen Hinweis", "Du kommst näher", "Du bist auf dem richtigen Weg", "Du suchst am falschen Ort", "schau weg", "geh tiefer",
  "nicht an der Oberfläche", "unter", "Geheimnis", "verschleiert", "maskiert", "es besteht Gefahr",
  "Sei vorsichtig", "Schauen Sie sich um", "sei nicht allein", "Bleiben Sie nicht im Dunkeln", "Verlasse das Licht nicht", "Schließe die Tür ab",
  "Schließen Sie das Fenster", "ziehe die Vorhänge zu", "Schau nicht in den Spiegel", "dreh dich nicht um", "Geh nicht dorthin, wo die Stimme herkommt", "Energie steigt",
  "Die Vibration nimmt zu", "Die Frequenz ändert sich", "Das Portal öffnet sich", "Der Durchgang ist offen", "interdimensionale Verbindung", "Das Signal wird stärker",
  "Kommunikation wird aufgebaut", "es gibt eine Verbindung", "Nachricht kommt", "Ich antworte", "Ich kann hören",
];

export const SPIRIT_NAMES: string[] = [
  "Hans", "Friedrich", "Wilhelm", "Heinrich", "Karl", "Otto",
  "Ludwig", "Ernst", "Gustav", "Wolfgang", "Albrecht", "Konrad",
  "Reinhard", "Dietrich", "Siegfried", "Hermann", "Bernhard", "Gottfried",
  "Adolf", "Rudolf", "Klaus", "Werner", "Manfred", "Helmut",
  "Günther", "Walther", "Lothar", "Eberhard", "Wilfried", "Theodor",
  "Anselm", "Berthold", "Detlef", "Engelbert", "Ferdinand", "Gerhard",
  "Hartmut", "Joachim", "Kasimir", "Leopold", "Greta", "Helga",
  "Ingrid", "Gerda", "Hilde", "Erna", "Frieda", "Else",
  "Käthe", "Margarete", "Brunhilde", "Adelheid", "Gudrun", "Waltraud",
  "Irmgard", "Roswitha", "Sieglinde", "Hedwig", "Gisela", "Edeltraud",
  "Mathilde", "Wilhelmina", "Bertha", "Klara", "Agnes", "Elsa",
  "Johanna", "Liesel", "Anneliese", "Cäcilia", "Dorothea", "Eleonore",
  "Friederike", "Henriette", "Josefine", "Karoline", "Leonore", "Magdalena",
  "Ottilie", "Philippine", "Rosalinde", "Theodora", "Ursula", "Veronika",
  "Wilfriede", "Adelina", "Brigitta", "Cordula", "Edelgard", "Felizitas",
  "Gertrud", "Hannelore", "Irmtraud", "Jutta", "Kunigunde", "Liselotte",
  "Mechthild", "Notburga", "Ottokar", "Reinhold", "Sebastian", "Thoralf",
  "Ulrich", "Volker", "Waldemar", "Adelbert", "Burkhard", "Diethelm",
  "Egbert", "Frowin", "Gernot", "Hagen", "Ingobert",
];

export const NUMBERS: string[] = [
  "eins", "zwei", "drei", "vier", "fünf", "sechs",
  "sieben", "acht", "neun", "zehn", "elf", "zwölf",
  "dreizehn", "vierzehn", "fünfzehn", "sechzehn", "siebzehn", "achtzehn",
  "neunzehn", "zwanzig", "einundzwanzig", "dreißig", "vierzig", "fünfzig",
  "sechzig", "siebzig", "achtzig", "neunzig", "Gesicht", "Tausend",
  "Null", "Millionen", "Milliarde", "eintausendachthundert", "eintausendneunhundert", "zweitausend",
  "fünfzehntes Jahrhundert", "sechzehntes Jahrhundert", "siebzehntes Jahrhundert", "achtzehntes Jahrhundert", "neunzehntes Jahrhundert", "zwanzigstes Jahrhundert",
];

export const HISTORICAL_WORDS: string[] = [
  "Ottomane", "Sultan", "Sultan", "Königin", "Pascha", "Herr.",
  "Dame", "Palast", "Schloss", "Turm", "Wand", "Graben",
  "Brücke", "Brunnen", "Moschee", "Kirche", "Tempel", "Mausoleum",
  "Madrasa", "Krieg", "Frieden", "Eroberung", "Belagerung", "Sieg",
  "Niederlage", "Knechtschaft", "Schwert", "Schild", "Pfeil", "Speer",
  "Dolch", "Gold", "Silber", "Eisen", "Diamant", "Rubin",
  "Adhan", "Gebet", "Gebet", "Engel", "Geist", "Fee",
  "Drache", "Gasthaus", "Badehaus", "Karawanserei", "aus dem Bedesten", "Markt",
  "Sonntag", "Reich", "Kalifat", "Herrschaft", "Thron", "Krone",
  "Edikt", "tuğra", "Siegel", "Engagement", "Charter", "Janitscharen",
  "Sipahi", "Räuber", "quälen", "levent", "Kapitän", "Chef",
  "Pirat", "Seemann", "Seemann", "Wohnwagen", "Kaufmann", "Verkäufer",
  "Geldwechsler", "Handwerker", "Derwisch", "Sufi", "Mevlevi", "Stachelbeere",
  "naqshbandi", "Lodge", "zawiya", "Lodge", "Chanka", "Ribat",
  "Prinz", "Gültiger Sultan", "haseki", "Konkubine", "kastrieren", "kaiserlicher Palast",
  "Topkapi", "Dolmabahçe", "Stern", "Çırağan", "Galata", "Beyoglu",
  "uskudar", "kadıköy", "Bosporus", "Rumelie", "Anatolien", "Thrakien",
  "Balkan", "Kaukasier", "Hethiter", "Sumer", "Assyrien", "Babylon",
  "Phrygien", "Lidya", "Lykien", "Karie", "Ionien", "Urartian",
  "seldschukisch", "Byzanz", "Rom", "griechisch", "Persien", "mongolisch",
  "Hunne", "Göktürk", "Karachaniden", "Ghaznavid",
];

export const NATURE_WORDS: string[] = [
  "Regen", "Schnee", "Eis", "Wind", "Sturm", "Hurrikan",
  "Blitz", "Blitz", "Wolke", "Mond", "Stern", "Meer",
  "Ozean", "See", "Fluss", "Wasserfall", "Berg", "Höhle",
  "Wald", "Wüste", "Vulkan", "Erdbeben", "Nacht", "tagsüber",
  "Morgendämmerung", "Dämmerung", "Sonne", "Welt", "Planet", "Universum",
  "Galaxie", "Nebel", "Schwarzes Loch", "Komet", "Meteor", "Meteorit",
  "Boden", "Rock", "Stein", "Sand", "Kies", "Baum",
  "Blatt", "Zweig", "Wurzel", "Blume", "Unkraut", "Moos",
  "Pilz", "Flechte", "Efeu", "Wolf", "Bär", "Adler",
  "Schlange", "Skorpion", "Fledermaus", "Eule", "Krähe", "Katze",
  "Hund", "Insekt", "Spinne", "fliegen", "Mücke", "Biene",
  "Fisch", "Delphin", "Hai", "Oktopus", "Qualle", "roh",
  "Frost", "voll", "Dusche", "Nieselregen", "nordöstlich", "Südwesten",
  "Brise", "Sam Wind", "Karayel", "Flut", "Flut", "Welle",
  "aktuell", "Wirbel", "Quelle", "Frühling", "Strom", "Tee",
  "Fluss", "Tal", "Schlucht", "Hals", "Durchgang", "Plateau",
  "Nebelwolke", "Dampf", "Kondensation", "Rand", "Lichtstoß", "Wind",
  "Mönchtum", "Erdrutsch", "Gehirnerschütterung", "Bruchlinie", "Schlitz", "Stalagmit",
  "Stalaktit", "Doline", "Krater", "Lava", "Magma", "Grundwasser",
  "Quellwasser", "Heilwasser", "magischer Frühling", "Schilf", "Teich", "Strom",
  "Bachbett", "Meeresschaum", "Flut", "Milbe", "Leck", "fallen lassen",
  "Schweiß", "Plasma", "Saft", "Harz", "Bernstein", "Fossil",
  "Rock", "mineralisch", "meins", "Erz",
];

export const EMOTION_WORDS: string[] = [
  "Angst", "Horror", "Panik", "Angst", "Angst", "Wut",
  "Groll", "hassen", "Ekel", "Traurigkeit", "Trauer", "Traurigkeit",
  "Sehnsucht", "Einsamkeit", "Verzweiflung", "Verzweiflung", "Schmerz", "Leiden",
  "quälen", "mahlen", "Bedauern", "Gewissen", "Schuld", "Neugier",
  "Erstaunen", "Erstaunen", "Frieden", "Stille", "Ruhe", "Angst",
  "Spannung", "Stress", "Depression", "Depression", "melancholisch", "Nostalgie",
  "Sehnsucht", "Sila", "im Ausland", "Freude", "Glück", "Freude",
  "Begeisterung", "Aufregung", "Hoffnung", "Erwartung", "Wunsch", "Anfrage",
  "Leidenschaft", "Enttäuschung", "Enttäuschung", "lass dich nicht täuschen", "täusche dich nicht", "Zweifel",
  "Zweifel", "Zögern", "Unentschlossenheit", "Unsicherheit", "Mut", "Mut",
  "Heldentum", "Opfer", "Gnade", "Mitgefühl", "Schade", "Empathie",
  "Eifersucht", "Neid", "Neid", "Neid", "schade", "Peinlichkeit",
  "Langeweile", "Langeweile", "Horror", "Brutalität", "Monstrosität", "Grausamkeit",
  "Grausamkeit",
];

export const BODY_WORDS: string[] = [
  "Hand", "Fuß", "Kopf", "Auge", "Ohr", "Mund",
  "Zahn", "Sprache", "Finger", "Hals", "zurück", "Brust",
  "Herz", "Gehirn", "Blut", "Knochen", "Leder", "Atem",
  "Puls", "reißen", "Schulter", "Arm", "Handgelenk", "Handvoll",
  "Nagel", "Knie", "Kalb", "Ferse", "Taille", "Bauch",
  "Leber", "Niere", "Leber", "Lunge", "Magen", "Vene",
  "Nerv", "Muskel", "Sehne", "Gelenk", "Haare", "Augenbraue",
  "Wimpern", "Schnurrbart", "Bart", "Versteh es", "Tempel", "Kinn",
  "Wange", "Nase", "Wirbelsäule", "Rippe", "Schlüsselbein", "Schaufel",
  "Becken", "Schädel", "Kieferknochen", "Jochbein", "Augenhöhle",
];

export const PLACE_WORDS: string[] = [
  "Haus", "Zimmer", "Halle", "Korridor", "Treppen", "Dach",
  "Keller", "Tür", "Fenster", "Wand", "Decke", "Friedhof",
  "Krankenhaus", "Gefängnis", "Wald", "Höhle", "Naja", "Tunnel",
  "Brücke", "Küche", "Badezimmer", "Schlafzimmer", "Wohnzimmer", "Balkon",
  "Garage", "Garten", "Innenhof", "Terrasse", "Veranda", "Kirche",
  "Moschee", "Synagoge", "Tempel", "Kloster", "Schloss", "Palast",
  "Turm", "Kerker", "Keller", "Schule", "Bibliothek", "Museum",
  "Theater", "Oper", "Fabrik", "Lager", "Lager", "Silo",
  "Hangar", "Dorf", "Stadt", "Stadt", "Metropole", "ruinieren",
  "trostlos", "ruinieren", "Trümmer", "Schutt", "Rückstand", "Insel",
  "Halbinsel", "Nase", "setzen", "Hafen", "Bahnhof", "Terminal",
  "Flughafen", "Pier", "Dock", "Park", "Garten", "Hain",
  "Wiese", "Feld", "Bauernhof", "Scheune", "Heuhaufen", "Mühle",
  "Ofen", "Badehaus", "Gasthaus", "Karawanserei", "aus dem Bedesten", "Markt",
  "Mausoleum", "sozialer Komplex", "Madrasa", "Lodge", "zawiya", "Friedhof",
  "Martyrium", "Mausoleum", "Sarkophag", "Sarkophag", "verlassenes Haus", "Spukhaus",
  "verfluchtes Schloss", "Geisterstadt", "tote Stadt", "verlorenes Dorf", "versunkenes Schiff", "verlassenes Krankenhaus",
  "altes Gefängnis", "unterirdische Stadt", "Katakombe", "Katakomben", "Straße", "Schattenmann",
  "Dachboden", "Labyrinth", "Geheimraum", "Schornstein", "Kamin", "unter Treppen",
  "Erdgeschoss", "Unterschlupf", "gewölbte Wand", "Spalte", "Strebe", "Strahl",
  "in der Krypta", "Katakombe", "Denkmal", "Ganzkörperspiegel",
];

export const TIME_WORDS: string[] = [
  "jetzt", "sofort", "danach", "vor", "gestern", "heute",
  "Mitternacht", "Morgen", "Abend", "Nacht", "Morgendämmerung", "Ewigkeit",
  "Ewigkeit", "Vergangenheit", "Zukunft", "Jahrhundert", "Mitternacht", "darüber hinaus",
  "ewig", "sterblich", "Morgendämmerung", "Sonnenwende", "Mondfinsternis", "Sonnenfinsternis",
  "Halbmond", "Dunkelmond", "blutiger Mond", "Sternschnuppe", "Milchstraße", "Konstellation",
  "Polarstern", "Norden", "Süden", "orientieren", "Westen", "Lager",
  "Horizontlinie", "morgen", "am Tag danach", "Woche", "Mond", "Jahr",
  "Jahrhundert", "tausend Jahre", "Ära", "Umsatz", "Zeitraum", "Moment",
  "zweitens", "Minuten", "Uhr", "momentan", "zuerst", "zuletzt",
  "beginnen", "Ende", "endgültig", "Geburt", "Tod", "Leben",
  "Leben", "Leben", "Frühling", "schreiben", "Herbst", "Winter",
  "Saison", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag",
  "Samstag", "Sonntag", "Feiertag", "Öllampe", "Vorabend",
];

export const ACTION_WORDS: string[] = [
  "komm", "geh", "hör auf", "warte", "laufen", "wie viele",
  "verstecken", "schau", "siehe", "Hör zu", "hören", "berühren",
  "fühlen", "reden", "sei still", "flüstern", "schreien", "Weinen",
  "schlafen", "wach auf", "Denken Sie daran", "vergessen", "hungrig", "schließen",
  "Schloss", "schneiden", "Landschaft", "Yak", "löschen", "sterben",
  "geboren", "leben", "verliere dich", "erscheinen", "anrufen", "finden",
  "verlieren", "verstecken", "verstecken", "begraben", "Gans", "geh raus",
  "einsteigen", "klettern", "überspringen", "Traum", "kriechen", "kriechen",
  "gehen", "tanzen", "Rückkehr", "drehen", "biegen", "sich winden",
  "Titer", "Sars", "schüttle es", "multiplizieren", "schlagen", "Hund",
  "überprüfen", "ziehen", "Stein", "Pferd", "essen", "Innenraum",
  "schlucken", "spucken", "Erbrechen", "atmen", "ausatmen", "ertrinken",
  "atmen", "Rose", "Weinen", "schrei", "stöhnen", "jammern",
  "flüstern", "brumm", "grunzen", "knurren", "heulen", "folgen",
  "schau", "ausspionieren", "auf der Lauer liegen", "Angriff", "verteidigen", "schützen",
  "nimm Schutz", "Bar", "Falle", "betteln", "Kragen", "Wunsch",
  "fragen", "Anfrage", "Fluch", "Fluch", "einen Zauber wirken", "Ritual durchführen",
  "eine Sitzung haben", "gestehen", "beichten", "akzeptiere", "leugnen", "ablehnen",
  "verzeihen", "verzeihen", "bestrafen", "Belohnung geben", "bleiben", "Hilfe",
  "Aussichtspunkt", "Aufgabe", "Anmelden", "Ausgang", "Seien Sie ehrlich", "löst sich auf",
  "gesperrt", "kostenlos", "verstecken", "lache nicht", "Rufen Sie an", "Nachverfolgung",
  "bringen", "wegnehmen", "sparen", "hilf mir", "lass es", "behalte es",
  "fangen", "lass nicht los", "vergiss es nicht", "Sag es mir", "schreie", "Rede",
  "Abdeckung", "abschalten", "Siegel", "lösen", "fesseln", "abbrechen",
  "leuchten", "verdunkeln",
];

export const RELIGIOUS_WORDS: string[] = [
  "Allah", "Bismillah", "Mashallah", "hoffentlich", "alhamdulillah", "Adhan",
  "Gebet", "Fasten", "Pilgerreise", "Zakat", "Himmel", "Hölle",
  "Fegefeuer", "Sirat", "Probebilanz", "Engel", "Teufel", "Geist",
  "Dämon", "Houri", "grimmiger Sensenmann", "Michael", "Gabriel", "israfil",
  "Apokalypse", "Apokalypse", "Auferstehung", "veröffentlichen", "ba's", "Qual im Grab",
  "Munkar", "nekir", "Abfrage", "Konto", "gute Tat", "Sünde",
  "Reue", "Vergebung", "Lob", "Sure", "Vers", "Hadith",
  "Beschneidung", "obligatorisch", "Halal", "haram", "ekelhaft", "zulässig",
  "obligatorisch", "Kirche", "Priester", "Priester", "Nonne", "Kreuz",
  "Taufe", "Geständnis", "Ritual", "Kommunion", "Weihwasser", "Rosenkranz",
  "Symbol", "Heiliger", "Heiliger", "Sufi", "Derwisch", "Mentor",
  "Schüler", "Sekte", "Dhikr", "Himmel", "Ekstase", "schlecht",
  "Überlebensfähigkeit", "Entdeckung", "Inspiration", "Wunder", "Wunder", "Magie",
  "böser Blick", "Auge", "böser Blick", "Neid", "Magie", "Amulett",
  "Talisman", "vefk", "hamail", "kopieren", "besessen", "Sara",
  "Berührung mit dem bösen Blick", "Faszination", "Nekromantie", "Metapher", "Traumdeutung", "Wahrsagerei",
  "Kaffee-Vermögen", "Tarot", "Astrologie", "Horoskop", "Horoskop",
];

export const PARANORMAL_TERMS: string[] = [
  "EMF", "Detektor", "Sensor", "Meter", "Radar", "Kamera",
  "Wärmebildkamera", "Nachtsicht", "Infrarot", "Ultraviolett", "Mikrofon", "Rekorder",
  "Stimmanalyse", "Frequenzanalyse", "Geisterbox", "Geisterbox", "Franks Box", "ovilus",
  "SLS-Kamera", "Kinect", "Lidar", "Tiefensensor", "K2 Meter", "Mel-Meter",
  "rem pod", "Bewegungssensor", "Wünschelrute", "Pendel", "Ouija-Brett", "Planchette",
  "EVP", "Klangphänomen", "elektronischer Klang", "statisches Rauschen", "Erscheinung", "erscheinen",
  "Bild", "Silhouette", "Schattenfigur", "kalter Ort", "kalter Ort", "Hotspot",
  "Anomalie", "Kugel", "Kugel aus Licht", "Lichtlinie", "Lichtstoß", "Poltergeist",
  "Telekinese", "Levitation", "Aufteilung", "Ektoplasma", "Ektoplasmabildung", "Materialisierung",
  "Ganzkörpererscheinung", "teilweise Erscheinung", "Schattenmensch", "verbleibender Spuk", "Intelligentes Spuken", "dämonischer Spuk",
  "Portal spukt", "Dimensionsübergang", "Zeitverschiebung", "Untersuchung", "Forschung", "Rezension",
  "Entdeckung", "Beobachtung", "Beweise", "Beweise", "finden", "Daten",
  "Analyse", "Bericht", "Registrierung", "Dokument", "Datei", "Archiv",
  "Sitzung", "Sitzung", "experimentieren", "testen", "Kontrolle", "Hypothese",
  "Theorie", "Ergebnis", "Kommentar", "Bewertung", "Magnetfeld", "Fluktuation",
  "statisches Rauschen", "weißes Rauschen", "Rosa Rauschen", "Frequenzabschaltung", "Signalverlust", "Datenstrom",
  "Verzerrung", "Energiestoß", "Ionisierung", "thermischer Abfall", "plötzliche Abkühlung", "Schaukel",
  "elektromagnetisch", "Strahlung", "Wellenlänge", "Scan-Rate", "Kanal-Hopping", "umgekehrte Stimme",
  "Spiegeleffekt", "Echokammer", "Schallwand", "Unterdrückung", "Filterung", "isoliert",
  "isoliert", "geschützt", "versiegelter Raum", "Quarantäne", "Kontamination", "Interaktion",
  "Auslöser", "Aktivierung", "Automatische Aufnahme", "Graph-Peak", "Frequenzspitze", "Sensor",
  "Browser", "Überwachungspanel", "globale-daten", "Standort", "koordinieren", "Höhe",
  "Druck", "atmosphärisch", "Feuchtigkeitsgehalt", "Rußgeruch", "Schwefel", "Ozon",
  "Brandgeruch", "Luftfeuchtigkeit", "Windkorridor", "Luftstrom", "aktuell", "statische Belastung",
  "Aufladen", "Entladung", "Batterieverbrauch", "Energieabsorption", "Spannung", "aktuell",
  "Widerstand", "Kondensator", "Spule", "Relais", "Leistungsschalter", "Kurzschluss",
  "Erdung", "Isolator", "leitfähig", "Halbleiter", "Quarz", "Objektiv",
  "Fokussierung", "reflektierend", "Pause", "Lichtbrechung", "Spektrum",
];

export const OBJECT_WORDS: string[] = [
  "Kerze", "Öllampe", "Laterne", "Lampe", "Fackel", "Spiegel",
  "Glas", "Kristall", "Globus", "Prisma", "Buch", "Notizbuch",
  "Brief", "Karte", "Kompass", "Uhr", "Glocke", "Glocke",
  "Pfeife", "Rohr", "Seil", "Kette", "Seil", "Seil",
  "Draht", "Messer", "Schwert", "Dolch", "Axt", "Hammer",
  "Stein", "Marmor", "Granit", "Obsidian", "Amethyst", "Silber",
  "Gold", "Kupfer", "Eisen", "führen", "Salz", "Wasser",
  "Feuer", "Boden", "Wetter", "Bild", "Foto", "Porträt",
  "Tisch", "Statue", "Spielzeug", "Baby", "Marionette", "Maske",
  "Kostüm", "Krone", "klingeln", "Halskette", "Armband", "Brosche",
  "Brust", "Box", "Tasche", "Koffer", "Korb", "Teppich",
  "Teppich", "Vorhang", "Abdeckung", "Decke", "Vase", "Platte",
  "Glas", "Schüssel", "Topf", "Gebetbuch", "Rosenkranz", "Kreuz",
  "Amulett", "böser Blick", "quietschen", "Türgriff", "Schlosszunge", "Schlüsselloch",
  "rostige Kette", "Vorhängeschloss", "Grabstein", "Büste", "altes Foto", "Leinwand",
  "Fresko", "Tapete", "zerrissen", "Glasscherben", "Fenstervorhang", "Tüll",
  "Spitze", "Mitgifttruhe", "altes Spielzeug", "Porzellanpuppe", "Wiege", "Schaukelstuhl",
  "Uhrpendel", "Wanduhr", "Kettenuhr", "Stoppuhr", "Sanduhr", "Gaslampe",
  "Kerzenhalter", "Institution", "Arbeit", "Staubwolke", "Spinnennetz", "Haarsträhne",
  "Kleidung", "Umhang", "Blutspur", "Feuchtigkeitsfleck", "Geruch", "muffiger Geruch",
  "antikes Buch", "Manuskript", "Pergament", "Lederbezug", "Tinte", "Tintenfass",
  "Bleistift", "Umschlag", "Siegellack", "Stempel", "Wappen", "Medaillon",
];

export const ADJECTIVE_WORDS: string[] = [
  "dunkel", "hell", "schwach", "hell", "langweilig", "kalt",
  "heiß", "warm", "eisig", "heiß", "alt", "neu",
  "uralt", "uralt", "zeitgenössisch", "groß", "klein", "gigantisch",
  "winzig", "klein", "lang", "kurz", "breit", "schmal",
  "tief", "schwer", "Licht", "dick", "dünn", "hart",
  "weich", "rau", "rutschig", "klebrig", "trocken", "nass",
  "feucht", "feucht", "schimmelig", "faul", "schön", "hässlich",
  "beängstigend", "beängstigend", "heimgesucht", "still", "laut", "ruhig",
  "friedlich", "unruhig", "schnell", "langsam", "plötzlich", "allmählich",
  "ständig", "unsichtbar", "transparent", "undurchsichtig", "verschwommen", "klar",
  "leben", "tot", "leblos", "bewegungslos", "gefroren", "verflucht",
  "heilig", "schmutzig", "sauber", "rein", "komplex", "einfach",
  "geheimnisvoll", "offen", "geschlossen", "echt", "gefälscht", "imaginär",
  "imaginär", "surreal", "flüstern", "warten", "weit weg", "schließen",
  "reserviert", "Talisman", "Einsiedler", "wütend", "unruhig", "allein",
  "Angst", "sprachlos", "ängstlich",
];

export const MANIPULATIVE_RESPONSES: string[] = [
  "ja", "Nein", "vielleicht", "kann sein", "niemals", "auf jeden Fall",
  "wahrscheinlich", "Das glaube ich nicht", "Ich bin mir nicht sicher", "wahr", "falsch", "teilweise",
  "manchmal", "immer", "niemals", "selten", "oft", "normalerweise",
  "schau richtig", "schau nach links", "schau nach oben", "schau nach unten", "schau hinter dich", "schau nach vorne",
  "Schauen Sie sich um", "Schau dir die Wand an", "geh zur Tür", "geh zum Fenster", "geh in den Keller", "geh aufs Dach",
  "geh raus", "komm rein", "Komm näher", "geh weg", "Schritt...", "mein Alter...",
  "Ich bin hier gestorben", "Ich habe hier gelebt", "Ich bin schon lange hier", "Ich habe hundert Jahre gewartet", "Ich habe auf dich gewartet", "Du hättest kommen sollen",
  "Schicksal", "Hab keine Angst", "Du solltest Angst haben", "Du bist nicht in Gefahr", "Du bist in Gefahr", "Du bist in Sicherheit",
  "Du bist nicht sicher", "Du bist nicht allein", "du bist allein", "Du wirst geliebt", "Du wirst nicht geliebt", "Du bist vergessen",
  "Du bleibst in Erinnerung", "die Zeit wird kommen", "Sei geduldig", "warte", "sei bereit", "Du wirst es bald verstehen",
  "alles wird erklärt", "wird ein Geheimnis bleiben", "Das kann ich nicht sagen", "verboten", "keine Erlaubnis", "Es gibt eine Grenze",
  "hinter dir", "daneben", "oben", "Ich habe es gesehen", "Du hast es gehört", "nähert sich",
  "berühren", "Empörung", "Vorfall", "verlorene Seele", "wir", "sie",
  "niemand", "Besucher", "habe", "Eigentum", "Treuhandkonto", "alt",
  "Ich weiß", "Du hast es gesehen", "Ich habe mich versteckt", "war hier", "sie gingen", "aufgewacht",
  "schlafen", "in der Tiefe", "weg", "Dein Name", "Ich habe begraben", "Ich habe es abgenommen",
  "Ich habe verloren", "Ich habe es gefunden", "Ich suche", "Ich komme", "Ich gehe", "Ich blieb",
  "ich bin gestorben", "Ich lebe", "bald", "direkt hinter dir", "auf der rechten Seite", "auf der linken Seite",
  "auf", "dazwischen", "in", "darüber hinaus", "beri-yakada", "gegenüber",
  "an der Grenze", "Wer bist du?", "Wie heißt du?", "Was willst du?", "Warum bist du hier?", "Wie viele seid ihr?",
  "Wann bist du gekommen?", "Wie-bist-du-gestorben?", "hörst du uns?", "Willst du Hilfe?", "sollen wir gehen",
];

export const LONG_PHRASES: string[] = [
  "Du bist heute Abend hier nicht allein", "Jemand lebt hinter den Mauern", "Ich komme jeden Abend zur gleichen Zeit", "Ich habe dich schon lange beobachtet", "Dieses Haus hat eine Geschichte", "Hier wurde viel Blut vergossen",
  "Niemand ist hier lebend rausgekommen", "Du wirst nicht der Letzte sein, der kommt", "Es hilft nicht, die Tür abzuschließen", "Ich bin die ganze Zeit überall", "Wenn du deine Augen schließt, siehst du mich", "Ich werde dich in deinen Träumen besuchen",
  "Sei wach, weil ich wach bin", "Schlaf heute Nacht nicht, schlaf nicht", "Hörst du deine Schritte?", "Der Schatten hinter dir ist nicht meiner", "Wenn du in den Spiegel schaust, wirst du mich sehen", "Ich bin die Stimme, die von der Decke kommt",
  "Da ist etwas im Keller", "jemand läuft auf dem Dach", "Ich sah einen Schatten im Garten", "jemand schaut aus dem Fenster", "Die Tür öffnete sich von selbst", "Lichter blinken",
  "Die Uhr blieb um drei Uhr morgens stehen", "Der Spiegel ist von alleine kaputt gegangen", "Blut tropft aus der Wand", "Vom Boden kommen Geräusche", "Es ist kein Wasser, es ist Blut, das von der Decke tropft", "Die Person auf dem Foto hat sich bewegt",
  "Die Puppe lächelte", "Jemand kommt die Treppe herunter", "Am Ende des Korridors steht jemand", "Hände greifen unter das Bett", "Jemand atmet im Schrank", "Hinter dem Vorhang ist eine Silhouette zu sehen",
  "Augen leuchten im Dunkeln", "Das Bild an der Wand beobachtet dich", "Deine Uhr hat aufgehört zu ticken", "Das Telefon klingelte, aber niemand war da", "Seltsame Geräusche kommen aus dem Radio", "Der Fernseher schaltete sich von selbst ein",
  "Auf dem Computerbildschirm erschien ein Gesicht", "Blut fließt aus dem Wasserhahn", "Ich habe kein Spiegelbild", "Mein Schatten bewegt sich unabhängig von mir", "Dies ist der Ort, den ich in meinen Träumen gesehen habe", "Ich war schon einmal hier",
  "Ich hatte diesen Moment schon einmal", "Ich bin in einer Zeitschleife", "Von hier aus gibt es keinen Ausweg", "Türen verschlossen, Fenster geschlossen", "Die Wände begannen zu schrumpfen", "die Decke senkt sich",
  "der Boden bricht zusammen", "das Wetter wird kälter", "Ich kann meinen Atem sehen", "etwas berührte mein Bein", "Mir wurden die Haare gezogen", "flüsterte mir ins Ohr",
  "Ich spürte einen kalten Atem an meinem Hals", "eine Hand berührte meine Schulter", "jemand schubst mich von hinten", "Mein Fuß blieb irgendwo hängen", "Etwas bewegte sich im Dunkeln", "Ein Schatten erschien in der Ecke und verschwand",
  "Es ist kein Staub, sondern Asche, die von der Decke regnet", "Die Uhr an der Wand geht rückwärts", "Aus dem Spiegel erscheint ein weiterer Raum", "Das Ende der Treppe öffnet sich in die Dunkelheit", "Dieser Korridor hat kein Ende", "Jedes Mal, wenn ich die Tür öffne, komme ich in denselben Raum",
  "kann nicht aus dem Fenster sehen", "Draußen gibt es nichts, nur Dunkelheit", "In diesem Raum wurde schon einmal jemand gehängt", "Unter dem Bett ist eine Leiche begraben", "In den Wänden befinden sich Knochen", "Das Fundament dieses Hauses wurde auf einem Friedhof errichtet",
  "Nachts kommen Geräusche von den Wänden", "Bei jedem Vollmond passieren seltsame Dinge", "Nachbarn bleiben diesem Haus fern", "Jeder, der hier lebt, ist verrückt geworden", "Der letzte Mieter ist verschwunden", "Selbst die Polizei darf dieses Haus nicht betreten",
  "Selbst der Imam konnte dieses Haus nicht reinigen", "Der Lehrer kam, rannte aber weg", "Die hier durchgeführten Rituale werden noch immer fortgesetzt", "Um drei Uhr morgens sind Schreie zu hören", "Kinder kommen an diesem Haus nicht vorbei", "Katzen kommen nicht in die Nähe dieses Hauses",
  "Hunde bellen vor diesem Haus", "Vögel fliegen nicht über dieses Haus", "Um dieses Haus herum trocknen Bäume", "In diesem Garten blühen keine Blumen", "Die Sonne kommt nicht in dieses Haus", "Die Uhr bleibt jede Nacht um drei Uhr stehen",
  "Spiegel gehen von alleine kaputt", "Kerzen brennen von selbst", "Türen öffnen und schließen automatisch", "Der Stuhl bewegt sich von selbst", "Die Augen der Gemälde folgen Ihnen", "Der Fleck an der Wand wird von Tag zu Tag größer",
  "Der Riss in der Decke sieht aus wie ein Gesicht", "Der Blutfleck auf dem Boden kann nicht gelöscht werden", "Die Luft in diesem Raum ist immer kalt", "Elektronische Geräte funktionieren hier nicht", "Hier wird der Akku Ihres Telefons schnell entladen.", "Der Kompass spielt hier verrückt",
  "Die Uhren zeigen hier falsch", "Die Kamera funktioniert hier nicht", "Auf den aufgenommenen Fotos sind seltsame Formen zu erkennen", "Es gibt jemanden, der in den Videos nicht zu sehen ist", "In den Audioaufnahmen gibt es Flüstern", "Das EMF-Messgerät spielt hier verrückt",
  "die Temperatur sinkt plötzlich", "Es liegt ein seltsamer Geruch in der Luft", "Muffiger Geruch, aber kein Schimmel", "Brandgeruch, aber kein Feuer", "Der Duft von Blumen, aber es gibt keine Blumen", "Es riecht nach Parfüm, aber niemand ist da",
];

export const MYTHOLOGY_WORDS: string[] = [
  "Nimm Frau", "Albtraum", "Schreckgespenst", "Ghul", "Riese", "Vielfraß",
  "albasti", "Concolos", "Overhead-Projektor", "Basilisk", "Hıdırellez", "Nowruz",
  "Ergenekon", "grauer Wolf", "asena", "Hauptberg", "Tuba-Baum", "Wasser des Lebens",
  "Wasser der Unsterblichkeit", "Phönix", "Phönix", "simurgh", "Windpferd", "Windfee",
  "Nymphe", "Bergfee", "Dryade", "böser Blick", "böser Blick", "bündig",
  "besessen", "Werwolf", "Nachteule", "Eule schreit", "schwarze Katze", "vierzig Zentimeter",
  "Mutterschaft", "Holen Sie sich Frau-Pushs", "Wunschbaum", "Wunschbrunnen", "Ort des Opfers", "leg dich hin",
  "Heiliger", "Heiliger", "Elternteil", "pir", "Großvater", "Cinci-Lehrer",
  "Zauberin", "Wahrsagerin Oma", "definieren", "Beerdigung", "Schatz", "Goldwürfel",
  "verfluchter Schatz", "Schutzgeist", "Schatzhüter", "talismanische Tür", "Zauberspiegel", "fliegender Teppich",
  "Unsichtbarkeit", "Unsterblichkeit", "Elixier der Jugend", "tote Waschmaschine", "Leichentuch", "Musalla-Stein",
  "Leichenwagen", "Grabstein", "Grabstein", "Fußstein", "Sarkophag", "Sarkophag",
  "Mausoleum", "Käfig", "Mausoleum", "Massengrab", "verlorenes Grab", "unmarkiertes Grab",
  "Nachtfriedhof", "verlassener Friedhof",
];

export const FOLK_BELIEFS: string[] = [
  "Perle des bösen Blicks", "Amulett schreiben", "Blei gegossen", "brennender Weihrauch", "ein Gelübde ablegen", "Wünsch dir nichts",
  "Traumdeutung", "Wahrsagerei", "Kaffee-Vermögen", "Handlesen", "Horoskop", "Wasser-Wahrsagerei",
  "Spiegelmagie", "Kerzenmagie", "Seilmagie", "Bindungszauber", "Trennungszauber", "Liebeszauber",
  "schwarze Magie", "weiße Magie", "Geistermagie", "Heiler", "Geist", "Amulettmacher",
  "Zauberer", "Zauberer", "Jongleur", "Illusionist", "Nekromantie", "Flip-Glas",
  "hält einen Bleistift", "Drehtisch", "Ouija-Brett", "Spiritboard", "Lade keinen Geist ein", "Exorzismus",
  "Binde keinen Gin", "Zauber", "afsun", "Lesen", "weht", "atme nicht",
  "Wasser lesen", "Heilung", "Blickkontakt", "Berührung mit dem bösen Blick", "Zungenberührung", "böser Geist",
  "guter Geist", "Schutzgeist", "Ahnengeist", "Großvatergeist", "Oma-Geist", "Hauself",
  "Badegeist", "Wassergeist", "Feuergeist", "Erd-Elf", "Wettergeist", "Muslimischer Dschinn",
  "ungläubiger Geist", "Geist in der Liebe",
];

export const HORROR_STORY_WORDS: string[] = [
  "Jump-Scare", "Spannung", "Angst", "Horror", "Panik", "Flucht",
  "jagen", "Hinterhalt", "Falle", "Falle", "Opfer", "Jäger",
  "Beute", "folgen", "Schatten", "quietschende Tür", "knisterndes Holz", "raschelndes Blatt",
  "heulender Wind", "heulende Pfeife", "klapperndes Fenster", "klingelndes Ohr", "pochender Kopf", "Hände schütteln",
  "gedämpfte Stimme", "verhaftete Sprache", "Blut gefrieren", "borstige Feder", "flauschige Feder", "zitternde Haut",
  "Herzklopfen", "kalter Schweiß", "Zittern", "Kontraktion", "Kurzatmigkeit", "Schwindel",
  "Übelkeit", "verschwommenes Sehen", "Tinnitus", "Taubheitsgefühl", "sei nicht gelähmt", "nicht einfrieren",
  "Steinschnitt", "Levitation", "Telekinese", "Selbstentzündung", "Gestaltwandlung", "Dimensionssprung",
  "Zeitreise", "Seelentrennung", "außerkörperliche Erfahrung", "Astralreisen", "Bewusstseinsübertragung", "Gedankenkontrolle",
  "Hypnose", "Massenhysterie", "kollektive Halluzination", "verfluchter Spiegel", "verfluchtes Baby", "verfluchter Ring",
  "verfluchtes Buch", "verfluchte Malerei", "verfluchtes Juwel", "verfluchter Dolch", "verfluchte Krone", "verfluchte Brust",
  "verfluchte Karte", "verfluchter Kompass", "verfluchte Uhr",
];

export const DIALOG_PHRASES: string[] = [
  "Hallo", "Hallo", "Willkommen", "Ich habe auf dich gewartet", "Endlich bist du gekommen", "Du bist zu spät",
  "Wo warst du?", "Mir gehört dieser Ort", "Ich bin die Seele dieses Hauses", "Ich bin hier gestorben", "Ich bin hier begraben", "Ich kann meinen Namen nicht sagen",
  "Ich habe meinen Namen vergessen", "keine Schritte mehr", "Ich habe nie existiert", "Ich bin eine Erinnerung", "Ich bin ein Echo", "Verschwinde jetzt von hier",
  "Bleib heute Nacht nicht hier", "geh, bevor die Sonne untergeht", "Gehen Sie vor Einbruch der Dunkelheit", "bis Mitternacht gehen", "vor drei Uhr abreisen", "Betreten Sie diesen Raum nicht noch einmal",
  "Öffne diese Tür nicht noch einmal", "Schauen Sie nicht noch einmal in diesen Spiegel", "Sagen Sie diesen Namen nicht noch einmal", "Es war einmal eine Familie, die hier lebte", "Dieses Haus wurde vor hundert Jahren gebaut", "Hier gab es ein Feuer",
  "Hier wurde ein Mord begangen", "hier ist ein Kind verloren gegangen", "Hier hat eine Frau Selbstmord begangen", "Hier ist ein Mann verrückt geworden", "Hier wurde ein Ritual abgehalten", "Hier ist ein Schatz vergraben",
  "Hier begann ein Fluch", "Ich werde dich hier behalten", "du wirst nie gehen", "Du wirst bei mir bleiben", "hier für immer", "es gibt kein entkommen",
  "kein Ausgang", "es gibt keine Erlösung", "Es hilft nicht, zu beten", "niemand kann dich retten", "Selbst wenn du schreist, wird es niemand hören", "Bitte geh nicht",
  "lass mich nicht allein", "Ich bin so einsam", "niemand kommt", "Ich warte schon seit Jahren", "Ich bin seit Jahrhunderten allein", "Ich brauche einen Freund",
  "Ich möchte mit jemandem reden", "Du bist der Erste, der meine Stimme hört", "Du bist der Erste, der mich sieht",
];

export const PROVERBS: string[] = [
  "Recht auf Tod", "Jedes Lebewesen wird den Tod schmecken", "Der Tod ist auf der Welt, Kopfschmerzen sind eine Ausrede", "Das Grab ist dunkel", "Die Erde ist kalt", "die Nacht ist lang",
  "der Morgen ist weit", "Angst nützt dem Tod nichts", "Jede Dunkelheit hat ein Ende", "Feuer brennt dort, wo es fällt", "Wasser schläft, der Feind schläft nicht", "Wer außer Sichtweite ist, ist außer Verstand",
  "Erwarte nicht, dass die Toten von den Lebenden kommen", "Sucht nach dem, was kommt und geht", "alles hat ein Ende", "Geduld ist bitter, aber ihre Frucht ist süß", "sie nennen die Vergangenheit Vergangenheit", "Aus alten Freunden werden keine Feinde",
  "Was mit Blut getan wird, kann nicht gereinigt werden", "jagt Tag und Nacht", "Dunkelheit verschluckt das Licht", "Stille ist der lauteste Schrei", "Der Tod klopft nicht an die Tür, er tritt ein", "Grabsteine reden nicht, aber sie erzählen",
  "Wind bläst Äste brechen", "Wasser fließt und findet seinen Weg", "Ohne Feuer gibt es keinen Rauch",
];

export const COLOR_LIGHT_WORDS: string[] = [
  "rot", "blau", "grün", "gelb", "orange", "lila",
  "rosa", "weiß", "schwarz", "grau", "braun", "beige",
  "Sahne", "Gold", "Silber", "Burgund", "dunkelblau", "türkis",
  "Magenta", "lila", "blutrot", "Mitternachtsblau", "Giftgrün", "Aschegrau",
  "Licht", "dunkel", "Schatten", "hell", "Dunkelheit", "Helligkeit",
  "matt", "undurchsichtig", "transparent", "durchscheinend", "Neon", "fluoreszierend",
  "phosphoreszierend", "leuchtend", "verblassen", "blinkt", "vibrierend", "zwinkert",
  "schwankend", "scharlachrot", "Nimm es", "Infrarot", "Moral", "Ultraviolett",
];

export const WEATHER_WORDS: string[] = [
  "es regnet", "es schneit", "es hagelt", "der Sturm kommt", "der Wind weht", "Hurrikan naht",
  "Blitzeinschläge", "Donner donnert", "Der Blitz schlug ein", "der Nebel ist gefallen", "es gibt Dunst", "es gibt Rauch",
  "es wird dunkel", "die Sonne geht unter", "der Mond geht auf", "Sterne erscheinen", "es ist Vollmond", "Neumond",
  "der Schatten wird länger", "Die Dunkelheit bricht herein", "die Nacht beginnt", "Kältewelle", "Hitzewelle", "die Luftfeuchtigkeit steigt",
  "Druck fällt", "Die Luft wird schwer", "glühend heiß", "eiskalt", "frostig", "Frost",
  "roh",
];

export const SOUND_WORDS: string[] = [
  "Melodie", "Melodie", "Lied", "Volkslied", "Klage", "Schlaflied",
  "Hymne", "munaat", "Adhan", "Sala", "Trommel", "zurna",
  "was", "Oud", "Gesetz", "Geige", "Klavier", "Orgel",
  "Glocke", "Glocke", "flüstern", "Murmeln", "grunzen", "keuchend",
  "Rascheln", "quietschen", "klicken", "Knistern", "Aufregung", "Lärm",
  "brumm", "Summen", "brutzeln", "klirren", "Knirschen", "Explosion",
  "Zusammenbruch", "Zusammenbruch", "brechen", "Zerfall", "Echo", "Öko",
  "Resonanz", "Vibration", "Frequenz", "Ultraschall", "Infraschall", "weißes Rauschen",
  "Rosa Rauschen", "Stille", "Ruhe", "Frieden", "Gelassenheit", "Rezession",
  "Lachen", "Weine nicht", "schrei", "jammern", "jammern", "Stöhnen",
  "jammern", "bettel nicht", "Flehen", "Gebet",
];

export const QUANTITY_WORDS: string[] = [
  "wenig", "viel", "ein bisschen", "ziemlich viel", "ziemlich viel", "genug",
  "unzureichend", "zu viel", "fehlt", "voll", "die Hälfte", "Viertel",
  "ein Drittel", "ein Viertel", "Single", "Paar", "mehrere", "viele",
  "unzählige", "unendlich", "unbegrenzt", "begrenzt", "eingeschränkt", "zuerst",
  "zuletzt", "mittlere", "führend", "hinterher", "zuerst", "zweitens",
  "Dritter", "Vierter", "Fünfter", "Sechster", "siebter", "Achter",
  "neunte", "Zehntel",
];

export const COMMUNICATION_WORDS: string[] = [
  "reden", "Hör zu", "Sag es mir", "fragen", "antworten", "schreiben",
  "lesen", "zeichnen", "darauf hinweisen", "zeigen", "Nachricht", "Brief",
  "Hinweis", "Schreiben", "Zeichen", "Symbol", "Code", "Passwort",
  "Schlüssel", "Hinweis", "Sprache", "Sprache", "polieren", "Mund",
  "Dialekt", "Präferenz", "Übersetzung", "Bedeutung", "Bedeutung", "Kommentar",
  "Versprechen", "Wort", "Satz", "Absatz", "Text", "Geschichte",
  "Märchen", "Legende", "Mythos", "episch", "Poesie", "Ode",
  "Ghazal", "rubai", "Couplet", "Gebet", "Fluch", "Eid",
  "Eid", "Versprechen", "Geheimnis", "geheime Nachricht", "verschlüsselte Nachricht", "Geheimtext",
  "unsichtbare Tinte", "geheimer Text", "umgekehrter Text",
];

export const RELATIONSHIP_WORDS: string[] = [
  "Mutter", "Vater", "Sohn", "Mädchen", "Bruder", "Bruder",
  "Schwester", "Onkel", "Onkel", "immer noch", "Tante", "Neffe",
  "Cousin", "Enkelkind", "Großvater", "Oma", "Oma", "Großvater",
  "Schwiegermutter", "Schwiegervater", "Frau", "Ehemann", "Frau", "Liebling",
  "verlobt", "Feind", "Rivale", "Gegner", "Opposition", "gegenüber",
  "Freund", "Freund", "Kamerad", "Bruder", "Vertrauter", "Nachbar",
  "vertraut", "Ausländer", "Gast", "Gast", "Diener", "Butler",
  "Konkubine", "Sklave", "Herr", "Herrscher", "König", "Königin",
  "Prinz", "Prinzessin",
];

export const WHISPER_PHRASES: string[] = [
  "pssst", "hallo", "Schau mich an", "hier", "Hör mich", "sehen Sie mich",
  "fühle mich", "Berühre mich", "Komm näher", "Komm näher", "Gib dein Ohr", "sssh",
  "Sei ruhig", "niemand sollte es hören", "langsam drehen", "schau langsam", "Ich habe ein Geheimnis", "Ich werde dir etwas sagen",
  "erzähl es niemandem", "Behalte es unter uns", "dieses Geheimnis", "Ich habe dich gewählt", "Du bist etwas Besonderes", "Du bist anders",
  "Du bist anders als andere", "Ich verstehe dich", "Du bist der Einzige, der mich versteht", "wir haben eine Bindung", "Deine Augen sehen etwas anderes", "Du kannst mich fühlen",
  "Andere können es nicht hören, aber Sie schon", "Unser Schicksal ist eins", "wir sind miteinander verbunden", "du kannst es nicht vermeiden", "geschrieben", "Schicksal",
  "Alles hat einen Grund", "kein Zufall", "Ich wollte, dass du hierher kommst", "Ich habe dich angerufen", "Meine Einladung wurde angenommen", "Willkommen in meinem Zuhause",
  "Ich habe so lange auf dich gewartet", "Du bist gerade rechtzeitig gekommen", "Du bist jetzt hier", "Du gehörst jetzt mir", "Ich werde dich nicht gehen lassen", "für immer",
  "wir werden zusammen sein", "wir werden nicht gehen", "Du bist mein letzter Gast", "Niemand ist hier wieder weggegangen", "Du wirst dich in diesem Haus verlaufen", "Wir sehen uns in deinen Träumen",
  "Ich werde in deinem Schlaf kommen", "Ich bin nachts hier", "Ich lebe im Dunkeln", "Ich habe Angst vor dem Licht", "Die Sonne verbrennt mich", "Die Nacht ist meine Zeit",
  "Dunkelheit ist mein Haus", "Nach Sonnenuntergang werde ich stärker", "Um drei Uhr morgens bin ich am stärksten", "Ich werde morgen früh verschwinden, aber warte bis zur Nacht", "Ich kenne deinen Namen", "Ich weiß, wo du wohnst",
  "Ich kenne deine Familie", "Ich kenne deine Vergangenheit", "Ich kenne deine Ängste", "Ich kenne deine Träume", "Ich war gestern in deinem Traum", "Bist du letzte Nacht nicht plötzlich aufgewacht?",
  "Ich hatte dieses seltsame Gefühl", "Sei heute Abend vorsichtig", "Du bist nicht sicher", "Mit jemandem zusammen sein", "schlafe nicht alleine", "Schalten Sie die Lampe nicht aus",
  "Schließe die Tür ab", "Lassen Sie das Fenster nicht offen", "Zieh deinen Vorhang zu", "Hast du gerade dieses Geräusch gehört?", "Jetzt ist es direkt hinter dir", "komm noch nicht zurück",
];

export const DETAILED_PLACES: string[] = [
  "verlassenes Krankenhaus", "psychiatrische Klinik", "Irrenhaus", "verlassene Schule", "verbranntes Gebäude", "ruinieren",
  "verlassene Fabrik", "altes Lagerhaus", "leeres Lager", "verlassenes Hotel", "Geisterstadt", "verlassenes Dorf",
  "unterirdischer Tunnel", "Abwasserkanal", "U-Bahn-Tunnel", "Kriegsunterkunft", "Luftschutzbunker", "geheimer Raum",
  "Geheimgang", "Tunnelmündung", "Höhleneingang", "gut unten", "gut wässern", "gut trocknen",
  "Keller", "Dachboden", "Dachboden", "Speisekammer", "Keller", "Weinkeller",
  "alte Moschee", "verlassene Kirche", "zerstörtes Kloster", "Synagoge", "Tempel", "Altar",
  "Altar", "Minarett", "Glockenturm", "Kanzel", "dunkler Wald", "verirrter Garten",
  "Sumpf", "Klippenrand", "Gebirgspass", "Tal", "Seeufer", "Flussbett",
  "unter dem Wasserfall", "Insel", "Halbinsel", "Nase", "steinig", "Strand",
  "Meeresküste", "Hafen", "Pier", "alte Brücke", "Steinbrücke", "Hängebrücke",
  "Schloss", "Festung", "Sternzeichen", "Wand", "Palast", "Herrenhaus",
  "Herrenhaus", "yali", "Badehaus", "Karawanserei", "Gasthaus", "aus dem Bedesten",
  "Madrasa", "Bibliothek", "Sternwarte", "Minze",
];

export const DETAILED_TIME: string[] = [
  "Morgendämmerung", "Sonnenaufgang", "am frühen Morgen", "Vormittag", "Mittag", "Nachmittag",
  "am Abend", "Sonnenuntergang", "Dämmerung", "Mitternacht", "drei Uhr morgens", "Morgendämmerung",
  "Osmanische Zeit", "Seldschukenzeit", "Byzantinische Zeit", "Römische Zeit", "Hethitische Zeit", "Sumerische Zeit",
  "mittelalterlich", "neues Zeitalter", "Moderne", "Kriegsjahre", "Jahre der Hungersnot", "Pestjahre",
  "jede Nacht", "jeden Morgen", "jeden Abend", "jeden Vollmond", "jeden Neumond", "alle Jahreszeiten",
  "jedes Jahr am selben Tag", "jedes Jubiläum", "einmal in hundert Jahren", "einmal in tausend Jahren", "seit Anbeginn der Zeit", "für immer",
  "letzte Nacht", "letzte Woche", "letzten Monat", "letztes Jahr", "vor Jahren", "vor Jahrhunderten",
  "vor tausend Jahren", "am Anfang der Zeit", "Weltuntergang", "Jüngster Tag", "letzter Tag", "letzte Stunde",
  "letzte Minute", "letzter Atemzug",
];

export const CURSES: string[] = [
  "Verdammt", "runter mit", "lass es verschwinden", "Du wirst deine Strafe finden", "Du wirst Rechenschaft ablegen", "Du wirst den Preis bezahlen",
  "Du wirst es bereuen", "Ich werde es nicht vergessen", "Ich werde nicht vergeben", "Ich werde nicht vergeben", "Ich werde mich rächen", "wir begleichen die Rechnung",
  "das ist noch nicht vorbei", "es ist noch nicht vorbei", "Ich fange gerade erst an", "Du wirst sehen", "Du wirst es verstehen", "Du wirst fühlen",
  "du wirst leiden", "Du wirst weinen", "du wirst betteln", "Um Hilfe zu bitten hilft nicht", "niemand kann helfen", "es gibt kein entkommen",
  "es gibt keine Erlösung", "es gibt kein Ende", "Dieser Fluch kann nicht gebrochen werden", "Dieser Zauber kann nicht gebrochen werden", "Diese Kette kann nicht unterbrochen werden", "Diese Bindung kann nicht gebrochen werden",
  "wird sieben Generationen überdauern", "es wird vierzig Tage dauern", "wird ewig dauern", "wird für immer weitergehen", "Diese Länder sind verflucht", "Dieses Haus ist verflucht",
  "Diese Familie ist verflucht", "Dieses Blut ist verflucht", "Jedes geborene Kind ist verflucht", "Jede Generation ist verflucht", "Der Fluch ist auf dich übergegangen", "jetzt gehört es dir",
  "Du wirst diese Last tragen", "nach dir zu deinen Kindern",
];

export const DREAM_WORDS: string[] = [
  "Traum", "Albtraum", "Traum", "Traum", "Vision", "Prophezeiung",
  "Vorahnung", "Intuition", "Instinkt", "sechster Sinn", "Unterbewusstsein", "bewusstlos",
  "trans", "Hypnose", "Meditation", "Schlaflähmung", "klarer Traum", "einen Albtraum haben",
  "im Traum fliegen", "in einen Traum fallen", "im Traum laufen", "in einem Traum fliehen", "in einem Traum verfolgt werden", "Im Traum tot sehen",
  "Blut im Traum sehen", "Eine Schlange im Traum sehen", "Eine Spinne im Traum sehen", "Wasser im Traum sehen", "Feuer im Traum sehen", "Ein Haus im Traum sehen",
  "Im Traum ein Grab sehen", "Im Traum einen Spiegel sehen", "Im Traum eine Tür sehen", "Treppen im Traum sehen", "Im Traum einen Korridor sehen", "Dunkelheit in einem Traum sehen",
  "Licht in einem Traum sehen", "eine Stimme in einem Traum hören", "im Traum ein Flüstern hören", "Schreie im Traum hören", "Musik im Traum hören", "jemanden in einem Traum sehen",
  "ein Fremder in einem Traum", "Schatten im Traum", "Gesicht im Traum", "Auge im Traum",
];

export const RESEARCH_JARGON: string[] = [
  "Anomalie erkannt", "Das Energiefeld hat sich verändert", "elektromagnetischer Stoß", "Temperaturanomalie", "Stimmanomalie", "visuelle Anomalie",
  "Datenerfassung", "Evidenzanalyse", "Ermittlungen am Tatort", "Zeugenaussage", "Augenzeuge", "Informationen aus erster Hand",
  "Sekundärquelle", "Archivdatensatz", "historisches Dokument", "Frequenzanalyse", "Spektrumanalyse", "Wellenlänge",
  "Infrarot", "Ultraviolett", "Wärmebild", "Nachtsicht", "Infrarot", "volles Spektrum",
  "SLS-Scannen", "EMF-Lesung", "EVP-Registrierung", "Geisterbox", "Geisterbox", "rem pod",
  "k-ii-Meter", "Mel-Meter", "Trifield-Meter", "digitales Thermometer", "Lasergitter", "Bewegungssensor",
  "Vibrationssensor", "Drucksensor", "Feuchtigkeitssensor", "Kontrollsitzung", "Provokation", "stille Sitzung",
  "Frage- und Antwortsitzung", "kostenlose Sitzung", "Erstmessung", "Referenzwert", "abnormales Lesen", "Spitzenwert",
  "Durchschnittswert",
];

export const ALL_WORDS: string[] = [
  ...PHONEMES,
  ...DARK_WORDS,
  ...DARK_PHRASES,
  ...SPIRIT_NAMES,
  ...NUMBERS,
  ...HISTORICAL_WORDS,
  ...NATURE_WORDS,
  ...EMOTION_WORDS,
  ...BODY_WORDS,
  ...PLACE_WORDS,
  ...TIME_WORDS,
  ...ACTION_WORDS,
  ...RELIGIOUS_WORDS,
  ...PARANORMAL_TERMS,
  ...OBJECT_WORDS,
  ...ADJECTIVE_WORDS,
  ...MANIPULATIVE_RESPONSES,
  ...LONG_PHRASES,
  ...MYTHOLOGY_WORDS,
  ...FOLK_BELIEFS,
  ...HORROR_STORY_WORDS,
  ...DIALOG_PHRASES,
  ...PROVERBS,
  ...COLOR_LIGHT_WORDS,
  ...WEATHER_WORDS,
  ...SOUND_WORDS,
  ...QUANTITY_WORDS,
  ...COMMUNICATION_WORDS,
  ...RELATIONSHIP_WORDS,
  ...WHISPER_PHRASES,
  ...DETAILED_PLACES,
  ...DETAILED_TIME,
  ...CURSES,
  ...DREAM_WORDS,
  ...RESEARCH_JARGON,
  ...HOME_OBJECT_PHRASES,
];

export const WORD_CATEGORIES = {
  phonemes: PHONEMES.length,
  darkWords: DARK_WORDS.length,
  darkPhrases: DARK_PHRASES.length,
  spiritNames: SPIRIT_NAMES.length,
  numbers: NUMBERS.length,
  historicalWords: HISTORICAL_WORDS.length,
  natureWords: NATURE_WORDS.length,
  emotionWords: EMOTION_WORDS.length,
  bodyWords: BODY_WORDS.length,
  placeWords: PLACE_WORDS.length,
  timeWords: TIME_WORDS.length,
  actionWords: ACTION_WORDS.length,
  religiousWords: RELIGIOUS_WORDS.length,
  paranormalTerms: PARANORMAL_TERMS.length,
  objectWords: OBJECT_WORDS.length,
  adjectiveWords: ADJECTIVE_WORDS.length,
  manipulativeResponses: MANIPULATIVE_RESPONSES.length,
  longPhrases: LONG_PHRASES.length,
  mythologyWords: MYTHOLOGY_WORDS.length,
  folkBeliefs: FOLK_BELIEFS.length,
  horrorStoryWords: HORROR_STORY_WORDS.length,
  dialogPhrases: DIALOG_PHRASES.length,
  proverbs: PROVERBS.length,
  colorLightWords: COLOR_LIGHT_WORDS.length,
  weatherWords: WEATHER_WORDS.length,
  soundWords: SOUND_WORDS.length,
  quantityWords: QUANTITY_WORDS.length,
  communicationWords: COMMUNICATION_WORDS.length,
  relationshipWords: RELATIONSHIP_WORDS.length,
  whisperPhrases: WHISPER_PHRASES.length,
  detailedPlaces: DETAILED_PLACES.length,
  detailedTime: DETAILED_TIME.length,
  curses: CURSES.length,
  dreamWords: DREAM_WORDS.length,
  researchJargon: RESEARCH_JARGON.length,
  total: 0,
};
WORD_CATEGORIES.total = ALL_WORDS.length;
